-- GENERATED by scripts/emit-cuisine-sql.mjs from lib/cuisine.js — DO NOT EDIT BY HAND.
-- Regenerate: node scripts/emit-cuisine-sql.mjs > this file
-- check-cuisine-sql-in-sync.mjs fails the build if this drifts from the module.
--
-- Backfills wf_inventory.cuisines for every food row using signals we ALREADY
-- hold: google_types[], the name, and wf_editorial prose. No API calls.
--
-- THE RULE: these are FILTER labels over local inventory, never query terms.

with ed as (
  select place_id, lower(coalesce(hook,'') || ' ' || coalesce(why_here,'')) as txt
  from public.wf_editorial
),
src as (
  select i.place_id, lower(i.name) as nm, coalesce(i.google_types,'{}') as tys,
         coalesce(ed.txt,'') as edtxt
  from public.wf_inventory i left join ed on ed.place_id = i.place_id
  where i.category = 'food'
),
vetoed as (
  select place_id from src where
    (nm ~* '\y(nightclub|night club|hookah|cigar)\y')   -- Havana Nights Nightclub is a nightclub — a cuisine label on it is a category error
    or
    (nm ~* '\y(apartments?|realty|salon|barber|storage|dentist|urgent care)\y')   -- a plaza, salon or clinic carrying a cuisine word is not a restaurant
    or
    (nm ~* '\y(outback|texas roadhouse|longhorn steakhouse)\y')   -- national steakhouse chains carry country words that are branding, not cuisine
),
-- Signal tables, emitted as VALUES so thirty regexes are one relation
-- instead of thirty unioned SELECTs.
type_map(ty, cuisine) as (values
  ('italian_restaurant','italian'),
  ('chinese_restaurant','chinese'),
  ('japanese_restaurant','japanese'),
  ('korean_restaurant','korean'),
  ('mexican_restaurant','mexican'),
  ('thai_restaurant','thai'),
  ('indian_restaurant','indian'),
  ('vietnamese_restaurant','vietnamese'),
  ('greek_restaurant','greek'),
  ('french_restaurant','french'),
  ('spanish_restaurant','spanish'),
  ('turkish_restaurant','turkish'),
  ('lebanese_restaurant','lebanese'),
  ('middle_eastern_restaurant','middle-eastern'),
  ('mediterranean_restaurant','mediterranean'),
  ('brazilian_restaurant','brazilian'),
  ('american_restaurant','american'),
  ('seafood_restaurant','seafood'),
  ('steak_house','steakhouse'),
  ('pizza_restaurant','pizza'),
  ('sushi_restaurant','sushi'),
  ('barbecue_restaurant','barbecue'),
  ('ramen_restaurant','ramen'),
  ('hamburger_restaurant','burgers'),
  ('breakfast_restaurant','breakfast'),
  ('brunch_restaurant','breakfast'),
  ('vegetarian_restaurant','vegetarian'),
  ('vegan_restaurant','vegan'),
  ('asian_restaurant','asian'),
  ('latin_american_restaurant','latin-american'),
  ('afghani_restaurant','afghan'),
  ('african_restaurant','african'),
  ('indonesian_restaurant','indonesian'),
  ('cuban_restaurant','cuban'),
  ('colombian_restaurant','colombian'),
  ('caribbean_restaurant','caribbean'),
  ('peruvian_restaurant','peruvian'),
  ('argentinian_restaurant','argentine')
),
name_map(cuisine, rx) as (values
  ('cuban','\y(cubana|cubano|cuban|kubana|kubano|habana|havana|ropa vieja|lechon|palomilla|medianoche|croqueta|croquetas|pastelito|vaca frita)\y'),
  ('puerto-rican','\y(puerto[ -]?rican|puerto[ -]?rico|boricua|borinquen|mofongo|lechonera|alcapurria|pernil|jibarito|tostones|piragua)\y'),
  ('colombian','\y(colombiana|colombiano|colombian|bandeja paisa|arepa|arepas|ajiaco|lechona|bunuelo|chuzo)\y'),
  ('venezuelan','\y(venezolana|venezuelan|pabellon|cachapas?|tequenos?|patacon(es)?|reina pepiada)\y'),
  ('dominican','\y(dominicana|dominican|la bandera|mangu|chimi)\y'),
  ('peruvian','\y(peruvian|peruano|lomo saltado|anticucho|pollo a la brasa|chifa)\y'),
  ('haitian','\y(haitian|ayiti|griot|tassot)\y'),
  ('jamaican','\y(jamaican|jamaica|jerk chicken|jerk pork|ackee|oxtail|patty shop|irie)\y'),
  ('caribbean','\y(caribbean|west indian|trinidad|bajan|roti shop|doubles)\y'),
  ('salvadoran','\y(salvadorena|salvadoran|pupuseria|pupusas|pupusa|curtido)\y'),
  ('argentine','\y(argentina|argentine|parrilla|choripan|milanesa)\y'),
  ('ethiopian','\y(ethiopian|injera|doro wat|habesha|berbere)\y'),
  ('filipino','\y(filipino|pinoy|lumpia|kamayan|halo[ -]?halo|lechon kawali)\y'),
  ('korean','\y(korean|k[ -]?bbq|kpot|k[ -]?pot|bibimbap|bulgogi|banchan|tteokbokki|jjigae|gochujang)\y'),
  ('japanese','\y(japanese|izakaya|yakitori|omakase|donburi|okonomiyaki|udon|teppanyaki|hibachi)\y'),
  ('vietnamese','\y(vietnamese|pho|banh mi|bun bo|com tam|banh xeo)\y'),
  ('thai','\y(thai|pad thai|tom yum|som tam|khao soi)\y'),
  ('indian','\y(indian|tandoori|tandoor|biryani|masala|dosa|chaat|punjabi|kerala)\y'),
  ('greek','\y(greek|souvlaki|gyro|gyros|taverna|spanakopita)\y'),
  ('turkish','\y(turkish|kebap|doner|anatolia)\y'),
  ('middle-eastern','\y(shawarma|falafel|hummus|kabob|kebab)\y'),
  ('chinese','\y(chinese|dim sum|szechuan|sichuan|cantonese|hunan|dumpling house)\y'),
  ('mexican','\y(mexican|taqueria|birria|barbacoa|al pastor|elote|mariscos|antojitos)\y'),
  ('soul-food','\y(soul food|southern kitchen|fish fry|smothered)\y'),
  ('barbecue','\y(bbq|barbecue|barbeque|smokehouse|brisket)\y')
),
scoped_veto(cuisine, rx, unless_rx) as (values
  ('japanese','\ykobe\y','japanese|sushi|hibachi|teppan|izakaya')
),
hits as (
  select s.place_id, tm.cuisine, 0.90::numeric as conf, 'google-types'::text as src
    from src s join type_map tm on tm.ty = any(s.tys)
  union all
  select s.place_id, nm2.cuisine, 0.70::numeric, 'name'::text
    from src s join name_map nm2 on s.nm ~* nm2.rx
  union all
  select s.place_id, nm2.cuisine, 0.55::numeric, 'editorial'::text
    from src s join name_map nm2 on s.edtxt <> '' and s.edtxt ~* nm2.rx
),
live as (
  select h.* from hits h
  join src s on s.place_id = h.place_id
  where h.place_id not in (select place_id from vetoed)
    and not exists (
      select 1 from scoped_veto sv
      where sv.cuisine = h.cuisine and s.nm ~* sv.rx
        and (sv.unless_rx is null or s.nm !~* sv.unless_rx))
),
ranked as (
  select place_id, cuisine, max(conf) as conf,
         bool_or(cuisine <> all(array['asian','latin-american','american','mediterranean','caribbean'])) over (partition by place_id) as has_specific
  from live group by place_id, cuisine
),
kept as (
  select place_id, cuisine, conf from ranked
  where has_specific = false or cuisine <> all(array['asian','latin-american','american','mediterranean','caribbean'])
),
agg as (
  select k.place_id,
         array_agg(k.cuisine order by k.conf desc, k.cuisine) as cuisines,
         max(k.conf) as conf,
         (select array_agg(distinct l.src order by l.src) from live l where l.place_id = k.place_id) as srcs
  from kept k group by k.place_id
)
update public.wf_inventory i set
  cuisines           = coalesce(a.cuisines, '{}'),
  cuisine_confidence = a.conf,
  cuisine_sources    = coalesce(a.srcs, case when v.place_id is not null then array['name-veto'] else '{}' end),
  cuisine_reason     = case
                         when v.place_id is not null then 'vetoed: not a cuisine-bearing restaurant'
                         when a.place_id is null then 'unclassifiable'
                         else 'classified' end,
  cuisine_checked_at = now()
from src s
  left join agg a on a.place_id = s.place_id
  left join vetoed v on v.place_id = s.place_id
where i.place_id = s.place_id;
