// lib/creatorCaptions.js — the captions, off the eager route bundle.
//
// v8.43. lib/creatorVideos.js is reached from the ranking path
// (lawfulOrder -> creatorBoost -> creatorVideosFor), so it is EAGER: every
// visitor downloads it before the first card paints. Captions were the single
// largest thing in it — ~30KB of prose that only THREE surfaces ever render,
// and all three are lazy:
//
//   app/components/sheets/Detail.js      nextDynamic (home.js loadDetail)
//   app/components/sheets/SocialFind.js  nextDynamic (home.js loadSocialFind)
//   lib/creatorPages.js                  server-only, /creators/[handle]
//
// So the bytes land in those chunks, where a reader has actually asked for
// them, instead of in everyone's first paint. scripts/check-bundle.mjs forced
// the question when a 93-place batch blew the route budget, and the answer was
// not to raise a ratchet that exists to be lowered.
//
// THE KEY IS "<entry key>|<video url>", NOT the url alone. A round-up post
// legitimately recommends several venues — one Instagram URL carries four
// different captions for the four Venezuelan hot-dog stands — so keying on url
// silently dropped 8 captions when this was first written. Measured, not
// assumed. creatorVideos.js stamps v.k = entry.key once at module load (from
// data it already holds, so it costs the bundle nothing) and captionFor()
// reads it.
//
// A missing key returns "" rather than throwing, and every renderable video is
// asserted to have a caption by scripts/test-creator-corroboration.mjs — so a
// caption can never silently vanish from a card.
//
// Captions are ALWAYS Wayfind's own words, never the creator's verbatim text
// (copyright + duplicate content). That rule lives with the captions.

export const CAPTIONS = {
  "spinning-coffee-bradenton|https://www.tiktok.com/@cindy.selects/video/7661821646973586702": "A local creator's visit to this Bradenton coffee spot.",
  "mai-kai-fort-lauderdale|https://www.facebook.com/share/r/1EPX6DN118/": "Fort Lauderdale's tiki landmark since 1956: a Polynesian dinner show, reservations required.",
  "marie-selby-sarasota|https://www.tiktok.com/@thefloridaqueenie_/video/7358206182676352298": "A local creator's visit to these downtown Sarasota bayfront gardens.",
  "perspire-lakewood-ranch|https://www.tiktok.com/@theerynlalonde/video/7593470206069017870": "A creator's infrared-sauna session at this Lakewood Ranch-area studio.",
  "jabal-coffee-house-orlando|https://www.tiktok.com/@cindy.selects/video/7668348057171365133": "A creator's iced coffee order at this Orlando coffee shop, a stop she didn't expect to find in the plaza it's tucked into.",
  "dolce-and-bake-orlando|https://www.tiktok.com/@cindy.selects/video/7667937697171885326": "A creator's cappuccino and pastry stop at this Orlando café and bakery.",
  "seek-first-coffee-shop-orlando|https://www.tiktok.com/@cindy.selects/video/7668826743108537613": "A creator's flan latte order at this Pine Castle-area Orlando coffee shop.",
  "neuroplay-sensory-playroom-orlando|https://www.tiktok.com/@cindy.selects/video/7669065801369914638": "A parent creator's visit to this Orlando indoor sensory playroom built for toddlers.",
  "ryans-coffee-house-parrish|https://www.tiktok.com/@cindy.selects/video/7664006021349723405": "A creator's order of a salted caramel mocha and a maple-gouda melt at this Parrish coffee house.",
  "gamble-creek-farms-parrish|https://www.tiktok.com/@parrishfloridahomes/video/7625665948711718158": "A local realtor's visit to this Parrish farm for farm-fresh goods and sunflowers.",
  "mote-sea-aquarium-sarasota|https://www.tiktok.com/@manateelittlelocals/video/7647673425548430605": "A family creator's walk through the sharks, jellyfish and sea turtle rehab at the UTC aquarium.",
  "bishop-museum-bradenton|https://www.tiktok.com/@manateelittlelocals/video/7649896505108598047": "A local family flags the free-admission weekends for Manatee County residents at this Bradenton science museum.",
  "eleanors-coffee-cakes-palmetto|https://www.tiktok.com/@manateelittlelocals/video/7651059904530205982": "A creator's coffee stop inside the historic 1912 Palmetto building.",
  "heritage-harbour-park-bradenton|https://www.tiktok.com/@manateelittlelocals/video/7656593993286913311": "A family creator's find: a fully fenced park tucked behind the Target and Costco on State Road 64.",
  "northeast-venice-park-nokomis|https://www.tiktok.com/@manateelittlelocals/video/7652542591308729631": "A family creator's first look at this newly opened park near Venice.",
  "lakewood-ranch-library-bradenton|https://www.tiktok.com/@manateelittlelocals/video/7665365282323582238": "A family creator's free rainy-day option: the children's wing at the Lakewood Ranch library.",
  "aleur-event-collective-sarasota|https://www.tiktok.com/@manateelittlelocals/video/7666837987786820895": "A creator's night at a women-owned-business gathering held at this Sarasota event space.",
  "jj-foxs-treehouse-bradenton|https://www.tiktok.com/@manateelittlelocals/video/7662469985997983006": "A family creator's indoor escape from the heat at this Bradenton play space.",
  "capybara-cafe-st-petersburg|https://www.tiktok.com/@manateelittlelocals/video/7618749588236668191": "A family creator's up-close visit with the capybaras and kangaroos at this St. Pete animal experience.",
  "hogans-place-gibsonton|https://www.tiktok.com/@manateelittlelocals/video/7643181676293639455": "A family creator's visit during baby-animal season at this farm south of Tampa.",
  "popstroke-sarasota|https://www.tiktok.com/@manateelittlelocals/video/7667009868250877214": "A family creator's morning meetup at the UTC putting course.",
  "joy-coffee-bradenton|https://www.tiktok.com/@cindy.selects/video/7662923109749640461": "A creator's iced Joy Latte and coffee cake stop at this Bradenton coffee shop, which also has a toddler play area.",
  "maple-street-biscuit-dr-phillips-orlando|https://www.tiktok.com/@cindy.selects/video/7675873812293963022": "A creator's maple-vanilla latte on a coffee run to this Dr. Phillips biscuit house.",
  "root-and-seed-lakewood-ranch|https://www.tiktok.com/@cindy.selects/video/7673644888927292685": "A creator's return trip for the strawberry matcha with oat milk and a bagel at this Lakewood Ranch coffee and gluten-free bakery.",
  "tuscan-hills-coffee-parrish|https://www.tiktok.com/@cindy.selects/video/7673283810074676494": "A creator's Salted Carmella Cove from this drive-up coffee window in Parrish.",
  "hashtag-cafe-sarasota|https://www.tiktok.com/@cindy.selects/video/7671424535832431885": "A creator's toasted-marshmallow cold brew and from-scratch breakfast sandwich at this Bee Ridge café.",
  "catrinas-tacos-tampa|https://www.instagram.com/reel/DZS1ZQGpK77/": "A creator's visit to this taco spot tucked inside a 1905 former Bank of Tampa building.",
  "lucky-tigre-tampa|https://www.instagram.com/reel/DYkwpV9Rr6Y/": "A creator's tasting of the Filipino-inspired menu at this West Tampa restaurant.",
  "palaus-restaurant-tampa|https://www.instagram.com/reel/DbTYFQupyxt/": "A creator's whole fried yellowtail snapper, hand-picked and fried to order, at this Tampa Cuban restaurant.",
  "atomic-cat-st-petersburg|https://www.instagram.com/reel/DbHSDSmpR6r/": "A creator's stop at this retro 70s-themed coffee shop in St. Petersburg.",
  "atomic-cat-st-petersburg|https://www.instagram.com/p/DbEPx0JP4bX/": "A second local creator's morning at the same St. Pete coffee shop.",
  "ro-hyde-park-tampa|https://www.instagram.com/reel/DbDuqRGpOal/": "A creator's lunch omakase at this Hyde Park sushi restaurant.",
  "boulan-wynwood-miami|https://www.instagram.com/reel/Dbihv67xOtC/": "A creator's slow-morning coffee and pastry stop at this European-style Wynwood cafe.",
  "boulan-wynwood-miami|https://www.instagram.com/p/DaXzACXOrPE/": "A second local creator's weekend brunch at this Argentine-owned Wynwood bakery.",
  "mayfair-grill-miami|https://www.instagram.com/p/DbgRMv0lcsL/": "A creator's Miami Spice tasting menu at this Coconut Grove restaurant.",
  "el-churrascaso-miami-lakes|https://www.instagram.com/reel/Dbdac7kxq5l/": "A creator's Brazilian steakhouse spread, meats served by the pound, at this Miami Lakes spot.",
  "el-churrascaso-miami-lakes|https://www.instagram.com/p/DXuw7y9Dq-g/": "A second local creator's plate from the same Miami Lakes grill, sold by the pound.",
  "silver-moon-drive-in-lakeland|https://www.instagram.com/reel/DYDJ0rxJA8K/": "A creator's retro drive-in date night at this 75-year-old Lakeland theater, one of only four left in Florida.",
  "catboat-clermont|https://www.instagram.com/reel/DVymPmojQ0x/": "A creator's self-driven mini-boat tour across the Clermont Chain of Lakes.",
  "old-sugar-mill-pancake-house-de-leon-springs|https://www.instagram.com/reel/DUx0WfhDSxh/": "A creator's cook-your-own pancake brunch inside De Leon Springs State Park's old sugar mill.",
  "main-street-pizza-kissimmee|https://www.instagram.com/reel/DbdVdP4g75L/": "A creator's attempt at Florida's biggest pizza, a 36-inch Monster, at this downtown Kissimmee pizzeria.",
  "pasta-wynwood-miami|https://www.instagram.com/p/DY7khOvx34K/": "A creator's date-night plate at this Wynwood room that came from Peru, where every noodle is made from scratch.",
  "borti-pasta-bar-miami|https://www.instagram.com/p/DalR3Xxxavv/": "A creator's carbonara, cooked at the pass with the chef, at this Miami pasta bar.",
  "charlatam-miami|https://www.instagram.com/p/DbbyA0xN0PG/": "A creator's fried chicken and BBQ ribs at this Latin American kitchen just off Brickell — built for a group table.",
  "la-tiendita-ii-miami-beach|https://www.instagram.com/p/Da8ArSoxGca/": "A creator's Peruvian sandwich from this tiny South Beach market — a takeout counter three blocks from the sand.",
  "wat-buddharangsi-homestead|https://www.instagram.com/p/DZtB5VGRQJW/": "A creator's Sunday at this Buddhist temple's weekly Thai street-food market — pad thai, satay and mango sticky rice cooked on the spot, 10:30am to 2pm only.",
  "hurrem-hammam-north-miami|https://www.instagram.com/p/DZNWyDBR5MV/": "A creator's day inside a 20,000 sq ft Ottoman-style bathhouse — marble hammam, kese scrub, cold plunge and an ice igloo.",
  "ichimi-midtown-miami|https://www.instagram.com/p/DYNta3cRRWQ/": "A creator's tonkotsu ramen and bao buns at this Midtown Miami pan-Asian counter.",
  "mi-colombia-miami-beach|https://www.instagram.com/p/DXxkLiAR4xW/": "A creator's visit to a family-run Colombian cafeteria in North Miami Beach, cooking the same homemade plates for 39 years.",
  "yamashiro-miami|https://www.instagram.com/p/DW7WWaxRtox/": "A creator's rooftop brunch downtown — matcha French toast and katsu sandos at the Miami outpost of a century-old Los Angeles restaurant.",
  "andres-carne-de-res-miami-beach|https://www.instagram.com/p/DW44WKUxbgZ/": "A creator's night at the Lincoln Road outpost of Colombia's loudest party steakhouse — chicharrón, arepas and a floor that turns into a dance.",
  "chefsfull-food-truck-miami|https://www.instagram.com/p/DWkJnwERymp/": "A creator's Jamaican plate from this Kendall food truck — Thursday through Sunday, oxtail on Saturdays.",
  "tres-leches-factory-doral|https://www.instagram.com/p/DWpUwoUxBs8/": "A creator's cuatro leches at the Doral bakery that has been supplying South Florida restaurants since 2001 — you have probably eaten it without knowing.",
  "bella-miami-beach|https://www.instagram.com/p/DWFRNWCRDH2/": "A creator's hand-made pasta at this small Mediterranean-leaning Italian room off Collins, tucked inside a hotel.",
  "sushiato-doral|https://www.instagram.com/p/DWAFlN6RQii/": "A creator's run through the fusion-roll menu at this Doral sushi room.",
  "domaselo-little-havana-miami|https://www.instagram.com/p/DUEoV86EU2W/": "A creator's sourdough from a walk-up window in Little Havana, where every loaf is stone-milled and baked from scratch.",
  "yambo-express-miami|https://www.instagram.com/p/DTjJO5ikdG5/": "A creator's Nicaraguan fritanga — carne asada straight off the grill — at this Kendall truck from the Yambo family.",
  "pronto-cafe-hialeah|https://www.instagram.com/p/DSlAeXbER_X/": "A creator's pan con bistec at the Hialeah Cuban cafe people argue about.",
  "pronto-cafe-hialeah|https://www.instagram.com/p/DXsIouEkytg/": "A second local creator came for the same pan con bistec — buttered toast, 48-hour marinade, house potatoes.",
  "la-casita-tropical-hollywood|https://www.instagram.com/p/DR0GLb1EbfZ/": "A creator's chicharrones at the Hollywood spot people drive across the state for, alongside a full Dominican menu.",
  "ay-bendito-miami|https://www.instagram.com/p/DXFm2CPR_Qa/": "A creator's mofongo, alcapurrias and pastelón at this Puerto Rican kitchen in Kendall.",
  "rio-izakaya-tampa|https://www.instagram.com/p/DWwEk5aETOW/": "A creator's first look at this elevated Japanese room in the Westshore Marina District.",
  "o-ku-tampa|https://www.instagram.com/p/DY1-DCgxzwQ/": "A creator's tour of this Bay to Bay sushi and robata room — hamachi carpaccio, seared scallop, hanger steak in black garlic shoyu.",
  "palmette-tampa|https://www.instagram.com/p/DVqnRLIjhpX/": "A creator's visit to this brasserie on the Courtney Campbell Causeway, inside the Westin Tampa Bay.",
  "predalina-tampa|https://www.instagram.com/p/DTDIKkaka9Y/": "A creator's return to this Water Street Mediterranean room after its refresh.",
  "urban-stillhouse-st-petersburg|https://www.instagram.com/p/DR9optOkYj7/": "A creator's holiday evening at this St. Pete distillery restaurant, which decorates hard for Christmas.",
  "sorsi-waterfront-tampa|https://www.instagram.com/p/DR4pktGkZGF/": "A creator's spritz in the sun at this Harbour Island aperitivo bar.",
  "stovall-house-tampa|https://www.instagram.com/p/DRab0KSDbJ4/": "A creator's look inside the Arabian Nights party at this Bayshore social club — a members event, not a walk-in.",
  "piccolo-buco-tampa|https://www.instagram.com/p/DP_hrJJjayi/": "A creator's opening night at Cooper's Hawk's Roman trattoria concept on North Dale Mabry.",
  "hyde-park-village-tampa|https://www.instagram.com/p/DPWEr2ijski/": "A creator's autumn afternoon at this open-air Tampa village, which fills with pumpkins the moment the season turns.",
  "1983-tampa|https://www.instagram.com/p/DN5gZSTji9i/": "A creator's preview of this South Tampa restaurant, bar and arcade before it opened.",
  "circles-waterfront-apollo-beach|https://www.instagram.com/p/DNdU5P3OtXD/": "A creator's afternoon at this Apollo Beach waterfront restaurant you can reach by boat, with a beach lounge and a second bar.",
  "rocca-tampa|https://www.instagram.com/p/DMxU4QPuOeO/": "A creator's table-side mozzarella cart at this Tampa Heights Italian room.",
  "st-regis-longboat-key|https://www.instagram.com/p/DLfaZB1uiVQ/": "A creator's stay at this Longboat Key beach resort.",
  "elliott-aster-st-petersburg|https://www.instagram.com/p/DKmfEUFOM-j/": "A creator's opening visit to this dining room at the Vinoy in downtown St. Pete.",
  "barcelona-wine-bar-tampa|https://www.instagram.com/p/DKMjlvtOYDt/": "A creator's stop for the South Tampa happy hour here, weekdays four to six.",
  "maru-rooftop-tampa|https://www.instagram.com/p/DJgsf_Eu-u6/": "A creator's first night at this rooftop cocktail and seafood bar above Bay to Bay.",
  "riverwalk-terrace-tampa|https://www.instagram.com/p/DIL9_eyRdas/": "A creator's opening look at this terrace bar on the Tampa Riverwalk.",
  "latitude-28-clearwater-beach|https://www.instagram.com/p/DIJpH5AxPtE/": "A creator's Thai-leaning tasting dinner at this Clearwater Beach resort restaurant — a one-night menu, not the everyday one.",
  "pjs-sandwich-shop-parrish|https://www.instagram.com/p/DbgbJhYB3dQ/": "A creator's Italian sub, with the house sub dressing, at the Parrish sandwich counter that has been open 42 years.",
  "berns-steak-house-tampa|https://www.instagram.com/p/CvphpPutyPR/": "A creator's night in the Harry Waugh Dessert Room — private booths built from old wine casks, a phone on the wall to request a song from the live pianist.",
  "berns-steak-house-tampa|https://www.instagram.com/p/DWBupkuDYSw/": "A creator's case for the Tampa institution: every steak arrives with soup, salad, potato and onion rings, and reservations open sixty days out.",
  "salt-shack-on-the-bay-tampa|https://www.instagram.com/p/CuCRAYzLv3z/": "A creator's waterfront afternoon — peel-and-eat shrimp, catch of the day, and yucca fries in sofrito. No reservations, so go early.",
  "sucre-table-tampa|https://www.instagram.com/p/CvPcmx2LYy7/": "A creator's visit to this Tampa pastry kitchen, known for laminated croissants and a rotating run of one-off specials.",
  "sapphire-tampa|https://www.instagram.com/p/DYj6SHYOzM_/": "A creator's night at this dinner-and-a-show room where every table faces the stage and a DJ takes over after ten. Check the dress code first.",
  "hog-island-fish-camp-dunedin|https://www.instagram.com/p/DXJuFhfDSVq/": "A creator's lunch a few blocks off the Dunedin main strip — parmesan-crusted hogfish, red and white chowders, fish landed by local boats.",
  "fortu-st-petersburg|https://www.instagram.com/p/DQrRVyHjce9/": "A creator's four-course dinner at this Michelin-listed downtown St. Pete room — lobster dumplings in ginger broth, black miso cod, an ube cheesecake.",
  "fortu-st-petersburg|https://www.instagram.com/p/DQ7--eQCS2A/": "A second creator on the same room, six weeks earlier — the Japanese-leaning pan-Asian menu that put it on the Michelin list.",
  "alessi-bakery-tampa|https://www.instagram.com/p/DYMuJ4rOTBo/": "A creator's stop at the Tampa bakery that has been open since 1912, now in a larger room with a bar and a patio. Do not leave without the scacciata.",
  "beccofino-tampa|https://www.instagram.com/p/DZ7flZquUi5/": "A creator's coursed-out dinner at this small South Tampa Italian room, where the cacio e pepe is finished at the table.",
  "tate-and-tilly-tampa|https://www.instagram.com/p/DU0nQjVjUUd/": "A creator's browse through this North Tampa gift shop, stocked largely from local makers — cookware, toys, jewellery and a Tampa section.",
  "cafe-rialto-tampa|https://www.instagram.com/p/DYzX3OoutDc/": "A creator's coffee inside this historic downtown event space, now open as a cafe with a tea room.",
  "tampa-edition|https://www.instagram.com/p/DRpQm0iDRx0/": "A creator's look at this downtown Tampa hotel, which decorates heavily through the holidays.",
  "sculleys-madeira-beach|https://www.instagram.com/p/DU_Cx5gjl47/": "A creator takes on the 64oz Bloody Mary at this John's Pass boardwalk seafood house — the single most-watched find in the library.",
  "frankies-italian-deli-riverview|https://www.instagram.com/p/DSViu5UiZRJ/": "A creator's chicken cutlet tacos at this Long Island-style Italian deli south of Tampa.",
  "southern-luv-bbq-tampa|https://www.instagram.com/p/DTGKcdQDtV6/": "A creator's tray at this Citrus Park barbecue joint — brisket, ribs and the sides that come with them.",
  "due-amici-ybor-tampa|https://www.instagram.com/p/DQHpIgyiQmR/": "A creator's pizza and pasta on Ybor's 7th Avenue, at the room locals argue is the city's best.",
  "el-chuzo-tampa|https://www.instagram.com/p/DKdbsVxoWco/": "A creator takes on the outsized burger at this Colombian grill on North Armenia — a shareable challenge, not a solo lunch.",
  "hungry-crab-tampa|https://www.instagram.com/p/DQ-tsMejvYq/": "A creator's all-you-can-eat seafood boil in New Tampa — crab legs, shrimp and corn by the bag.",
  "jay-luigi-tampa|https://www.instagram.com/p/DU57J1kjgfE/": "A creator's dinner at this SoHo Italian room, one of the highest-rated in the city.",
  "madison-avenue-pizza-dunedin|https://www.instagram.com/p/DTNnJTdCRJR/": "A creator takes on one of the largest pizzas in the country at this Dunedin pizzeria — thin crust, and bigger than the table.",
  "weeki-wachee-springs|https://www.instagram.com/p/DIjUdubpr9w/": "A creator's kayak down the spring run about 45 minutes north of Tampa — 74-degree water year round, with manatees and turtles on the way.",
  "snack-trap-ybor-tampa|https://www.instagram.com/p/DSBwcM1DsBj/": "A creator's stop for the wings at this small Ybor bar.",
  "la-la-cafe-st-petersburg|https://www.instagram.com/p/DbqZ0FDJN9y/": "A Vietnamese cafe on 66th Street North, filmed by a local creator for the matcha and the rubber-duck wall.",
  "arwa-coffee-temple-terrace|https://www.instagram.com/p/DbjAv2TpLzw/": "A Yemeni coffee house in Temple Terrace with a prayer room, filmed by a local creator.",
  "farooj-abo-alabed-temple-terrace|https://www.instagram.com/p/DbQw4TXOyOG/": "Lebanese charcoal-grilled chicken inside the N 56th Street halal food court, filmed by a local creator.",
  "papa-kanafa-temple-terrace|https://www.instagram.com/p/DbQw4TXOyOG/": "Kunafa counter inside the N 56th Street halal food court, filmed by a local creator.",
  "juice-time-temple-terrace|https://www.instagram.com/p/DbQw4TXOyOG/": "Juice and dessert counter inside the N 56th Street halal food court, filmed by a local creator.",
  "qahwtea-tampa|https://www.instagram.com/p/DaTsOPMJOQB/": "A Yemeni coffee shop on East Fowler Avenue, filmed by a local creator before its grand opening.",
  "slap-burger-tampa|https://www.instagram.com/p/Dao-eQ4JOSx/": "A halal smash-burger counter open late, filmed by a local creator.",
  "oou-cha-pinellas-park|https://www.instagram.com/p/DauKX7yp6YH/": "A Tampa Bay tea cafe, filmed by a local creator for the blueberry matcha.",
  "quiero-coffee-sarasota|https://www.instagram.com/p/DaLx1mJJMF-/": "A Latina-owned coffee and matcha stand, filmed by a local creator at a Sarasota event.",
  "annapoorna-rasoi-tampa|https://www.instagram.com/p/DaYKbxwpEg9/": "Halal Indo-Chinese and street-style Indian cooking in Tampa, filmed by a local creator.",
  "alessi-bakeries-tampa|https://www.instagram.com/p/DZ8Di3PpY3X/": "A Tampa bakery and food market running since 1912, filmed by a local creator.",
  "alessi-bakeries-tampa|https://www.instagram.com/p/Dayg5BhB0x6/": "The same Tampa bakery after its renovation, filmed by a second local creator.",
  "brewed-awakening-tampa|https://www.instagram.com/p/DZ2kUZCpGQ1/": "Cuban cold brew in Tampa, filmed by a local creator.",
  "say-coffee-st-petersburg|https://www.instagram.com/p/DZycKGYJyU0/": "A Vietnamese cafe in St. Pete, filmed by a local creator.",
  "say-coffee-st-petersburg|https://www.instagram.com/p/DaBgdAyRrFI/": "The same St. Pete Vietnamese coffee house, filmed by a second local creator.",
  "cococello-st-petersburg|https://www.instagram.com/p/DZsUafKphmW/": "Thai coconut ice cream in St. Pete, filmed by a local creator.",
  "cococello-st-petersburg|https://www.instagram.com/p/DWZzHpACbfI/": "Coconut-bowl ice cream and mango sticky rice matcha, filmed by a local creator.",
  "ichiban-sushi-ramen-tampa|https://www.instagram.com/p/DZQtJKspsqS/": "A Seminole Heights sushi room open four decades, filmed by a local creator.",
  "shanghai-dumpling-house-tampa|https://www.instagram.com/p/DY2lXU_pPSV/": "Handmade soup dumplings in Tampa, filmed by a local creator.",
  "aker-sweets-tampa|https://www.instagram.com/p/DYldoFmJoJ4/": "Nablus-style kunafa and Levantine sweets, filmed by a local creator at the first US location.",
  "pasta-flame-tampa|https://www.instagram.com/p/DYH6ZjtJhcB/": "Tableside cheese-wheel pasta on Cross Creek Boulevard, filmed by a local creator.",
  "pasta-flame-tampa|https://www.instagram.com/p/DVXpNSgAFe4/": "Halal Italian cooking with homemade pasta, filmed by a local creator.",
  "eight-turn-crepe-wesley-chapel|https://www.instagram.com/p/DYQMmZ3J8oG/": "Japanese-style savoury and sweet crepes in Wesley Chapel, filmed by a local creator.",
  "99-cafe-tampa|https://www.instagram.com/p/DXzCBtEpp8Y/": "A South Tampa cafe where the menu runs on 99-cent endings, filmed by a local creator.",
  "la-pinoz-pizza-longwood|https://www.instagram.com/p/DXj4tBfCSOW/": "Halal Indian-style pizza near Orlando, filmed by a local creator.",
  "sufrat-ramallah-tampa|https://www.instagram.com/p/DXddCgICY7U/": "A Palestinian breakfast spread inside Ramallah Market, filmed by a local creator.",
  "ghawar-restaurant-tampa|https://www.instagram.com/p/DXaWmEmifXU/": "Traditional Levantine cooking in Tampa, filmed by a local creator.",
  "soul-of-korea-tampa|https://www.instagram.com/p/DXV25U0iUNw/": "Halal Korean cooking, a Tampa local favourite, filmed by a local creator.",
  "doggy-dogs-tampa|https://www.instagram.com/p/DW2eNA2CcXy/": "A South Tampa food truck doing beef hot dogs and smash burgers, filmed by a local creator.",
  "saki-endless-sushi-hibachi-tampa|https://www.instagram.com/p/DWuYHg3iaqd/": "All-you-can-eat sushi and hibachi in Tampa, filmed by a local creator.",
  "byte-burger-tampa|https://www.instagram.com/p/DWacZcxCWvO/": "A halal smash-burger spot in Tampa, filmed by a local creator.",
  "kubana-kafe-tampa|https://www.instagram.com/p/DU6LRc2iRv9/": "A Cuban-owned coffee shop in South Tampa, filmed by a local creator.",
  "bibimgo-wesley-chapel|https://www.instagram.com/p/DTUBXRjiQgJ/": "Halal Korean rice bowls built to order in Wesley Chapel, filmed by a local creator.",
  "rosto-tampa|https://www.instagram.com/p/DTIndw-iRvy/": "Syrian-style rotisserie chicken in Tampa, filmed by a local creator.",
  "banus-chai-tampa|https://www.instagram.com/p/DSVey-Jies0/": "A Desi chai cart doing pani puri, filmed by a local creator.",
  "qamaria-tampa|https://www.instagram.com/p/DR0SAvGCWbU/": "Chocolate-covered mousse pastries in Tampa Bay, filmed by a local creator.",
  "grind-haus-coffee-lutz|https://www.instagram.com/p/DQKfkSmCZCm/": "A moody rustic cafe at Lutz Lake Crossing, filmed by a local creator.",
  "akasaka-orlando|https://www.instagram.com/p/Da8JslLxxTz/": "A sushi room in Orlando, filmed by a local creator on its new menu.",
  "bloom-ride-orlando|https://www.instagram.com/p/DZ9DwVKCCmO/": "A 90-minute themed afternoon-tea bus ride past Orlando landmarks, filmed by a local creator.",
  "teapioca-lounge-oviedo|https://www.instagram.com/p/DZ-3thLh6_P/": "A boba counter in Oviedo at Alafaya Square, filmed by a local creator.",
  "aurora-at-the-celeste-orlando|https://www.instagram.com/p/DZyARU3RXNB/": "A three-course tasting menu inside The Celeste, filmed by a local creator.",
  "the-dark-room-orlando|https://www.instagram.com/p/DZn50K-RSQF/": "A bar running a month of scratch-made espresso martinis, filmed by a local creator.",
  "azal-coffee-altamonte-springs|https://www.instagram.com/p/DZa-Yp9xa1A/": "Traditional Yemeni coffee and desserts in Altamonte Springs, filmed by a local creator on opening week.",
  "izuki-orlando|https://www.instagram.com/p/DZI2KN3RWf4/": "An 18-course omakase counter in Orlando, filmed by a local creator.",
  "morimoto-asia-orlando|https://www.instagram.com/p/DY98mpQxs_8/": "A pan-Asian dining room at Disney Springs, filmed by a local creator on its Passport to Asia menu.",
  "bar-louie-winter-park|https://www.instagram.com/p/DY72oe6RtmX/": "A Winter Park Village patio bar, filmed by a local creator on its weekday happy hour.",
  "pisco-peruvian-gastrobar-orlando|https://www.instagram.com/p/DY0ObAJRHZZ/": "Peruvian cooking and summer cocktails in Orlando, filmed by a local creator.",
  "ace-cafe-sanford|https://www.instagram.com/p/DYuZBPwxzm5/": "A downtown Sanford room doing live music and Sunday brunch, filmed by a local creator.",
  "wala-la-noodles-orlando|https://www.instagram.com/p/DYksrcuRlwk/": "Hand-pulled beef noodles in Orlando, filmed by a local creator.",
  "hh-bagels-altamonte-springs|https://www.instagram.com/p/DYfAjy0RT-6/": "New-York-style bagels in Altamonte Springs, filmed by a local creator.",
  "woodhouse-spa-altamonte-springs|https://www.instagram.com/p/DYVekDgx_cm/": "A day spa in Altamonte Springs, filmed by a local creator.",
  "parlor-doughnuts-orlando|https://www.instagram.com/p/DYE5N5cR8YB/": "A doughnut counter in Orlando, filmed by a local creator on a limited seasonal box.",
  "banh-mi-go-orlando|https://www.instagram.com/p/DX8ULEFCpvi/": "Banh mi and pho in Orlando's SoDo, filmed by a local creator at its grand opening.",
  "hamlin-house-social-orlando|https://www.instagram.com/p/DXO7EbzkXiB/": "Courts, food and a patio in one room at Hamlin, filmed by a local creator.",
  "baires-grill-orlando|https://www.instagram.com/p/DXKruaXEeT8/": "An Argentine grill in Orlando, filmed by a local creator.",
  "great-big-game-show-orlando|https://www.instagram.com/p/DWkCnINEVAP/": "A team-vs-team live game show in Orlando, filmed by a local creator.",
  "four-flamingos-orlando|https://www.instagram.com/p/DWUovChEda4/": "A Richard Blais seafood room at the Hyatt Regency Grand Cypress, filmed by a local creator.",
  "color-me-mine-altamonte-springs|https://www.instagram.com/p/DaL8-IYRL9a/": "A paint-your-own pottery studio in Altamonte Springs, filmed by a local creator.",
  "grove-resort-water-park-winter-garden|https://www.instagram.com/p/DbbhaJvtlFp/": "An Orlando family resort with its own water park, filmed by a local creator.",
  "volcano-bay-orlando|https://www.instagram.com/p/DXj9uMcgFWc/": "Universal's water park and its after-hours summer nights, filmed by a local creator.",
  "blue-man-group-orlando|https://www.instagram.com/p/Davc2nGt2Jr/": "The Blue Man Group residency at ICON Park, filmed by a local creator.",
  "epic-universe-orlando|https://www.instagram.com/p/DagwO9NgYZw/": "Universal's newest park and its after-hours nights, filmed by a local creator.",
  "aquatica-orlando|https://www.instagram.com/p/DYfPNhxgnIb/": "Aquatica's after-dark Aqua Glow event, filmed by a local creator.",
  "pizza-ponte-disney-springs|https://www.instagram.com/p/DYNN6vfgQ1D/": "Roman-style slices at Disney Springs, filmed by a local creator.",
  "ivory-nail-lounge-orlando|https://www.instagram.com/p/DYAHGzNgaOa/": "A nail salon in the Orlando area, filmed by a local creator.",
  "sage-head-spa-winter-park|https://www.instagram.com/p/DX1ySKLgXFC/": "A head-spa treatment room in Winter Park, filmed by a local creator.",
  "dollywood-splash-country|https://www.instagram.com/p/Da8O6HnApNf/": "Dollywood's water park in the Smoky Mountains, filmed by a Florida creator on a trip.",
  "cookie-dough-bliss-tampa|https://www.instagram.com/p/DbsxXh2hdSD/": "Edible cookie dough by the spoonful in Tampa, filmed by a local creator.",
  "howard-and-platt-tampa|https://www.instagram.com/p/DbqMjUxBpul/": "A SoHo dining room with a Tuesday-to-Friday happy hour, filmed by a local creator.",
  "born-and-bread-bakehouse-lakeland|https://www.instagram.com/p/DbeNz-JhPPx/": "An artisan bakehouse in Lakeland known for croissants and cruffins, filmed by a local creator.",
  "tommys-chophouse-tampa|https://www.instagram.com/p/DbYMItJhBTW/": "A new Ybor steakhouse named for a Tampa architect, filmed by a local creator.",
  "heights-drive-thru-tampa|https://www.instagram.com/p/DbQ4qH9BUjc/": "A drive-thru bodega in Tampa Heights doing coffee, sandwiches and groceries, filmed by a local creator.",
  "heights-drive-thru-tampa|https://www.instagram.com/p/Db4JkEsNn_e/": "A second local creator's drive-thru run here for matcha and soft serve.",
  "circus-arts-foundry-tampa|https://www.instagram.com/p/DbOL3rthpb0/": "Aerial-arts classes for all levels in Tampa Bay, filmed by a local creator.",
  "nueva-cantina-tampa|https://www.instagram.com/p/DbEgtYDhrLD/": "Tequila-infused soft-serve margaritas downtown, filmed by a local creator.",
  "dairy-joy-tampa|https://www.instagram.com/p/DbBwea4h2VX/": "A retro Tampa ice cream stand open since 1958, filmed by a local creator.",
  "loveshackfancy-tampa|https://www.instagram.com/p/Da-lXn3hlOF/": "The brand's first Tampa store, at Hyde Park Village, filmed by a local creator.",
  "birdettes-tampa|https://www.instagram.com/p/Da8AmPGhI6i/": "A craft cafe in Tampa Bay where you make something and take it home, filmed by a local creator.",
  "book-rescuers|https://www.instagram.com/p/Da3vq20h_xT/": "Affordable pre-loved books, filmed by a local creator.",
  "beach-house-coffee-tampa-bay|https://www.instagram.com/p/DawFjyoxUlM/": "A beach-house-styled coffee shop in Tampa Bay, filmed by a local creator.",
  "fit-bowl-co|https://www.instagram.com/p/Dad6iPIBmWC/": "Acai bowls and fruit smoothies, filmed by a local creator.",
  "sunshine-needlepoint-tampa-bay|https://www.instagram.com/p/DaWHxuDyE9a/": "A needlepoint shop in Tampa Bay built for sitting and stitching, filmed by a local creator.",
  "new-york-bagel-cafe-tampa|https://www.instagram.com/p/DaOcFmUy7Iq/": "Bagels and iced coffee inside Carrollwood Village Park, filmed by a local creator.",
  "food-and-beer-tampa|https://www.instagram.com/p/DZvql_MxaOJ/": "Big screens, beer and matchday atmosphere in Tampa, filmed by a local creator.",
  "black-english-bookstore|https://www.instagram.com/p/DZm5GpUx_K3/": "A bookstore and community hub for Black literature and history, filmed by a local creator.",
  "zen-glass-studio-st-petersburg|https://www.instagram.com/p/DZdqNq5RkUd/": "Beginner-friendly glassblowing in St. Pete, filmed by a local creator.",
  "gametime-tampa|https://www.instagram.com/p/DZaOKsDxD3J/": "Arcade games, mini bowling and food under one roof, filmed by a local creator.",
  "roasted813-tampa|https://www.instagram.com/p/DZVkJ70yIsT/": "The viral dot cake, from a Tampa dessert maker, filmed by a local creator.",
  "drip-ybor-tampa|https://www.instagram.com/p/DZI8YuHRPtY/": "A pottery wheel session in Ybor, filmed by a local creator.",
  "forbici-st-petersburg|https://www.instagram.com/p/DcV4QqnxjHU/": "A downtown St. Pete Italian dining room, filmed by a local creator as a date-night pick.",
  "shaker-and-peel-oldsmar|https://www.instagram.com/p/DcSRQteti52/": "Tacos and dessert churros at this Oldsmar restaurant, filmed by a local creator.",
  "cali-st-petersburg|https://www.instagram.com/p/DcOuXfqBCNW/": "Build-your-own bowls and sourdough pizza at this St. Pete kitchen, filmed by a local creator.",
  "buddy-brew-seminole|https://www.instagram.com/p/DcCLHeSPmqd/": "The Tampa roaster's new Seminole coffee counter, filmed by a local creator soon after it opened.",
  "olivia-st-petersburg|https://www.instagram.com/p/Db9vTbIt_k3/": "The tableside chicken parm downtown St. Pete queues for, filmed by a local creator.",
  "park-and-rec-st-petersburg|https://www.instagram.com/p/Db07OFNtdRr/": "A downtown St. Pete bar with arcade games and a first-Friday crowd, filmed by a local creator.",
  "oou-cha-pinellas-park|https://www.instagram.com/p/Dbvj9HmOtuW/": "Matcha, boba and tea flights at this Pinellas Park tea house, filmed by a local creator.",
  "craft-street-kitchen-oldsmar|https://www.instagram.com/p/DboMuwgJylo/": "A scratch-kitchen dinner and dessert in Oldsmar, filmed by a local creator.",
  "starlite-horizon-south-pasadena|https://www.instagram.com/p/Dbl9g3jP7k9/": "Dinner and sunset from a St. Pete dining yacht — a creator's date-night pick.",
  "central-park-food-hall-st-petersburg|https://www.instagram.com/p/Dba4caAul17/": "A Central Avenue food hall whose Sunday market fills with local makers, filmed by a local creator.",
  "pin-on-grand-st-petersburg|https://www.instagram.com/p/DbY9yEWveE5/": "An $18 sushi lunch set in St. Pete's Grand Central district, filmed by a local creator.",
  "new-power-medicine-st-petersburg|https://www.instagram.com/p/DbWnntHPfiM/": "A St. Pete wellness clinic offering IV drips and holistic consultations, filmed by a local creator.",
  "zees-barbeque-st-petersburg|https://www.instagram.com/p/DbOEwJiu9BC/": "Barbecue from a small counter on St. Pete's 22nd Street South, filmed by a local creator.",
  "dolphin-racer-south-pasadena|https://www.instagram.com/p/DbHHttOP2lo/": "A dolphin-watching run out of the St. Pete Beach causeway, filmed by a local creator.",
  "eclipse-cafe-tampa|https://www.instagram.com/p/Da6Fl_8PRIE/": "Mushroom coffee and matcha at this Carrollwood cafe, filmed by a local creator.",
  "dirty-laundry-st-petersburg|https://www.instagram.com/p/Da00b0QP3zu/": "A Grand Central speakeasy St. Pete goes to dance, filmed by a local creator.",
  "the-bagel-nook-tampa|https://www.instagram.com/p/Da0oFQas_m5/": "Stuffed bagels for a downtown Tampa breakfast, filmed by a local creator.",
  "kungfu-kitchen-brandon|https://www.instagram.com/p/DayK-rgun66/": "Hand-pulled noodles, soup dumplings and chocolate dumplings in Brandon, filmed by a local creator.",
  "fusillo-st-petersburg|https://www.instagram.com/p/DavfhuHuv9J/": "Fresh pasta and tiramisu on Central Avenue, filmed by a local creator.",
  "agave-social-tampa|https://www.instagram.com/p/DafzW8tu19B/": "Tacos and strawberry margaritas in Carrollwood — a creator's date-night pick.",
  "sodough-square-st-petersburg|https://www.instagram.com/p/DUWx4GQjwMt/": "Sourdough pizza from this St. Pete bakery and pizzeria, filmed by a local creator.",
  "alfreds-bakery-doral|https://www.instagram.com/p/Dap7jd8Ot6V/": "A Venezuelan bakery in Doral doing sourdough, sweet breads and imported cheeses, filmed by a local creator.",
  "alfreds-bakery-doral|https://www.instagram.com/p/DWrAtrHjisw/": "The same creator's earlier visit to this Doral Venezuelan bakery.",
  "kaseya-center-miami|https://www.instagram.com/p/DXIFkaPE_JV/": "What to do at a Miami Heat game beyond the game itself, filmed by a local creator.",
  "kaseya-center-miami|https://www.instagram.com/p/DWbkA83jiz-/": "The two cocktail stops on the arena's main concourse, filmed by a local creator.",
  "arepera-araguaney-miami|https://www.instagram.com/p/DcWG3n4uMQj/": "Homemade Venezuelan arepas with more than twenty fillings, filmed by a local creator.",
  "south-florida-off-road-tours-miami|https://www.instagram.com/p/DcRx5FMznfn/": "Night ATV runs in the Redland on Thursday through Saturday, filmed by a local creator.",
  "aloha-catering-medley|https://www.instagram.com/p/DcPNRWCzJzH/": "All-you-can-eat sushi every evening from 6:30pm, filmed by a local creator.",
  "la-esquina-del-chicharron-miami|https://www.instagram.com/p/Db_pGQ3T50c/": "Dominican street food in Wynwood built around oven-roasted chicharrón, filmed by a local creator.",
  "manasota-key-resort-englewood|https://www.instagram.com/p/Db6f1xAzXOz/": "A Gulf-side resort with a private beach, about three hours from Miami, filmed by a local creator.",
  "rio-grande-coral-way-miami|https://www.instagram.com/p/Dav1ElQzMuM/": "Brazilian rodizio on Coral Way — the servers keep coming while your disc stays green, filmed by a local creator.",
  "madame-olivia-midtown-miami|https://www.instagram.com/p/Dak2E0UOcdd/": "The bakery's second location, in Midtown, doing breakfast and brunch, filmed by a local creator.",
  "hakuna-matata-pizzeria-miami|https://www.instagram.com/p/DajB-LGTgok/": "Cuban-style pizza — thick, airy, with a crisp cheese crust around the edge, filmed by a local creator.",
  "la-macha-taqueria-doral|https://www.instagram.com/p/DagbmIfTXeQ/": "Sinaloa-style tacos with tortillas pressed through the day and mesquite-grilled meat, filmed by a local creator.",
  "mister-o1-wynwood-miami|https://www.instagram.com/p/DadEBlNuu97/": "An Ecuadorian-inspired pizza built with a guest chef at this Wynwood pizzeria, filmed by a local creator.",
  "mister-1111-medley|https://www.instagram.com/p/DZ7tQqJOnQg/": "Venezuelan cachapas made from corn ground the same day, filmed by a local creator.",
  "inka-nikkei-miami|https://www.instagram.com/p/DZzv0iCucEs/": "Peruvian-Japanese nikkei cooking in west Kendall, filmed by a local creator.",
  "the-best-acai-miami-beach|https://www.instagram.com/p/DZvjdRiTC8X/": "Brazil's self-serve açaí chain, at its first North American counter on Lincoln Road, filmed by a local creator.",
  "veganlitaly-coral-gables|https://www.instagram.com/p/DZs4a5uT94X/": "A small plant-based trattoria on Calle Ocho doing pasta, pizza and lasagna, filmed by a local creator.",
  "sano-food-doral|https://www.instagram.com/p/DZm30_eO869/": "Made-to-order healthy plates in Doral, filmed by a local creator.",
  "blast-house-burgers-miami|https://www.instagram.com/p/DZh1MTfOeco/": "Certified-angus classics, smash and grilled-chicken burgers on Bird Road, filmed by a local creator.",
  "7tyone-miami-beach|https://www.instagram.com/p/DZKtUL-uJFa/": "Venezuelan arepas, empanadas and cachapas on Normandy Isle from 8am daily, filmed by a local creator.",
  "madame-olivia-north-miami|https://www.instagram.com/p/DYkFfG7uw-M/": "Naturally leavened sourdough and French pastry, baked daily, filmed by a local creator.",
  "fresh-salad-doral|https://www.instagram.com/p/DYe7vNvOpgz/": "All-day breakfast made in house in Doral, filmed by a local creator.",
  "hot-dog-maracay-miami|https://www.instagram.com/p/DYXQ8O1OC7T/": "Venezuelan street-style hot dogs, one of four stops on a local creator's guide.",
  "the-barking-bun-miami|https://www.instagram.com/p/DYXQ8O1OC7T/": "Venezuelan street-style hot dogs downtown, one of four stops on a local creator's guide.",
  "el-lider-hialeah|https://www.instagram.com/p/DYXQ8O1OC7T/": "Venezuelan street-style hot dogs in Hialeah, one of four stops on a local creator's guide.",
  "pal-perrero-miami|https://www.instagram.com/p/DYXQ8O1OC7T/": "Venezuelan street-style hot dogs near Doral, one of four stops on a local creator's guide.",
  "forages-southwest-ranches|https://www.instagram.com/p/DZYRjgxzXip/": "A family ranch outside Miami grilling meat over open wood, open daily from 8am, filmed by a local creator.",
  "crete-frozen-yogurt-medley|https://www.instagram.com/p/DYCnLF0uM_a/": "House-made frozen yogurt with twenty-plus toppings, filmed by a local creator.",
  "san-marco-miami-beach|https://www.instagram.com/p/DZGQfZDzrHu/": "An Italian dining room in South Beach, filmed by a local creator.",
  "sardellis-hollywood|https://www.instagram.com/p/DZPymLiOXdF/": "A four-floor Italian steakhouse by the beach — a creator's date-night pick.",
  "nino-gordo-wynwood-miami|https://www.instagram.com/p/DYSwfAiT9yk/": "Argentine grill crossed with Asian technique in Wynwood, filmed by a local creator.",
  "parrillada-da-silva-doral|https://www.instagram.com/p/DZDBw1ruGAE/": "Home-style bowls from $14.99 at this Doral grill, filmed by a local creator.",
  "stl-cafe-miami|https://www.instagram.com/p/DY0O1O-TozG/": "Soufflé pancakes and 3D latte art at this Asian-inspired cafe, filmed by a local creator.",
  "mokah-wynwood-miami|https://www.instagram.com/p/DYuVObYubwx/": "Miami's first jianbing counter — Chinese savoury crepes made to order, filmed by a local creator.",
  "sawa-coral-gables|https://www.instagram.com/p/DYrziHCusqY/": "One stop on a local creator's martini crawl through Miami bars.",
  "balloon-museum-miami|https://www.instagram.com/p/DYcTrZMOOw8/": "The Pop Air exhibition at Mana Wynwood — twenty-plus inflatable installations you walk inside, filmed by a local creator.",
  "oh-mamma-miami|https://www.instagram.com/p/DYZu42MOtED/": "Artisan breads, pastry and fresh pasta from the Pasta Market owners, filmed by a local creator.",
  "brutal-pepitos-miami|https://www.instagram.com/p/DYQLwqBzs12/": "Barquisimeto-style Venezuelan pepitos with fourteen-plus fillings, filmed by a local creator.",
  "piacere-pizza-doral|https://www.instagram.com/p/DYKSxxxOC3z/": "A wood-fired pizzeria in Doral, filmed by a local creator at its opening.",
  "mister-corn-doral|https://www.instagram.com/p/DYHtUMOuwXd/": "Venezuelan empanadas milled from pilled corn — pickup and delivery only, filmed by a local creator.",
  "el-sushi-by-soya-doral|https://www.instagram.com/p/DX-DTrnz9hG/": "A weekday happy hour of two full-size rolls for $16, dine-in only, filmed by a local creator.",
  "plant-the-future-miami|https://www.instagram.com/p/DX4QCsIOO4g/": "A botanical art gallery and plant shop in Little River, filmed by a local creator.",
  "southwest-ranches-farmers-market|https://www.instagram.com/p/DXzMGabOvFV/": "A covered open-air market of food stalls near Weston, closed Mondays, filmed by a local creator.",
  "sifu-doral|https://www.instagram.com/p/DXwo-rDuSux/": "Venezuelan coastal seafood — whole stuffed snapper and shrimp cups, filmed by a local creator.",
  "rosso-coffee-club-davie|https://www.instagram.com/p/DWEKQtLjtzt/": "A plant-filled coffee bar in Davie, filmed by a local creator.",
  "305-peruvian-miami|https://www.instagram.com/p/DXmPFRPDlw2/": "Peruvian cooking on Eighth Street with plating well above its price, filmed by a local creator.",
  "etaru-hallandale-beach|https://www.instagram.com/p/DXfQOTdEwth/": "Japanese robatayaki right on the sand — a creator's date-night and celebration pick.",
  "pincho-west-flagler-miami|https://www.instagram.com/p/DXb_Pvxjk2R/": "Weekday $10 daily specials at the West Flagler location, filmed by a local creator.",
  "rio-grande-hollywood|https://www.instagram.com/p/DXXiUI9k9bs/": "Unlimited Brazilian rodizio in Hollywood with a full salad bar, filmed by a local creator.",
  "parrilla-point-medley|https://www.instagram.com/p/DXPHNmHDmeb/": "Venezuelan mixed grill in portions for one, two or five, filmed by a local creator.",
  "frenchies-calientes-southwest-ranches|https://www.instagram.com/p/DXKqT6EE8S0/": "Venezuelan street-style hot dogs, one of four stops on a local creator's guide.",
  "naguara-hot-dogs-miami|https://www.instagram.com/p/DXKqT6EE8S0/": "Venezuelan street-style hot dogs near Doral, one of four stops on a local creator's guide.",
  "diyon-hotdogs-miami|https://www.instagram.com/p/DXKqT6EE8S0/": "Venezuelan street-style hot dogs in Allapattah, one of four stops on a local creator's guide.",
  "metro-caracas-hotdog-miami|https://www.instagram.com/p/DXKqT6EE8S0/": "Venezuelan street-style hot dogs in Edgewater, one of four stops on a local creator's guide.",
  "casa-tua-cucina-wynwood-miami|https://www.instagram.com/p/DXEyDFsjjmS/": "The Wynwood edition of Casa Tua's open-kitchen market hall, filmed by a local creator soon after it opened.",
  "ava-coconut-grove-miami|https://www.instagram.com/p/DW_nHsijgDq/": "A prix-fixe weekend brunch in Coconut Grove, filmed by a local creator.",
  "by-brothers-miami|https://www.instagram.com/p/DW6dkXnDrJO/": "Part farm, part fairground, open daily in the Redland, filmed by a local creator.",
  "lira-house-wynwood-miami|https://www.instagram.com/p/DW2DqvZCS-z/": "Lebanese cooking around one of Wynwood's quietest courtyards, filmed by a local creator.",
  "lentrecote-sunny-isles-beach|https://www.instagram.com/p/DWwKRhvDr_y/": "A French room with one thing on the menu: steak frites, salad and unlimited fries, filmed by a local creator.",
  "superblue-miami|https://www.instagram.com/p/DWmqq4JDjhi/": "An immersive art house where the rooms react to you, filmed by a local creator.",
  "le-specialita-coconut-grove-miami|https://www.instagram.com/p/DWhhYt0DvB9/": "An Italian cafe downstairs and a pasta market upstairs, inside Mr. C in Coconut Grove, filmed by a local creator.",
  "majestic-portuguese-bakehouse-miami|https://www.instagram.com/p/DWeMFQSjn9e/": "Miami's Portuguese bakery, everything made in house, filmed by a local creator.",
  "milagros-farm-miami|https://www.instagram.com/p/DWZCiwujhpC/": "A weekends-only outdoor family spot in the Redland with free activities for kids, filmed by a local creator.",
  "mayami-wynwood-miami|https://www.instagram.com/p/DWUpDtpjpLX/": "A Wynwood restaurant and bar with live music, open to 3am daily, filmed by a local creator.",
  "tu-sancocho-express-doral|https://www.instagram.com/p/DWJoyzaDvVQ/": "Saturday-only sancocho and mondongo from a twenty-year family recipe, filmed by a local creator.",
  "pasta-e-basta-miami|https://www.instagram.com/p/DV80-8Rjvzl/": "An Italian dining room a local creator rates among Miami's best.",
  "signor-sassi-hallandale-beach|https://www.instagram.com/p/DV6IuicDhpa/": "The London Italian institution's Florida dining room, filmed by a local creator.",
  "el-nano-coral-gables|https://www.instagram.com/p/DV1EEk_jsIl/": "Ecuadorian classics — bolón, encebollado and ceviche — on Miracle Mile, filmed by a local creator.",
  "mangiamo-doral|https://www.instagram.com/p/DVwiZaXju28/": "Italian schiacciata sandwiches on house sourdough, from a truck, filmed by a local creator.",
  "canta-corazon-wynwood-miami|https://www.instagram.com/p/DVoHYrrDiBu/": "A rodeo-themed Wynwood bar with a mechanical bull and live shows, filmed by a local creator.",
  "madison-avenue-pizza-dunedin|https://www.instagram.com/p/DOWPbDKjXom/": "A Dunedin pizzeria known for an outsized pie and house wing sauces, filmed by a local creator.",
  "sogna-napoli-tampa|https://www.instagram.com/p/C_i-9OFxzKh/": "Neapolitan dough, truffle-honey pizza and pistachio lasagna in Carrollwood, filmed by a local creator.",
  "burger-culture-lutz|https://www.instagram.com/p/DcRnHGjppJT/": "A north Tampa burger truck whose coated fries a local creator rated as highly as the patties.",
  "lady-and-the-mug-tampa|https://www.instagram.com/p/DcMgE1QpSX9/": "A specialty coffee shop just outside Hyde Park, filmed by a local creator.",
  "farooj-abo-alabed-temple-terrace|https://www.instagram.com/p/DcKI6tHAdvS/": "Lebanese cooking in the Terrace Oaks food hall, alongside kunafa and Dubai-chocolate desserts, filmed by a local creator.",
  "bodega-bus-tampa|https://www.instagram.com/p/DcHUNpnpGKK/": "A downtown Tampa late-night counter and convenience stop, open 7am to 4am, filmed by a local creator.",
  "sodough-square-tampa|https://www.instagram.com/p/DcBueVYux2S/": "Detroit-style pizza at the brand's Tampa location, filmed by a local creator.",
  "ebisu-tampa|https://www.instagram.com/p/Db60LmPJd2e/": "A Japanese department store in New Tampa — gashapon, collectibles, snacks, stationery and plushies, filmed by a local creator.",
  "brewly-cafe-tampa|https://www.instagram.com/p/Db4EfTYJM_n/": "A coffee truck by the Tampa Riverwalk doing pineapple matcha and pastries, filmed by a local creator.",
  "station-house-bbq-tampa|https://www.instagram.com/p/Dby6I8HJY78/": "Brisket, ribs and pulled pork on Nebraska Avenue — barbecue Friday and Saturday, Cubans on Thursday, filmed by a local creator.",
  "ploy-thai-brandon|https://www.instagram.com/p/DbtAgOvuTOO/": "A Brandon Thai dining room a local creator singled out for the duck panang.",
  "sofresh-tampa|https://www.instagram.com/p/DbqULBMuaMf/": "Build-your-own protein bowls and wraps downtown, filmed by a local creator.",
  "cairo-cravings-temple-terrace|https://www.instagram.com/p/Dbi1cHNuK0r/": "Egyptian feteer and koshari, fully halal, filmed by a local creator.",
  "brick-and-mortar-st-petersburg|https://www.instagram.com/p/DbbHW8COJxe/": "A Central Avenue dining room a local creator calls her staple St. Pete date night — braised short rib over house-made noodles.",
  "nazs-halal-tampa|https://www.instagram.com/p/DbV5JkkOqPJ/": "Halal chicken-and-rice platters and chopped cheese near USF, filmed by a local creator.",
  "perro-y-salsa-tampa|https://www.instagram.com/p/DbQnTFUuCh6/": "Venezuelan street hot dogs and oversized sandwiches from a Tampa truck, filmed by a local creator.",
  "marina-grille-clearwater-beach|https://www.instagram.com/p/DbHE8hGJ7pR/": "Waterfront seafood and sushi above the Clearwater Beach marina, filmed by a local creator.",
  "the-red-bird-temple-terrace|https://www.instagram.com/p/DbEafgeJt4J/": "Halal hot chicken and a lemon-forward Caesar wrap, filmed by a local creator.",
  "ganges-sarasota|https://www.instagram.com/p/Da-m1xiOmHA/": "Indian cooking with tableside service in Sarasota, filmed by a local creator.",
  "sunda-new-asian-tampa|https://www.instagram.com/p/DayaiokJw2k/": "Asian fusion in Midtown Tampa — a local creator's date-night pick.",
  "alimento-tampa|https://www.instagram.com/p/DavUl-jOt2i/": "Seed-oil-free build-your-own bowls, tucked inside a Dale Mabry dealership, filmed by a local creator.",
  "happy-fish-tampa|https://www.instagram.com/p/Dagf38apoqC/": "Peruvian classics — pulpo anticuchero, tallarines verdes and suspiro a la limeña, filmed by a local creator.",
  "rock-n-roll-sushi-apollo-beach|https://www.instagram.com/p/DabG49Gp5O6/": "A guitar-shaped sushi platter in Apollo Beach, filmed by a local creator.",
  "international-plaza-tampa|https://www.instagram.com/p/DaQh0dOuUNg/": "Bay Street's restaurant row at Tampa's International Plaza, walked end to end by a local creator.",
  "slap-burger-tampa|https://www.instagram.com/p/DZ-VnHaOu1c/": "Smash burgers, tenders and bowls on Bruce B Downs, filmed by a local creator.",
  "con-amor-tampa|https://www.instagram.com/p/DZ0AnocOmW5/": "Soft-serve margaritas and a tapas-sized summer menu in Seminole Heights, filmed by a local creator.",
  "sea-worthy-fish-bar-tierra-verde|https://www.instagram.com/p/DZnOZbCuVRa/": "Seafood and pasta on the Pinellas Bayway, near Pass-a-Grille, filmed by a local creator.",
  "tommys-chophouse-tampa|https://www.instagram.com/p/Db9PerOJKxm/": "A second local creator marked its Ybor opening \u2014 the steakhouse is trading now.",
  "roasted813-tampa|https://www.instagram.com/p/Da8MiUSu9nR/": "A second local creator's two-pound Dubai-chocolate dessert platter from the same Temple Terrace counter.",
};

/** The caption for a curated video, or "" when none was written. Never throws. */
export function captionFor(video) {
  if (!video || typeof video.url !== "string" || !video.url) return "";
  return CAPTIONS[(video.k || "") + "|" + video.url] || "";
}
