// lib/curated.js
// GabeGOL's curated Wayfind picks — first-party local knowledge, hand-tagged
// into intents so "I want to be outside" etc. surface these, and flagged
// `featured: true` so they get a visibility boost in ranking.
//
// intents (cross-category vibes, v4.78): "outdoors" | "hiddengems" |
//   "bucketlist" | "familyfun" — must match the intent keys in EXPERIENCES
//   (app/page.js). A curated place tagged with a vibe always passes that
//   vibe's filter.
// tags (secondary filters/collections): romantic, datenight, beach, waterfront,
//   breakfast, brunch, coffee, dessert, seafood, nightlife, bar, rooftop,
//   family, iconicflorida, instagrammable, groups, livemusic, view
//
// priceNum: 0 Free · 1 $ · 2 $$ · 3 $$$ · 4 $$$$ (null = attraction/beach/park)
// Rating & reviews are the user-supplied Google values at time of curation.

export const CURATED = [
  // ── Sarasota ────────────────────────────────────────────────────────────
  { name: "Morton's Gourmet Market", area: "Sarasota", rating: 4.6, reviews: 1624, priceNum: null, category: "Gourmet Grocery", distMi: 22,
    intents: ["hiddengems"], tags: ["dessert"],
    hook: "The elevated grab-and-go locals use for picnics and dessert.",
    funFact: "Known for its Firehouse Chili Cook Off around October.",
    mustSee: "The bakery and prepared-food cases.",
    tip: "Great for picnic supplies, desserts, or something elevated without a full restaurant meal." },

  { name: "Perq Coffee Bar", area: "Sarasota", rating: 4.7, reviews: 604, priceNum: 1, category: "Coffee shop", distMi: 22,
    intents: ["hiddengems"], tags: ["coffee", "brunch"],
    hook: "One of Sarasota's strongest coffee stops.",
    funFact: "Latte art is a good sign the baristas care about technique.",
    mustSee: "The coffee presentation and outdoor seating.",
    tip: "Best for coffee lovers, remote work, or a slow morning." },

  { name: "Mote Marine Laboratory", area: "Sarasota", rating: 4.7, reviews: 9828, priceNum: null, category: "Aquarium", distMi: 22,
    intents: ["familyfun", "hiddengems"], tags: ["family"],
    hook: "Sharks, sea turtles, manatees, and real ocean research in action.",
    funFact: "Mote is both an aquarium and an active marine research lab.",
    mustSee: "The shark and sea turtle exhibits.",
    tip: "Go early and pair it with Lido Key or St. Armands." },

  { name: "The Blind Goat Food & Drink Co.", area: "Sarasota", rating: 4.5, reviews: 1093, priceNum: 2, category: "Grill", distMi: 22,
    intents: ["hiddengems"], tags: ["groups", "nightlife", "bar"],
    hook: "A hidden-gem grill with bold comfort food and a local-bar feel.",
    funFact: "The red-and-black interior gives it more personality than a standard sports bar.",
    mustSee: "The bar area and loaded plates.",
    tip: "Good for groups, casual dinner, and late-night food." },

  { name: "Bushido Sushi SRQ", area: "Sarasota", rating: 4.8, reviews: 301, priceNum: 2, category: "Sushi", distMi: 22,
    intents: ["hiddengems"], tags: ["datenight"],
    hook: "Creative rolls and chef-driven presentation with a personal, local feel.",
    funFact: "The owner's name is John — a real small-business connection.",
    mustSee: "The plated specialty rolls.",
    tip: "Ask for the chef's recommendation." },

  { name: "Chart House", area: "Sarasota", rating: 4.2, reviews: 2023, priceNum: 3, category: "Seafood", distMi: 22,
    intents: [], tags: ["romantic", "datenight", "waterfront", "seafood", "view"],
    hook: "Romantic waterfront seafood with bay views and special-occasion energy.",
    funFact: "Chart House locations are known for scenic waterfront settings.",
    mustSee: "Window or patio seating near sunset.",
    tip: "Go for the view and atmosphere." },

  { name: "Cask and Ale", area: "Sarasota", rating: 4.4, reviews: 705, priceNum: 2, category: "Cocktail Bar", distMi: 21,
    intents: [], tags: ["datenight", "bar", "nightlife"],
    hook: "Downtown cocktail-and-whiskey spot with an easy dinner-to-night-out feel.",
    funFact: "Leans into craft cocktails, wine, and whiskey over basic bar drinks.",
    mustSee: "The bar setup and cocktail presentations.",
    tip: "Best for date-night drinks or a classy first stop before downtown." },

  { name: "Mattison's City Grille", area: "Sarasota", rating: 4.2, reviews: 2184, priceNum: 2, category: "American", distMi: 21,
    intents: [], tags: ["livemusic", "nightlife", "groups"],
    hook: "Outdoor dining, live music, and Main Street Sarasota energy in one place.",
    funFact: "One of the easiest spots to feel downtown Sarasota nightlife without a club.",
    mustSee: "The outdoor patio when music is playing.",
    tip: "Go on a live music night." },

  { name: "The Gator Club", area: "Sarasota", rating: 3.9, reviews: 498, priceNum: 1, category: "Nightclub", distMi: 21,
    intents: [], tags: ["nightlife", "bar"],
    hook: "Historic downtown nightlife with cocktails, dancing, and a classic neon sign.",
    funFact: "The building is one of Sarasota's older downtown landmarks.",
    mustSee: "The glowing Gator sign at night.",
    tip: "Best later in the evening, not an early dinner stop." },

  { name: "Sage Restaurant", area: "Sarasota", rating: 4.4, reviews: 617, priceNum: 4, category: "Fine Dining", distMi: 21,
    intents: [], tags: ["romantic", "datenight"],
    hook: "Upscale dinner with dramatic interiors and special-occasion energy.",
    funFact: "Housed in a historic building, giving the dining room real character.",
    mustSee: "The upstairs dining room and rooftop-style atmosphere.",
    tip: "Save this for anniversaries, birthdays, or client dinners." },

  { name: "Art Ovation Hotel, Autograph Collection", area: "Sarasota", rating: 4.5, reviews: 1586, priceNum: null, category: "Hotel", distMi: 21,
    intents: ["hiddengems"], tags: ["rooftop", "instagrammable", "view"],
    hook: "Creative downtown hotel with rooftop parties and art-forward design.",
    funFact: "Built around rotating art and live creative experiences.",
    mustSee: "The rooftop pool deck.",
    tip: "Great for drinks, events, or a stylish staycation." },

  { name: "Perspective Rooftop Pool Bar", area: "Sarasota", rating: 4.4, reviews: 466, priceNum: 2, category: "Rooftop Bar", distMi: 21,
    intents: [], tags: ["rooftop", "bar", "view", "datenight", "instagrammable"],
    hook: "Rooftop pool bar with city views, cocktails, and golden-hour vibes.",
    funFact: "Rooftops hit harder in Sarasota — city, water, and golden light together.",
    mustSee: "The skyline view from the pool deck.",
    tip: "Go before sunset and grab photos before it gets crowded." },

  { name: "KOJO", area: "Sarasota", rating: 4.6, reviews: 775, priceNum: 3, category: "Asian", distMi: 21,
    intents: ["hiddengems"], tags: ["datenight", "groups"],
    hook: "One of Sarasota's best upscale Asian restaurants — bao, truffle dumplings, wagyu noodles.",
    funFact: "Blends Japanese, Korean, and modern Asian influences.",
    mustSee: "The green KOJO wall and beautifully plated dishes.",
    tip: "Order several plates to share." },

  { name: "The Westin Sarasota", area: "Sarasota", rating: 4.4, reviews: 2620, priceNum: null, category: "Hotel", distMi: 21,
    intents: ["hiddengems"], tags: ["rooftop", "view"],
    hook: "Downtown hotel with one of the best rooftop views in the city.",
    funFact: "The rooftop gives both city and bay views.",
    mustSee: "The rooftop bar/pool at sunset.",
    tip: "Even if you're not staying, check whether rooftop access is available." },

  { name: "Patrona Coastal Cafe", area: "Sarasota", rating: 4.0, reviews: 660, priceNum: 1, category: "Coffee shop", distMi: 21,
    intents: [], tags: ["coffee"],
    hook: "Tropical coastal café with palm-shaded seating and a beachy feel.",
    funFact: "The patio atmosphere is stronger than the rating suggests.",
    mustSee: "The outdoor seating and colorful drinks.",
    tip: "Best for a casual coffee stop, not a destination meal." },

  { name: "Tamiami Tap", area: "Sarasota", rating: 4.6, reviews: 536, priceNum: 2, category: "Taproom", distMi: 21,
    intents: ["hiddengems"], tags: ["groups", "bar"],
    hook: "Lively taproom-style spot with drinks and shareable plates.",
    funFact: "The name nods to Tamiami Trail, one of Florida's most iconic old highways.",
    mustSee: "The bar area when it's busy.",
    tip: "Good for groups and pre-dinner drinks." },

  { name: "Unconditional Surrender", area: "Sarasota", rating: 4.7, reviews: 1767, priceNum: null, category: "Tourist attraction", distMi: 21,
    intents: ["outdoors", "hiddengems", "familyfun"], tags: ["instagrammable", "waterfront", "family"],
    hook: "Sarasota's giant kissing statue — a signature bayfront photo stop.",
    funFact: "Based on the famous WWII V-J Day kiss image.",
    mustSee: "The statue at night or with the marina behind it.",
    tip: "Pair it with Marina Jack and Bayfront Park." },

  { name: "LeBarge Tropical Cruises", area: "Sarasota", rating: 4.6, reviews: 951, priceNum: null, category: "Boat tour", distMi: 21,
    intents: ["outdoors", "hiddengems"], tags: ["datenight", "waterfront", "view"],
    hook: "Tropical boat cruise with bay views, dolphins if you're lucky, and sunset energy.",
    funFact: "Sunset cruises are one of the best ways to see Sarasota from a new angle.",
    mustSee: "Sunset over the bay from the upper deck.",
    tip: "Book the sunset cruise." },

  { name: "Marina Jack", area: "Sarasota", rating: 4.4, reviews: 7245, priceNum: 2, category: "Seafood", distMi: 21,
    intents: [], tags: ["waterfront", "seafood", "livemusic", "view"],
    hook: "Waterfront classic with marina views and live music downstairs.",
    funFact: "Sits right on Sarasota Bay — one of the city's most recognizable spots.",
    mustSee: "Outdoor seating near sunset.",
    tip: "Lower level is better for casual drinks and music." },

  { name: "O'Leary's Tiki Bar & Grill", area: "Sarasota", rating: 4.4, reviews: 4785, priceNum: 1, category: "Tiki Bar", distMi: 22,
    intents: [], tags: ["waterfront", "bar", "view"],
    hook: "Laid-back waterfront tiki bar with a vacation feel downtown.",
    funFact: "One of the easiest places to get that 'Florida lunch by the water' feeling.",
    mustSee: "Yellow umbrellas and waterfront tables.",
    tip: "Go for lunch and keep expectations casual." },

  { name: "Bayfront Park", area: "Sarasota", rating: 4.8, reviews: 6047, priceNum: null, category: "City park", distMi: 22,
    intents: ["outdoors", "hiddengems", "familyfun"], tags: ["waterfront", "family", "view", "instagrammable"],
    hook: "Scenic waterfront park with walking paths, marina views, and public art.",
    funFact: "One of the best free ways to experience downtown Sarasota's waterfront.",
    mustSee: "The colorful entrance, bay views, and sunset walkway.",
    tip: "Combine it with O'Leary's, Marina Jack, and Unconditional Surrender." },

  { name: "Marie Selby Botanical Gardens", area: "Sarasota", rating: 4.7, reviews: 6452, priceNum: null, category: "Botanical garden", distMi: 22,
    intents: ["outdoors", "hiddengems", "familyfun"], tags: ["waterfront", "instagrammable", "family"],
    hook: "Waterfront gardens known for orchids, banyan trees, and bay views.",
    funFact: "Selby is internationally known for its orchid and epiphyte collections.",
    mustSee: "The banyan trees and bayfront garden paths.",
    tip: "Go in the morning for cooler weather and better photos." },

  { name: "Ringling Bridge Causeway Park", area: "Sarasota", rating: 4.8, reviews: 694, priceNum: null, category: "Park", distMi: 22,
    intents: ["outdoors", "hiddengems"], tags: ["waterfront", "instagrammable", "view"],
    hook: "One of Sarasota's best sunset-photo spots with bridge and bay views.",
    funFact: "The Ringling Bridge is one of the city's most photographed landmarks.",
    mustSee: "Sunset behind the palms and bridge.",
    tip: "Bring a camera and go during golden hour." },

  { name: "Ca' d'Zan", area: "Sarasota", rating: 4.8, reviews: 3261, priceNum: null, category: "Historical Museum", distMi: 19,
    intents: ["bucketlist", "hiddengems"], tags: ["iconicflorida", "instagrammable", "waterfront", "view"],
    hook: "The breathtaking Venetian-inspired mansion of circus legend John Ringling.",
    funFact: "Nearly every room is filled with priceless European art and antiques.",
    mustSee: "The marble courtyard, Venetian architecture, and sunset over Sarasota Bay.",
    tip: "Visit after The Ringling Museum; arrive late afternoon for the best light." },

  // ── Tampa / Hyde Park / Ybor / Downtown ─────────────────────────────────
  { name: "Timpano Hyde Park", area: "Tampa", rating: 4.1, reviews: 2066, priceNum: 3, category: "Restaurant", distMi: 22,
    intents: [], tags: ["romantic", "datenight"],
    hook: "Polished Hyde Park date-night spot with steakhouse energy and cocktails.",
    funFact: "Hyde Park is one of Tampa's best areas for upscale walkable dining.",
    mustSee: "The patio and dramatic interior lighting.",
    tip: "Best for a fancy date, not a casual bite." },

  { name: "Craft Tampa", area: "Tampa", rating: 4.6, reviews: 462, priceNum: 4, category: "Restaurant", distMi: 22,
    intents: ["hiddengems"], tags: ["romantic", "datenight", "waterfront", "view"],
    hook: "A floating dining experience that turns dinner into a date-night cruise.",
    funFact: "The boat setting makes the view part of the meal.",
    mustSee: "Skyline views from the deck.",
    tip: "Book ahead and treat it like an experience, not just dinner." },

  { name: "Terra Gaucha Brazilian Steakhouse", area: "Tampa", rating: 4.8, reviews: 7253, priceNum: 3, category: "Steakhouse", distMi: 22,
    intents: ["hiddengems"], tags: ["groups", "datenight"],
    hook: "High-end churrascaria with endless carved meats and big celebration energy.",
    funFact: "Brazilian rodízio service brings grilled meats tableside until you tap out.",
    mustSee: "Picanha and the gourmet salad bar.",
    tip: "Arrive hungry and skip heavy snacks beforehand." },

  { name: "Water Street Tampa", area: "Tampa", rating: null, reviews: null, priceNum: null, category: "District", distMi: 22,
    intents: ["outdoors"], tags: ["waterfront", "view", "groups"],
    hook: "Modern waterfront district with restaurants, events, and walkable downtown energy.",
    funFact: "One of Tampa's biggest new urban redevelopment areas.",
    mustSee: "Waterfront views and event nights.",
    tip: "Check the event calendar before going." },

  { name: "Yacht StarShip Cruises & Events", area: "Tampa", rating: 4.4, reviews: 2200, priceNum: null, category: "Dinner Cruise", distMi: 22,
    intents: ["outdoors"], tags: ["romantic", "datenight", "waterfront", "view"],
    hook: "A dinner-cruise experience with skyline views, water, and music.",
    funFact: "Seeing downtown Tampa from the water makes the city feel completely different.",
    mustSee: "Sunset or evening skyline views from the deck.",
    tip: "Best for anniversaries or a planned romantic night." },

  { name: "LightHaus Beer Garden", area: "Tampa", rating: 4.2, reviews: 187, priceNum: 1, category: "Beer Garden", distMi: 22,
    intents: [], tags: ["groups", "bar", "nightlife"],
    hook: "Casual beer garden with outdoor seating and a relaxed social vibe.",
    funFact: "Beer gardens are built for groups and low-pressure hangouts.",
    mustSee: "The patio setup.",
    tip: "Best for casual drinks, not a formal dinner." },

  { name: "Tampa Riverwalk", area: "Tampa", rating: 4.7, reviews: 567, priceNum: null, category: "Waterfront walk", distMi: 23,
    intents: ["outdoors", "hiddengems", "familyfun"], tags: ["waterfront", "family", "view", "instagrammable"],
    hook: "Tampa's signature downtown waterfront trail with skyline views and events.",
    funFact: "Stretches about 2.6 miles through the heart of downtown.",
    mustSee: "Sunset by the river and the lit-up skyline at night.",
    tip: "Pair it with Sparkman Wharf, Armature Works, or Water Street." },

  { name: "Bayshore Boulevard", area: "Tampa", rating: null, reviews: null, priceNum: null, category: "Scenic Waterfront", distMi: 19,
    intents: ["outdoors", "familyfun"], tags: ["waterfront", "view", "instagrammable", "family"],
    hook: "One of the world's longest continuous waterfront sidewalks along Tampa Bay.",
    funFact: "The pathway stretches nearly five uninterrupted miles.",
    mustSee: "Sunrise, the downtown skyline, and the iconic white balustrades.",
    tip: "Visit early morning before the Florida heat arrives." },

  { name: "Columbia Restaurant (Downtown Tampa)", area: "Tampa", rating: 4.5, reviews: 5841, priceNum: 2, category: "Spanish", distMi: 23,
    intents: ["hiddengems", "bucketlist"], tags: ["iconicflorida"],
    hook: "Historic Spanish-Cuban dining with sangria, paella, and old Tampa character.",
    funFact: "Columbia is Florida's oldest restaurant brand, dating back to 1905.",
    mustSee: "The tiled exterior and tableside 1905 salad.",
    tip: "Order the 1905 salad and sangria." },

  { name: "Columbia Restaurant (Ybor City original)", area: "Ybor City", rating: 4.6, reviews: 21973, priceNum: 2, category: "Spanish", distMi: 24,
    intents: ["hiddengems", "bucketlist"], tags: ["iconicflorida", "instagrammable"],
    hook: "A legendary Florida landmark with Spanish-Cuban dishes and serious history.",
    funFact: "The Ybor City original is one of Florida's most famous dining landmarks.",
    mustSee: "The 1905 salad, sangria, and tile-filled dining rooms.",
    tip: "This belongs in 'Iconic Florida,' not just restaurants." },

  { name: "Nueva Cantina — Downtown Tampa", area: "Tampa", rating: 4.5, reviews: 1658, priceNum: 2, category: "Mexican", distMi: 23,
    intents: ["hiddengems"], tags: ["groups", "nightlife"],
    hook: "Downtown hidden-gem Mexican with tacos, margaritas, and pre-event energy.",
    funFact: "Downtown Mexican spots work best before concerts, games, or Riverwalk plans.",
    mustSee: "Colorful interior and taco plates.",
    tip: "Good before a night out." },

  { name: "Ringside Restaurant", area: "Tampa", rating: 4.4, reviews: 89, priceNum: 3, category: "Restaurant", distMi: 23,
    intents: [], tags: ["romantic", "datenight", "instagrammable"],
    hook: "A stylish, theatrical-feeling restaurant with a showtime vibe.",
    funFact: "The name and design give it a showtime feel before the meal even starts.",
    mustSee: "The dramatic checkerboard-and-red interior.",
    tip: "Use this for a dress-up dinner." },

  { name: "Madame Fortune Dessert + HiFi Parlour", area: "Ybor City", rating: 4.7, reviews: 2312, priceNum: 3, category: "Dessert Lounge", distMi: 24,
    intents: ["hiddengems"], tags: ["dessert", "datenight", "nightlife", "instagrammable"],
    hook: "A stylish Ybor dessert lounge with craft cocktails and a hidden-speakeasy vibe.",
    funFact: "The HiFi Parlour concept blends vintage music culture with elevated desserts.",
    mustSee: "The dramatic plated desserts and moody interior.",
    tip: "Save this for after dinner or a date night." },

  { name: "Barterhouse Ybor", area: "Ybor City", rating: 4.2, reviews: 418, priceNum: 3, category: "American", distMi: 24,
    intents: [], tags: ["nightlife", "seafood", "livemusic", "datenight"],
    hook: "Upscale American with fresh oysters, cocktails, and an industrial-chic feel.",
    funFact: "Regularly hosts live music and special events.",
    mustSee: "The raw bar and dramatic dining room.",
    tip: "Great before exploring Ybor City's nightlife." },

  { name: "La Sétima Club", area: "Ybor City", rating: 4.9, reviews: 196, priceNum: 3, category: "Wine Bar", distMi: 24,
    intents: ["hiddengems"], tags: ["romantic", "datenight"],
    hook: "One of Tampa's best hidden date-night spots — curated wines and Spanish small plates.",
    funFact: "'The Seventh Club' in Spanish, reflecting Ybor's Latin heritage.",
    mustSee: "The cozy candlelit interior and beautifully plated dishes.",
    tip: "Ideal for anniversaries, first dates, or anyone looking to impress." },

  { name: "Catrinas Tacos and Tequila Bar", area: "Ybor City", rating: 4.4, reviews: 595, priceNum: 2, category: "Mexican", distMi: 24,
    intents: [], tags: ["nightlife", "groups", "instagrammable"],
    hook: "Lively Ybor Mexican with street tacos, tequila flights, and colorful décor.",
    funFact: "Tequila is produced exclusively from blue agave grown in specific regions of Mexico.",
    mustSee: "The vibrant murals and signature margaritas.",
    tip: "Perfect before concerts, bar hopping, or a night exploring Ybor." },

  { name: "Davis Islands", area: "Tampa", rating: 4.7, reviews: 62, priceNum: null, category: "Island", distMi: 21,
    intents: ["outdoors", "hiddengems"], tags: ["waterfront", "view", "instagrammable"],
    hook: "A scenic Tampa island neighborhood with waterfront views and a peaceful feel.",
    funFact: "Davis Islands was created from dredged land in the 1920s.",
    mustSee: "Sunset views across the water.",
    tip: "Best as a scenic drive/photo stop, not a full-day destination." },

  // ── St. Petersburg / St. Pete Beach / Central Ave ───────────────────────
  { name: "La Croisette", area: "St. Pete Beach", rating: 4.8, reviews: 6488, priceNum: 1, category: "Breakfast", distMi: 23,
    intents: ["hiddengems"], tags: ["breakfast", "brunch", "beach", "instagrammable"],
    hook: "A beloved beach-town breakfast spot with croissants, crepes, and hearty plates.",
    funFact: "Won local 'best restaurant' recognition, matching the crowd loyalty.",
    mustSee: "The pink exterior and breakfast plates.",
    tip: "Try the BLT, French crepe, or meat-lover croissant." },

  { name: "Caddy's Treasure Island", area: "Treasure Island", rating: 4.3, reviews: 9361, priceNum: 2, category: "Beach Bar", distMi: 24,
    intents: [], tags: ["beach", "waterfront", "groups", "nightlife", "seafood"],
    hook: "A beach-bar classic where you can watch games and step onto the sand.",
    funFact: "One of the area's easiest beach-day food stops.",
    mustSee: "Beachfront seating and game-day atmosphere.",
    tip: "Great for World Cup or big sports games by the beach." },

  { name: "Lido Key Beach", area: "Lido Key", rating: 4.7, reviews: 5701, priceNum: null, category: "Beach", distMi: 24,
    intents: ["outdoors", "familyfun"], tags: ["beach", "instagrammable", "family", "view"],
    hook: "Powder-soft white sand and turquoise water, quieter than Siesta Key.",
    funFact: "Minutes from St. Armands Circle — pair beach time with shops and dining.",
    mustSee: "The wide white-sand shoreline at sunset.",
    tip: "Pair it with Mote Marine or St. Armands for the perfect Sarasota day." },

  { name: "Noble Crust of St. Petersburg", area: "St. Petersburg", rating: 4.6, reviews: 4609, priceNum: 2, category: "Italian", distMi: 21,
    intents: ["hiddengems"], tags: ["brunch"],
    hook: "A must-try brunch and dinner spot mixing Italian comfort food with Southern flavor.",
    funFact: "Known for 'deep South Italian' cooking.",
    mustSee: "Brunch plates and the open dining room.",
    tip: "Go for brunch if you want the best first impression." },

  { name: "Pangea Alchemy Lab", area: "Sarasota", rating: 4.6, reviews: 752, priceNum: 1, category: "Lounge Bar", distMi: 21,
    intents: ["hiddengems"], tags: ["datenight", "nightlife", "bar", "instagrammable"],
    hook: "A creative cocktail lounge with moody lighting and a hidden-night-out feel.",
    funFact: "'Alchemy' fits because the cocktails feel experimental.",
    mustSee: "The colorful cocktail presentations.",
    tip: "Best after dinner, not as the first stop." },

  { name: "The Garden Room Cafe at Shoogie Boogies", area: "Sarasota", rating: 4.8, reviews: 203, priceNum: 3, category: "Cafe", distMi: 21,
    intents: ["hiddengems"], tags: ["brunch", "romantic", "instagrammable", "datenight"],
    hook: "A garden-cottage cafe built for brunch, photos, and a dreamy day-date.",
    funFact: "The setting is half the experience — plants, vines, romantic garden-room energy.",
    mustSee: "The sunny atrium and outdoor garden tables.",
    tip: "Belongs in 'Instagrammable,' 'Brunch,' and 'Romantic.'" },

  { name: "The Mable Bar & Grill", area: "St. Petersburg", rating: 4.7, reviews: 433, priceNum: 1, category: "Bar", distMi: 20,
    intents: ["hiddengems"], tags: ["bar", "nightlife"],
    hook: "A cozy neighborhood bar with creative burgers and a relaxed local atmosphere.",
    funFact: "Small but one of downtown's favorite hidden hangouts.",
    mustSee: "The vintage interior and handcrafted burgers.",
    tip: "Great stop before exploring Central Avenue nightlife." },

  { name: "Weedon Island Preserve", area: "St. Petersburg", rating: 4.8, reviews: 453, priceNum: null, category: "Nature Preserve", distMi: 20,
    intents: ["outdoors", "hiddengems", "familyfun"], tags: ["family", "view", "instagrammable"],
    hook: "Mangrove boardwalks, kayak trails, and ancient Indigenous history in one stop.",
    funFact: "Connects to the ancient Weedon Island culture, known for pottery and shell mounds.",
    mustSee: "The observation tower and mangrove kayak tunnels.",
    tip: "Rent a kayak for the full experience." },

  { name: "Star Fish Company", area: "Cortez", rating: 4.6, reviews: 2226, priceNum: 2, category: "Seafood", distMi: 20,
    intents: ["hiddengems", "bucketlist"], tags: ["seafood", "waterfront", "iconicflorida", "view"],
    hook: "Fresh fish dockside in a real working fishing village.",
    funFact: "Cortez is one of Florida's oldest fishing villages.",
    mustSee: "Outdoor seating by the marina.",
    tip: "Order grouper and go before sunset." },

  { name: "The Doctor's Office", area: "St. Petersburg", rating: 4.5, reviews: 979, priceNum: null, category: "Cocktail Bar", distMi: 20,
    intents: ["hiddengems"], tags: ["datenight", "nightlife", "bar", "instagrammable"],
    hook: "A doctor-themed speakeasy where cocktails are served like prescriptions.",
    funFact: "Every drink is designed around the playful medical concept.",
    mustSee: "The vintage pharmacy décor and creative cocktail presentations.",
    tip: "Ask the bartender for an off-menu recommendation." },

  { name: "Cococello (2620 Central Ave)", area: "St. Petersburg", rating: null, reviews: null, priceNum: 1, category: "Dessert", distMi: 19,
    intents: [], tags: ["dessert", "instagrammable"],
    hook: "Authentic Thai coconut ice cream served inside a real coconut.",
    funFact: "Became a Central Avenue favorite through word of mouth.",
    mustSee: "The coconut presentation.",
    tip: "Grab dessert while walking Central Avenue's murals and shops." },

  // ── Anna Maria Island / Longboat Key / Cortez / Bradenton ───────────────
  { name: "Cortez Beach", area: "Anna Maria Island", rating: 4.7, reviews: 2706, priceNum: null, category: "Beach", distMi: 21,
    intents: ["outdoors"], tags: ["beach", "instagrammable", "view"],
    hook: "A quieter AMI beach with soft sand and a relaxed feel.",
    funFact: "Sits near historic Bridge Street — pair beach time with food and shops.",
    mustSee: "The turquoise water and wide white-sand shoreline.",
    tip: "Great for photos, sunsets, and a calmer beach day." },

  { name: "Shore Longboat Key", area: "Longboat Key", rating: 4.6, reviews: 1636, priceNum: 3, category: "Restaurant", distMi: 21,
    intents: ["hiddengems"], tags: ["romantic", "datenight", "waterfront", "seafood", "view"],
    hook: "A polished waterfront restaurant with romantic views and stylish seafood.",
    funFact: "Longboat Key dining is all about water views and slower luxury.",
    mustSee: "The outdoor seating and seafood towers.",
    tip: "Reserve near sunset." },

  { name: "The Breakfast House", area: "Anna Maria Island", rating: 4.4, reviews: 1583, priceNum: 1, category: "Breakfast", distMi: 21,
    intents: [], tags: ["breakfast", "brunch", "instagrammable"],
    hook: "A colorful converted house serving cozy breakfast and beachy charm.",
    funFact: "The bright yellow exterior makes it instantly recognizable.",
    mustSee: "The patio/tiki-style outdoor seating and colorful decor.",
    tip: "Go early because it gets packed." },

  { name: "Mar Vista Dockside Restaurant & Pub", area: "Longboat Key", rating: 4.5, reviews: 3146, priceNum: 3, category: "Seafood", distMi: 21,
    intents: ["hiddengems", "bucketlist"], tags: ["romantic", "waterfront", "seafood", "iconicflorida", "view"],
    hook: "A dockside restaurant under giant trees that feels pure Old Florida.",
    funFact: "The property dates back to Longboat Key's early fishing-village days.",
    mustSee: "The shaded outdoor tables by the water.",
    tip: "Best for a slow lunch or sunset dinner." },

  { name: "Rosemary And Thyme", area: "Sarasota", rating: 4.5, reviews: 603, priceNum: 3, category: "Restaurant", distMi: 21,
    intents: ["hiddengems"], tags: ["romantic", "datenight", "seafood"],
    hook: "A refined romantic dinner spot with an intimate feel.",
    funFact: "Works best when you want conversation, not noise.",
    mustSee: "The elegant dining room and plated seafood.",
    tip: "Better for couples than big groups." },

  { name: "Toasted Mango Cafe", area: "Sarasota", rating: 4.5, reviews: 1640, priceNum: 1, category: "Breakfast", distMi: 21,
    intents: ["hiddengems"], tags: ["breakfast", "brunch", "livemusic"],
    hook: "A Sarasota breakfast favorite near the bayfront with tropical energy.",
    funFact: "Mango shows up throughout the brand — leaning into Florida sunshine.",
    mustSee: "The French toast and bright breakfast plates.",
    tip: "Great before a bayfront walk." },

  { name: "Mediterraneo", area: "Sarasota", rating: 4.6, reviews: 924, priceNum: 3, category: "Italian", distMi: 21,
    intents: ["hiddengems"], tags: ["romantic", "datenight", "seafood"],
    hook: "A classic Italian restaurant with seafood pasta and white-tablecloth energy.",
    funFact: "Blends coastal Italian flavors with fresh seafood.",
    mustSee: "The seafood pasta dishes.",
    tip: "Good for dinner before a downtown Sarasota night." },

  { name: "Green Iguana Bar & Grill", area: "Sarasota", rating: 4.4, reviews: 1948, priceNum: 2, category: "Grill", distMi: 21,
    intents: [], tags: ["groups", "nightlife", "bar"],
    hook: "A lively bar-and-grill with sports, tacos, and late-night energy.",
    funFact: "Built for casual groups more than quiet dinners.",
    mustSee: "The colorful bar area.",
    tip: "Best for drinks, games, and easy food." },

  { name: "Raffurty's Bar and Grill", area: "Sarasota", rating: 4.4, reviews: 866, priceNum: 2, category: "Sports Bar", distMi: 21,
    intents: [], tags: ["groups", "nightlife", "bar"],
    hook: "A downtown sports bar with wings, drinks, and a reliable game-day crowd.",
    funFact: "Sports bars survive on atmosphere as much as food.",
    mustSee: "The patio and TVs during big games.",
    tip: "Go when there's a game on." },

  { name: "Melting Pot", area: "Sarasota", rating: 4.4, reviews: 1058, priceNum: 3, category: "Fondue", distMi: 21,
    intents: [], tags: ["romantic", "datenight"],
    hook: "A romantic fondue dinner where the meal becomes the activity.",
    funFact: "Fondue became famous as a Swiss communal dining tradition.",
    mustSee: "The chocolate fondue finale.",
    tip: "Best for anniversaries or slower date nights." },

  { name: "Sandbar Seafood + Spirits", area: "Anna Maria Island", rating: 4.4, reviews: 8732, priceNum: 2, category: "Seafood", distMi: 21,
    intents: [], tags: ["beach", "waterfront", "seafood", "view"],
    hook: "A beachfront seafood classic — cocktail, Gulf views, straight onto the sand.",
    funFact: "One of Anna Maria Island's most iconic beach restaurants.",
    mustSee: "Sunset from the beachside tables.",
    tip: "Book ahead or expect a wait." },

  { name: "Cortez Clam Factory", area: "Cortez", rating: 4.4, reviews: 2066, priceNum: 2, category: "Seafood", distMi: 19,
    intents: [], tags: ["seafood", "waterfront", "iconicflorida"],
    hook: "A laid-back seafood institution where locals come for fresh Gulf seafood.",
    funFact: "Cortez is one of Florida's oldest continuously operating fishing villages.",
    mustSee: "Commercial fishing boats arriving while you eat waterfront.",
    tip: "Order the fried seafood platter and explore nearby Star Fish Company after." },

  { name: "Manatee Public Beach", area: "Anna Maria Island", rating: 4.7, reviews: 9061, priceNum: null, category: "Public Beach", distMi: 20,
    intents: ["outdoors", "familyfun"], tags: ["beach", "family", "instagrammable", "view"],
    hook: "One of AMI's easiest beach days — soft white sand, calm Gulf water, food nearby.",
    funFact: "AMI sunsets are among the most photographed on Florida's west coast.",
    mustSee: "Sunset over the Gulf.",
    tip: "Go early for parking." },

  { name: "Buttermilk Handcrafted Food", area: "Sarasota", rating: 4.7, reviews: 645, priceNum: 1, category: "Breakfast & Brunch", distMi: 20,
    intents: ["hiddengems"], tags: ["breakfast", "brunch"],
    hook: "A breakfast/brunch favorite built around scratch-made comfort food.",
    funFact: "Nearly everything is prepared fresh daily from scratch.",
    mustSee: "The biscuit sandwiches.",
    tip: "Arrive early on weekends to avoid the wait." },

  { name: "JR's Old Packinghouse Café", area: "Sarasota", rating: 4.5, reviews: 1476, priceNum: 1, category: "American", distMi: 20,
    intents: ["hiddengems", "bucketlist"], tags: ["livemusic", "iconicflorida", "groups"],
    hook: "A funky Old Florida café with comfort food and live music.",
    funFact: "Feels like a roadside time capsule.",
    mustSee: "The rustic signage and live music setup.",
    tip: "Go when music is scheduled." },

  { name: "Gulf Drive Café", area: "Anna Maria Island", rating: 3.8, reviews: 3477, priceNum: 2, category: "American", distMi: 21,
    intents: [], tags: ["beach", "breakfast", "waterfront", "view"],
    hook: "Breakfast by the beach with Gulf views and a walk-to-the-sand location.",
    funFact: "Beachfront breakfast is rare enough that the view may matter more than the rating.",
    mustSee: "Tables facing the water.",
    tip: "Best for the view, not a fancy food experience." },

  { name: "Bamboo Island Bar", area: "Anna Maria Island", rating: 4.8, reviews: 647, priceNum: 2, category: "Restaurant", distMi: 21,
    intents: ["hiddengems"], tags: ["datenight", "seafood"],
    hook: "A warm tropical restaurant with seafood, steaks, and a polished-but-relaxed feel.",
    funFact: "Feels like a vacation dinner instead of a regular local meal.",
    mustSee: "The bar lighting and plated seafood.",
    tip: "Better for dinner than a quick stop." },

  { name: "Beach House Waterfront Restaurant", area: "Anna Maria Island", rating: 4.4, reviews: 7158, priceNum: 3, category: "Seafood", distMi: 21,
    intents: [], tags: ["beach", "waterfront", "seafood", "livemusic", "view"],
    hook: "A beachfront AMI restaurant where the star is eating with your chair almost in the sand.",
    funFact: "One of AMI's most recognizable waterfront restaurants.",
    mustSee: "Beachside seating and sunset.",
    tip: "Book around golden hour." },

  { name: "Stottlemyer's Smokehouse", area: "Sarasota", rating: 4.3, reviews: 3797, priceNum: 2, category: "BBQ", distMi: 19,
    intents: [], tags: ["livemusic", "groups", "iconicflorida"],
    hook: "A rustic Old Florida smokehouse with BBQ, live music, and a big thatched pavilion.",
    funFact: "The open-air setup makes it one of the more unique casual dining spots near Sarasota.",
    mustSee: "The tiki-style pavilion and live music nights.",
    tip: "Check the entertainment schedule before going." },

  { name: "Sarasota Jungle Gardens", area: "Sarasota", rating: 4.3, reviews: 6472, priceNum: null, category: "Zoo", distMi: 20,
    intents: ["outdoors", "familyfun"], tags: ["family", "instagrammable"],
    hook: "A classic old-Florida family attraction — feed flamingos, walk tropical paths, see animal shows.",
    funFact: "Has been part of Sarasota since the 1930s.",
    mustSee: "The flamingo feeding area — very photo-friendly.",
    tip: "Go in the morning before heat and crowds build." },

  { name: "Pia's Trattoria", area: "Bradenton", rating: 4.7, reviews: 3689, priceNum: 3, category: "Italian", distMi: 20,
    intents: ["hiddengems"], tags: ["romantic", "datenight", "instagrammable"],
    hook: "A romantic hidden-gem Italian with a courtyard that feels more like Tuscany than Florida.",
    funFact: "The ivy-covered courtyard is consistently ranked among the most romantic in the region.",
    mustSee: "The courtyard lit by string lights.",
    tip: "Reserve outdoor seating for the full experience." },

  { name: "Salt Shack on the Bay", area: "Tampa", rating: 4.4, reviews: 8387, priceNum: 2, category: "Seafood", distMi: 20,
    intents: [], tags: ["waterfront", "seafood", "view", "groups"],
    hook: "Waterfront dining where boats pull right up and sunsets steal the show.",
    funFact: "Many locals consider it one of Tampa Bay's best casual sunset restaurants.",
    mustSee: "Golden-hour views over Old Tampa Bay.",
    tip: "Arrive about an hour before sunset for the best seats." },

  { name: "Ted Sperling Park Nature Trail", area: "Lido Key", rating: 4.7, reviews: 82, priceNum: null, category: "Nature Trail", distMi: 24,
    intents: ["outdoors", "hiddengems", "familyfun"], tags: ["family", "instagrammable", "view"],
    hook: "A peaceful mangrove preserve with walking trails and kayak launches.",
    funFact: "The mangrove tunnels are among Sarasota's most photographed kayaking routes.",
    mustSee: "The winding boardwalk and mangrove waterways.",
    tip: "Go early morning for cooler weather and better wildlife viewing." },
];

// ── Data-quality holds (do NOT publish until resolved) ──────────────────────
// Removed as permanently closed: "Circo" (Tex-Mex, Sarasota).
// Needs name verification before publishing: the "5224 S Dale Mabry Hwy" bakery
//   ("world's best croissant") — confirm the exact business name first.

export const CURATED_NEEDS_VERIFY = [
  { placeholder: "5224 S Dale Mabry Hwy", area: "Tampa", distMi: 19, category: "Bakery",
    note: "Croissant/pastry stop — confirm exact business name before publishing.",
    tags: ["dessert", "breakfast"] },
];
