// 2026-10-07 farm gap fill (owner: "make sure we have more place cards on
// pumpkin patches and farms ... do some research in the areas we cover").
//
// Measured on production that day: Fort Myers and Naples showed one farm card,
// Venice and North Port one, Port Charlotte none. Both rows below were read live
// in a real browser on the organizer's own page on 2026-10-07; venue identity
// is the exact wf_inventory row with an owned photo, so no paid lookup and no
// neighbour's picture. Kept in its own module so the counted 33-row owner
// discovery registry (lib/fallDiscoveries2026.js) stays exactly as reviewed.
// Their one primary intent is pinned in FALL_DISCOVERY_RAIL like every other row.

const FARM_EVENT = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  select_nights: false,
  category: "seasonal",
  subcategory: "pumpkin-patch",
  state: "FL",
  source_type: "official-organizer",
  source_tier: 1,
  verification_confidence: "high",
  editorial_score: 7,
  uniqueness_score: 7,
  popularity_score: 6,
  audience: ["families", "kids"],
  is_free: false,
};

export const FALL_GAP_FILL_2026_10_07 = Object.freeze([
  {
    ...FARM_EVENT,
    event_id: "lakes-park-pumpkin-patch-fort-myers-2026",
    event_series_id: "lakes-park-pumpkin-patch-fort-myers",
    event_name: "Lakes Regional Park Pumpkin Patch",
    short_title: "Lakes Park Pumpkin Patch",
    slug: "lakes-regional-park-pumpkin-patch-2026",
    start_date: "2026-10-09",
    end_date: "2026-10-25",
    select_nights: true,
    occurrence_dates: ["2026-10-09", "2026-10-10", "2026-10-11", "2026-10-15", "2026-10-16", "2026-10-17", "2026-10-18", "2026-10-22", "2026-10-23", "2026-10-24", "2026-10-25"],
    schedule_note: "October 9–11, 15–18 and 22–25. Thursday–Friday 6–9 pm, Saturday–Sunday 10 am–9 pm. Free entry; parking $3 per vehicle.",
    venue: "Lakes Regional Park",
    address: "7330 Gladiolus Drive, Fort Myers, FL 33908",
    city: "Fort Myers",
    county: "Lee",
    lat: 26.5281,
    lng: -81.8768,
    place_id: "ChIJbTdu29E_24gRK68-KIMT5iw",
    is_free: true,
    price_band: "free",
    price_min: 0,
    tags: ["fall", "family", "pumpkins", "pumpkin-patch", "hayride"],
    official_event_url: "https://wheelfunrentals.com/fl/fort-myers/lakes-regional-park/pumpkin-patch",
    source_url: "https://wheelfunrentals.com/fl/fort-myers/lakes-regional-park/pumpkin-patch",
    last_verified_at: "2026-10-07T00:00:00+00:00",
    card_hook: "Pick a pumpkin, ride a hay surrey and stay for the lake at sunset.",
    editorial_summary: "Wheel Fun Rentals' patch at Lakes Regional Park: pumpkins for sale, hay rides on a surrey, music and snacks, with free entry.",
    why_go: "The easiest real pumpkin patch in Fort Myers, with evening hours on weeknights.",
    insider_tip: "Weeknight hours are Thursday and Friday only, 6 to 9 pm; weekends run 10 am to 9 pm.",
    parking_tip: "Park parking is $3 per vehicle.",
    duration_recommendation: "1-2 hours",
  },
  {
    ...FARM_EVENT,
    event_id: "north-port-pumpkin-plunge-2026",
    event_series_id: "north-port-pumpkin-plunge",
    event_name: "Pumpkin Plunge at North Port Aquatic Center",
    short_title: "Pumpkin Plunge",
    slug: "north-port-pumpkin-plunge-2026",
    start_date: "2026-10-17",
    end_date: "2026-10-17",
    start_time: "09:00:00",
    end_time: "11:00:00",
    select_nights: false,
    schedule_note: "Saturday, October 17, 2026, 9 to 11 am. $15 per child, includes one supervising adult.",
    venue: "North Port Aquatic Center",
    address: "6205 W Price Blvd, North Port, FL",
    city: "North Port",
    county: "Sarasota",
    lat: 27.0678,
    lng: -82.2241,
    place_id: "ChIJ-1BSWChTw4gRMHlGPNVGODo",
    price_min: 15,
    price_max: 15,
    price_band: "$",
    crowd_level: null,
    tags: ["fall", "family", "pumpkins", "pumpkin-patch"],
    official_event_url: "https://www.northportfl.gov/Event-Directory/Pumpkin-Plunge",
    source_url: "https://www.northportfl.gov/Event-Directory/Pumpkin-Plunge",
    last_verified_at: "2026-10-07T00:00:00+00:00",
    card_hook: "Kids swim through a floating pumpkin patch and pick one to take home.",
    editorial_summary: "North Port's floating pumpkin patch: kids wade or swim to pick a pumpkin, then decorate it poolside with supplies included.",
    why_go: "The most Florida pumpkin patch there is, and the decorating kit is part of the ticket.",
    duration_recommendation: "Two hours",
  },
  {
    ...FARM_EVENT,
    event_id: "utc-pumpkin-patch-sarasota-2026",
    event_series_id: "utc-pumpkin-patch-sarasota",
    event_name: "Pumpkin Patch at UTC",
    short_title: "UTC Pumpkin Patch",
    slug: "pumpkin-patch-at-utc-sarasota-2026",
    start_date: "2026-10-09",
    end_date: "2026-10-25",
    select_nights: false,
    schedule_note: "October 9–25 on The Green at UTC. Monday–Friday 3–6 pm, Saturday 10 am–6 pm, Sunday noon–5 pm. Pumpkins available while supplies last.",
    venue: "The Green at University Town Center",
    address: "210 N Cattlemen Rd, Sarasota, FL 34243",
    city: "Sarasota",
    county: "Sarasota",
    lat: 27.38446,
    lng: -82.45263,
    place_id: "ChIJHcu6u2BHw4gRDKuRC9sow20",
    is_free: true,
    price_band: "free",
    tags: ["fall", "family", "pumpkins", "pumpkin-patch"],
    official_event_url: "https://utcsarasota.com/event/pumpkin-patch-at-utc-5/",
    source_url: "https://utcsarasota.com/event/pumpkin-patch-at-utc-5/",
    last_verified_at: "2026-10-07T00:00:00+00:00",
    verify_note: "2026-10-07: utcsarasota.com/events lists 'OCTOBER 9 - OCTOBER 25 Pumpkin Patch at UTC' among dated 2026 events; the event page gives daily hours and Detwiler's Farm Market as presenter.",
    card_hook: "Pick a pumpkin on The Green, and every one you buy helps an animal rescue.",
    editorial_summary: "Detwiler's Farm Market sets up the annual patch on The Green at UTC; every pumpkin benefits Nate's Honor Animal Rescue.",
    why_go: "The easiest pumpkin stop in Sarasota, with after-school hours on weekdays.",
    duration_recommendation: "Under an hour",
  },
  {
    ...FARM_EVENT,
    event_id: "harvestmoon-fun-farm-fall-2026",
    event_series_id: "harvestmoon-fun-farm-fall",
    event_name: "HarvestMoon Fun Farm Fall Festival",
    short_title: "HarvestMoon Fall Festival",
    slug: "harvestmoon-fun-farm-fall-festival-2026",
    start_date: "2026-09-26",
    end_date: "2026-11-08",
    select_nights: true,
    schedule_note: "Sept 26 – Nov 8. October: Saturday & Sunday 10 am–5 pm; weekdays from Oct 7, Wednesday–Friday 10 am–2 pm (closed Monday–Tuesday, open Monday Oct 12). November: Nov 1, 7 and 8, 10 am–5 pm. Admission $16.95 weekends, $13.95 weekdays, plus tax; ages 2 and under free.",
    venue: "HarvestMoon Fun Farm",
    address: null,
    city: "Masaryktown",
    county: "Hernando",
    lat: 28.4374,
    lng: -82.4693,
    place_id: "ChIJLdY0hDanwogRXI-7-GI37Is",
    price_min: 13.95,
    price_max: 16.95,
    price_band: "$$",
    tags: ["fall", "family", "pumpkins", "farm", "corn-maze", "harvest"],
    official_event_url: "https://www.harvestmoonfunfarm.com/fall",
    official_ticket_url: "https://www.simpletix.com/e/harvestmoon-fun-farm-fall-festival-fright-tickets-287150",
    source_url: "https://www.harvestmoonfunfarm.com/fall",
    last_verified_at: "2026-10-07T00:00:00+00:00",
    verify_note: "2026-10-07: harvestmoonfunfarm.com/fall '2026 Dates & Hours September 26th- November 8th'; prices from /tickets-hours. Haunted Nights (Fri-Sat Oct 10-30) are a separate ticket and not this card.",
    card_hook: "Corn maze, pumpkins, a cow train and farm animals north of Tampa.",
    editorial_summary: "HarvestMoon's 2026 fall season: a corn maze, pumpkin patch, cow train and farm animals, with beer, wine and hard cider on weekends.",
    why_go: "A full farm day with weekday hours, so you can skip the weekend crowds.",
    insider_tip: "Weekdays are cheaper but run limited activities; weekends include every attraction and the maze.",
    duration_recommendation: "Half day",
  },
]);
