// Owner supplied Fall in Florida discoveries, verified for the 2026 season.
//
// These are events instead of permanent fall places because each recommendation
// depends on a seasonal program. The explicit rail registry keeps every card in
// one intent only, even when a farm is also family friendly or a cafe also works
// for a date.

const BUSINESS_DISCOVERY = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  select_nights: false,
  category: "seasonal",
  state: "FL",
  source_type: "owner-received-discovery",
  source_tier: 3,
  verification_confidence: "medium",
  last_verified_at: "2026-09-02T00:00:00+00:00",
  editorial_score: 8,
  uniqueness_score: 8,
  popularity_score: 7,
  is_free: false,
  price_band: "$$",
};

const FARM_EVENT = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  select_nights: false,
  category: "seasonal",
  subcategory: "farm-festival",
  state: "FL",
  source_type: "official-organizer",
  source_tier: 1,
  verification_confidence: "high",
  last_verified_at: "2026-09-02T00:00:00+00:00",
  editorial_score: 8,
  uniqueness_score: 7,
  popularity_score: 8,
  audience: ["families", "kids"],
  tags: ["fall", "family", "pumpkins", "farm", "harvest"],
  is_free: false,
  price_band: "$$",
  duration_recommendation: "Half day",
  crowd_level: "high",
};

// Dated Miami / South Florida Fall 2026 programs. Not owner-received
// seasonal-place cards: place_id stays null until an owned Places id is
// already in-repo (this pack does not call Place Details).
const MIAMI_EVENT = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  select_nights: false,
  category: "seasonal",
  state: "FL",
  source_type: "official-organizer",
  source_tier: 1,
  verification_confidence: "high",
  last_verified_at: "2026-09-06T00:00:00+00:00",
  editorial_score: 8,
  uniqueness_score: 7,
  popularity_score: 7,
  is_free: false,
  price_band: "$$",
  place_id: null,
};

export const FALL_DISCOVERIES_2026 = Object.freeze([
  {
    ...BUSINESS_DISCOVERY,
    event_id: "haunted-mangoni-2026",
    event_series_id: "haunted-mangoni",
    event_name: "Haunted Mangoni",
    short_title: "Haunted Mangoni",
    slug: "haunted-mangoni-winter-garden-2026",
    start_date: "2026-09-05",
    end_date: "2026-10-31", // 2026-09-03: Visit Orlando bar-takeover roundup (updated 2026-08-31) — "Sept. 5 – Oct. 31, 2026"
    source_tier: 1,
    verification_confidence: "high",
    schedule_note: "September 5 through October 31 during regular hours; reservations open.",
    venue: "MANGONI Italian Market Pizza",
    address: "251 Tremaine St",
    city: "Winter Garden",
    county: "Orange",
    lat: 28.56483,
    lng: -81.5883934,
    place_id: "ChIJRStTdYSD54gRhH5dTvKQLJI",
    subcategory: "themed-restaurant",
    tags: ["fall", "halloween", "date-night", "nightlife", "themed-bar"],
    audience: ["adults", "couples"],
    official_event_url: "https://mangoniwg.com/",
    source_url: "https://www.instagram.com/p/DcyS5k4gVV5/",
    card_hook: "Wood-fired pizza with a side of haunted.",
    editorial_summary: "Halloween decor, cocktails and wood-fired pizza turn dinner into the actual event — now with a venue-confirmed date.",
    why_go: "Book this when the plan needs a scare between the antipasto and the pizza.",
    fun_fact: "Mangoni rests its pizza dough for 24 hours before it reaches the wood fired oven.",
    wayfind_verdict: "Winter Garden's spookiest slice just got official.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "rosallie-lattes-leaves-2026",
    event_series_id: "rosallie-lattes-leaves",
    event_name: "Lattes and Leaves at Rosallie",
    short_title: "Lattes and Leaves",
    slug: "rosallie-lattes-leaves-winter-garden-2026",
    start_date: "2026-09-05",
    end_date: null,
    schedule_note: "Begins September 5. The closing date has not been published.",
    venue: "Rosallie Le French Cafe",
    address: "141 W Plant Street",
    city: "Winter Garden",
    county: "Orange",
    lat: 28.5656211,
    lng: -81.5872974,
    place_id: "ChIJ15lqd26D54gR0zik2zNTX4o",
    subcategory: "seasonal-cafe",
    tags: ["fall", "food", "coffee", "pastries"],
    audience: ["adults", "couples", "families"],
    official_event_url: "https://rosallie.com/winter-garden/",
    source_url: "https://rosallie.com/winter-garden/",
    card_hook: "Parisian pastry energy, Florida fall edition.",
    editorial_summary: "Seasonal drinks, pastries and leafy decor deliver fall without the farm day.",
    why_go: "Choose this when you want cozy now and pumpkins later.",
    fun_fact: "Rosallie serves its French cafe concept in Winter Garden and Las Vegas.",
    wayfind_verdict: "The quickest cozy fall win in Winter Garden.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "nueva-cantina-halloween-tampa-2026",
    event_series_id: "nueva-cantina-halloween-tampa",
    event_name: "Halloween at Nueva Cantina Downtown Tampa",
    short_title: "Nueva Cantina Halloween",
    slug: "nueva-cantina-halloween-downtown-tampa-2026",
    start_date: "2026-09-02",
    end_date: null,
    schedule_note: "Verified for the 2026 fall season. The closing date has not been published.",
    venue: "Nueva Cantina Downtown Tampa",
    address: "903 N Franklin St",
    city: "Tampa",
    county: "Hillsborough",
    lat: 27.9517198,
    lng: -82.4594849,
    place_id: "ChIJmzKZ8InEwogR0PM7xTqUB6M",
    subcategory: "themed-restaurant",
    tags: ["fall", "halloween", "date-night", "nightlife", "themed-bar", "food"],
    audience: ["adults", "couples"],
    official_event_url: "https://nuevacantina.com/locations/",
    // Upgraded 2026-09-02: the venue's own account, newer than the prior
    // third-party reel it replaces.
    source_url: "https://www.instagram.com/reel/Dcwmv51CK5T/",
    card_hook: "Tacos, margaritas and a Halloween takeover.",
    editorial_summary: "Themed drinks, food and decor turn downtown dinner into the night out.",
    why_go: "Choose this when your fall plan needs cocktails, not a corn maze.",
    fun_fact: "The Downtown Tampa location stays open until midnight on Friday and Saturday.",
    wayfind_verdict: "Halloween dinner that keeps the night moving.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "you-do-the-dishes-fall-2026",
    event_series_id: "you-do-the-dishes-fall",
    event_name: "Fall Pottery at You Do the Dishes",
    short_title: "Fall Pottery and Coffee",
    slug: "you-do-the-dishes-fall-pottery-tampa-2026",
    start_date: "2026-09-02",
    end_date: null,
    schedule_note: "Verified for the 2026 fall season. The closing date has not been published.",
    venue: "You Do the Dishes",
    address: "15357 Amberly Drive",
    city: "Tampa",
    county: "Hillsborough",
    lat: 28.0876248,
    lng: -82.4037597,
    place_id: "ChIJIV9AOfbHwogR5SPjijvBLRM",
    subcategory: "creative-date",
    tags: ["fall", "halloween", "date-night", "pottery", "coffee"],
    audience: ["couples", "families", "kids"],
    official_event_url: "https://www.youdothedishes.com/",
    source_url: "https://www.youdothedishes.com/",
    card_hook: "Paint a pumpkin. Sip coffee. Keep the evidence.",
    editorial_summary: "Fall pottery and a full coffee bar make this a date, girls day or family plan.",
    why_go: "You leave with a memory and a piece you made yourself.",
    fun_fact: "The studio offers more than 75 paint colors and fires finished pieces for pickup in three to five days.",
    wayfind_verdict: "Tampa's most hands on fall date.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "perfect-press-fall-coffee-2026",
    event_series_id: "perfect-press-fall-coffee",
    event_name: "Fall at The Perfect Press Coffee Co.",
    short_title: "Perfect Press Fall Coffee",
    slug: "perfect-press-fall-coffee-carrollwood-2026",
    start_date: "2026-09-02",
    end_date: null,
    schedule_note: "Verified for the 2026 fall season. The closing date has not been published.",
    venue: "The Perfect Press Coffee Co.,LLC",
    city: "Carrollwood",
    county: "Hillsborough",
    lat: 28.0728871,
    lng: -82.5219324,
    place_id: "ChIJc9TZhGDAwogRRHZ5EzKtJIc",
    subcategory: "seasonal-cafe",
    tags: ["fall", "food", "coffee", "seasonal-drinks"],
    audience: ["adults", "couples", "families"],
    official_event_url: "https://www.theperfectpresscoffee.com/",
    source_url: "https://www.theperfectpresscoffee.com/",
    card_hook: "The storefront dressed for fall before Florida did.",
    editorial_summary: "Pumpkins, florals and seasonal drinks turn a coffee stop into a fall reset.",
    why_go: "Get the atmosphere and the pumpkin matcha without losing half a day.",
    fun_fact: "The seasonal styling covers the storefront, so the fall experience starts before you order.",
    wayfind_verdict: "Carrollwood's quick hit of fall.",
  },
  {
    ...FARM_EVENT,
    event_id: "showcase-citrus-pumpkin-ponderosa-2026",
    event_series_id: "showcase-citrus-pumpkin-ponderosa",
    event_name: "Showcase of Citrus Pumpkin Ponderosa",
    short_title: "Pumpkin Ponderosa",
    slug: "showcase-of-citrus-pumpkin-ponderosa-2026",
    start_date: "2026-09-18",
    end_date: "2026-10-31",
    select_nights: true,
    schedule_note: "September 18 through October 31. Haunted monster truck rides run on select nights.",
    venue: "Showcase of Citrus",
    address: "15051 Frank Jarrell Rd",
    city: "Clermont",
    county: "Lake",
    lat: 28.4237254,
    lng: -81.7037559,
    place_id: "ChIJW5C20gaI54gRZuH_-8hPQy8",
    official_event_url: "https://www.showcaseofcitrus.com/updates.html",
    source_url: "https://www.showcaseofcitrus.com/updates.html",
    card_hook: "Pumpkins by day. Haunted monster trucks by night.",
    editorial_summary: "A patch, fall food, family activities and monster trucks make this peak Florida fall.",
    why_go: "Pick this when a normal pumpkin patch sounds too normal.",
    fun_fact: "The 2026 Pumpkin Ponderosa is the event's eighth annual season.",
    wayfind_verdict: "The pumpkin patch with the best plot twist.",
  },
  {
    ...FARM_EVENT,
    event_id: "amber-brooke-fall-festival-2026",
    event_series_id: "amber-brooke-fall-festival",
    event_name: "Amber Brooke Farms Fall Festival",
    short_title: "Amber Brooke Fall Festival",
    slug: "amber-brooke-farms-fall-festival-2026",
    start_date: "2026-09-19",
    end_date: "2026-11-22",
    select_nights: true,
    schedule_note: "Fridays 10am–5pm, Saturdays 10am–6pm, Sundays 10am–5pm, September 19 through November 22.", // 2026-09-03: amberbrookefarms.ticketspice.com hours
    venue: "Amber Brooke Farms",
    address: "36111 N CR 44A",
    city: "Eustis",
    county: "Lake",
    lat: 28.876023,
    lng: -81.639841,
    // Resolved through Google Places Nearby Search 2026-09-03 (the farm itself,
    // not its bakery/stage/gift-shop sub-listings) so the card wears the venue's
    // own photo instead of a blank tile.    place_id: "ChIJkyg5UW6654gRECAKyCherD8",
    official_event_url: "https://amberbrookefarms.com/event/6th-annual-fall-festival-11/",
    source_url: "https://amberbrookefarms.com/event/6th-annual-fall-festival-11/",
    card_hook: "More than 25 ways to earn the ride home nap.",
    editorial_summary: "Pumpkins, tractor rides, music, animals and jump pads fill a full family day.",
    why_go: "Come for the pumpkin barn when the kids need more than one activity.",
    fun_fact: "The 2026 festival is Amber Brooke Farms' sixth annual fall celebration.",
    wayfind_verdict: "The all day family farm near Eustis.",
  },
  {
    ...FARM_EVENT,
    event_id: "green-meadows-fall-2026",
    event_series_id: "green-meadows-fall",
    event_name: "Green Meadows Farm Fall",
    short_title: "Green Meadows Pumpkin Picking",
    slug: "green-meadows-farm-fall-2026",
    start_date: "2026-09-26",
    end_date: "2026-11-08",
    select_nights: true,
    schedule_note: "Pumpkin picking runs September 26 through November 8. Each paid admission includes one pumpkin.",
    venue: "Green Meadows Petting Farm",
    address: "1881 Jack Calhoun Dr",
    city: "Kissimmee",
    county: "Osceola",
    lat: 28.2711014,
    lng: -81.4323259,
    place_id: "ChIJMRKPC1mC3YgRTs5evGTqF4k",
    official_event_url: "https://greenmeadowsfarm.com/special-events/",
    source_url: "https://greenmeadowsfarm.com/special-events/",
    card_hook: "Meet the animals. Pick a pumpkin. Keep it.",
    editorial_summary: "A full petting farm visit comes with pumpkin picking and clear family value.",
    why_go: "One pumpkin is included with every paid admission, so there is no checkout surprise.",
    fun_fact: "Green Meadows also schedules family Candy Hunts during select October weekends.",
    wayfind_verdict: "The smartest value farm day in Kissimmee.",
  },
  {
    ...FARM_EVENT,
    event_id: "great-scott-fall-fest-2026",
    event_series_id: "great-scott-fall-fest",
    event_name: "Great Scott Farms Fall Fest and Corn Maze",
    short_title: "Great Scott Fall Fest",
    slug: "great-scott-farms-fall-fest-2026",
    start_date: "2026-09-26",
    end_date: "2026-11-15", // 2026-09-03: visitgreatscott.com/fall-festival — "2026 Fall Festival September 26th- November 15th"
    select_nights: true,
    schedule_note: "Saturdays and Sundays, 10am–5pm, September 26 through November 15. $16 online, $20 at the gate; 2 and under free.",
    venue: "Great Scott Farms",
    address: "26216 County Road 448A",
    city: "Mount Dora",
    county: "Lake",
    lat: 28.7285925,
    lng: -81.6683983,
    // Resolved through Google Places Nearby Search 2026-09-03 (the farm itself,
    // not its bakery/stage/gift-shop sub-listings) so the card wears the venue's
    // own photo instead of a blank tile.
    place_id: "ChIJ68SLYriZ54gRaJgw169KqYA",
    official_event_url: "https://www.visitgreatscott.com/fall-festival",
    source_url: "https://www.visitgreatscott.com/fall-festival",    card_hook: "Seven acres of corn between you and victory.",
    editorial_summary: "A giant maze, jumping pillow, zip line and super slide keep the whole crew moving.",
    why_go: "Choose this when the corn maze is the main event, not background decor.",
    fun_fact: "Long and Scott Farms has grown Zellwood sweet corn and other produce since 1963.",
    wayfind_verdict: "Central Florida's classic corn maze day.",
  },
  {
    ...FARM_EVENT,
    event_id: "southern-hill-farms-fall-festival-2026",
    event_series_id: "southern-hill-farms-fall-festival",
    event_name: "Southern Hill Farms Fall Festival",
    short_title: "Southern Hill Farms",
    slug: "southern-hill-farms-fall-festival-2026",
    start_date: "2026-09-26",
    end_date: "2026-11-22",
    select_nights: true,
    schedule_note: "Select Thursdays (11am–7pm) and every Friday–Sunday (about 9am–8pm), September 26 through November 22, plus Monday October 12. $29.94, online only, ages 3+.",
    venue: "Southern Hill Farms",
    address: "16651 Schofield Rd",
    city: "Clermont",
    county: "Lake",
    lat: 28.4489467,
    lng: -81.682954,
    // Resolved through Google Places Nearby Search 2026-09-03 (the farm itself,
    // not its bakery/stage/gift-shop sub-listings) so the card wears the venue's
    // own photo instead of a blank tile.
    place_id: "ChIJ-aI9NvSI54gRrVByB84z-AY",
    official_event_url: "https://southernhillfarms.com/events/",    source_url: "https://southernhillfarms.com/event/11th-annual-fall-festival/",
    card_hook: "The fall festival that needs a full itinerary.",
    editorial_summary: "Rides, corn, flowers, animals, music and food make this Clermont's anchor fall day.",
    why_go: "Choose it when everyone wants something different and nobody wants to leave early.",
    fun_fact: "The 2026 season is Southern Hill Farms' 11th annual Fall Festival.",
    wayfind_verdict: "Clermont's biggest all in fall day.",
  },
  {
    ...FARM_EVENT,
    event_id: "hastings-ranch-farm-festival-2026",
    event_series_id: "hastings-ranch-farm-festival",
    event_name: "Hastings Ranch and Farm Festival",
    short_title: "Hastings Ranch Festival",
    slug: "hastings-ranch-farm-festival-2026",
    start_date: "2026-10-10",
    end_date: "2026-11-01",
    select_nights: true,
    schedule_note: "October 10 and 11, 17 and 18, 24 and 25, and October 31 through November 1, 10 AM to 5 PM.",
    venue: "Hastings Ranch and Farm",
    address: "1550 Dolphin Dr",
    city: "St Cloud",
    county: "Osceola",
    lat: 28.2610709,
    lng: -81.1856788,
    place_id: "ChIJAyTZ7DqN3YgRrdAAVCHFMkA",
    official_event_url: "https://hastingsranchandfarm.com/farm-festival/",
    source_url: "https://hastingsranchandfarm.com/farm-festival/",
    card_hook: "Big fall energy without the giant festival stampede.",
    editorial_summary: "Games, food, hay rides, corn and pumpkins deliver the full ranch day near St Cloud.",
    why_go: "Pick it when local charm beats an Instagram famous crowd.",
    fun_fact: "The 2026 event is Hastings Ranch and Farm's eighth annual festival.",
    wayfind_verdict: "The local alternative to the giant farm festivals.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "dead-coconut-club-harvest-citywalk-2026",
    event_series_id: "dead-coconut-club-harvest",
    event_name: "Dead Coconut Club: Harvest",
    short_title: "Dead Coconut Club: Harvest",
    slug: "dead-coconut-club-harvest-citywalk-orlando-2026",
    start_date: "2026-08-28",
    end_date: "2026-11-01",
    select_nights: true,
    source_tier: 1,
    verification_confidence: "high",
    schedule_note: "Open from 4 PM on Halloween Horror Nights 35 event nights only — select nights, not every night, Aug 28 through Nov 1, 2026, per Universal Orlando's own event page.",
    venue: "Red Coconut Club (seasonally the Dead Coconut Club)",
    address: "6000 Universal Blvd",
    city: "Orlando",
    county: "Orange",
    lat: 28.4731837,
    lng: -81.4650605,
    place_id: "ChIJwZ_GK-d-54gRm5Ahg7PZYeY",
    subcategory: "themed-bar",
    tags: ["fall", "halloween", "date-night", "nightlife", "themed-bar"],
    audience: ["adults", "couples"],
    official_event_url: "https://www.universalorlando.com/web/en/us/things-to-do/events/halloween-horror-nights/index.html",
    source_url: "https://www.instagram.com/reel/Dcg3_aRix46/",
    card_hook: "CityWalk's nightclub goes full Halloween — no HHN ticket required.",
    editorial_summary: "Free, all-ages walk-up: CityWalk's Red Coconut Club becomes the Dead Coconut Club each Horror Nights season, open 4 PM.",
    why_go: "Choose this when the group wants Horror Nights energy without buying a Horror Nights ticket.",
    fun_fact: "It runs on the same select-night calendar as Halloween Horror Nights itself, August 28 through November 1, 2026.",
    wayfind_verdict: "CityWalk's free-entry answer to Horror Nights.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "haraz-house-pumpkin-spice-wesley-chapel-2026",
    event_series_id: "haraz-house-pumpkin-spice",
    event_name: "Pumpkin Spice Bakery Menu at Haraz House",
    short_title: "Haraz House Pumpkin Spice",
    slug: "haraz-house-pumpkin-spice-wesley-chapel-2026",
    start_date: "2026-09-02",
    end_date: null,
    schedule_note: "Verified for the 2026 fall season. The closing date has not been published.",
    venue: "Haraz Coffee House",
    address: "1722 Bruce B Downs Blvd",
    city: "Wesley Chapel",
    county: "Pasco",
    lat: 28.1823545,
    lng: -82.3514208,
    place_id: "ChIJQVp535WxwogR42W828PdPRw",
    subcategory: "seasonal-cafe",
    tags: ["fall", "food", "coffee", "pastries"],
    audience: ["adults", "couples", "families"],
    official_event_url: "https://harazcoffeehouse.com/pages/menu",
    source_url: "https://www.instagram.com/reel/DctUcUexTXR/",
    card_hook: "A Yemeni coffee house adds pumpkin spice to its own bakery case.",
    editorial_summary: "Haraz Coffee House turns its Wesley Chapel bakery case fall, alongside its usual Yemeni coffee and pastries.",
    why_go: "Choose this when the plan is coffee and a pastry, not a full meal.",
    fun_fact: "Haraz Coffee House is a Yemeni-owned chain with locations across the country; this is the Wesley Chapel room.",
    wayfind_verdict: "A fall pastry stop on Bruce B Downs.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "all-fired-up-halloween-pottery-winter-park-2026",
    // Distinct series_id from the Waterford Lakes entry below on purpose: the
    // fall-rail composer dedupes by event_series_id (lib/fallIntentRails.js),
    // and these are two real venues that should both render, not one event
    // franchise where only the nearest copy should survive.
    event_series_id: "all-fired-up-halloween-pottery-winter-park",
    event_name: "Halloween Pottery Collection at All Fired Up",
    short_title: "All Fired Up Halloween Pottery",
    slug: "all-fired-up-halloween-pottery-winter-park-2026",
    start_date: "2026-08-19",
    end_date: null,
    schedule_note: "Launched August 19, per the studio's own collaboration post. The closing date has not been published.",
    venue: "All Fired Up (Winter Park) Pottery Painting",
    address: "229 W Fairbanks Ave",
    city: "Winter Park",
    county: "Orange",
    lat: 28.593253,
    lng: -81.352214,
    place_id: "ChIJjapVvA9w54gRY4Tpi19HXhI",
    subcategory: "creative-date",
    tags: ["fall", "halloween", "date-night", "pottery", "family"],
    audience: ["couples", "families", "kids"],
    official_event_url: "https://allfireduponline.com/pages/location",
    source_url: "https://www.instagram.com/reel/DcPT0D5Rwn6/",
    card_hook: "Paint your own pumpkin. Take the pottery home.",
    editorial_summary: "All Fired Up turns its paint-your-own-pottery studio into a full Halloween collection for the season.",
    why_go: "Choose this when the group wants a keepsake, not just a pumpkin patch photo.",
    fun_fact: "All Fired Up runs two Central Florida studios, in Winter Park and Waterford Lakes, both carrying the collection.",
    wayfind_verdict: "A hands-on fall date that comes home with you.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "all-fired-up-halloween-pottery-waterford-lakes-2026",
    event_series_id: "all-fired-up-halloween-pottery-waterford-lakes",
    event_name: "Halloween Pottery Collection at All Fired Up",
    short_title: "All Fired Up Halloween Pottery",
    slug: "all-fired-up-halloween-pottery-waterford-lakes-2026",
    start_date: "2026-08-19",
    end_date: null,
    schedule_note: "Launched August 19, per the studio's own collaboration post. The closing date has not been published.",
    venue: "All Fired Up (Waterford Lakes) Pottery Painting",
    address: "709 N Alafaya Trail",
    city: "Orlando",
    county: "Orange",
    lat: 28.553835,
    lng: -81.205856,
    place_id: "ChIJhbni_xFn54gR0p89LazzSD8",
    subcategory: "creative-date",
    tags: ["fall", "halloween", "date-night", "pottery", "family"],
    audience: ["couples", "families", "kids"],
    official_event_url: "https://allfireduponline.com/pages/location",
    source_url: "https://www.instagram.com/reel/DcPT0D5Rwn6/",
    card_hook: "Paint your own pumpkin. Take the pottery home.",
    editorial_summary: "All Fired Up turns its paint-your-own-pottery studio into a full Halloween collection for the season.",
    why_go: "Choose this when the group wants a keepsake, not just a pumpkin patch photo.",
    fun_fact: "All Fired Up runs two Central Florida studios, in Winter Park and Waterford Lakes, both carrying the collection.",
    wayfind_verdict: "A hands-on fall date that comes home with you.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "sirens-of-helena-icon-park-2026",
    event_series_id: "sirens-of-helena",
    event_name: "Sirens of Helena at Helena Modern Riviera",
    short_title: "Sirens of Helena",
    slug: "sirens-of-helena-icon-park-orlando-2026",
    start_date: "2026-09-05",
    end_date: null,
    schedule_note: "Begins September 5, per the venue's own announcement. The venue's site confirms the pop-up but does not publish a closing date.",
    venue: "Helena Modern Riviera",
    address: "8441 International Dr #260",
    city: "Orlando",
    county: "Orange",
    lat: 28.4428765,
    lng: -81.4692785,
    place_id: "ChIJP1om-VJ-54gRAF-_k_y5cig",
    subcategory: "themed-restaurant",
    tags: ["fall", "halloween", "date-night", "nightlife", "themed-bar"],
    audience: ["adults", "couples"],
    official_event_url: "https://helenamodernriviera.com/",
    source_url: "https://www.instagram.com/reel/DcoNdFxBQEx/",
    card_hook: "A sea change at ICON Park: sirens, smoke, and a diver-helmet cocktail.",
    editorial_summary: "Helena Modern Riviera turns its ICON Park dining room into an underwater escape with themed cocktails and dishes.",
    why_go: "Choose this when your night out needs a plot twist and a smoke machine.",
    fun_fact: "Helena Modern Riviera sits inside ICON Park on International Drive, home of The Wheel and several themed nightly experiences.",
    wayfind_verdict: "ICON Park just got haunted by mermaids.",
  },
  {
    ...FARM_EVENT,
    event_id: "the-berry-farm-harvest-festival-2026",
    event_series_id: "the-berry-farm-harvest-festival",
    event_name: "The Berry Farm Harvest Festival",
    short_title: "Berry Farm Harvest Festival",
    slug: "the-berry-farm-harvest-festival-miami-2026",
    start_date: "2026-09-16",
    end_date: "2026-11-15",
    select_nights: true,
    last_verified_at: "2026-09-06T00:00:00+00:00",
    schedule_note: "September 16 through November 15, 2026. Extended hours to 9 PM on listed Fridays and Sundays in October and November; not Saturday nights.",
    venue: "The Berry Farm",
    address: "13720 SW 216th St",
    city: "Miami",
    county: "Miami-Dade",
    lat: 25.562,
    lng: -80.42,
    place_id: null,
    official_event_url: "https://www.visittheberryfarm.com/pages/the-berry-farm-harvest-festival-2026-2027",
    source_url: "https://www.visittheberryfarm.com/pages/the-berry-farm-harvest-festival-2026-2027",
    card_hook: "South Florida's only 5-acre corn maze, in Redland.",
    editorial_summary: "The 7th annual Harvest Festival: pumpkin patch, 5-acre corn maze, sunflower fields, hayrides, and seasonal food for eight weeks.",
    why_go: "Pick this when Miami needs a real farm day, not a parking-lot pumpkin pile.",
    fun_fact: "Admission includes the maze, pumpkin patch, unlimited hayrides, and play areas; food and U-pick cost extra.",
    wayfind_verdict: "Miami's actual fall farm, not a pop-up.",
  },
  {
    ...FARM_EVENT,
    event_id: "bedners-fall-festival-2026",
    event_series_id: "bedners-fall-festival",
    event_name: "Bedner's Farm Fresh Market Fall Festival",
    short_title: "Bedner's Fall Festival",
    slug: "bedners-fall-festival-boynton-beach-2026",
    start_date: "2026-10-03",
    end_date: "2026-11-01",
    last_verified_at: "2026-09-06T00:00:00+00:00",
    source_tier: 2,
    verification_confidence: "medium",
    schedule_note: "October 3 through November 1, 2026. The farm's Fall Festival page confirms the 2026 season; detailed hours were not published on that page at fetch.",
    venue: "Bedner's Farm Fresh Market",
    address: "10066 Lee Road",
    city: "Boynton Beach",
    county: "Palm Beach",
    lat: 26.545,
    lng: -80.145,
    place_id: null,
    official_event_url: "https://bedners.com/fall-festival/",
    source_url: "https://bedners.com/fall-festival/",
    card_hook: "Boynton Beach farm festival: pumpkins and hayrides.",
    editorial_summary: "Bedner's annual Fall Festival returns to the Boynton Beach farm with a pumpkin patch and classic farm-day rides.",
    why_go: "Choose this when the drive north is the point — a working farm festival, not a city pop-up.",
    fun_fact: "The farm's own Fall Festival 2026 page lists the season at 10066 Lee Road in Boynton Beach.",
    wayfind_verdict: "The Palm Beach farm day for a Miami-north drive.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "the-horrorland-jungle-island-2026",
    event_series_id: "the-horrorland-jungle-island",
    event_name: "The Horrorland at Jungle Island",
    short_title: "The Horrorland",
    slug: "the-horrorland-jungle-island-miami-2026",
    start_date: "2026-09-10",
    end_date: "2026-11-01",
    select_nights: true,
    schedule_note: "September 10 through November 1, 2026. Thursday–Sunday, 7–10 PM. Hours subject to change.",
    venue: "Jungle Island",
    address: "1111 Parrot Jungle Trail",
    city: "Miami",
    county: "Miami-Dade",
    // Lane C (2026-09-06): the sourced point (25.816) sat 2 mi north of the
    // venue. 1111 Parrot Jungle Trail is Watson Island; these are the owned
    // Jungle Island row's coordinates (see fall-venue-identity-proof).
    lat: 25.7862,
    lng: -80.175,
    subcategory: "haunted-house",
    tags: ["fall", "halloween", "scary", "haunt"],
    audience: ["adults", "couples"],
    official_event_url: "https://www.thehorrorland.com/info",
    source_url: "https://www.thehorrorland.com/",
    card_hook: "Season 7 scream park at Jungle Island.",
    editorial_summary: "Horrorland's Season 7 at Jungle Island: haunted houses, scare zones, and the Circus of Terror on one ticket.",
    why_go: "Choose this when the night needs a full scream park, not a single walk-through.",
    fun_fact: "Gates open at 7 PM; the welcome show is at 7:30 PM. Tickets include the Circus of Terror.",
    wayfind_verdict: "Miami's in-town haunt campus.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "house-of-horror-carnival-2026",
    event_series_id: "house-of-horror-carnival",
    event_name: "House of Horror Carnival",
    short_title: "House of Horror Carnival",
    slug: "house-of-horror-carnival-tropical-park-2026",
    start_date: "2026-09-24",
    end_date: null, // unpublished on the official homepage at fetch — do not invent a close
    select_nights: true,
    schedule_note: "Opens September 24, 2026. Mon–Thu and Sunday 6–11 PM; Friday and Saturday 6 PM–midnight. Closed September 28 and October 5. Closing date unpublished.",
    venue: "House of Horror at Tropical Park",
    address: "7900 SW 40th St",
    city: "Miami",
    county: "Miami-Dade",
    lat: 25.724,
    lng: -80.319,
    subcategory: "haunted-house",
    tags: ["fall", "halloween", "scary", "haunt"],
    audience: ["adults", "couples"],
    official_event_url: "https://houseofhorrorcarnival.com/",
    source_url: "https://houseofhorrorcarnival.com/",
    card_hook: "Tropical Park haunt-carnival with a dark coaster.",
    editorial_summary: "Miami's haunt-carnival at Tropical Park: haunted houses, midway rides, and Howie's Blind Terror dark coaster.",
    why_go: "Pick this when the group wants a haunt and a carnival on the same ticket.",
    fun_fact: "Howie's Blind Terror is billed as the only haunted dark coaster in North America.",
    wayfind_verdict: "The long-running Tropical Park Halloween.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "nightmare-village-xtreme-action-park-2026",
    event_series_id: "nightmare-village-xtreme-action-park",
    event_name: "Nightmare Village at Xtreme Action Park",
    short_title: "Nightmare Village",
    slug: "nightmare-village-xtreme-action-park-2026",
    start_date: "2026-10-02",
    end_date: "2026-11-01",
    select_nights: true,
    schedule_note: "Select nights October 2 through November 1, 2026. Last admission 30 minutes before close. Not recommended for children under 13.",
    venue: "Xtreme Action Park",
    address: "5300 N Powerline Rd",
    city: "Fort Lauderdale",
    county: "Broward",
    lat: 26.193,
    lng: -80.154,
    subcategory: "haunted-house",
    tags: ["fall", "halloween", "scary", "haunt"],
    audience: ["adults"],
    official_event_url: "https://xtremeactionpark.com/experience-nightmare-village/",
    source_url: "https://xtremeactionpark.com/experience-nightmare-village/",
    card_hook: "Three haunted houses inside Xtreme Action Park.",
    editorial_summary: "Nightmare Village returns to Fort Lauderdale with three haunted houses and a listed October–November night calendar.",
    why_go: "Choose this when Fort Lauderdale needs a haunt night without a theme-park ticket.",
    fun_fact: "Official 2026 houses: Patches' Slaughter, The Collection, and The Cellar.",
    wayfind_verdict: "Broward's indoor haunt village.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "oktoberfest-miami-german-american-social-club-2026",
    event_series_id: "oktoberfest-miami-german-american-social-club",
    event_name: "Oktoberfest Miami at the German American Social Club",
    short_title: "Oktoberfest Miami",
    slug: "oktoberfest-miami-german-american-social-club-2026",
    start_date: "2026-10-09",
    end_date: "2026-10-18",
    select_nights: true,
    source_tier: 2,
    schedule_note: "October 9–11 and 16–18, 2026. Friday 6 PM–midnight; Saturday 2 PM–midnight; Sunday 2–10 PM. Skip American German Club of Lake Worth — different venue.",
    venue: "German American Social Club of Greater Miami",
    address: "11919 SW 56th St",
    city: "Miami",
    county: "Miami-Dade",
    lat: 25.712,
    lng: -80.388,
    subcategory: "oktoberfest",
    tags: ["fall", "beer", "oktoberfest"],
    audience: ["adults", "families"],
    official_event_url: "https://www.miamiandbeaches.com/event/oktoberfest-miami/13642",
    source_url: "https://www.miamiandbeaches.com/event/oktoberfest-miami/13642",
    card_hook: "German beer, bratwurst, and bands — two weekends.",
    editorial_summary: "Imported German beer, bratwurst, and European bands fill two weekends at the German American Social Club.",
    why_go: "Choose this when Miami wants a real Oktoberfest, not a one-night beer special.",
    fun_fact: "2026 lineup lists Die Donau Piraten, Die Seitz Bubn, and Schlager performer VRONI.",
    wayfind_verdict: "Miami's two-weekend Bavarian party.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "weekend-at-berryhaus-2026",
    event_series_id: "weekend-at-berryhaus",
    event_name: "Weekend at BerryHaus",
    short_title: "Weekend at BerryHaus",
    slug: "weekend-at-berryhaus-miami-2026",
    start_date: "2026-11-14",
    end_date: "2026-11-15",
    select_nights: true,
    schedule_note: "November 14–15, 2026, the final Harvest Festival weekend. Included with Harvest Festival admission.",
    venue: "The Berry Farm",
    address: "13720 SW 216th St",
    city: "Miami",
    county: "Miami-Dade",
    lat: 25.562,
    lng: -80.42,
    subcategory: "oktoberfest",
    tags: ["fall", "beer", "oktoberfest", "harvest"],
    audience: ["adults", "families"],
    official_event_url: "https://www.visittheberryfarm.com/pages/berryhaus",
    source_url: "https://www.visittheberryfarm.com/pages/berryhaus",
    card_hook: "Austrian harvest finale at The Berry Farm.",
    editorial_summary: "Harvest Festival's last weekend: Austrian-inspired food, seasonal beer, and live entertainment at BerryHaus.",
    why_go: "Stay for the last farm weekend when the beer garden is the reason.",
    fun_fact: "Owner Karl Wiegandt's Austrian family heritage is the stated inspiration for the weekend.",
    wayfind_verdict: "The Harvest Festival's closing toast.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "not-so-scary-halloween-bash-miami-childrens-museum-2026",
    event_series_id: "not-so-scary-halloween-bash-miami-childrens-museum",
    event_name: "Not So Scary Halloween Bash at Miami Children's Museum",
    short_title: "Not So Scary Halloween Bash",
    slug: "not-so-scary-halloween-bash-miami-childrens-museum-2026",
    start_date: "2026-10-04",
    end_date: "2026-10-04",
    schedule_note: "Sunday, October 4, 2026, 1–5 PM. Trick-or-treat through 17 galleries.",
    venue: "Miami Children's Museum",
    address: "980 MacArthur Causeway",
    city: "Miami",
    county: "Miami-Dade",
    lat: 25.785,
    lng: -80.178,
    subcategory: "family-halloween",
    tags: ["fall", "halloween", "trick-or-treat", "family"],
    audience: ["families", "kids"],
    official_event_url: "https://www.miamichildrensmuseum.org/upcoming-events",
    source_url: "https://www.miamichildrensmuseum.org/upcoming-events",
    card_hook: "Trick-or-treat through 17 museum galleries.",
    editorial_summary: "Costume day at Miami Children's Museum: mini pumpkins, crafts, character meet-and-greets, and a kid haunted house.",
    why_go: "Choose this when the kids want Halloween without a scream park.",
    fun_fact: "Proceeds support the museum's educational programs for children of all backgrounds and abilities.",
    wayfind_verdict: "The causeway's kid-safe Halloween.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "zoo-boo-zoo-miami-2026",
    event_series_id: "zoo-boo-zoo-miami",
    event_name: "Zoo Boo at Zoo Miami",
    short_title: "Zoo Boo",
    slug: "zoo-boo-zoo-miami-2026",
    start_date: "2026-10-24",
    end_date: "2026-10-25",
    schedule_note: "Saturday, October 24 and Sunday, October 25, 2026, 10 AM–3 PM. Included with Zoo Miami admission.",
    venue: "Zoo Miami",
    address: "12400 SW 152 St",
    city: "Miami",
    county: "Miami-Dade",
    lat: 25.613,
    lng: -80.4,
    subcategory: "family-halloween",
    tags: ["fall", "halloween", "trick-or-treat", "family"],
    audience: ["families", "kids"],
    official_event_url: "https://www.zoomiami.org/zoo-boo",
    source_url: "https://www.zoomiami.org/zoo-boo",
    card_hook: "Toddler-friendly trick-or-treat, included with Zoo.",
    editorial_summary: "Zoo Miami's premier toddler-friendly trick-or-treat weekend, with costumes, inflatables, and animal Halloween treats.",
    why_go: "Pick this when the costume has to work before nap time.",
    fun_fact: "Trick-or-treating is for ages 12 and under and is included with Zoo Miami admission.",
    wayfind_verdict: "The zoo day that already includes Halloween.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "boo-bash-pompano-beach-2026",
    event_series_id: "boo-bash-pompano-beach",
    event_name: "Boo Bash Pompano Beach Parks",
    short_title: "Pompano Boo Bash",
    slug: "boo-bash-pompano-beach-2026",
    start_date: "2026-10-24",
    end_date: "2026-10-24",
    is_free: true,
    price_band: "free",
    schedule_note: "Saturday, October 24, 2026, 4–9 PM at Community Park. Admission is free.",
    venue: "Pompano Beach Community Park",
    address: "1801 NE 6th St",
    city: "Pompano Beach",
    county: "Broward",
    lat: 26.241,
    lng: -80.114,
    subcategory: "family-halloween",
    tags: ["fall", "halloween", "family"],
    audience: ["families", "kids"],
    official_event_url: "https://parks.pompanobeachfl.gov/events/boo-bash-2026",
    source_url: "https://parks.pompanobeachfl.gov/events/boo-bash-2026",
    card_hook: "Free Community Park Halloween night in Pompano.",
    editorial_summary: "Pompano Beach Parks' free Boo Bash: carnival rides, food trucks, hay rides, and a costume contest.",
    why_go: "Choose this when Halloween has to be free and outdoors.",
    fun_fact: "The city lists carnival rides, hay rides, a pie-eating contest, and first-responder meetups.",
    wayfind_verdict: "Pompano's free park Halloween.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "bonnet-house-halloween-fest-2026",
    event_series_id: "bonnet-house-halloween-fest",
    event_name: "Bonnet House Halloween Fest",
    short_title: "Bonnet House Halloween Fest",
    slug: "bonnet-house-halloween-fest-2026",
    start_date: "2026-10-31",
    end_date: "2026-10-31",
    schedule_note: "Saturday, October 31, 2026, 11 AM–4 PM. Adults $25; ages 6–17 $8; 5 and under free.",
    venue: "Bonnet House Museum & Gardens",
    address: "900 N Birch Rd",
    city: "Fort Lauderdale",
    county: "Broward",
    lat: 26.137,
    lng: -80.105,
    subcategory: "family-halloween",
    tags: ["fall", "halloween", "family"],
    audience: ["families", "kids"],
    official_event_url: "https://www.bonnethouse.org/celebrate-halloween-in-historic-style-at-bonnet-houses-halloween-fest-2026/",
    source_url: "https://www.bonnethouse.org/celebrate-halloween-in-historic-style-at-bonnet-houses-halloween-fest-2026/",
    card_hook: "Halloween on a historic Fort Lauderdale estate.",
    editorial_summary: "Bonnet House Halloween Fest: costumes, a trick-or-treat trail, and a pet-and-people runway on the historic grounds.",
    why_go: "Pick this when the costume deserves a garden, not a parking lot.",
    fun_fact: "Pets are invited to the Pet, Adult & Children's Costume Runway.",
    wayfind_verdict: "Fort Lauderdale's historic-estate Halloween.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "boo-in-bloom-fruit-spice-park-2026",
    event_series_id: "boo-in-bloom-fruit-spice-park",
    event_name: "Boo in Bloom at Fruit & Spice Park",
    short_title: "Boo in Bloom",
    slug: "boo-in-bloom-fruit-spice-park-2026",
    start_date: "2026-10-31",
    end_date: "2026-10-31",
    source_tier: 2,
    verification_confidence: "medium",
    schedule_note: "Saturday, October 31, 2026, 10 AM–5 PM. Costume contest at 2 PM.",
    venue: "Fruit & Spice Park",
    address: "24801 SW 187th Ave",
    city: "Homestead",
    county: "Miami-Dade",
    lat: 25.5347,
    lng: -80.4947,
    subcategory: "family-halloween",
    tags: ["fall", "halloween", "family"],
    audience: ["families", "kids"],
    official_event_url: "https://www.miamiandbeaches.com/event/boo-in-bloom/42211",
    source_url: "https://www.miamiandbeaches.com/event/boo-in-bloom/42211",
    card_hook: "Costume day among Homestead fruit trees.",
    editorial_summary: "Halloween in costume at Fruit & Spice Park: tropical gardens, a 2 PM costume contest, and a daytime park outing.",
    why_go: "Choose this when Halloween should be outside, in a garden, before dark.",
    fun_fact: "Guests in costume can receive a free seed pack while supplies last.",
    wayfind_verdict: "Homestead's garden Halloween.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "roars-smores-snores-spooktacular-campout-zoo-miami-2026",
    event_series_id: "roars-smores-snores-spooktacular-campout-zoo-miami",
    event_name: "Roars, S'mores and Snores Spooktacular Campout at Zoo Miami",
    short_title: "Roars, S'mores and Snores",
    slug: "roars-smores-snores-spooktacular-campout-zoo-miami-2026",
    start_date: "2026-10-10",
    end_date: "2026-10-11",
    select_nights: true,
    schedule_note: "October 10–11, 2026, 6:00 PM Saturday through 9:30 AM Sunday. Bring your own tent. $80 per person.",
    venue: "Zoo Miami",
    address: "12400 SW 152 St",
    city: "Miami",
    county: "Miami-Dade",
    lat: 25.613,
    lng: -80.4,
    subcategory: "family-halloween",
    tags: ["fall", "halloween", "family"],
    audience: ["families", "kids"],
    official_event_url: "https://www.zoomiami.org/night-programs",
    source_url: "https://www.zoomiami.org/night-programs",
    card_hook: "Zoo Miami's 20th annual spooky overnight.",
    editorial_summary: "The 20th annual Roars, S'mores and Snores campout adds a spooky twist: night tram tour and hands-on activities.",
    why_go: "Book this when the kids want to sleep at the zoo, not just visit it.",
    fun_fact: "Groups need one adult for every eight minors. The program runs rain or shine, no weather refunds.",
    wayfind_verdict: "The zoo overnight with a Halloween twist.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "deerfield-beach-fall-festival-2026",
    event_series_id: "deerfield-beach-fall-festival",
    event_name: "Deerfield Beach Fall Festival",
    short_title: "Deerfield Beach Fall Festival",
    slug: "deerfield-beach-fall-festival-2026",
    start_date: "2026-10-10",
    end_date: "2026-10-10",
    is_free: true,
    price_band: "free",
    schedule_note: "Saturday, October 10, 2026, 4–8 PM at Pioneer Park, 217 NE 5th Ave. Free admission.",
    venue: "Pioneer Park",
    address: "217 NE 5th Ave",
    city: "Deerfield Beach",
    county: "Broward",
    lat: 26.318,
    lng: -80.08,
    category: "festival",
    subcategory: "fall-festival",
    tags: ["fall", "festival", "pumpkins", "family"],
    audience: ["families", "kids", "adults"],
    official_event_url: "https://deerfield-beach.com/1407/Fall-Festival",
    source_url: "https://deerfield-beach.com/1407/Fall-Festival",
    card_hook: "Free Pioneer Park night: pumpkins and Biergarten.",
    editorial_summary: "Deerfield Beach's free Fall Festival: pumpkin patch, Biergarten, Trunk-or-Treat, live music, and vendors.",
    why_go: "Choose this when the night should be free, local, and outdoors.",
    fun_fact: "The pumpkin patch offers one large pumpkin per family, while supplies last.",
    wayfind_verdict: "Deerfield's free fall night in Pioneer Park.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "zoo-miami-monster-masquerade-2026",
    event_series_id: "zoo-miami-monster-masquerade",
    event_name: "Zoo Miami Monster Masquerade",
    short_title: "Monster Masquerade",
    slug: "zoo-miami-monster-masquerade-2026",
    start_date: "2026-10-17",
    end_date: "2026-10-17",
    schedule_note: "Saturday, October 17, 2026, 7–11 PM. Adults only (21+).",
    venue: "Zoo Miami",
    address: "12400 SW 152 St",
    city: "Miami",
    county: "Miami-Dade",
    lat: 25.613,
    lng: -80.4,
    subcategory: "theme-park",
    tags: ["fall", "halloween", "theme-park"],
    audience: ["adults"],
    official_event_url: "https://www.zoomiami.org/monster",
    source_url: "https://www.zoomiami.org/monster",
    card_hook: "21+ Halloween night at Zoo Miami.",
    editorial_summary: "Zoo Miami's adults-only Monster Masquerade: open bars, complimentary bites, DJ, and a costume contest under the moonlight.",
    why_go: "Choose this when Halloween needs a zoo after dark and a costume contest.",
    fun_fact: "The official program includes open bars by BACARDÍ, a tiger feeding, and after-hours animal ambassadors.",
    wayfind_verdict: "The 21+ zoo night.",
  },
  {
    ...MIAMI_EVENT,
    event_id: "halloween-at-faena-miami-beach-2026",
    event_series_id: "halloween-at-faena-miami-beach",
    event_name: "Halloween at Faena Miami Beach",
    short_title: "Halloween at Faena",
    slug: "halloween-at-faena-miami-beach-2026",
    start_date: "2026-10-31",
    end_date: "2026-11-01",
    select_nights: true,
    schedule_note: "Living Room Halloween: October 31 and November 1. Prelude dinners and Faena Theater's EVERAFTER are listed for October 31.",
    venue: "Faena Miami Beach",
    address: "3201 Collins Ave",
    city: "Miami Beach",
    county: "Miami-Dade",
    lat: 25.808,
    lng: -80.124,
    subcategory: "themed-bar",
    tags: ["fall", "halloween", "date-night", "nightlife"],
    audience: ["adults", "couples"],
    official_event_url: "https://www.faena.com/miami-beach/things-to-do/event-calendar/halloween-at-faena-miami-beach",
    source_url: "https://www.faena.com/miami-beach/things-to-do/event-calendar/halloween-at-faena-miami-beach",
    card_hook: "Living Room Halloween soirée, then Everafter.",
    editorial_summary: "Faena Miami Beach's Halloween: Living Room cocktails and live music, prelude dinners, then EVERAFTER in the theater.",
    why_go: "Book this when the date needs a hotel soirée, not a scream park.",
    fun_fact: "Indoor Los Fuegos reservations include Living Room access; veranda reservations do not.",
    wayfind_verdict: "Collins Avenue's Halloween night out.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "palace-miami-beach-fall-harvest-menu-2026",
    event_series_id: "palace-miami-beach-fall-harvest-menu",
    event_name: "Palace Miami Beach Fall Harvest Menu",
    short_title: "Palace Fall Harvest",
    slug: "palace-miami-beach-fall-harvest-menu-2026",
    start_date: "2026-09-21",
    end_date: null,
    // Press-verified: official homepage at fetch listed Spice and standing
    // menus only — no Fall Harvest block. Keep this as a dated event, not a
    // seasonal-place card, until an owned place_id exists.
    source_type: "press",
    source_tier: 3,
    verification_confidence: "medium",
    last_verified_at: "2026-09-06T00:00:00+00:00",
    schedule_note: "Press-verified Fall Harvest menu (WSVN Deco Drive, 2026). Official homepage lacked Fall Harvest text at fetch. Closing date unpublished.",
    venue: "Palace South Beach",
    address: "1052 Ocean Drive",
    city: "Miami Beach",
    county: "Miami-Dade",
    lat: 25.781,
    lng: -80.131,
    place_id: null,
    subcategory: "seasonal-cafe",
    tags: ["fall", "food", "seasonal-drinks"],
    audience: ["adults", "couples"],
    official_event_url: "https://palacesouthbeach.com/",
    source_url: "https://wsvn.com/entertainment/deco-drive/miami-restaurants-unique-pumpkin-dishes/",
    card_hook: "Pumpkin margarita, gnocchi, and a fall arepa.",
    editorial_summary: "Palace's Fall Harvest menu, confirmed by WSVN: pumpkin cocktails, pumpkin gnocchi, and a burrata-pumpkin arepa.",
    why_go: "Choose this when Ocean Drive needs a seasonal plate, not another pumpkin spice latte.",
    fun_fact: "WSVN: the star cocktail is a pumpkin espresso martini finished with condensed milk.",
    wayfind_verdict: "The South Beach fall menu the official site did not yet print.",
  },
]);

export const FALL_DISCOVERY_RAIL = Object.freeze({
  "haunted-mangoni-2026": "date-night",
  "rosallie-lattes-leaves-2026": "food",
  "nueva-cantina-halloween-tampa-2026": "date-night",
  "you-do-the-dishes-fall-2026": "date-night",
  "perfect-press-fall-coffee-2026": "food",
  "showcase-citrus-pumpkin-ponderosa-2026": "farms",
  "amber-brooke-fall-festival-2026": "farms",
  "green-meadows-fall-2026": "farms",
  "great-scott-fall-fest-2026": "farms",
  "southern-hill-farms-fall-festival-2026": "farms",
  "hastings-ranch-farm-festival-2026": "farms",
  "dead-coconut-club-harvest-citywalk-2026": "date-night",
  "haraz-house-pumpkin-spice-wesley-chapel-2026": "food",
  "all-fired-up-halloween-pottery-winter-park-2026": "date-night",
  "all-fired-up-halloween-pottery-waterford-lakes-2026": "date-night",
  "sirens-of-helena-icon-park-2026": "date-night",
  // 2026-09-06 — Miami / South Florida Fall coverage pack. American German
  // Club of Lake Worth is deliberately absent (different venue).
  "the-berry-farm-harvest-festival-2026": "farms",
  "bedners-fall-festival-2026": "farms",
  "the-horrorland-jungle-island-2026": "haunts",
  "house-of-horror-carnival-2026": "haunts",
  "nightmare-village-xtreme-action-park-2026": "haunts",
  "oktoberfest-miami-german-american-social-club-2026": "oktoberfest",
  "weekend-at-berryhaus-2026": "oktoberfest",
  "not-so-scary-halloween-bash-miami-childrens-museum-2026": "family",
  "zoo-boo-zoo-miami-2026": "family",
  "boo-bash-pompano-beach-2026": "family",
  "bonnet-house-halloween-fest-2026": "family",
  "boo-in-bloom-fruit-spice-park-2026": "family",
  "roars-smores-snores-spooktacular-campout-zoo-miami-2026": "family",
  "deerfield-beach-fall-festival-2026": "festivals",
  "zoo-miami-monster-masquerade-2026": "theme-parks",
  "halloween-at-faena-miami-beach-2026": "date-night",
  "palace-miami-beach-fall-harvest-menu-2026": "food",
  // 2026-09-03 — the Sarasota-side rows from scripts/seed-fall-sarasota-2026.mjs,
  // each pinned to ONE shelf. Three of these the keyword classifier would
  // misfile: the Halloween demolition derby reads as "family" (audience +
  // halloween tag), and the two small-town festivals read as "festivals" when
  // the reason they are on the poster is the drive.
  "sir-henrys-haunted-trail-2026": "haunts",
  "fearville-dk-farms-2026": "haunts",
  "lights-at-spooky-point-2026": "family",
  "selby-spooktacular-2026": "family",
  "island-trunk-or-treat-ami-2026": "family",
  "oktoberfest-tampa-bay-german-american-2026": "oktoberfest",
  "three-daughters-oktoberfest-2026": "oktoberfest",
  "oktoberfest-tampa-curtis-hixon-2026": "oktoberfest",
  "park-toberfest-bay-sarasota-2026": "oktoberfest",
  "rocktoberfest-sarasota-2026": "oktoberfest",
  "sharktoberfest-mote-2026": "date-night",
  "haunted-sarasota-trolley-2026": "date-night",
  "candlelight-halloween-siesta-key-2026": "date-night",
  "sarasota-boos-booze-bar-crawl-2026": "date-night",
  "st-pete-halloween-bar-crawl-2026": "date-night",
  "ami-bayfest-2026": "festivals",
  "ruskin-seafood-festival-2026": "festivals",
  "freedom-factory-halloween-destruction-2026": "festivals",
  "cedar-key-seafood-festival-2026": "day-trips",
  "mount-dora-craft-fair-2026": "day-trips",
  "crystal-river-manatee-season-2026": "day-trips",
});

// These discoveries describe a seasonal product at a permanent business,
// not a dated event. They still carry start/end evidence because the offering
// is seasonal, but the card must open the Google place, show the venue's own
// photo and use place actions. Keeping this distinction outside the wf_events
// storage shape lets older seeded rows render correctly without a production
// data rewrite.
export const FALL_SEASONAL_PLACE_IDS = Object.freeze(new Set(
  FALL_DISCOVERIES_2026
    .filter((row) => row && row.source_type === "owner-received-discovery")
    .map((row) => row.event_id),
));
