// Owner supplied Fall in Florida discoveries, verified for the 2026 season.
//
// These are events instead of permanent fall places because each recommendation
// depends on a seasonal program. The explicit rail registry keeps every card in
// one intent only, even when a farm is also family friendly or a cafe also works
// for a date.

const BUSINESS_DISCOVERY = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  select_nights: false,
  category: "seasonal",
  state: "FL",
  source_type: "owner-received-discovery",
  source_tier: 3,
  verification_confidence: "medium",
  last_verified_at: "2026-09-02T00:00:00+00:00",
  editorial_score: 8,
  uniqueness_score: 8,
  popularity_score: 7,
  is_free: false,
  price_band: "$$",
};

const FARM_EVENT = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  select_nights: false,
  category: "seasonal",
  subcategory: "farm-festival",
  state: "FL",
  source_type: "official-organizer",
  source_tier: 1,
  verification_confidence: "high",
  last_verified_at: "2026-09-02T00:00:00+00:00",
  editorial_score: 8,
  uniqueness_score: 7,
  popularity_score: 8,
  audience: ["families", "kids"],
  tags: ["fall", "family", "pumpkins", "farm", "harvest"],
  is_free: false,
  price_band: "$$",
  duration_recommendation: "Half day",
  crowd_level: "high",
};

export const FALL_DISCOVERIES_2026 = Object.freeze([
  {
    ...BUSINESS_DISCOVERY,
    event_id: "haunted-mangoni-2026",
    event_series_id: "haunted-mangoni",
    event_name: "Haunted Mangoni",
    short_title: "Haunted Mangoni",
    slug: "haunted-mangoni-winter-garden-2026",
    start_date: "2026-09-05",
    end_date: null,
    source_tier: 1,
    verification_confidence: "high",
    schedule_note: "Begins September 5, confirmed by the venue's own announcement (reservations now open). The closing date has not been published.",
    venue: "MANGONI Italian Market Pizza",
    address: "251 Tremaine St",
    city: "Winter Garden",
    county: "Orange",
    lat: 28.56483,
    lng: -81.5883934,
    place_id: "ChIJRStTdYSD54gRhH5dTvKQLJI",
    subcategory: "themed-restaurant",
    tags: ["fall", "halloween", "date-night", "nightlife", "themed-bar"],
    audience: ["adults", "couples"],
    official_event_url: "https://mangoniwg.com/",
    source_url: "https://www.instagram.com/p/DcyS5k4gVV5/",
    card_hook: "Wood-fired pizza with a side of haunted.",
    editorial_summary: "Halloween decor, cocktails and wood-fired pizza turn dinner into the actual event — now with a venue-confirmed date.",
    why_go: "Book this when the plan needs a scare between the antipasto and the pizza.",
    fun_fact: "Mangoni rests its pizza dough for 24 hours before it reaches the wood fired oven.",
    wayfind_verdict: "Winter Garden's spookiest slice just got official.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "rosallie-lattes-leaves-2026",
    event_series_id: "rosallie-lattes-leaves",
    event_name: "Lattes and Leaves at Rosallie",
    short_title: "Lattes and Leaves",
    slug: "rosallie-lattes-leaves-winter-garden-2026",
    start_date: "2026-09-05",
    end_date: null,
    schedule_note: "Begins September 5. The closing date has not been published.",
    venue: "Rosallie Le French Cafe",
    address: "141 W Plant Street",
    city: "Winter Garden",
    county: "Orange",
    lat: 28.5656211,
    lng: -81.5872974,
    place_id: "ChIJ15lqd26D54gR0zik2zNTX4o",
    subcategory: "seasonal-cafe",
    tags: ["fall", "food", "coffee", "pastries"],
    audience: ["adults", "couples", "families"],
    official_event_url: "https://rosallie.com/winter-garden/",
    source_url: "https://rosallie.com/winter-garden/",
    card_hook: "Parisian pastry energy, Florida fall edition.",
    editorial_summary: "Seasonal drinks, pastries and leafy decor deliver fall without the farm day.",
    why_go: "Choose this when you want cozy now and pumpkins later.",
    fun_fact: "Rosallie serves its French cafe concept in Winter Garden and Las Vegas.",
    wayfind_verdict: "The quickest cozy fall win in Winter Garden.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "nueva-cantina-halloween-tampa-2026",
    event_series_id: "nueva-cantina-halloween-tampa",
    event_name: "Halloween at Nueva Cantina Downtown Tampa",
    short_title: "Nueva Cantina Halloween",
    slug: "nueva-cantina-halloween-downtown-tampa-2026",
    start_date: "2026-09-02",
    end_date: null,
    schedule_note: "Verified for the 2026 fall season. The closing date has not been published.",
    venue: "Nueva Cantina Downtown Tampa",
    address: "903 N Franklin St",
    city: "Tampa",
    county: "Hillsborough",
    lat: 27.9517198,
    lng: -82.4594849,
    place_id: "ChIJmzKZ8InEwogR0PM7xTqUB6M",
    subcategory: "themed-restaurant",
    tags: ["fall", "halloween", "date-night", "nightlife", "themed-bar", "food"],
    audience: ["adults", "couples"],
    official_event_url: "https://nuevacantina.com/locations/",
    // Upgraded 2026-09-02: the venue's own account, newer than the prior
    // third-party reel it replaces.
    source_url: "https://www.instagram.com/reel/Dcwmv51CK5T/",
    card_hook: "Tacos, margaritas and a Halloween takeover.",
    editorial_summary: "Themed drinks, food and decor turn downtown dinner into the night out.",
    why_go: "Choose this when your fall plan needs cocktails, not a corn maze.",
    fun_fact: "The Downtown Tampa location stays open until midnight on Friday and Saturday.",
    wayfind_verdict: "Halloween dinner that keeps the night moving.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "you-do-the-dishes-fall-2026",
    event_series_id: "you-do-the-dishes-fall",
    event_name: "Fall Pottery at You Do the Dishes",
    short_title: "Fall Pottery and Coffee",
    slug: "you-do-the-dishes-fall-pottery-tampa-2026",
    start_date: "2026-09-02",
    end_date: null,
    schedule_note: "Verified for the 2026 fall season. The closing date has not been published.",
    venue: "You Do the Dishes",
    address: "15357 Amberly Drive",
    city: "Tampa",
    county: "Hillsborough",
    lat: 28.0876248,
    lng: -82.4037597,
    place_id: "ChIJIV9AOfbHwogR5SPjijvBLRM",
    subcategory: "creative-date",
    tags: ["fall", "halloween", "date-night", "pottery", "coffee"],
    audience: ["couples", "families", "kids"],
    official_event_url: "https://www.youdothedishes.com/",
    source_url: "https://www.youdothedishes.com/",
    card_hook: "Paint a pumpkin. Sip coffee. Keep the evidence.",
    editorial_summary: "Fall pottery and a full coffee bar make this a date, girls day or family plan.",
    why_go: "You leave with a memory and a piece you made yourself.",
    fun_fact: "The studio offers more than 75 paint colors and fires finished pieces for pickup in three to five days.",
    wayfind_verdict: "Tampa's most hands on fall date.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "perfect-press-fall-coffee-2026",
    event_series_id: "perfect-press-fall-coffee",
    event_name: "Fall at The Perfect Press Coffee Co.",
    short_title: "Perfect Press Fall Coffee",
    slug: "perfect-press-fall-coffee-carrollwood-2026",
    start_date: "2026-09-02",
    end_date: null,
    schedule_note: "Verified for the 2026 fall season. The closing date has not been published.",
    venue: "The Perfect Press Coffee Co.,LLC",
    city: "Carrollwood",
    county: "Hillsborough",
    lat: 28.0728871,
    lng: -82.5219324,
    place_id: "ChIJc9TZhGDAwogRRHZ5EzKtJIc",
    subcategory: "seasonal-cafe",
    tags: ["fall", "food", "coffee", "seasonal-drinks"],
    audience: ["adults", "couples", "families"],
    official_event_url: "https://www.theperfectpresscoffee.com/",
    source_url: "https://www.theperfectpresscoffee.com/",
    card_hook: "The storefront dressed for fall before Florida did.",
    editorial_summary: "Pumpkins, florals and seasonal drinks turn a coffee stop into a fall reset.",
    why_go: "Get the atmosphere and the pumpkin matcha without losing half a day.",
    fun_fact: "The seasonal styling covers the storefront, so the fall experience starts before you order.",
    wayfind_verdict: "Carrollwood's quick hit of fall.",
  },
  {
    ...FARM_EVENT,
    event_id: "showcase-citrus-pumpkin-ponderosa-2026",
    event_series_id: "showcase-citrus-pumpkin-ponderosa",
    event_name: "Showcase of Citrus Pumpkin Ponderosa",
    short_title: "Pumpkin Ponderosa",
    slug: "showcase-of-citrus-pumpkin-ponderosa-2026",
    start_date: "2026-09-18",
    end_date: "2026-10-31",
    select_nights: true,
    schedule_note: "September 18 through October 31. Haunted monster truck rides run on select nights.",
    venue: "Showcase of Citrus",
    address: "15051 Frank Jarrell Rd",
    city: "Clermont",
    county: "Lake",
    lat: 28.4237254,
    lng: -81.7037559,
    place_id: "ChIJW5C20gaI54gRZuH_-8hPQy8",
    official_event_url: "https://www.showcaseofcitrus.com/updates.html",
    source_url: "https://www.showcaseofcitrus.com/updates.html",
    card_hook: "Pumpkins by day. Haunted monster trucks by night.",
    editorial_summary: "A patch, fall food, family activities and monster trucks make this peak Florida fall.",
    why_go: "Pick this when a normal pumpkin patch sounds too normal.",
    fun_fact: "The 2026 Pumpkin Ponderosa is the event's eighth annual season.",
    wayfind_verdict: "The pumpkin patch with the best plot twist.",
  },
  {
    ...FARM_EVENT,
    event_id: "amber-brooke-fall-festival-2026",
    event_series_id: "amber-brooke-fall-festival",
    event_name: "Amber Brooke Farms Fall Festival",
    short_title: "Amber Brooke Fall Festival",
    slug: "amber-brooke-farms-fall-festival-2026",
    start_date: "2026-09-19",
    end_date: "2026-11-22",
    select_nights: true,
    schedule_note: "Weekends from September 19 through November 22, 10 AM to 6 PM.",
    venue: "Amber Brooke Farms",
    address: "36111 N CR 44A",
    city: "Eustis",
    county: "Lake",
    lat: 28.8754542,
    lng: -81.6394191,
    official_event_url: "https://amberbrookefarms.com/event/6th-annual-fall-festival-11/",
    source_url: "https://amberbrookefarms.com/event/6th-annual-fall-festival-11/",
    card_hook: "More than 25 ways to earn the ride home nap.",
    editorial_summary: "Pumpkins, tractor rides, music, animals and jump pads fill a full family day.",
    why_go: "Come for the pumpkin barn when the kids need more than one activity.",
    fun_fact: "The 2026 festival is Amber Brooke Farms' sixth annual fall celebration.",
    wayfind_verdict: "The all day family farm near Eustis.",
  },
  {
    ...FARM_EVENT,
    event_id: "green-meadows-fall-2026",
    event_series_id: "green-meadows-fall",
    event_name: "Green Meadows Farm Fall",
    short_title: "Green Meadows Pumpkin Picking",
    slug: "green-meadows-farm-fall-2026",
    start_date: "2026-09-26",
    end_date: "2026-11-08",
    select_nights: true,
    schedule_note: "Pumpkin picking runs September 26 through November 8. Each paid admission includes one pumpkin.",
    venue: "Green Meadows Petting Farm",
    address: "1881 Jack Calhoun Dr",
    city: "Kissimmee",
    county: "Osceola",
    lat: 28.2711014,
    lng: -81.4323259,
    place_id: "ChIJMRKPC1mC3YgRTs5evGTqF4k",
    official_event_url: "https://greenmeadowsfarm.com/special-events/",
    source_url: "https://greenmeadowsfarm.com/special-events/",
    card_hook: "Meet the animals. Pick a pumpkin. Keep it.",
    editorial_summary: "A full petting farm visit comes with pumpkin picking and clear family value.",
    why_go: "One pumpkin is included with every paid admission, so there is no checkout surprise.",
    fun_fact: "Green Meadows also schedules family Candy Hunts during select October weekends.",
    wayfind_verdict: "The smartest value farm day in Kissimmee.",
  },
  {
    ...FARM_EVENT,
    event_id: "great-scott-fall-fest-2026",
    event_series_id: "great-scott-fall-fest",
    event_name: "Great Scott Farms Fall Fest and Corn Maze",
    short_title: "Great Scott Fall Fest",
    slug: "great-scott-farms-fall-fest-2026",
    start_date: "2026-09-26",
    end_date: null,
    select_nights: true,
    schedule_note: "Opens September 26. The farm has not published a closing date.",
    venue: "Great Scott Farms",
    address: "26216 County Road 448A",
    city: "Mount Dora",
    county: "Lake",
    lat: 28.72853,
    lng: -81.6682,
    official_event_url: "https://longandscottfarms.com/",
    source_url: "https://longandscottfarms.com/",
    card_hook: "Seven acres of corn between you and victory.",
    editorial_summary: "A giant maze, jumping pillow, zip line and super slide keep the whole crew moving.",
    why_go: "Choose this when the corn maze is the main event, not background decor.",
    fun_fact: "Long and Scott Farms has grown Zellwood sweet corn and other produce since 1963.",
    wayfind_verdict: "Central Florida's classic corn maze day.",
  },
  {
    ...FARM_EVENT,
    event_id: "southern-hill-farms-fall-festival-2026",
    event_series_id: "southern-hill-farms-fall-festival",
    event_name: "Southern Hill Farms Fall Festival",
    short_title: "Southern Hill Farms",
    slug: "southern-hill-farms-fall-festival-2026",
    start_date: "2026-09-26",
    end_date: "2026-11-22",
    select_nights: true,
    schedule_note: "Select Thursdays and every Friday through Sunday from September 26 through November 22, plus October 12.",
    venue: "Southern Hill Farms",
    address: "16651 Schofield Rd",
    city: "Clermont",
    county: "Lake",
    lat: 28.4541904,
    lng: -81.6783927,
    official_event_url: "https://southernhillfarms.com/event/11th-annual-fall-festival/",
    source_url: "https://southernhillfarms.com/event/11th-annual-fall-festival/",
    card_hook: "The fall festival that needs a full itinerary.",
    editorial_summary: "Rides, corn, flowers, animals, music and food make this Clermont's anchor fall day.",
    why_go: "Choose it when everyone wants something different and nobody wants to leave early.",
    fun_fact: "The 2026 season is Southern Hill Farms' 11th annual Fall Festival.",
    wayfind_verdict: "Clermont's biggest all in fall day.",
  },
  {
    ...FARM_EVENT,
    event_id: "hastings-ranch-farm-festival-2026",
    event_series_id: "hastings-ranch-farm-festival",
    event_name: "Hastings Ranch and Farm Festival",
    short_title: "Hastings Ranch Festival",
    slug: "hastings-ranch-farm-festival-2026",
    start_date: "2026-10-10",
    end_date: "2026-11-01",
    select_nights: true,
    schedule_note: "October 10 and 11, 17 and 18, 24 and 25, and October 31 through November 1, 10 AM to 5 PM.",
    venue: "Hastings Ranch and Farm",
    address: "1550 Dolphin Dr",
    city: "St Cloud",
    county: "Osceola",
    lat: 28.2610709,
    lng: -81.1856788,
    place_id: "ChIJAyTZ7DqN3YgRrdAAVCHFMkA",
    official_event_url: "https://hastingsranchandfarm.com/farm-festival/",
    source_url: "https://hastingsranchandfarm.com/farm-festival/",
    card_hook: "Big fall energy without the giant festival stampede.",
    editorial_summary: "Games, food, hay rides, corn and pumpkins deliver the full ranch day near St Cloud.",
    why_go: "Pick it when local charm beats an Instagram famous crowd.",
    fun_fact: "The 2026 event is Hastings Ranch and Farm's eighth annual festival.",
    wayfind_verdict: "The local alternative to the giant farm festivals.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "dead-coconut-club-harvest-citywalk-2026",
    event_series_id: "dead-coconut-club-harvest",
    event_name: "Dead Coconut Club: Harvest",
    short_title: "Dead Coconut Club: Harvest",
    slug: "dead-coconut-club-harvest-citywalk-orlando-2026",
    start_date: "2026-08-28",
    end_date: "2026-11-01",
    select_nights: true,
    source_tier: 1,
    verification_confidence: "high",
    schedule_note: "Open from 4 PM on Halloween Horror Nights 35 event nights only — select nights, not every night, Aug 28 through Nov 1, 2026, per Universal Orlando's own event page.",
    venue: "Red Coconut Club (seasonally the Dead Coconut Club)",
    address: "6000 Universal Blvd",
    city: "Orlando",
    county: "Orange",
    lat: 28.4731837,
    lng: -81.4650605,
    place_id: "ChIJwZ_GK-d-54gRm5Ahg7PZYeY",
    subcategory: "themed-bar",
    tags: ["fall", "halloween", "date-night", "nightlife", "themed-bar"],
    audience: ["adults", "couples"],
    official_event_url: "https://www.universalorlando.com/web/en/us/things-to-do/events/halloween-horror-nights/index.html",
    source_url: "https://www.instagram.com/reel/Dcg3_aRix46/",
    card_hook: "CityWalk's nightclub goes full Halloween — no HHN ticket required.",
    editorial_summary: "Free, all-ages walk-up: CityWalk's Red Coconut Club becomes the Dead Coconut Club each Horror Nights season, open 4 PM.",
    why_go: "Choose this when the group wants Horror Nights energy without buying a Horror Nights ticket.",
    fun_fact: "It runs on the same select-night calendar as Halloween Horror Nights itself, August 28 through November 1, 2026.",
    wayfind_verdict: "CityWalk's free-entry answer to Horror Nights.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "haraz-house-pumpkin-spice-wesley-chapel-2026",
    event_series_id: "haraz-house-pumpkin-spice",
    event_name: "Pumpkin Spice Bakery Menu at Haraz House",
    short_title: "Haraz House Pumpkin Spice",
    slug: "haraz-house-pumpkin-spice-wesley-chapel-2026",
    start_date: "2026-09-02",
    end_date: null,
    schedule_note: "Verified for the 2026 fall season. The closing date has not been published.",
    venue: "Haraz Coffee House",
    address: "1722 Bruce B Downs Blvd",
    city: "Wesley Chapel",
    county: "Pasco",
    lat: 28.1823545,
    lng: -82.3514208,
    place_id: "ChIJQVp535WxwogR42W828PdPRw",
    subcategory: "seasonal-cafe",
    tags: ["fall", "food", "coffee", "pastries"],
    audience: ["adults", "couples", "families"],
    official_event_url: "https://harazcoffeehouse.com/pages/menu",
    source_url: "https://www.instagram.com/reel/DctUcUexTXR/",
    card_hook: "A Yemeni coffee house adds pumpkin spice to its own bakery case.",
    editorial_summary: "Haraz Coffee House turns its Wesley Chapel bakery case fall, alongside its usual Yemeni coffee and pastries.",
    why_go: "Choose this when the plan is coffee and a pastry, not a full meal.",
    fun_fact: "Haraz Coffee House is a Yemeni-owned chain with locations across the country; this is the Wesley Chapel room.",
    wayfind_verdict: "A fall pastry stop on Bruce B Downs.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "all-fired-up-halloween-pottery-winter-park-2026",
    // Distinct series_id from the Waterford Lakes entry below on purpose: the
    // fall-rail composer dedupes by event_series_id (lib/fallIntentRails.js),
    // and these are two real venues that should both render, not one event
    // franchise where only the nearest copy should survive.
    event_series_id: "all-fired-up-halloween-pottery-winter-park",
    event_name: "Halloween Pottery Collection at All Fired Up",
    short_title: "All Fired Up Halloween Pottery",
    slug: "all-fired-up-halloween-pottery-winter-park-2026",
    start_date: "2026-08-19",
    end_date: null,
    schedule_note: "Launched August 19, per the studio's own collaboration post. The closing date has not been published.",
    venue: "All Fired Up (Winter Park) Pottery Painting",
    address: "229 W Fairbanks Ave",
    city: "Winter Park",
    county: "Orange",
    lat: 28.593253,
    lng: -81.352214,
    place_id: "ChIJjapVvA9w54gRY4Tpi19HXhI",
    subcategory: "creative-date",
    tags: ["fall", "halloween", "date-night", "pottery", "family"],
    audience: ["couples", "families", "kids"],
    official_event_url: "https://allfireduponline.com/pages/location",
    source_url: "https://www.instagram.com/reel/DcPT0D5Rwn6/",
    card_hook: "Paint your own pumpkin. Take the pottery home.",
    editorial_summary: "All Fired Up turns its paint-your-own-pottery studio into a full Halloween collection for the season.",
    why_go: "Choose this when the group wants a keepsake, not just a pumpkin patch photo.",
    fun_fact: "All Fired Up runs two Central Florida studios, in Winter Park and Waterford Lakes, both carrying the collection.",
    wayfind_verdict: "A hands-on fall date that comes home with you.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "all-fired-up-halloween-pottery-waterford-lakes-2026",
    event_series_id: "all-fired-up-halloween-pottery-waterford-lakes",
    event_name: "Halloween Pottery Collection at All Fired Up",
    short_title: "All Fired Up Halloween Pottery",
    slug: "all-fired-up-halloween-pottery-waterford-lakes-2026",
    start_date: "2026-08-19",
    end_date: null,
    schedule_note: "Launched August 19, per the studio's own collaboration post. The closing date has not been published.",
    venue: "All Fired Up (Waterford Lakes) Pottery Painting",
    address: "709 N Alafaya Trail",
    city: "Orlando",
    county: "Orange",
    lat: 28.553835,
    lng: -81.205856,
    place_id: "ChIJhbni_xFn54gR0p89LazzSD8",
    subcategory: "creative-date",
    tags: ["fall", "halloween", "date-night", "pottery", "family"],
    audience: ["couples", "families", "kids"],
    official_event_url: "https://allfireduponline.com/pages/location",
    source_url: "https://www.instagram.com/reel/DcPT0D5Rwn6/",
    card_hook: "Paint your own pumpkin. Take the pottery home.",
    editorial_summary: "All Fired Up turns its paint-your-own-pottery studio into a full Halloween collection for the season.",
    why_go: "Choose this when the group wants a keepsake, not just a pumpkin patch photo.",
    fun_fact: "All Fired Up runs two Central Florida studios, in Winter Park and Waterford Lakes, both carrying the collection.",
    wayfind_verdict: "A hands-on fall date that comes home with you.",
  },
  {
    ...BUSINESS_DISCOVERY,
    event_id: "sirens-of-helena-icon-park-2026",
    event_series_id: "sirens-of-helena",
    event_name: "Sirens of Helena at Helena Modern Riviera",
    short_title: "Sirens of Helena",
    slug: "sirens-of-helena-icon-park-orlando-2026",
    start_date: "2026-09-05",
    end_date: null,
    schedule_note: "Begins September 5, per the venue's own announcement. The venue's site confirms the pop-up but does not publish a closing date.",
    venue: "Helena Modern Riviera",
    address: "8441 International Dr #260",
    city: "Orlando",
    county: "Orange",
    lat: 28.4428765,
    lng: -81.4692785,
    place_id: "ChIJP1om-VJ-54gRAF-_k_y5cig",
    subcategory: "themed-restaurant",
    tags: ["fall", "halloween", "date-night", "nightlife", "themed-bar"],
    audience: ["adults", "couples"],
    official_event_url: "https://helenamodernriviera.com/",
    source_url: "https://www.instagram.com/reel/DcoNdFxBQEx/",
    card_hook: "A sea change at ICON Park: sirens, smoke, and a diver-helmet cocktail.",
    editorial_summary: "Helena Modern Riviera turns its ICON Park dining room into an underwater escape with themed cocktails and dishes.",
    why_go: "Choose this when your night out needs a plot twist and a smoke machine.",
    fun_fact: "Helena Modern Riviera sits inside ICON Park on International Drive, home of The Wheel and several themed nightly experiences.",
    wayfind_verdict: "ICON Park just got haunted by mermaids.",
  },
]);

export const FALL_DISCOVERY_RAIL = Object.freeze({
  "haunted-mangoni-2026": "date-night",
  "rosallie-lattes-leaves-2026": "food",
  "nueva-cantina-halloween-tampa-2026": "date-night",
  "you-do-the-dishes-fall-2026": "date-night",
  "perfect-press-fall-coffee-2026": "food",
  "showcase-citrus-pumpkin-ponderosa-2026": "farms",
  "amber-brooke-fall-festival-2026": "farms",
  "green-meadows-fall-2026": "farms",
  "great-scott-fall-fest-2026": "farms",
  "southern-hill-farms-fall-festival-2026": "farms",
  "hastings-ranch-farm-festival-2026": "farms",
  "dead-coconut-club-harvest-citywalk-2026": "date-night",
  "haraz-house-pumpkin-spice-wesley-chapel-2026": "food",
  "all-fired-up-halloween-pottery-winter-park-2026": "date-night",
  "all-fired-up-halloween-pottery-waterford-lakes-2026": "date-night",
  "sirens-of-helena-icon-park-2026": "date-night",
});

// These discoveries describe a seasonal product at a permanent business,
// not a dated event. They still carry start/end evidence because the offering
// is seasonal, but the card must open the Google place, show the venue's own
// photo and use place actions. Keeping this distinction outside the wf_events
// storage shape lets older seeded rows render correctly without a production
// data rewrite.
export const FALL_SEASONAL_PLACE_IDS = Object.freeze(new Set(
  FALL_DISCOVERIES_2026
    .filter((row) => row && row.source_type === "owner-received-discovery")
    .map((row) => row.event_id),
));
