// 2026-10-08 fall food gap fill (owner brief: "Start with Naples, which still
// has zero fall food cards, then Venice and the thin collections in Port
// Charlotte and Fort Myers").
//
// Every row is a dated 2026 post or page FROM THE BUSINESS ITSELF (or, for
// Black Letter, from the Venetian Village shopping center that houses it),
// read live in a real browser on 2026-10-08. Each names the actual seasonal
// item; "sells coffee" never qualified a row. Venue identity is the exact
// Google place id resolved through Wayfind's own place search (name, address
// and coordinates agree), so the card shows a real photo of that business via
// /api/photo under the existing monthly photo cap. A price is printed only
// when the business's own ordering page lists it (Bean Trolley); every other
// row leaves price empty rather than guess.
//
// Rows with no published end date carry an open-run note, so they show
// "Closing TBA" and age out after EVENT_OPEN_RUN_DAYS instead of lingering.
// Kept in its own module so the counted 33-row owner discovery registry stays
// exactly as reviewed. Each is pinned to the food shelf in FALL_DISCOVERY_RAIL.

const OPEN_RUN = "End date not published by the business.";

const FALL_FOOD = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  select_nights: false,
  category: "seasonal",
  subcategory: "seasonal-cafe",
  state: "FL",
  source_type: "official-social",
  source_tier: 2,
  verification_confidence: "high",
  last_verified_at: "2026-10-08T00:00:00+00:00",
  editorial_score: 7,
  uniqueness_score: 6,
  popularity_score: 6,
  tags: ["fall", "food", "seasonal-drinks"],
  audience: ["adults", "couples", "families"],
  is_free: false,
  price_band: null,
  price_min: null,
  start_time: null,
  end_time: null,
};

export const FALL_FOOD_GAP_2026_10_08 = Object.freeze([
  // ---------------------------------------------------------------- Naples
  {
    ...FALL_FOOD,
    event_id: "bean-trolley-fall-drinks-naples-2026",
    event_series_id: "bean-trolley-fall-drinks-naples",
    event_name: "The Bean Trolley Cafe Fall Drink Menu",
    short_title: "Bean Trolley Fall Drinks",
    slug: "bean-trolley-fall-drinks-naples-2026",
    start_date: "2026-08-31",
    end_date: "2026-12-31",
    schedule_note: "Fall drink menu August 31 to December 31, 2026, per the cafe's own post.",
    venue: "The Bean Trolley Cafe",
    address: "11576 Tamiami Trail E, Naples, FL",
    city: "Naples",
    county: "Collier",
    lat: 26.07433,
    lng: -81.71687,
    place_id: "ChIJhfVX8uUULEkRiaUo_cC0kf8",
    official_event_url: "https://www.instagram.com/p/DcraWj8FBeu/",
    source_url: "https://www.instagram.com/p/DcraWj8FBeu/",
    price_min: 6.5,
    price_band: "$",
    menu_source_url: "https://www.toasttab.com/local/order/thebeantrolleycafe",
    verify_note: "2026-10-08: @thebeantrolleycafe Aug 30, 2026 post: 'Fall Drink Menu is here! Starting tomorrow, August 31st, through December 31st ... eight brand-new fall-inspired drinks'. The cafe's own Toast ordering page lists Fall in a Cup ($7.50), Golden Orchard ($8.00), Caramel Apple Matcha, Pumpkin Chai and Apple Chai (from $6.50), read live 2026-10-08.",
    card_hook: "Pumpkin Chai and Fall in a Cup, served through December 31.",
    editorial_summary: "The Bean Trolley's 2026 fall menu: Fall in a Cup with pumpkin cold foam, a Golden Orchard apple seltzer, Caramel Apple Matcha, Pumpkin Chai and Apple Chai, from $6.50.",
    why_go: "A fall drink menu that runs all the way to December 31.",
    insider_tip: "It is on the Tamiami Trail east of downtown, an easy stop on the way to Marco Island.",
  },
  {
    ...FALL_FOOD,
    event_id: "black-letter-fall-menu-naples-2026",
    event_series_id: "black-letter-fall-menu-naples",
    event_name: "Black Letter Coffee + Cafe Fall Menu",
    short_title: "Black Letter Fall Menu",
    slug: "black-letter-fall-menu-naples-2026",
    start_date: "2026-10-01",
    end_date: null,
    source_type: "official-venue",
    schedule_note: "Fall menu featured October 1, 2026. " + OPEN_RUN,
    venue: "Black Letter Coffee + Cafe, Venetian Village",
    address: "4350 Gulf Shore Blvd N #506, Naples, FL",
    city: "Naples",
    county: "Collier",
    lat: 26.19716,
    lng: -81.81143,
    place_id: "ChIJHwtZB8Af24gRC0AycQbO0YQ",
    official_event_url: "https://www.venetianvillage.com/fall-the-florida-way/",
    source_url: "https://www.venetianvillage.com/fall-the-florida-way/",
    verify_note: "2026-10-08: Venetian Village 'Fall the Florida Way' (Oct 1, 2026) and its Instagram post p/Dd9wqO3CZwv list Apple Pie Latte, Caramel Scotch Latte, Autumn Leaf Tea, Pumpkin Cider and Pumpkin Spice Latte at Black Letter; the Apple Pie Latte is 'Espresso with apple butter, cinnamon and caramel, finished with an apple Pop-Tart. Order it iced'.",
    card_hook: "Apple Pie Latte with a Pop-Tart on top, by the water.",
    editorial_summary: "Black Letter's fall menu at Venetian Village: Apple Pie Latte, Caramel Scotch Latte, Autumn Leaf Tea, Pumpkin Cider and a Pumpkin Spice Latte.",
    why_go: "The most playful fall coffee in Naples, steps from the Venetian Bay boardwalk.",
    insider_tip: "The Apple Pie Latte can be ordered iced.",
  },
  {
    ...FALL_FOOD,
    event_id: "perry-coffee-shop-fall-naples-2026",
    event_series_id: "perry-coffee-shop-fall-naples",
    event_name: "Perry Coffee Shop Fall Drinks",
    short_title: "Perry Coffee Shop Fall",
    slug: "perry-coffee-shop-fall-naples-2026",
    start_date: "2026-10-08",
    end_date: null,
    schedule_note: "Fall drinks announced October 8, 2026; the coffee shop is open daily 7 to 11am and welcomes locals. " + OPEN_RUN,
    venue: "Perry Coffee Shop, The Perry Hotel Naples",
    address: "12155 Tamiami Trail N, Naples, FL",
    city: "Naples",
    county: "Collier",
    lat: 26.28106,
    lng: -81.80274,
    place_id: "ChIJEVbdY68Z24gRFTJkr-rdchQ",
    official_event_url: "https://www.instagram.com/p/DeOvVeYE-9Z/",
    source_url: "https://www.instagram.com/p/DeOvVeYE-9Z/",
    verify_note: "2026-10-08: @perryhotelnaples Oct 8, 2026: 'Fall flavors have officially arrived at The Perry Coffee Shop, and yes we're open to locals' — Pumpkin Spice Latte, Toasted Pecan Latte, Pomegranate Refresher; 'Open daily | 7 AM – 11 AM. Locals welcome!'",
    card_hook: "Toasted Pecan Latte and a Pomegranate Refresher, open to locals.",
    editorial_summary: "The Perry Hotel's coffee shop added fall drinks: Pumpkin Spice Latte, Toasted Pecan Latte and a Pomegranate Refresher.",
    why_go: "A quiet North Naples morning stop that is not another strip-mall chain.",
    insider_tip: "Mornings only: the coffee shop is open 7 to 11am.",
  },
  // ---------------------------------------------------------------- Venice
  {
    ...FALL_FOOD,
    event_id: "venice-avenue-creamery-fall-flavors-2026",
    event_series_id: "venice-avenue-creamery-fall-flavors",
    event_name: "Venice Avenue Creamery Fall Flavors",
    short_title: "Venice Creamery Fall Flavors",
    slug: "venice-avenue-creamery-fall-flavors-2026",
    start_date: "2026-09-16",
    end_date: null,
    schedule_note: "Pumpkin chai latte posted September 16; pumpkin and caramel apple cheesecake ice cream added to the rotation October 2, 2026. Flavors rotate. " + OPEN_RUN,
    venue: "Venice Avenue Creamery",
    address: "Venice Ave, Venice, FL",
    city: "Venice",
    county: "Sarasota",
    lat: 27.0997,
    lng: -82.44741,
    place_id: "ChIJVfAZTbtbw4gRnZMlnR6ZWkI",
    tags: ["fall", "food", "seasonal-drinks", "dessert"],
    official_event_url: "https://www.instagram.com/p/DeAVGTaoNiv/",
    source_url: "https://www.instagram.com/p/DeAVGTaoNiv/",
    verify_note: "2026-10-08: @veniceavenuecreamery Oct 2, 2026 'favorite flavors have made their way into the rotation' (#Caramelapplecheesecake #pumpkin); Oct 2 reel 'Halloween Edition Cookies & Cream' (homemade); Sep 16 'Iced Pumpkin Chai Latte'.",
    card_hook: "Homemade pumpkin and caramel apple cheesecake ice cream.",
    editorial_summary: "Venice Avenue Creamery's fall rotation: homemade pumpkin and caramel apple cheesecake ice cream, a Halloween cookies and cream, and an iced pumpkin chai latte.",
    why_go: "Fall you can eat with a spoon, on Venice's main street.",
    insider_tip: "Flavors rotate, so the case can change day to day.",
  },
  {
    ...FALL_FOOD,
    event_id: "seed-and-bean-venice-fall-menu-2026",
    event_series_id: "seed-and-bean-venice-fall-menu",
    event_name: "Seed & Bean Venice Fall Menu",
    short_title: "Seed & Bean Fall Menu",
    slug: "seed-and-bean-venice-fall-menu-2026",
    start_date: "2026-09-02",
    end_date: "2026-10-31",
    schedule_note: "September and October drink lineup; Pumpkin Maple Pancakes available throughout October 2026.",
    venue: "Seed & Bean Venice",
    address: "116 W Venice Ave, Venice, FL",
    city: "Venice",
    county: "Sarasota",
    lat: 27.10012,
    lng: -82.44478,
    place_id: "ChIJV12TgcJbw4gR710nwEnWcTs",
    official_event_url: "https://www.instagram.com/p/Dd9U4MQkbW-/",
    source_url: "https://www.instagram.com/p/Dd9U4MQkbW-/",
    verify_note: "2026-10-08: @seedandbeanmktvenice Sep 2, 2026 (p/Dcy_8qYnxTO) 'September + October drink lineup': Pumpkin Spice Latte, Maple Pecan Chai, Banana Bread Chagaccino, Apple Cider Mimosa Mocktail; Oct 1, 2026 (p/Dd9U4MQkbW-) Pumpkin Maple Pancakes 'available throughout October'.",
    card_hook: "Pumpkin Maple Pancakes and a Maple Pecan Chai, all October.",
    editorial_summary: "Seed & Bean's fall lineup on Venice Avenue: Pumpkin Maple Pancakes plus a Pumpkin Spice Latte, Maple Pecan Chai and an Apple Cider Mimosa Mocktail.",
    why_go: "The one Venice spot with a real fall breakfast, not just a latte.",
    insider_tip: "The pancakes are on the October menu only.",
  },
  // ---------------------------------------------------------- Port Charlotte
  {
    ...FALL_FOOD,
    event_id: "hallowbean-halloween-treats-port-charlotte-2026",
    event_series_id: "hallowbean-halloween-treats-port-charlotte",
    event_name: "HallowBean Coffee Co Halloween Treats",
    short_title: "HallowBean Halloween Treats",
    slug: "hallowbean-halloween-treats-port-charlotte-2026",
    start_date: "2026-10-05",
    end_date: null,
    schedule_note: "Seasonal treat restock posted October 5, 2026. " + OPEN_RUN,
    venue: "HallowBean Coffee Co",
    address: "1900 Tamiami Trail #114, Port Charlotte, FL",
    city: "Port Charlotte",
    county: "Charlotte",
    lat: 27.00659,
    lng: -82.13057,
    place_id: "ChIJkb4uPACr3IgR6cG5vYPJRmk",
    tags: ["fall", "food", "seasonal-drinks", "halloween"],
    official_event_url: "https://www.instagram.com/p/DeH6ntyljP0/",
    source_url: "https://www.instagram.com/p/DeH6ntyljP0/",
    verify_note: "2026-10-08: @hallowbeancoffee Oct 5, 2026: dirt cake latte, classic pumpkin cheesecake, new Oreo cookie pops and cauldron cakes.",
    card_hook: "Dirt cake latte and pumpkin cheesecake in a Halloween coffee shop.",
    editorial_summary: "HallowBean is a Halloween-themed coffee shop; this month it pours a dirt cake latte and sells pumpkin cheesecake and cauldron cakes.",
    why_go: "The spookiest coffee stop in Charlotte County, made for October.",
    insider_tip: "The treat case changes; the cafe posts each restock on Instagram.",
  },
  {
    ...FALL_FOOD,
    event_id: "brix-coffee-pumpkin-menu-port-charlotte-2026",
    event_series_id: "brix-coffee-pumpkin-menu-port-charlotte",
    event_name: "Brix Coffee Pumpkin Season",
    short_title: "Brix Pumpkin Season",
    slug: "brix-coffee-pumpkin-menu-port-charlotte-2026",
    start_date: "2026-08-26",
    end_date: null,
    verification_confidence: "medium",
    schedule_note: "Pumpkin drinks back August 26 and limited-time fall pastries from September 5, 2026. Posts are brand-wide across Brix's Sarasota-area shops. " + OPEN_RUN,
    venue: "Brix Coffee",
    address: "844 Tamiami Trail, Port Charlotte, FL",
    city: "Port Charlotte",
    county: "Charlotte",
    lat: 27.01866,
    lng: -82.16503,
    place_id: "ChIJe46Ywqar3IgRZorq_9M44XM",
    official_event_url: "https://www.instagram.com/p/Dc55pkyxzoE/",
    source_url: "https://www.instagram.com/p/Dc55pkyxzoE/",
    verify_note: "2026-10-08: @brixcoffeefl Aug 26, 2026 (p/Dcgoayomj--) 'Pumpkin season is officially back': Pumpkin Chai, Pumpkin White Chocolate, Pumpkin Banana; Sep 5, 2026 (p/Dc55pkyxzoE) limited-time Pumpkin Cream Cheese Muffin, Pumpkin Loaf Cake, Apple Cinnamon Muffin. Brand posts are tagged #portcharlottefl; per-store participation not stated, so confidence is medium.",
    card_hook: "Pumpkin Chai and a pumpkin cream cheese muffin.",
    editorial_summary: "Brix's pumpkin season: Pumpkin Chai, Pumpkin White Chocolate and Pumpkin Banana drinks, plus limited-time pumpkin muffins and loaf cake.",
    why_go: "A reliable fall drink and pastry on the Tamiami Trail.",
    insider_tip: "Fall pastries are limited-time, so ask what is in the case.",
  },
  {
    ...FALL_FOOD,
    event_id: "goombah-coffee-dessert-lattes-port-charlotte-2026",
    event_series_id: "goombah-coffee-dessert-lattes-port-charlotte",
    event_name: "Goombah Coffee Fall Dessert Lattes",
    short_title: "Goombah Dessert Lattes",
    slug: "goombah-coffee-dessert-lattes-port-charlotte-2026",
    start_date: "2026-10-02",
    end_date: null,
    schedule_note: "Lattes launched with the SunCoast Coffee Crawl on October 2, 2026. " + OPEN_RUN,
    venue: "Goombah Coffee",
    address: "23188 Freedom Ave, Port Charlotte, FL",
    city: "Port Charlotte",
    county: "Charlotte",
    lat: 26.95993,
    lng: -82.06792,
    place_id: "ChIJ1_w1YdCp3IgR2oG33UnAUls",
    official_event_url: "https://www.instagram.com/p/Dd3wXOVsk28/",
    source_url: "https://www.instagram.com/p/Dd3wXOVsk28/",
    verify_note: "2026-10-08: @goombahcoffee Sep 29, 2026: 'The SunCoast Coffee Crawl starts FRIDAY, and we're bringing dessert in a cup': Pumpkin Pie, Apple Pie à la Mode, Banana Bread, made with housemade syrups. 'Passports go on sale October 2 for $25 ... 13 participating stops'.",
    card_hook: "Pumpkin Pie and Apple Pie à la Mode lattes with house syrups.",
    editorial_summary: "Goombah's fall lattes taste like dessert: Pumpkin Pie, Apple Pie à la Mode and Banana Bread, all with housemade syrups.",
    why_go: "The most dessert-like fall coffee in Port Charlotte.",
    insider_tip: "It is a stop on the 2026 SunCoast Coffee Crawl passport.",
  },
  // ------------------------------------------------------------- Fort Myers
  {
    ...FALL_FOOD,
    event_id: "banyan-cafe-pumpkin-edison-ford-2026",
    event_series_id: "banyan-cafe-pumpkin-edison-ford",
    event_name: "Banyan Cafe Pumpkin Menu at Edison & Ford",
    short_title: "Banyan Cafe Pumpkin",
    slug: "banyan-cafe-pumpkin-edison-ford-2026",
    start_date: "2026-10-01",
    end_date: null,
    schedule_note: "Reopened October 1, 2026 with pumpkin bread and an iced pumpkin latte; open until 3pm. " + OPEN_RUN,
    venue: "Banyan Cafe, Edison & Ford Winter Estates",
    address: "2350 McGregor Blvd, Fort Myers, FL",
    city: "Fort Myers",
    county: "Lee",
    lat: 26.63372,
    lng: -81.87889,
    place_id: "ChIJi2GwaNJB24gRiEGMCSX-vMQ",
    official_event_url: "https://www.instagram.com/p/Dd9A_dYxg03/",
    source_url: "https://www.instagram.com/p/Dd9A_dYxg03/",
    verify_note: "2026-10-08: @banyancafefortmyers Oct 1, 2026: 'We're back! Pumpkin two ways: pumpkin bread & an iced pumpkin latte topped with whipped cream and pumpkin purée. Here until 3pm'. Edison & Ford confirmed the reopening the same day (p/Dd9Eur0DtQj).",
    card_hook: "Pumpkin bread and an iced pumpkin latte under the banyan.",
    editorial_summary: "Banyan Cafe at Edison & Ford Winter Estates reopened with pumpkin two ways: pumpkin bread and an iced pumpkin latte with whipped cream and pumpkin purée.",
    why_go: "Fall coffee in one of Fort Myers' prettiest historic settings.",
    insider_tip: "The cafe closes at 3pm.",
  },
  {
    ...FALL_FOOD,
    event_id: "savour-coffee-october-specials-fort-myers-2026",
    event_series_id: "savour-coffee-october-specials-fort-myers",
    event_name: "Savour Coffee October Specials",
    short_title: "Savour October Specials",
    slug: "savour-coffee-october-specials-fort-myers-2026",
    start_date: "2026-10-04",
    end_date: "2026-10-31",
    schedule_note: "October 2026 monthly specials.",
    venue: "Savour Coffee",
    address: "16520 S Tamiami Trail #138, Fort Myers, FL",
    city: "Fort Myers",
    county: "Lee",
    lat: 26.50064,
    lng: -81.85694,
    place_id: "ChIJRwbz1ncV24gRgcdv4nmcg4E",
    official_event_url: "https://www.instagram.com/reel/DeE011WR7Va/",
    source_url: "https://www.instagram.com/reel/DeE011WR7Va/",
    verify_note: "2026-10-08: @savourcoffeeswfl Oct 4, 2026 'Special October Drink': Frankinlotus and Pumpkin Peanut Buttercup; Oct 6, 2026 (p/DeKYnW_EZfn) monthly specials plus 'Extra Basic' (pumpkin spice latte).",
    card_hook: "October-only Pumpkin Peanut Buttercup and a Frankinlotus.",
    editorial_summary: "Savour's October specials: a Pumpkin Peanut Buttercup, a Halloween-named Frankinlotus, and the Extra Basic, its pumpkin spice latte.",
    why_go: "The most inventive monthly specials in south Fort Myers.",
    insider_tip: "Specials change monthly, so these end with October.",
  },
]);

export const FALL_FOOD_GAP_2026_10_08_IDS = Object.freeze(FALL_FOOD_GAP_2026_10_08.map((row) => row.event_id));
