// Owner-requested Fall in Florida festivals, reviewed September 25, 2026.
// Explicit dates are attendance days, not the continuous season envelope.
// No invented quality scores: existing database scores survive the source merge.
const BASE = {
  year: 2026, timezone: "America/New_York", state: "FL",
  event_status: "scheduled", category: "festival", subcategory: "farm-festival",
  select_nights: true, source_type: "official-organizer", source_tier: 1,
  verification_confidence: "high", last_verified_at: "2026-09-25T00:00:00Z",
  audience: ["families", "kids"], tags: ["fall", "festival", "pumpkins", "farm", "harvest"],
  is_free: false, price_band: "$", image_is_venue: true,
  // These cards promise organizer information, not verified ticket availability.
  official_ticket_url: null,
};
const OCT_WEEKENDS = [3, 4, 10, 11, 17, 18, 24, 25, 31].map((day) => `2026-10-${String(day).padStart(2, "0")}`);
const THREE_WEEKENDS = [10, 11, 17, 18, 24, 25].map((day) => `2026-10-${day}`);
export const FALL_FEATURED_FESTIVALS_2026 = Object.freeze([
  {
    ...BASE, event_id: "fruitville-grove-pumpkin-2026", event_series_id: "fruitville-grove-pumpkin",
    event_name: "Fruitville Grove Pumpkin Festival", short_title: "Fruitville Grove Pumpkin Festival",
    slug: "fruitville-grove-pumpkin-festival-2026", venue: "Fruitville Grove", city: "Sarasota", county: "Sarasota",
    address: "7410 Fruitville Rd, Sarasota, FL 34240", lat: 27.3378046, lng: -82.4230065,
    place_id: "ChIJhWqZvoVHw4gRehUSFsbZARo",
    start_date: "2026-10-03", end_date: "2026-11-01", start_time: "10:00:00", end_time: "17:00:00",
    occurrence_dates: [...OCT_WEEKENDS, "2026-11-01"],
    schedule_note: "Saturdays and Sundays, October 3–November 1, 10am–5pm. Admission $5; ages 6 and under free. Free parking; some activities cost extra.",
    price_min: 5, official_event_url: "https://fruitvillegrovefarm.com/festival/", source_url: "https://fruitvillegrovefarm.com/festival/",
    verify_note: "2026 organizer page confirms all ten dates, hours and $5 admission/free parking. Address corroborated by Florida Agritourism Association and Florida Farm Bureau; owned venue anchor retained.",
    card_hook: "Pumpkins, hayrides and a full weekend of farm fun.",
    editorial_summary: "A Sarasota pumpkin festival with hayrides, animals, live music, craft vendors and fall photo opportunities. Some attractions cost extra.",
    hero_image: "/api/photo?place=ChIJhWqZvoVHw4gRehUSFsbZARo&g=2&w=800",
    image_alt: "Fruitville Grove; venue photo",
  },
  {
    ...BASE, event_id: "dakin-harvest-festival-2026", event_series_id: "dakin-harvest-festival",
    event_name: "Dakin Dairy Farms Fall Harvest Festival", short_title: "Dakin Dairy Harvest Festival",
    slug: "dakin-dairy-harvest-festival-2026", venue: "Dakin Dairy Farms", city: "Myakka City", county: "Manatee",
    address: "30771 Betts Rd, Myakka City, FL 34251", lat: 27.3625249, lng: -82.2295465,
    place_id: "ChIJB_GKfW81w4gRsCQHi5hjasA",
    start_date: "2026-10-10", end_date: "2026-10-25", start_time: "10:00:00", end_time: "17:00:00", occurrence_dates: [...THREE_WEEKENDS],
    schedule_note: "October 10–11, 17–18 and 24–25, 10am–5pm. Admission $20; ages 5 and under free. Free parking. Selected attractions cost extra.",
    price_min: 20, official_event_url: "https://dakindairyfarms.com/events/", source_url: "https://dakindairyfarms.com/events/",
    verify_note: "Organizer Event Details enumerates all six dates; use those rather than generic every-weekend prose.",
    card_hook: "Harvest weekends on a working dairy farm.",
    editorial_summary: "Hayrides, farm animals, a corn maze and fall activities in Myakka City. Check the organizer for pumpkin and calf-cuddling add-ons.",
    hero_image: "/api/photo?place=ChIJB_GKfW81w4gRsCQHi5hjasA&g=2&w=640", image_alt: "Dakin Dairy Farms; venue photo",
  },
  {
    ...BASE, event_id: "hunsader-pumpkin-2026", event_series_id: "hunsader-pumpkin",
    event_name: "Hunsader Farms Pumpkin Festival", short_title: "Hunsader Farms Pumpkin Festival",
    slug: "hunsader-farms-pumpkin-festival-2026", venue: "Hunsader Farms", city: "Bradenton", county: "Manatee",
    address: "5500 County Road 675, Bradenton, FL 34211", lat: 27.4448076, lng: -82.3046144,
    place_id: "ChIJuSnFvF8xw4gRt0WOWL_cqRc",
    start_date: "2026-10-10", end_date: "2026-10-25", start_time: "09:00:00", end_time: "17:00:00", occurrence_dates: [...THREE_WEEKENDS],
    schedule_note: "October 10–11, 17–18 and 24–25, 9am–5pm. Ages 10+ $15; ages 5–9 $5; under 5 free. Parking $5. Cash only.",
    price_min: 15, official_event_url: "https://www.hunsaderfarms.com/pumpkin-festival", source_url: "https://www.hunsaderfarms.com/pumpkin-festival",
    verify_note: "Organizer confirms 2026 dates/hours; admission and cash-only terms on https://www.hunsaderfarms.com/copy-of-pumpkin-festival. Photo shows venue goats, not the 2026 festival.",
    card_hook: "Three pumpkin-filled weekends at Hunsader Farms.",
    editorial_summary: "Pumpkins, hayrides, craft vendors, live music and farm animals across three October weekends.",
    hero_image: "/guides/verified/hunsader-farms-goats.webp", image_alt: "Resting goats at Hunsader Farms; venue photo",
    photoAttr: "Robin Teng · Unsplash", photoAttrHref: "https://unsplash.com/photos/i_sBNY7UoNQ",
  },
  {
    ...BASE, event_id: "keel-farms-harvest-days-2026", event_series_id: "keel-farms-harvest-days",
    event_name: "Keel Farms Harvest Days", short_title: "Keel Farms Harvest Days",
    slug: "keel-farms-harvest-days-2026", venue: "Keel Farms", city: "Plant City", county: "Hillsborough",
    address: "5202 Thonotosassa Rd, Plant City, FL 33565", lat: 28.0666, lng: -82.1467, place_id: "ChIJ_5yVrBY13YgRwSgyH1hrRjg",
    start_date: "2026-10-03", end_date: "2026-10-31", start_time: "10:00:00", end_time: "15:00:00", occurrence_dates: [...OCT_WEEKENDS],
    is_free: true, price_band: "free", price_min: 0,
    schedule_note: "Every Saturday and Sunday in October, including Saturday October 31, 10am–3pm. Free admission; $10 parking. No tickets required.",
    official_event_url: "https://www.keelfarms.com/festivals", source_url: "https://www.keelfarms.com/festivals",
    verify_note: "Organizer lists every Saturday and Sunday in October, 10am–3pm, free admission and $10 parking.",
    hero_image: "/api/photo?place=ChIJ_5yVrBY13YgRwSgyH1hrRjg&g=2&w=800", image_alt: "Keel Farms; venue photo",
    card_hook: "Corn maze, fall fun and a farm afternoon in Plant City.",
    editorial_summary: "Keel Farms Harvest Days brings a corn maze, seasonal entertainment and fall activities. Admission is free; parking is $10.",
  },
  {
    ...BASE, event_id: "frrm-pumpkin-patch-express-2026", event_series_id: "frrm-pumpkin-patch-express",
    event_name: "Florida Railroad Museum Pumpkin Patch Express", short_title: "Pumpkin Patch Express",
    slug: "parrish-pumpkin-patch-express-2026", venue: "Florida Railroad Museum", city: "Parrish", county: "Manatee",
    address: "12210 83rd St E, Parrish, FL 34219", lat: 27.59013, lng: -82.42348, place_id: "ChIJ______8sw4gRMudh58gsGMU",
    start_date: "2026-10-17", end_date: "2026-10-25", start_time: null, end_time: null,
    occurrence_dates: ["2026-10-17", "2026-10-18", "2026-10-24", "2026-10-25"],
    source_type: "organizer-with-corroboration", source_tier: 2, verification_confidence: "medium", price_band: null,
    schedule_note: "October 17–18 and 24–25; about 2.5 hours. Check the museum for available departures and tickets.",
    official_event_url: "https://www.frrm.org/pumpkin-patch-express/", source_url: "https://fun4tampakids.com/Whats-Happening/Fall-Festivals/",
    verify_note: "Organizer confirms named experience. 2026 dates/departures corroborated by Fun4TampaKids and Tampa Bay Parenting https://tampabayparenting.com/halloween-in-tampa-bay-1555/. Operator booking calendar did not expose availability; do not imply tickets verified.",
    card_hook: "Ride the train to your pumpkin-patch adventure.",
    editorial_summary: "A roughly 2.5-hour museum outing with a train ride, pumpkin patch, hayride, crafts and games. Check the museum for departures and availability.",
    hero_image: "/guides/verified/nature-parrish-railroad-museum.webp", image_alt: "Florida Railroad Museum railcar ticket office; venue photo",
    photoAttr: "Ebyabe · CC BY-SA 3.0", photoAttrHref: "https://commons.wikimedia.org/wiki/File:Parrish_FL_Florida_Railroad_Museum01.jpg",
  },
]);
export const FALL_FEATURED_FESTIVAL_IDS = new Set(FALL_FEATURED_FESTIVALS_2026.map((row) => row.event_id));
