// 2026-10-08 Tampa fall/Halloween pass (owner: "make sure to include these
// places into Wayfind, especially in the fall poster ... somewhere that is
// easy to be seen", followed by 24 Tampa names).
//
// Measured on production that morning (/api/events/fall at downtown Tampa):
// most of the 24 were already live on the Fall collection. This module adds
// the two verified offerings that were missing and corrects one live card:
//   - Guppyween at The Florida Aquarium (new family card)
//   - the free Armature Works pumpkin patch (new farm card; the Fall Fest row
//     stays held because the organizer's own page gives two different weekends)
//   - the Crawl With US Tampa Halloween crawl now names all five bars the
//     organizer publishes (MacDinton's, Grove, Bulla, LALA, Tiny Tap)
//   - Armature Works Fall Fest: both weekends (Oct 10-11 and 24-25), from the
//     organizer's live Eventbrite series, with its exact venue identity
// Every fact below was read on the organizer's own page on 2026-10-08. Venue
// identity is the exact wf_inventory row with an owned photo: no paid lookup.
// Each row's one primary rail is pinned in FALL_DISCOVERY_RAIL.

const TAMPA = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  city: "Tampa",
  county: "Hillsborough",
  state: "FL",
  source_type: "official-organizer",
  source_tier: 1,
  verification_confidence: "high",
  last_verified_at: "2026-10-08T00:00:00+00:00",
};

// Every Thursday through Sunday from today through the patch's last day.
const ARMATURE_PATCH_DATES = [
  "2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11",
  "2026-10-15", "2026-10-16", "2026-10-17", "2026-10-18",
  "2026-10-22", "2026-10-23", "2026-10-24", "2026-10-25",
  "2026-10-29", "2026-10-30", "2026-10-31", "2026-11-01",
];

export const FALL_TAMPA_PICKS_2026_10_08 = Object.freeze([
  {
    ...TAMPA,
    event_id: "florida-aquarium-guppyween-2026",
    event_series_id: "florida-aquarium-guppyween",
    event_name: "Guppyween at The Florida Aquarium",
    short_title: "Guppyween",
    slug: "florida-aquarium-guppyween-2026",
    start_date: "2026-10-24",
    end_date: "2026-10-31",
    start_time: "09:00:00",
    end_time: "17:00:00",
    select_nights: false,
    schedule_note: "October 24–31, 2026, 9 am–5 pm. Children in costume get free admission with a paid parent or guardian; the offer is redeemed at the Aquarium ticket window only.",
    venue: "The Florida Aquarium",
    address: "701 Channelside Dr, Tampa, FL 33602",
    lat: 27.944,
    lng: -82.4449,
    place_id: "ChIJCXAq5_DEwogRjTPE2xlsZtE",
    category: "halloween",
    subcategory: "family-halloween",
    tags: ["halloween", "fall", "family", "kids", "costume"],
    audience: ["families", "kids"],
    is_free: false,
    official_event_url: "https://www.flaquarium.org/news-events/attend-an-event/calendar/guppyween/",
    source_url: "https://www.flaquarium.org/news-events/attend-an-event/calendar/guppyween/",
    verify_note: "2026-10-08: flaquarium.org Guppyween page reads 'October 24–31, 2026 | 9:00 AM - 5:00 PM' and the costumed-child free admission offer (ticket window only).",
    card_hook: "Eight days of costume-friendly Halloween fun at the aquarium, built for little kids.",
    editorial_summary: "The Florida Aquarium's family Halloween event for little monsters, merfolk, pirates and princesses.",
    why_go: "A Halloween outing small kids enjoy without real scares, with the whole aquarium to explore.",
    duration_recommendation: "2-3 hours",
    editorial_score: 7,
    uniqueness_score: 6,
    popularity_score: 7,
  },
  {
    ...TAMPA,
    event_id: "armature-works-pumpkin-patch-2026",
    event_series_id: "armature-works-pumpkin-patch",
    event_name: "Free Pumpkin Patch at Armature Works",
    short_title: "Armature Works Pumpkin Patch",
    slug: "armature-works-pumpkin-patch-2026",
    start_date: "2026-10-01",
    end_date: "2026-11-01",
    select_nights: true,
    occurrence_dates: ARMATURE_PATCH_DATES,
    schedule_note: "Thursdays through Sundays through November 1. Thursday 4–9 pm, Friday 3–10 pm, Saturday 10 am–10 pm, Sunday 10 am–7 pm; Halloween, Saturday October 31, 10 am–6 pm. Free, no ticket needed; pumpkins sold onsite.",
    venue: "Armature Works",
    address: "1910 N Ola Ave, Tampa, FL 33602",
    lat: 27.9609,
    lng: -82.4643,
    place_id: "ChIJYWj9iZ_PwogRQebjN7pJ_Nw",
    category: "seasonal",
    subcategory: "pumpkin-patch",
    tags: ["fall", "family", "pumpkins", "pumpkin-patch"],
    audience: ["families", "kids", "couples"],
    is_free: true,
    price_band: "free",
    price_min: 0,
    official_event_url: "https://www.armatureworks.com/pumpkin-patch-tampa/",
    source_url: "https://www.armatureworks.com/pumpkin-patch-tampa/",
    verify_note: "2026-10-08: armatureworks.com/pumpkin-patch-tampa lists 'Patch Hours' per weekday, 'Halloween, Sat Oct 31: 10am - 6pm', free with no ticket, final day Sunday November 1.",
    card_hook: "Pick a pumpkin by the river, then stay for dinner in the food hall.",
    editorial_summary: "A free riverside pumpkin patch in Tampa Heights, with the Armature Works food hall and bars steps away.",
    why_go: "A pumpkin patch you can pair with dinner and drinks without moving the car.",
    duration_recommendation: "Under an hour",
    editorial_score: 7,
    uniqueness_score: 6,
    popularity_score: 7,
  },
  {
    ...TAMPA,
    // Same event_id as the live wf_events row (seeded Oct 10-11 only, no venue
    // identity, so it never rendered). The organizer's website contradicts
    // itself (headline Oct 24-25, body Oct 10-11); its Eventbrite series lists
    // four live sessions, so both weekends are real.
    event_id: "armature-works-9th-annual-fall-fest-2026",
    event_series_id: "armature-works-fall-fest",
    event_name: "Armature Works 9th Annual Fall Fest",
    short_title: "Armature Works Fall Fest",
    slug: "armature-works-9th-annual-fall-fest-2026",
    start_date: "2026-10-10",
    end_date: "2026-10-25",
    start_time: "12:00:00",
    select_nights: true,
    occurrence_dates: ["2026-10-10", "2026-10-11", "2026-10-24", "2026-10-25"],
    schedule_note: "Two weekends: Saturday October 10, noon–5 pm; Sunday October 11, noon–4 pm; Saturday October 24, noon–5 pm; Sunday October 25, noon–4 pm. Free to attend; the bounce zone pass, animal rides and face painting cost extra.",
    venue: "Armature Works West Lawn and Market Street",
    address: "1910 N Ola Ave, Tampa, FL 33602",
    lat: 27.9609,
    lng: -82.4643,
    place_id: "ChIJYWj9iZ_PwogRQebjN7pJ_Nw",
    category: "festival",
    subcategory: "fall-festival",
    tags: ["fall", "festival", "family", "pumpkins"],
    audience: ["families", "kids", "couples"],
    is_free: true,
    price_band: "free",
    official_event_url: "https://www.armatureworks.com/fall-festival/",
    official_ticket_url: null,
    source_url: "https://www.eventbrite.com/e/the-heights-districts-9th-annual-fall-fest-tickets-2000417237808",
    verify_note: "2026-10-08: Eventbrite series 2000417237808 (organizer Armature Works) lists four live sessions: 2026-10-10 12:00-17:00, 2026-10-11 12:00-16:00, 2026-10-24 12:00-17:00, 2026-10-25 12:00-16:00. armatureworks.com/fall-festival says free to attend with a $20 per-day bounce zone pass and separately priced animal rides and face painting; its headline (Oct 24-25) and body (Oct 10-11) each show one weekend.",
    card_hook: "A free riverside fall market with live music, a petting zoo and pony rides.",
    editorial_summary: "Armature Works' ninth Fall Fest fills the West Lawn and Market Street with local vendors, fall cocktails and kids' activities.",
    why_go: "A full fall afternoon with no admission, and the food hall is right there when the kids get hungry.",
    duration_recommendation: "2-3 hours",
    editorial_score: 7,
    uniqueness_score: 6,
    popularity_score: 7,
  },
  {
    ...TAMPA,
    event_id: "tampa-halloween-bar-crawl-2026",
    event_series_id: "tampa-halloween-bar-crawl-2026",
    event_name: "Tampa Halloween Bar Crawl 2026",
    short_title: "Tampa Halloween Bar Crawl",
    slug: "tampa-halloween-bar-crawl-2026",
    start_date: "2026-10-31",
    end_date: "2026-10-31",
    start_time: "16:00:00",
    end_time: "23:59:00",
    select_nights: false,
    schedule_note: "Saturday, October 31, 4 pm to 11:59 pm. Check in at MacDinton's SoHo 4–6 pm; crawl 4–10 pm across five SoHo bars: MacDinton's, Grove Soho (mid party 7–9 pm), Bulla Gastrobar, LALA Tampa and Tiny Tap Tavern; after party 10 pm to 11:59 pm. 21+ with valid ID.",
    venue: "MacDinton's SoHo (check-in venue)",
    address: "405 S Howard Ave, Tampa, FL 33606",
    lat: 27.9405322,
    lng: -82.4831814,
    place_id: "ChIJTSQO5GTDwogR5VNtdse_zBw",
    category: "halloween",
    subcategory: "bar-crawl",
    tags: ["fall", "halloween", "bar-crawl", "nightlife", "costume", "soho", "tampa"],
    audience: ["adults"],
    minimum_age: 21,
    is_free: false,
    official_ticket_url: "https://www.eventbrite.com/e/tampa-halloween-bar-crawl-2026-tickets-1583901996509",
    official_event_url: "https://www.crawlwith.us/tampa/halloween",
    hero_image: "/api/photo?place=ChIJTSQO5GTDwogR5VNtdse_zBw&g=2&w=800",
    image_alt: "MacDinton's Irish Pub in Tampa",
    source_url: "https://www.crawlwith.us/tampa/halloween",
    verify_note: "2026-10-08: crawlwith.us/tampa/halloween (organizer Crawl With US) lists Saturday, October 31, 2026, 4PM-10PM, check-in MacDinton's SoHo 4-6PM, mid party Grove Soho 7-9PM, and the lineup MacDinton's SoHo, Grove Soho, Bulla Gastrobar, LALA Tampa, Tiny Tap Tavern, with '2-3 drinks or shots', '5 bars, zero cover with your badge' and free event photographers; its Get Tickets button is Eventbrite 1583901996509, the same listing verified 2026-10-06 (4-11:59pm with after party, 21+).",
    card_hook: "Halloween night down Howard Ave, five SoHo bars on one badge.",
    editorial_summary: "Crawl With US runs Tampa's Halloween night crawl. There is no set route, so you hit the bars in any order.",
    why_go: "The ticket includes 2 to 3 drinks or shots, no cover at the bars and free event photos.",
    skip_if: "Skip it if you are under 21 or cannot make the 4–6 pm check-in.",
    duration_recommendation: "Evening into late night",
    crowd_level: "high",
    wayfind_verdict: "The SoHo pick for Halloween night out.",
    editorial_score: 7,
    uniqueness_score: 6,
    popularity_score: 7,
  },
]);
