import { FALL_FEATURED_FESTIVALS_2026 } from "./fallFeaturedFestivals2026";
import { FALL_DISCOVERIES_2026 } from "./fallDiscoveries2026";
import { GULF_COAST_FALL_2026_ROWS } from "./gulfCoastFall2026";

// Guide only additions fill statewide coverage gaps that are not yet in the
// canonical fall registries. Every dated row below was checked on 2026-09-25
// against an organizer, venue, destination organization, or an existing
// Wayfind event record. Keep these rows editorial only until the canonical
// event import owns them.
const GUIDE_ONLY_EVENTS_2026 = Object.freeze([
  {
    event_id: "halloween-horror-nights-orlando-2026",
    event_name: "Halloween Horror Nights 35",
    city: "Orlando",
    start_date: "2026-08-28",
    end_date: "2026-11-01",
    schedule_note: "48 select nights from August 28 through November 1. Universal says the event is not recommended for children under 13.",
    href: "/florida-events/halloween-horror-nights-orlando-2026",
    tags: ["halloween", "haunted", "nightlife"],
    audience: ["adults", "teens"],
    guide_kind: "haunts",
    region: "Central Florida and Orlando",
  },
  {
    event_id: "howl-o-scream-seaworld-orlando-2026",
    event_name: "Howl O Scream at SeaWorld Orlando",
    city: "Orlando",
    start_date: "2026-09-11",
    end_date: "2026-10-31",
    schedule_note: "Select nights September 11 through October 31. Separate event ticket. The event is designed for mature audiences.",
    official_event_url: "https://seaworld.com/orlando/events/howl-o-scream/",
    tags: ["halloween", "haunted", "nightlife"],
    audience: ["adults", "teens"],
    guide_kind: "haunts",
    region: "Central Florida and Orlando",
  },
  {
    event_id: "mickeys-not-so-scary-halloween-party-2026",
    event_name: "Mickey's Not So Scary Halloween Party",
    city: "Orlando",
    start_date: "2026-08-07",
    end_date: "2026-10-31",
    schedule_note: "Select nights August 7 through October 31 at Magic Kingdom. This is the family Halloween party with trick or treat trails, parade, stage show and fireworks.",
    official_event_url: "https://disneyworld.disney.go.com/events-tours/magic-kingdom/mickeys-not-so-scary-halloween-party/",
    tags: ["halloween", "family", "trick-or-treat"],
    audience: ["families", "kids"],
    guide_kind: "family",
    region: "Central Florida and Orlando",
  },
  {
    event_id: "epcot-food-wine-festival-2026",
    event_name: "EPCOT International Food and Wine Festival",
    city: "Orlando",
    start_date: "2026-08-27",
    end_date: "2026-11-21",
    schedule_note: "Daily August 27 through November 21. Festival access is included with EPCOT admission. Food and drinks are purchased separately.",
    official_event_url: "https://disneyworld.disney.go.com/events-tours/epcot/epcot-international-food-and-wine-festival/",
    tags: ["food", "festival", "wine"],
    audience: ["adults", "families"],
    guide_kind: "food",
    region: "Central Florida and Orlando",
  },
  {
    event_id: "legoland-florida-brick-or-treat-2026",
    event_name: "Brick or Treat at LEGOLAND Florida",
    city: "Winter Haven",
    start_date: "2026-09-05",
    end_date: "2026-10-31",
    schedule_note: "18 select days September 5 through October 31. Halloween activities are included with regular park admission.",
    official_event_url: "https://www.legoland.com/florida/things-to-do/seasonal-events/brick-or-treat/",
    tags: ["halloween", "family", "trick-or-treat"],
    audience: ["families", "kids"],
    guide_kind: "family",
    region: "Central Florida and Orlando",
  },
  {
    event_id: "gatorland-ghosts-goblins-2026",
    event_name: "Gators, Ghosts and Goblins at Gatorland",
    city: "Orlando",
    start_date: "2026-10-10",
    end_date: "2026-10-25",
    schedule_note: "Three weekends, October 10 and 11, 17 and 18, and 24 and 25, from 10 AM to 5 PM. Halloween activities are included with regular admission.",
    href: "/florida-events/gatorland-ghosts-goblins-2026",
    tags: ["halloween", "family", "trick-or-treat"],
    audience: ["families", "kids"],
    guide_kind: "family",
    region: "Central Florida and Orlando",
  },
  {
    event_id: "howl-o-scream-tampa-2026",
    event_name: "Howl O Scream at Busch Gardens Tampa Bay",
    city: "Tampa",
    start_date: "2026-09-11",
    end_date: "2026-10-31",
    schedule_note: "Select nights September 11 through October 31 with haunted houses, scare zones and rides after dark.",
    href: "/florida-events/howl-o-scream-tampa-2026",
    tags: ["halloween", "haunted", "nightlife"],
    audience: ["adults", "teens"],
    guide_kind: "haunts",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "screamageddon-2026",
    event_name: "Scream A Geddon Horror Park",
    city: "Dade City",
    start_date: "2026-09-04",
    end_date: "2026-11-01",
    schedule_note: "Select nights September 4 through November 1 at the outdoor horror park in Dade City.",
    href: "/florida-events/screamageddon-2026",
    tags: ["halloween", "haunted", "nightlife"],
    audience: ["adults", "teens"],
    guide_kind: "haunts",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "st-pete-pier-fall-fest-2026",
    event_name: "St. Pete Pier Fall Fest and Pumpkin Patch",
    city: "St. Petersburg",
    start_date: "2026-10-09",
    end_date: "2026-10-25",
    schedule_note: "The pumpkin patch runs October 9 through 25. Fall Fest is October 10 and 11 with family activities, live music and food.",
    official_event_url: "https://stpetepier.org/signature-event/st-pete-fall-festival/",
    tags: ["pumpkins", "family", "festival"],
    audience: ["families", "kids"],
    guide_kind: "farms",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "fox-squirrel-maze-2026",
    event_name: "Fox Squirrel Corn Maze and Pumpkin Patch",
    city: "Plant City",
    start_date: "2026-09-26",
    end_date: "2026-10-25",
    schedule_note: "Weekend fall season September 26 through October 25 with a corn maze, pumpkin patch, live music and farm activities.",
    official_event_url: "https://www.foxsquirrelcornmaze.com/",
    tags: ["pumpkins", "farm", "corn-maze"],
    audience: ["families", "kids"],
    guide_kind: "farms",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "tampa-riverwalk-trick-or-treat-2026",
    event_name: "Tampa Riverwalk Trick or Treat",
    city: "Tampa",
    start_date: "2026-10-24",
    end_date: "2026-10-24",
    schedule_note: "Saturday, October 24 from 4 PM to 9 PM at Cotanchobee Fort Brooke Park. Free family Halloween plan.",
    href: "/florida-events/tampa-riverwalk-trick-or-treat-2026",
    tags: ["halloween", "family", "trick-or-treat"],
    audience: ["families", "kids"],
    guide_kind: "family",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "halloween-on-central-st-pete-2026",
    event_name: "Halloween on Central",
    city: "St. Petersburg",
    start_date: "2026-10-25",
    end_date: "2026-10-25",
    schedule_note: "Sunday, October 25 from noon to 5 PM. Free family Halloween festival on Central Avenue.",
    href: "/florida-events/halloween-on-central-st-pete-2026",
    tags: ["halloween", "family", "trick-or-treat", "festival"],
    audience: ["families", "kids"],
    guide_kind: "family",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "tampa-pig-jig-2026",
    event_name: "Tampa Pig Jig",
    city: "Tampa",
    start_date: "2026-10-17",
    end_date: "2026-10-17",
    schedule_note: "Saturday, October 17 on the Tampa riverfront with barbecue teams and a full music lineup.",
    href: "/florida-events/tampa-pig-jig-2026",
    tags: ["food", "festival", "music"],
    audience: ["adults", "families"],
    guide_kind: "food",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "oktoberfest-tampa-curtis-hixon-2026",
    event_name: "Oktoberfest Tampa",
    city: "Tampa",
    start_date: "2026-10-09",
    end_date: "2026-10-11",
    schedule_note: "October 9 through 11 at Curtis Hixon Waterfront Park with German beer, food, music, contests and riverfront festival energy.",
    href: "/florida-events/oktoberfest-tampa-curtis-hixon-2026",
    tags: ["oktoberfest", "food", "festival"],
    audience: ["adults", "families"],
    guide_kind: "food",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "fantasy-fest-2026",
    event_name: "Fantasy Fest",
    city: "Key West",
    start_date: "2026-10-16",
    end_date: "2026-10-25",
    schedule_note: "October 16 through 25 in Key West with ten days of costume events, street celebrations and the closing weekend parade.",
    href: "/florida-events/fantasy-fest-2026",
    tags: ["festival", "costumes", "nightlife"],
    audience: ["adults"],
    guide_kind: "festival",
    region: "South Florida and the Keys",
  },
  {
    event_id: "stone-crab-festival-2026",
    event_name: "Naples Stone Crab Festival",
    city: "Naples",
    start_date: "2026-10-23",
    end_date: "2026-10-25",
    schedule_note: "October 23 through 25 around Tin City with stone crab, seafood, live music and waterfront festival stops.",
    href: "/florida-events/stone-crab-festival-2026",
    tags: ["food", "festival", "seafood"],
    audience: ["adults", "families"],
    guide_kind: "food",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "mount-dora-craft-fair-2026",
    event_name: "Mount Dora Craft Fair",
    city: "Mount Dora",
    start_date: "2026-10-24",
    end_date: "2026-10-25",
    schedule_note: "Saturday and Sunday, October 24 and 25 in downtown Mount Dora with more than 400 juried crafters.",
    href: "/florida-events/mount-dora-craft-fair-2026",
    tags: ["festival", "market", "crafts"],
    audience: ["adults", "families"],
    guide_kind: "festival",
    region: "Central Florida and Orlando",
  },
  {
    event_id: "sir-henrys-haunted-trail-2026",
    event_name: "Sir Henry's Haunted Trail",
    city: "Plant City",
    start_date: "2026-09-25",
    end_date: "2026-11-01",
    schedule_note: "Select nights September 25 through November 1. Trails open after the 7:15 PM opening ceremony and timed entry is sold online.",
    official_event_url: "https://sirhenryshauntedtrail.com/",
    tags: ["halloween", "haunted", "nightlife"],
    audience: ["adults", "teens"],
    guide_kind: "haunts",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "fearville-dk-farms-2026",
    event_name: "FEARville at DK Farms",
    city: "Largo",
    start_date: "2026-10-02",
    end_date: "2026-10-31",
    schedule_note: "Every Friday and Saturday in October from 7 PM to 10 PM. A gentler SpookyVille period runs before the haunts open.",
    official_event_url: "https://www.dkfarmsandgardens.com/fearville",
    tags: ["halloween", "haunted", "family"],
    audience: ["adults", "teens", "families"],
    guide_kind: "haunts",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "lights-at-spooky-point-2026",
    event_name: "Lights at Spooky Point",
    city: "Osprey",
    start_date: "2026-10-01",
    end_date: "2026-10-31",
    schedule_note: "Timed evening entry throughout October at Historic Spanish Point. The checked ticket calendar does not offer October 13 or 19, so choose an available date before leaving.",
    official_event_url: "https://selby.org/hsp/hsp-special-events/lights-at-spooky-point/",
    tags: ["halloween", "lights", "family"],
    audience: ["families", "adults"],
    guide_kind: "family",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "selby-spooktacular-2026",
    event_name: "Selby Spooktacular",
    city: "Sarasota",
    start_date: "2026-10-25",
    end_date: "2026-10-25",
    schedule_note: "Sunday, October 25 from 10 AM to 1 PM at Selby Gardens. Halloween activities are included with garden admission.",
    official_event_url: "https://selby.org/dsc/dsc-special-events/selby-spooktacular/",
    tags: ["halloween", "family", "garden"],
    audience: ["families", "kids"],
    guide_kind: "family",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "island-trunk-or-treat-ami-2026",
    event_name: "Island Trunk or Treat",
    city: "Anna Maria",
    start_date: "2026-10-30",
    end_date: "2026-10-30",
    schedule_note: "Friday, October 30 from 6 PM to 8 PM behind The Center of Anna Maria Island. Free.",
    official_event_url: "https://centerami.org/events/",
    tags: ["halloween", "family", "trick-or-treat"],
    audience: ["families", "kids"],
    guide_kind: "family",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "oktoberfest-tampa-bay-german-american-2026",
    event_name: "Oktoberfest Tampa Bay",
    city: "Pinellas Park",
    start_date: "2026-09-25",
    end_date: "2026-10-10",
    schedule_note: "Three Friday and Saturday weekends from September 25 through October 10 with German food, music and festival traditions.",
    official_event_url: "https://germantampabay.com/oktoberfest/",
    tags: ["oktoberfest", "food", "festival"],
    audience: ["adults", "families"],
    guide_kind: "food",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "park-toberfest-bay-sarasota-2026",
    event_name: "Parktoberfest at The Bay",
    city: "Sarasota",
    start_date: "2026-10-11",
    end_date: "2026-10-11",
    schedule_note: "Sunday, October 11 from 5 PM to 7 PM on The Oval at The Bay Park. Free with registration.",
    official_event_url: "https://www.thebaysarasota.org/event/park-toberfest-at-the-bay/",
    tags: ["oktoberfest", "food", "festival"],
    audience: ["adults", "families"],
    guide_kind: "food",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "rocktoberfest-sarasota-2026",
    event_name: "ROCKtoberfest Downtown Sarasota",
    city: "Sarasota",
    start_date: "2026-10-10",
    end_date: "2026-10-10",
    schedule_note: "Saturday, October 10 from 5 PM to 11 PM at J.D. Hamel Park. Free admission with live music and downtown festival food.",
    official_event_url: "https://destinationdowntownsarasota.com/rocktoberfest/",
    tags: ["oktoberfest", "music", "festival", "food"],
    audience: ["adults", "families"],
    guide_kind: "food",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "sharktoberfest-mote-2026",
    event_name: "Sharktoberfest at Mote SEA",
    city: "Sarasota",
    start_date: "2026-10-17",
    end_date: "2026-10-17",
    schedule_note: "Saturday, October 17 from 7 PM to 11 PM. Ticketed and 21 plus.",
    official_event_url: "https://mote.org/event/sharktoberfest/",
    tags: ["oktoberfest", "nightlife", "food"],
    audience: ["adults"],
    guide_kind: "food",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "haunted-sarasota-trolley-2026",
    event_name: "Haunted Sarasota Ghost Tour",
    city: "Sarasota",
    start_date: "2026-10-01",
    end_date: "2026-10-31",
    schedule_note: "Nightly in October on the operator calendar. The trolley experience lasts about 75 minutes and is for ages 12 and older.",
    official_event_url: "https://www.discoversarasotatours.com/all-tours/haunted-sarasota/",
    tags: ["halloween", "ghost", "tour", "nightlife"],
    audience: ["adults", "teens"],
    guide_kind: "haunts",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "candlelight-halloween-siesta-key-2026",
    event_name: "Candlelight Halloween Classics at Siesta Key",
    city: "Siesta Key",
    start_date: "2026-10-24",
    end_date: "2026-10-24",
    schedule_note: "Saturday, October 24 with evening showtimes on the ticket page. The candlelit concert runs about 65 minutes.",
    official_event_url: "https://feverup.com/en/sarasota/candlelight-halloween",
    tags: ["halloween", "music", "date-night"],
    audience: ["adults", "couples"],
    guide_kind: "activities",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "sarasota-boos-booze-bar-crawl-2026",
    event_name: "Sarasota Boos and Booze Halloween Bar Crawl",
    city: "Sarasota",
    start_date: "2026-10-31",
    end_date: "2026-10-31",
    schedule_note: "Saturday, October 31 from 3 PM to 10 PM. Ticketed and 21 plus.",
    official_event_url: "https://www.eventbrite.com/e/sarasota-boos-booze-halloween-bar-crawl-2nd-annual-by-bar-crawl-usa-tickets-1984374423318",
    tags: ["halloween", "nightlife", "bar-crawl"],
    audience: ["adults"],
    guide_kind: "haunts",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "st-pete-halloween-bar-crawl-2026",
    event_name: "St. Pete Official Halloween Bar Crawl",
    city: "St. Petersburg",
    start_date: "2026-10-30",
    end_date: "2026-10-31",
    schedule_note: "Friday, October 30 and Saturday, October 31 from 6 PM to 1 AM. Ticketed and 21 plus.",
    official_event_url: "https://www.eventbrite.com/e/st-pete-official-halloween-bar-crawl-2026-by-bar-crawl-live-tickets-1987573665337",
    tags: ["halloween", "nightlife", "bar-crawl"],
    audience: ["adults"],
    guide_kind: "haunts",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "ami-bayfest-2026",
    event_name: "Anna Maria Island BayFest",
    city: "Anna Maria",
    start_date: "2026-10-17",
    end_date: "2026-10-17",
    schedule_note: "Saturday, October 17 from 10 AM to 9 PM on Pine Avenue. Free. Confirm the chamber schedule before making a special trip because destination and chamber listings were not yet synchronized at the last check.",
    official_event_url: "https://www.bradentongulfislands.com/event/24th-bayfest-hosted-by-anna-maria-island-chamber-of-commerce/",
    tags: ["festival", "music", "food"],
    audience: ["adults", "families"],
    guide_kind: "festival",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "freedom-factory-halloween-destruction-2026",
    event_name: "Tour of Destruction Halloween Edition",
    city: "Bradenton",
    start_date: "2026-10-30",
    end_date: "2026-10-31",
    schedule_note: "Friday, October 30 and Saturday, October 31 at Freedom Factory with gates in the late afternoon and racing at night.",
    official_event_url: "https://www.tourofdestruction.com/florida",
    tags: ["halloween", "motorsports", "festival"],
    audience: ["adults", "families"],
    guide_kind: "festival",
    region: "Tampa Bay and Gulf Coast",
  },
  {
    event_id: "cedar-key-seafood-festival-2026",
    event_name: "Cedar Key Seafood Festival",
    city: "Cedar Key",
    start_date: "2026-10-17",
    end_date: "2026-10-17",
    schedule_note: "Saturday, October 17 from 10 AM in downtown Cedar Key. The chamber listing confirms Saturday. Confirm before planning a second day.",
    official_event_url: "https://www.cedarkey.org/2026/10/17/476073/seafood-festival",
    tags: ["food", "seafood", "festival"],
    audience: ["adults", "families"],
    guide_kind: "food",
    region: "Panhandle and North Florida",
  },
  {
    event_id: "jacksonville-pumpkin-fest-2026",
    event_name: "Jacksonville Pumpkin Festival at Amazing Grace Family Farms",
    city: "Green Cove Springs",
    start_date: "2026-10-02",
    end_date: "2026-10-31",
    schedule_note: "Fridays and Saturdays in October, plus Monday October 12. Pumpkin patch, flower fields, crop maze and family attractions. The farm says the season is crop and weather dependent.",
    official_event_url: "https://www.agcropmaze.com/",
    tags: ["pumpkins", "farm", "corn-maze", "flowers"],
    audience: ["families", "kids"],
    guide_kind: "farms",
    region: "Panhandle and North Florida",
  },
  {
    event_id: "congaree-pumpkin-patch-2026",
    event_name: "Congaree and Penn Pumpkin Patch",
    city: "Jacksonville",
    start_date: "2026-09-24",
    end_date: "2026-11-01",
    schedule_note: "Thursday through Sunday, September 24 through November 1. Fall on the Farm Grounds adds live music, food and the farm bar on select evenings.",
    official_event_url: "https://www.congareeandpenn.com/pumpkins",
    tags: ["pumpkins", "farm", "food", "music"],
    audience: ["adults", "families"],
    guide_kind: "farms",
    region: "Panhandle and North Florida",
  },
  {
    event_id: "sykes-family-farms-fall-2026",
    event_name: "Sykes Family Farms Fall Festival",
    city: "Elkton",
    start_date: "2026-10-03",
    end_date: "2026-11-01",
    schedule_note: "Fridays, Saturdays and Sundays from October 3 through November 1. The 9 acre corn maze is the centerpiece, with farm attractions and pumpkins available separately.",
    official_event_url: "https://sycofarms.com/",
    tags: ["pumpkins", "farm", "corn-maze"],
    audience: ["families", "kids"],
    guide_kind: "farms",
    region: "Panhandle and North Florida",
  },
  {
    event_id: "sweet-season-farms-2026",
    event_name: "Sweet Season Farms Corn Maze and Fall Fun Festival",
    city: "Milton",
    start_date: "2026-09-26",
    end_date: "2026-11-08",
    schedule_note: "Saturdays and Sundays September 26 through November 8. Flashlight maze nights run October 23 and 30 from 6 PM to 10 PM.",
    official_event_url: "https://www.sweetseasonfarms.com/",
    tags: ["pumpkins", "farm", "corn-maze", "hayride"],
    audience: ["families", "kids"],
    guide_kind: "farms",
    region: "Panhandle and North Florida",
  },
  {
    event_id: "aunt-louises-farm-fall-2026",
    event_name: "Aunt Louise's Farm Fall Farm Days",
    city: "Monticello",
    start_date: "2026-10-03",
    end_date: "2026-11-15",
    schedule_note: "Saturdays and Sundays October 3 through November 15 with a corn maze, wagon rides, barrel train, animals and fall food.",
    official_event_url: "https://www.auntlouisesfarm.com/",
    tags: ["farm", "corn-maze", "hayride", "animals"],
    audience: ["families", "kids"],
    guide_kind: "farms",
    region: "Panhandle and North Florida",
  },
  {
    event_id: "pensacola-interstate-fair-2026",
    event_name: "Pensacola Interstate Fair",
    city: "Pensacola",
    start_date: "2026-10-22",
    end_date: "2026-11-01",
    schedule_note: "October 22 through November 1 with rides, entertainment, exhibits, livestock, food and fair attractions.",
    official_event_url: "https://pensacolafair.com/general-fair-information/",
    tags: ["fair", "festival", "food", "rides"],
    audience: ["families", "adults"],
    guide_kind: "festival",
    region: "Panhandle and North Florida",
  },
  {
    event_id: "jacksonville-zoo-spooktacular-2026",
    event_name: "Spooktacular at Jacksonville Zoo and Botanical Gardens",
    city: "Jacksonville",
    start_date: "2026-10-10",
    end_date: "2026-10-31",
    schedule_note: "October 10, 15 through 18, 22 through 25, and 29 through 31. Family Halloween nights with costumes, treats and zoo activities.",
    official_event_url: "https://www.visitjacksonville.com/events/annual/halloween/",
    tags: ["halloween", "family", "trick-or-treat"],
    audience: ["families", "kids"],
    guide_kind: "family",
    region: "Panhandle and North Florida",
  },
  {
    event_id: "foo-foo-festival-pensacola-2026",
    event_name: "Foo Foo Festival",
    city: "Pensacola",
    start_date: "2026-10-29",
    end_date: "2026-11-09",
    schedule_note: "October 29 through November 9. Twelve days of art, music, performance and cultural events across Pensacola. Some events are free and some require tickets.",
    official_event_url: "https://foofoofest.com/",
    tags: ["festival", "arts", "music"],
    audience: ["adults", "families"],
    guide_kind: "festival",
    region: "Panhandle and North Florida",
  },
  {
    event_id: "taste-of-the-beach-pensacola-2026",
    event_name: "Taste of the Beach Festival",
    city: "Pensacola Beach",
    start_date: "2026-10-29",
    end_date: "2026-11-01",
    schedule_note: "October 29 through November 1. The Saturday festival at Casino Beach brings restaurant tastings, live music and family activities.",
    official_event_url: "https://www.visitpensacola.com/events/taste-of-the-beach-festival/",
    tags: ["food", "festival", "seafood"],
    audience: ["adults", "families"],
    guide_kind: "food",
    region: "Panhandle and North Florida",
  },
]);

function dedupeById(rows) {
  const seen = new Set();
  const out = [];
  for (const row of rows) {
    if (!row || !row.event_id || !row.event_name || seen.has(row.event_id)) continue;
    seen.add(row.event_id);
    out.push(row);
  }
  return out;
}

function sortByDate(a, b) {
  return String(a.start_date || "9999-12-31").localeCompare(String(b.start_date || "9999-12-31"))
    || String(a.event_name || "").localeCompare(String(b.event_name || ""));
}

export const FLORIDA_FALL_GUIDE_EVENTS_2026 = Object.freeze(
  dedupeById([
    ...FALL_FEATURED_FESTIVALS_2026,
    ...FALL_DISCOVERIES_2026,
    ...GULF_COAST_FALL_2026_ROWS,
    ...GUIDE_ONLY_EVENTS_2026,
  ]).sort(sortByDate),
);

export const FLORIDA_FALL_GUIDE_EVENT_COUNT = FLORIDA_FALL_GUIDE_EVENTS_2026.length;

const REGION_CITY_SETS = Object.freeze({
  "Panhandle and North Florida": new Set([
    "Pensacola", "Pensacola Beach", "Milton", "Monticello", "Jacksonville",
    "Green Cove Springs", "Elkton", "Gainesville", "Micanopy", "Lake City",
    "Hilliard", "Cedar Key", "Newberry", "High Springs",
  ]),
  "Central Florida and Orlando": new Set([
    "Orlando", "Winter Garden", "Clermont", "Eustis", "Kissimmee", "St Cloud",
    "St. Cloud", "Winter Park", "Mount Dora", "Umatilla", "Winter Haven",
    "Daytona Beach", "Polk City",
  ]),
  "Tampa Bay and Gulf Coast": new Set([
    "Tampa", "St. Petersburg", "Plant City", "Largo", "Wesley Chapel",
    "Carrollwood", "Dade City", "Sarasota", "Bradenton", "Myakka City",
    "Parrish", "Venice", "Osprey", "Anna Maria", "Pinellas Park", "Ruskin",
    "Cape Coral", "Naples", "Terra Ceia",
  ]),
  "Space, Treasure and Palm Beach": new Set([
    "Palm Bay", "Melbourne", "Hobe Sound", "Boynton Beach", "Port St. Lucie",
  ]),
  "South Florida and the Keys": new Set([
    "Miami", "Miami Beach", "Homestead", "Fort Lauderdale", "Pompano Beach",
    "Key West",
  ]),
});

export const FALL_GUIDE_REGION_ORDER = Object.freeze([
  "Panhandle and North Florida",
  "Central Florida and Orlando",
  "Tampa Bay and Gulf Coast",
  "Space, Treasure and Palm Beach",
  "South Florida and the Keys",
  "Other Florida",
]);

export function fallGuideRegion(event) {
  if (event?.region) return event.region;
  for (const [region, cities] of Object.entries(REGION_CITY_SETS)) {
    if (cities.has(event?.city)) return region;
  }
  return "Other Florida";
}

export function fallGuideKind(event) {
  if (event?.guide_kind) return event.guide_kind;
  const text = [
    event?.event_name,
    event?.short_title,
    event?.subcategory,
    ...(Array.isArray(event?.tags) ? event.tags : []),
    ...(Array.isArray(event?.audience) ? event.audience : []),
  ].filter(Boolean).join(" ").toLowerCase();

  if (/trick|spooktacular|zoo boo|not so scary|brick or treat|goblins|trunk or treat|boo in bloom/.test(text)) return "family";
  if (/horror|haunt|scream|ghost|fear|nightmare|bar crawl|boos and booze/.test(text)) return "haunts";
  if (/oktoberfest|food|wine|coffee|cider|stone crab|pig jig|taste of the beach|seasonal menu/.test(text)) return "food";
  if (/pumpkin|farm|corn maze|harvest|sunflower|u-pick/.test(text)) return "farms";
  if (/fair|festival|craft|bayfest|foo foo|fantasy fest/.test(text)) return "festival";
  return "activities";
}

export const FALL_GUIDE_KIND_LABELS = Object.freeze({
  farms: "Pumpkin patches and farms",
  family: "Family Halloween",
  haunts: "Haunts and after dark",
  food: "Fall food and drink",
  festival: "Big fall weekends",
  activities: "Fall activities",
});

export function fallGuideEventHref(event) {
  return event?.href || event?.official_event_url || event?.source_url || null;
}

export function findFallGuideEvent(eventId) {
  return FLORIDA_FALL_GUIDE_EVENTS_2026.find((event) => event.event_id === eventId) || null;
}

export const FALL_GUIDE_STARTER_IDS = Object.freeze([
  "frrm-pumpkin-patch-express-2026",
  "hunsader-pumpkin-2026",
  "dakin-harvest-festival-2026",
  "keel-farms-harvest-days-2026",
  "southern-hill-farms-fall-festival-2026",
  "fruitville-grove-pumpkin-2026",
  "halloween-horror-nights-orlando-2026",
  "fantasy-fest-2026",
  "epcot-food-wine-festival-2026",
  "gatorland-ghosts-goblins-2026",
]);

export const FALL_GUIDE_WEEKDAY_IDS = Object.freeze([
  "epcot-food-wine-festival-2026",
  "showcase-citrus-pumpkin-ponderosa-2026",
  "green-meadows-fall-2026",
  "all-fired-up-halloween-pottery-winter-park-2026",
  "dead-coconut-club-harvest-citywalk-2026",
  "haunted-sarasota-trolley-2026",
  "haunted-mangoni-2026",
  "rosallie-lattes-leaves-2026",
  "perfect-press-fall-coffee-2026",
  "you-do-the-dishes-fall-2026",
  "house-of-horror-carnival-2026",
]);

export const FALL_GUIDE_OCTOBER_WEEKENDS = Object.freeze([
  {
    date: "Oct 2 to 4",
    title: "Start with farms and first weekend energy",
    note: "This is the first big overlap of pumpkin patches, corn mazes and South Florida harvest season.",
    ids: [
      "fruitville-grove-pumpkin-2026",
      "keel-farms-harvest-days-2026",
      "green-meadows-fall-2026",
      "great-scott-fall-fest-2026",
      "southern-hill-farms-fall-festival-2026",
      "nightmare-village-xtreme-action-park-2026",
    ],
  },
  {
    date: "Oct 9 to 11",
    title: "The farm plus Oktoberfest weekend",
    note: "This is the strongest mix of classic farm days, Tampa Oktoberfest and family Halloween openings.",
    ids: [
      "dakin-harvest-festival-2026",
      "hunsader-pumpkin-2026",
      "oktoberfest-tampa-curtis-hixon-2026",
      "sarasota-oktoberfest-benderson-2026",
      "gatorland-ghosts-goblins-2026",
      "roars-smores-snores-spooktacular-campout-zoo-miami-2026",
    ],
  },
  {
    date: "Oct 16 to 18",
    title: "Pick the unusual experience",
    note: "Train rides, seafood towns, island festivals, costume season and adult night events all overlap here.",
    ids: [
      "frrm-pumpkin-patch-express-2026",
      "fantasy-fest-2026",
      "tampa-pig-jig-2026",
      "sharktoberfest-mote-2026",
      "night-of-wonder-ringling-2026",
      "zoo-miami-monster-masquerade-2026",
    ],
  },
  {
    date: "Oct 23 to 25",
    title: "The biggest family Halloween weekend",
    note: "This weekend stacks trick or treating, zoo events, crafts, seafood and the final big farm weekends.",
    ids: [
      "tampa-riverwalk-trick-or-treat-2026",
      "lights-at-spooky-point-2026",
      "zoo-boo-zoo-miami-2026",
      "mount-dora-craft-fair-2026",
      "boo-bash-pompano-beach-2026",
      "selby-spooktacular-2026",
    ],
  },
  {
    date: "Oct 30 to Nov 1",
    title: "Go all in on Halloween",
    note: "Use this weekend for the biggest scare nights, costume events, fairs and Halloween day plans.",
    ids: [
      "halloween-horror-nights-orlando-2026",
      "the-horrorland-jungle-island-2026",
      "house-of-horror-carnival-2026",
      "bonnet-house-halloween-fest-2026",
      "freedom-factory-halloween-destruction-2026",
      "boo-in-bloom-fruit-spice-park-2026",
      "halloween-at-faena-miami-beach-2026",
      "haunted-mangoni-2026",
    ],
  },
]);
