// lib/guidesSummer2026.js — SEASONAL: the ten summer-2026 city guides.
//
// Researched 2026-08-07 from live sources (see the session doc
// wayfind-florida-summer-2026-top-cities-research-2026-08-07 in the project for
// per-item sourcing). Same editorial rules as lib/guides.js: honest picks,
// famous verifiable claims only, affiliate links disclosed, teasers grounded in
// the guide's own body (check-guide-teasers proves it).
//
// ⏳ SUNSET 2026-08-30 (owner decision, 2026-08-07). These pages come DOWN on
// Aug 30: remove the spread in lib/guides.js and delete this file. A scheduled
// removal task exists per the registry's global rule (b) — dated content ships
// with its deletion reminder created at entry.
//
// Regions beyond the four core metros fail soft everywhere by design: no
// LANDING_CITIES entry means no bridge picks, regionCity() returns null so the
// live-inventory tier skips, and REGION_COORDS entries added in guideNow.js
// give every region the ISR weather block.

export const SUMMER_2026_GUIDES = {
  "things-to-do-orlando-summer-2026": {
    teaser: "The new show in Celestial Park runs every night this summer, but the after-dark water park parties are where the lines are actually shorter.",
    region: "Orlando",
    title: "10 Best Things to Do in Orlando This Summer (2026)",
    description: "Epic Universe's new nighttime show, the Muppets coaster, glow-in-the-dark water park nights, and where locals actually eat: Orlando's summer 2026, ranked.",
    keyword: "things to do in orlando this summer",
    updated: "2026-08-07",
    intro: "Summer 2026 is the biggest new-attraction season Orlando has had in years: Universal's newest park picked up a nighttime spectacular, Disney reopened two classics with new tricks, and the water parks turned their evenings into parties. Here's what earns your sweat this summer, ranked.",
    picks: [
      { name: "Universal Epic Universe", indoor: false, appQuery: "Universal Epic Universe", blurb: "Universal's newest park is still the hottest ticket in America, and TIME just named it to its World's Greatest Places 2026 list. Five worlds — Super Nintendo World, Isle of Berk, the Ministry of Magic, Dark Universe, and Celestial Park — and new 2026 multi-day tickets finally let you enter every day of your trip.", tip: "Single days run about $140 and up; the 2026 multi-day tickets are the math that works.", bookQuery: "Universal Orlando tickets" },
      { name: "Universal Celestial Goodnight, the new night show", indoor: false, appQuery: null, blurb: "The park's first nighttime spectacular debuted July 7 in Celestial Park and runs every night this summer: about 600 synchronized lights, 350-plus fountains, projection mapping, and a fireworks finale. It's included with admission, so the only cost is staying past dark.", tip: "Stake out the Celestial Park lagoon 30 minutes before showtime; the fountains read best from the water's edge." },
      { name: "Magic Kingdom's reopened classics", indoor: false, appQuery: "Magic Kingdom", blurb: "Big Thunder Mountain came back this spring with new track and the Rainbow Caverns scene, and Buzz Lightyear's Space Ranger Spin returned with handheld blasters and live scoring. Two rides people had memorized are suddenly worth re-riding.", tip: "Rope-drop Big Thunder; its new scenes are drawing the longest standby waits in Frontierland.", bookQuery: "Walt Disney World tickets" },
      { name: "Rock 'n' Roller Coaster Starring The Muppets", indoor: true, appQuery: "Disney's Hollywood Studios", blurb: "The most talked-about Disney change of the year: Aerosmith is out and Dr. Teeth and the Electric Mayhem are in, with new Audio-Animatronics in the pre-show. Same launch, entirely new attitude — and air conditioning.", tip: "Pair it with the Millennium Falcon's new mission, added in May, which lets you pick destinations like Bespin." },
      { name: "The after-dark water park parties", indoor: false, appQuery: null, blurb: "This is the viral Orlando move of summer 2026: Disney's H2O Glow After Hours at Typhoon Lagoon, Volcano Bay Nights, and Aquatica's AquaGlow all run neon-lit evenings with DJ sets — and the lines are noticeably shorter than any daytime visit. Separately ticketed, roughly $30 to $79 depending on the park.", tip: "H2O Glow runs through September 5 and Volcano Bay Nights ends August 21 — book the dated ticket before you build the day around it." },
      { name: "SeaWorld's Electric Ocean nights", indoor: false, appQuery: "SeaWorld Orlando", blurb: "Electric Ocean runs through September 7 with drone shows, fireworks, and DJ parties after dusk, and the new Expedition Odyssey experience opened this season. Online tickets are routinely discounted to around $80 or less.", tip: "Guests 21 and over get free beer samples during Electric Ocean; the stand is near Waterway Grill.", bookQuery: "SeaWorld Orlando tickets" },
      { name: "EPCOT's Soarin' Across America", indoor: true, appQuery: "EPCOT", blurb: "A limited-time Soarin' film that debuted Memorial Day weekend for America's 250th birthday, flying the theater over the country's biggest landscapes. With the semiquincentennial running all summer, EPCOT is unusually patriotic right now.", tip: "It's a limited run tied to the America 250 season — see it this summer rather than assuming it stays." },
      { name: "ICON Park's new entertainment wave", indoor: true, appQuery: "ICON Park", blurb: "Blue Man Group returned to Orlando on May 1 in a purpose-built 500-seat theater, next to the new glow-in-the-dark Ripley's Crazy Golf and The Great Big Game Show with live hosts. International Drive quietly became a real second night out.", tip: "The Wheel at ICON Park after the Blue Man show puts the theme-park fireworks on the horizon in three directions.", bookQuery: "ICON Park Orlando" },
      { name: "Level99 at Disney Springs", indoor: true, appQuery: "Disney Springs", blurb: "A massive interactive gaming venue opening this summer in the old NBA Experience building: 60-plus physical and mental challenge rooms plus a two-story bar doing Detroit-style pizza. The buzziest non-park opening of the year.", tip: "It's built for groups of three to six; solo visitors get matched or wait — bring your crew." },
      { name: "Eola Food Hall and the Mills 50 crawl", indoor: true, appQuery: "Mills 50 Orlando", blurb: "Food TikTok's Orlando obsession is real: the new Eola Food Hall downtown runs ten local chef stalls, and Mills 50 keeps stacking hits from dumpling shops to Vietnamese dessert counters. Most meals land between $15 and $40 a head.", tip: "Cafe Tu Tu Tango on I-Drive — tapas while live painters work the room — is the rare famous one that still delivers." },
    ],
    faq: [
      { q: "Is Epic Universe worth it over the older Universal parks?", a: "For a first 2026 visit, yes — it's the newest major theme park in America and the new nighttime show gives the evening a real finale. The 2026 multi-day tickets that include it every day beat single-day pricing comfortably." },
      { q: "How bad is Orlando heat in August?", a: "Mid-90s with afternoon storms most days. The working pattern: parks at open, indoor rides or the hotel pool from 1 to 4pm, then evenings for shows and the after-dark water parties." },
      { q: "What's genuinely new this summer versus last?", a: "The Celestial Goodnight night show, the Muppets takeover of Rock 'n' Roller Coaster, Big Thunder's Rainbow Caverns, Soarin' Across America, Level99, and Blue Man Group's return — 2026 stacked more openings than any recent summer." },
    ],
    // The guide is ABOUT Orlando attractions, and the registry deal that covers
    // them is the CityPASS bundle — read by id from lib/coupons, never a URL here.
    dealId: "cpn-citypass-orlando",
    dealCards: ["cpn-citypass-orlando", "cpn-clipp-fl-orlando"],
  },

  "things-to-do-miami-summer-2026": {
    teaser: "August is when 300 restaurants drop to prix fixe menus, and one 1924 spring water pool is how locals survive the heat.",
    region: "Miami",
    title: "10 Best Things to Do in Miami This Summer (2026)",
    description: "Miami Spice's prix fixe month, the Balloon Museum in Wynwood, the Venetian Pool, and the World Cup afterglow: Miami's summer 2026, honestly ranked.",
    keyword: "things to do in miami this summer",
    updated: "2026-08-07",
    intro: "Miami summers run on a trade: brutal heat in exchange for the year's best prices. August is when roughly 300 restaurants drop to prix fixe menus for Miami Spice, the spas discount, and the crowds thin to survivable. Add a World Cup summer's afterglow and the strongest new-opening run in years, and 2026 is the summer to take the trade.",
    picks: [
      { name: "Wynwood Walls and the arts district", indoor: false, appQuery: "Wynwood Walls", blurb: "The open-air street art museum with 50-plus large murals stays Miami's most-filmed backdrop, and the district keeps leveling up — the Grotto Baths wellness center and the two-level Midline music venue both arrive this year. The murals themselves cost nothing to walk.", tip: "Go before 11am in summer: shade is scarce, and the light on the murals is better anyway.", bookQuery: "Wynwood art tour" },
      { name: "Balloon Museum at Mana Wynwood", indoor: true, appQuery: null, blurb: "The immersive inflatable-art blockbuster runs through September 27 — room-scale installations, mirrored rooms, and a ball pit that has flooded every Miami feed this summer. It topped Time Out's July list of what to do right now. Tickets run $41 to $49.", tip: "It's the city's best two air-conditioned hours; book a weekday morning slot to shoot the rooms empty." },
      { name: "Miami Spice month", indoor: true, appQuery: null, blurb: "August through September, about 300 of the city's top restaurants serve three-course prix fixe menus at $40 to $65 — the local-approved way to eat at Michelin-level rooms for a fraction of winter prices. Miami Spa Months discounts the five-star spas in parallel.", tip: "The famous rooms release Spice tables in waves; if a restaurant shows nothing this week, check again Monday." },
      { name: "The Venetian Pool", indoor: false, appQuery: "Venetian Pool", blurb: "A 1924 landmark public pool in Coral Gables holding 820,000 gallons of spring water, refreshed daily, with waterfalls and a grotto. It is the single best answer to a Miami August afternoon, and entry starts around $22.", tip: "The spring water runs cool all day — it's how locals survive the heat of summer, and the swim they pick over the ocean." },
      { name: "South Pointe Park Pier and South Beach", indoor: false, appQuery: "South Pointe Park", blurb: "The southern tip of Miami Beach is the city's reigning golden-hour spot: sunrise runs, cruise ships sliding past close enough to wave at, and the Art Deco strip a short walk north. The pier and park are free.", tip: "Cruise ships depart late afternoon into evening — time a pier walk to watch one pass at arm's length." },
      { name: "Inter Miami at Miami Freedom Park", indoor: false, appQuery: null, blurb: "Messi's club moved into its new 131-acre stadium complex this year, and the city is still riding its World Cup summer — Hard Rock Stadium hosted seven matches in July, including a quarterfinal. Soccer fever here is at an all-time high.", tip: "Resale prices drop hardest for midweek league matches; weekend games against big clubs stay premium." },
      { name: "Joia Beach Club on Watson Island", indoor: false, appQuery: "Joia Beach", blurb: "The Ibiza-style waterfront beach club with skyline views keeps topping this year's Miami guides: DJs, cabanas, and toes-in-the-sand dining that runs sunset into night. Expect beach-club pricing and daybed minimums.", tip: "Sunset is the show — book a table for the last two hours of light rather than a midday daybed." },
      { name: "The Coral Gables restaurant boom", indoor: true, appQuery: "Coral Gables", blurb: "The Gables is suddenly the hottest dining zip code in Miami: Clay Conley opened Buccan in May, Palm Beach sushi institution Imoto followed in June, and Michelin-starred chef Shingo Akikuni launched Stand, a Japanese kissaten by day and izakaya by night.", tip: "Several of the new rooms are on the Miami Spice roster in their first summer — the cheapest these kitchens will ever be." },
      { name: "Versace Mansion and the Ocean Drive icons", indoor: false, appQuery: "Ocean Drive Miami Beach", blurb: "Villa Casa Casuarina's mosaic pool and gilded gates remain the most-photographed doorstep on Ocean Drive, with Damien Hirst's gold mammoth at the Faena up the beach. Walking the strip costs nothing; dinner at the mansion is the famous splurge.", tip: "Shoot the mansion steps before 9am — by mid-morning there's a line to stand on them." },
      { name: "Little Havana's Calle Ocho", indoor: false, appQuery: "Little Havana", blurb: "Hand-rolled cigars, cafecito windows, live music, and the domino masters of Máximo Gómez Park make this Miami's essential culture walk. Budget a few dollars for a cortadito and a croqueta and it's the cheapest great afternoon in the city.", tip: "The domino park peaks late afternoon; photograph the games from outside the fence unless invited in.", bookQuery: "Little Havana food tour" },
    ],
    faq: [
      { q: "Is Miami worth visiting in August?", a: "If you build the day around the heat, yes — it's the cheapest month for the city's best restaurants and hotels thanks to Miami Spice and Spa Months, and the big openings this year give the trip a hook. Mornings outside, afternoons indoors or in the water, evenings out." },
      { q: "What is Miami Spice exactly?", a: "An annual August–September program where around 300 top restaurants serve three-course prix fixe menus — roughly $40 lunch and $65 dinner — including rooms that are hard tables the rest of the year." },
      { q: "Beach or pool in summer?", a: "Both, but the Venetian Pool's spring water stays cooler than the ocean, which bathwater-warms by August. The beach wins early morning; the pool wins the afternoon." },
    ],
  },

  "things-to-do-tampa-summer-2026": {
    teaser: "The margaritas come out of a soft-serve machine this summer, but the new manatee rescue center is where you watch real patients up close.",
    region: "Tampa",
    title: "10 Best Things to Do in Tampa This Summer (2026)",
    description: "ZooTampa's new manatee rescue center, the Busch Gardens lion habitat, soft-serve margaritas, and the Riverwalk done right: Tampa's summer 2026, ranked.",
    keyword: "things to do in tampa this summer",
    updated: "2026-08-07",
    intro: "Tampa's 2026 summer story is new animals and viral drinks: the zoo opened its biggest expansion ever around a manatee rescue center, Busch Gardens added a lion savanna, and the bay area's Mexican restaurants started swirling margaritas out of soft-serve machines. Here's the summer, ranked.",
    picks: [
      { name: "Busch Gardens and the new Lions and Hyena Ridge", indoor: false, appQuery: "Busch Gardens Tampa Bay", blurb: "The flagship park's newest habitat opened this spring in Edge of Africa: a 35,000-square-foot savanna with five young lion brothers and two hyenas, viewable from a 270-degree vantage. Gate price runs about $124, with steep online discounts.", tip: "Animals are active at park open and after 5pm; midday they nap and so should you.", bookQuery: "Busch Gardens Tampa tickets" },
      { name: "ZooTampa's Florida Waters expansion", indoor: false, appQuery: "ZooTampa at Lowry Park", blurb: "The zoo's largest expansion ever opened in March: a manatee rescue center where you watch real patients rehabbing up close, an otter habitat, and a 10,000-gallon tropical tank. The zoo released a record 26 rescued manatees back to the wild last year — this is the feel-good ticket in town.", tip: "Rescue-center feedings are the moment; ask a keeper for the day's schedule at the gate.", bookQuery: "ZooTampa tickets" },
      { name: "The Riverwalk with the Pirate Water Taxi", indoor: false, appQuery: "Tampa Riverwalk", blurb: "The free 2.5-mile waterfront path strings together Curtis Hixon park, the art museum, Armature Works, and Sparkman Wharf. The water taxi between stops is the summer move — the skyline from the river beats the sidewalk view anyway.", tip: "Walk one direction, boat back; an all-day taxi pass beats re-parking three times.", bookQuery: "Tampa river cruise" },
      { name: "Ybor City", indoor: false, appQuery: "Ybor City", blurb: "The historic cigar district is a National Historic Landmark that still works: hand-rollers in the windows, the Columbia — Florida's oldest restaurant — and the free-roaming roosters that own every visitor's camera roll. Free to wander.", tip: "The Columbia's 1905 Salad is table-made theater; go at lunch when the walk-in wait is half the dinner line." },
      { name: "Armature Works at golden hour", indoor: true, appQuery: "Armature Works", blurb: "The restored 1910 trolley barn turned food hall anchors the Riverwalk's north end with dozens of vendors and a rooftop bar over the Hillsborough. It's the most-tagged food spot in Tampa this year, and the golden-hour river shot is why.", tip: "Weekend brunch is a crush; weekday evenings get the same rooftop with none of the wait." },
      { name: "The soft-serve margarita crawl", indoor: true, appQuery: null, blurb: "Tampa Bay's official drink of summer 2026: frozen margaritas swirled soft-serve style, launched at Mad Beach Cantina on Cinco de Mayo and now spreading across the area's Mexican restaurants as the videos rack up views. Typically $10 to $15 a pour.", tip: "The machine matters — ask if it's swirled to order or pre-poured; the swirl is the whole point." },
      { name: "Sparkman Wharf", indoor: false, appQuery: "Sparkman Wharf", blurb: "Shipping-container eateries and a big lawn at the Channel District's edge, next to the aquarium. Rotating chef-driven stalls, dog-friendly, and one of the easiest cheap evenings in town.", tip: "Thursday through Sunday there's usually live music on the lawn; check the wharf's calendar before you pick your night." },
      { name: "The Florida Aquarium", indoor: true, appQuery: "The Florida Aquarium", blurb: "The downtown classic walks you from Florida's springs out to open ocean, with a shark tank and touch pools — and an outdoor splash zone that saves parents in August. Tickets from about $27.", tip: "It's the best two indoor hours downtown when the daily 3pm storm rolls in.", bookQuery: "Florida Aquarium tickets" },
      { name: "Adventure Island", indoor: false, appQuery: "Adventure Island Tampa", blurb: "Busch Gardens' sister water park across the street: nine slides, a wave pool, and lazy rivers. It is the default local answer to a 95-degree day, and bundling it with Busch Gardens tickets cuts the price hard.", tip: "Gate price is about $80; the combo tickets and online rates are the only way locals pay.", bookQuery: "Adventure Island Tampa tickets" },
      { name: "Roasted's fruit-shaped ice cream", indoor: true, appQuery: "Roasted Temple Terrace", blurb: "The family-run Temple Terrace dessert shop that blew up on TikTok for hyper-realistic fruit-shaped ice creams — whole peaches and pineapples that are actually frozen desserts. A few dollars a piece and a short drive from Busch Gardens.", tip: "The fruit shapes sell out on weekends; weekday afternoons are the safe run." },
    ],
    faq: [
      { q: "What's actually new in Tampa this summer?", a: "ZooTampa's Florida Waters expansion with the manatee rescue center opened in March, Busch Gardens' lion and hyena habitat opened in spring, and the soft-serve margarita wave hit the bay's restaurants in May. All three are 2026 arrivals." },
      { q: "Is the Riverwalk doable in August heat?", a: "Early morning or evening, comfortably — it's flat and waterfront the whole way. Midday, break it up with the water taxi, the art museum, and the aquarium, all of which sit directly on the path." },
      { q: "Busch Gardens or Adventure Island in summer?", a: "August favors Adventure Island — waits are shorter and the water is the point. If you want both, the combo ticket is dramatically cheaper than two gates." },
    ],
    dealId: "cpn-citypass-tampa",
    dealCards: ["cpn-citypass-tampa", "cpn-clipp-fl-tampa", "cpn-partner-tampa-deal-adventure-island"],
  },

  "things-to-do-fort-lauderdale-summer-2026": {
    teaser: "The famous rotating rooftop is back after the luxury revamp, but the flagship brunch spot TikTok tracked for months is new on Las Olas this summer.",
    region: "Fort Lauderdale",
    title: "10 Best Things to Do in Fort Lauderdale This Summer (2026)",
    description: "Pier Sixty-Six's rotating rooftop, the world's first pickleball stadium, the Las Olas restaurant wave, and the water taxi: Fort Lauderdale's summer 2026.",
    keyword: "things to do in fort lauderdale this summer",
    updated: "2026-08-07",
    intro: "Fort Lauderdale's summer 2026 is a glow-up season: the Pier Sixty-Six resort reopened with its famous rotating rooftop, a riverfront park came back rebuilt, the world's first pickleball stadium opened, and Las Olas Boulevard is collecting the most-tracked restaurant openings in South Florida. The beach was already good.",
    picks: [
      { name: "Fort Lauderdale Beach and the reef offshore", indoor: false, appQuery: "Fort Lauderdale Beach", blurb: "The signature stretch of sand along A1A hides a real asset: a living coral reef starting about 300 feet offshore, plus 76-plus dive-able shipwrecks that earn the city its Shipwreck Capital title. The sand is free; the snorkeling is a cheap add.", tip: "Snorkel the reef at morning slack tide for the visibility; afternoon chop kills it.", bookQuery: "Fort Lauderdale snorkeling", viatorUrl: "https://www.viator.com/tours/Fort-Lauderdale/Guided-Snorkel-Tour/d660-415671P1" },
      { name: "The Water Taxi through the Venice of America", indoor: false, appQuery: null, blurb: "The hop-on hop-off boat runs the Intracoastal and New River past mega-yachts and mansions, doubling as transit and the city's best sightseeing for about $40 all day. A new stop comes online at the convention center's waterfront plaza this year.", tip: "Board at a quiet stop mid-afternoon for a seat on the bow rail; sunset runs fill first.", bookQuery: "Fort Lauderdale boat tour", viatorUrl: "https://www.viator.com/tours/Fort-Lauderdale/Family-Friendly-Boat-Cruise-and-Swim/d660-125185P4" },
      { name: "Pier Sixty-Six and the rotating Pier Top", indoor: true, appQuery: "Pier Sixty-Six Fort Lauderdale", blurb: "The 1960s icon reopened after a massive luxury revamp, and its revolving rooftop lounge is back: 360-degree views of the Intracoastal and ocean, one slow rotation at a time. It is the sunset cocktail reservation in town this year.", tip: "Book Pier Top days ahead for a table in the last hour of light — the rotation covers the full skyline in about 66 minutes." },
      { name: "Las Olas Boulevard's restaurant wave", indoor: true, appQuery: "Las Olas Boulevard", blurb: "The classic shopping strip is mid-glow-up, with this summer's openings led by Little Hen — the flower-drenched brunch spot food TikTok tracked for months before its 190-seat flagship landed — and Skinny Louie, the smash-burger name that blew up in Wynwood.", tip: "Little Hen brunch will book out weekends its first season; a weekday afternoon tea slot is the workaround." },
      { name: "The Fort, the world's first pickleball stadium", indoor: false, appQuery: null, blurb: "Fort Lauderdale just opened the world's first professional pickleball stadium: 43 tournament-level courts, now headquarters of the Association of Pickleball Players, plus a scratch-kitchen restaurant. Come to play, watch pros train, or just eat.", tip: "Open-play sessions are priced per person and beginners get grouped by level — you don't need a foursome." },
      { name: "Huizenga Park, rebuilt", indoor: false, appQuery: "Huizenga Park Fort Lauderdale", blurb: "Downtown's riverfront park reopened early this year after a full reimagining, anchored by Sweetwaters and its 3,500-square-foot riverfront patio, with free events running along the Riverwalk all season.", tip: "Friday evenings stack free programming on the lawn — check the Riverwalk calendar and build dinner around it." },
      { name: "An Everglades airboat morning", indoor: false, appQuery: null, blurb: "The classic day-trip: a high-speed airboat through the sawgrass with near-guaranteed gator sightings, about 30 minutes from the beach and roughly $30 to $40 for adults. It is the quintessential South Florida bucket item for a reason.", tip: "Book the first departure — gators are most active early, and the heat is civilized.", bookQuery: "Everglades airboat tour Fort Lauderdale" },
      { name: "Puttshack at Dania Beach", indoor: true, appQuery: "Dania Beach", blurb: "Newly opened tech-infused mini golf where the balls score themselves, wrapped in a full bar and upscale food. It's the buzzy rainy-afternoon and summer-night play in the Dania Beach entertainment district, around $15 to $25 a round.", tip: "Summer afternoon storms make walk-ins spike — book a tee time like it's real golf." },
      { name: "Peppi's Pizza after the One Bite review", indoor: true, appQuery: "Peppi's Pizza Fort Lauderdale", blurb: "The NY-style joint on Sunrise that got national attention from Dave Portnoy's One Bite review is the city's viral cheap eat this summer — $10 to $20 with maximum bragging rights.", tip: "Go off-peak; the review lines are real at dinner but gone by 3pm." },
      { name: "Las Olas Beach at sunrise", indoor: false, appQuery: "Las Olas Beach", blurb: "The livelier stretch where the bars sit across the street from the sand is also the best sunrise on this coast — flat light, empty beach, and coffee within a hundred yards when it's done.", tip: "Parking meters along A1A are cheapest before 9am, which is also when the beach is at its best in summer." },
    ],
    faq: [
      { q: "What's new in Fort Lauderdale this year?", a: "Pier Sixty-Six's reopening with the rotating Pier Top lounge, the rebuilt Huizenga Park, the world's first pickleball stadium, and a Las Olas restaurant wave led by Little Hen and Skinny Louie — 2026 is the city's biggest opening year in a while." },
      { q: "Is the water taxi worth it over a tour boat?", a: "For most visitors, yes — it covers the same mansion-and-yacht waterways as the tours, runs all day on one pass, and doubles as transport between the beach, Las Olas, and downtown." },
      { q: "Can you really snorkel from the beach?", a: "Yes — a living reef starts roughly 300 feet off the sand in swimmable depth. Calm mornings offer the best visibility; bring a dive flag, which Florida law requires." },
    ],
  },

  "things-to-do-key-west-summer-2026": {
    teaser: "The famous buoy is living at a temporary pocket park while its corner is rebuilt, but the new speakeasy is built into an Old Town bank vault.",
    region: "Key West",
    title: "10 Best Things to Do in Key West This Summer (2026)",
    description: "Mallory Square sunsets, reef snorkeling, the new Reserve with its carousel bar and vault speakeasy, and August's back-to-back festivals: Key West summer 2026.",
    keyword: "things to do in key west this summer",
    updated: "2026-08-07",
    intro: "Key West in summer is the locals' version of the island: hot, slow, cheaper than winter, and stacked with August festivals. This year adds a twist — the Southernmost Point buoy is living at a temporary pocket park while its corner is rebuilt, and the buzziest opening in years just took over an Old Town bank. Here's the island, ranked.",
    picks: [
      { name: "Mallory Square's sunset celebration", indoor: false, appQuery: "Mallory Square", blurb: "The nightly ritual: street performers, musicians, food carts, and a few hundred strangers facing west from the Gulf-front plaza. It's free, it's every evening, and it's still the anchor of any first visit.", tip: "Arrive 45 minutes before sundown for the performers' main sets; the crowd peaks at the sun and thins in minutes." },
      { name: "Snorkeling the continental US's only living reef", indoor: false, appQuery: null, blurb: "The Keys reef sits just offshore with turtles, rays, and tropical fish, and summer's calm, warm water is prime season. Half-day catamaran trips run constantly from the Historic Seaport at roughly $50 to $90 a head.", tip: "Book the morning trip: calmer water, better visibility, and the afternoon storm risk stays behind you.", bookQuery: "Key West snorkel catamaran", viatorUrl: "https://www.viator.com/tours/Key-West/Key-West-Snorkeling/d661-2642P8" },
      { name: "The Reserve, the new bank takeover", indoor: true, appQuery: "The Reserve Key West", blurb: "The buzziest opening of 2026: a culinary collective inside a converted Old Town bank at 510 Southard, with a rotating carousel bar in the 1950s midcentury room and The Vault — a speakeasy built into the original bank vault.", tip: "The Vault seats a handful; put your name in early evening and drink the carousel bar while you wait." },
      { name: "The Southernmost Point buoy, temporary edition", indoor: false, appQuery: "Southernmost Point", blurb: "The famous 90-miles-to-Cuba corner is closed for seawall reconstruction, and a full-scale 12-foot replica now stands at Duval Pocket Park at 1400 Duval. Photos with the relocated buoy became their own social moment this summer; the original corner targets late 2026.", tip: "The pocket park line is a fraction of the old corner's — mornings are effectively walk-up." },
      { name: "The Duval Street crawl", indoor: false, appQuery: "Duval Street", blurb: "The mile of shopping, galleries, and open-air bars from Sloppy Joe's south is where the island's festival street fairs and pub crawls all play out. Free to wander; the bar tab is your call.", tip: "Upper Duval near the pocket park is the gallery-and-quiet end; lower Duval is the party — pick your mile-half accordingly." },
      { name: "The Hemingway Home's six-toed cats", indoor: true, appQuery: "Ernest Hemingway Home and Museum", blurb: "Papa's house with the writing studio, the famous six-toed cats, and blessed air conditioning at peak heat. July's Hemingway Days brought a hundred look-alikes to Sloppy Joe's; the house itself is the year-round keeper.", tip: "The cats nap through midday — morning tours get them moving and beat the heat in the gardens.", bookQuery: "Hemingway Home Key West" },
      { name: "August's festival stack: Lobsterfest and Rum Fest", indoor: false, appQuery: null, blurb: "Back-to-back August festivals are the trending reason to come right now: Lobsterfest celebrates spiny lobster season's opening with a Duval street fair and pool parties, and Rum Fest follows with mojito parties and a grand tasting of 30-plus rum brands.", tip: "Lobster boils sell out before the street fair weekend — buy the dinner tickets when you book the room." },
      { name: "Fort Zachary Taylor's beach and fort", indoor: false, appQuery: "Fort Zachary Taylor State Park", blurb: "The Civil War-era fort shares the park with the island's best swimming and snorkel-from-shore beach. State park entry is a few dollars, and the tree line behind the sand is the island's best natural shade.", tip: "Snorkel the rocks at the beach's west end — it's the reef-fish show without a boat ticket." },
      { name: "Blue Heaven's pie under the bougainvillea", indoor: false, appQuery: "Blue Heaven Key West", blurb: "The Bahama Village institution: pecan pancakes, shrimp Benedict, roosters between the tables, and the towering meringue-piled Key lime pie that is one of the most-posted food shots on the island. Roughly $15 to $30 a plate.", tip: "The wait says an hour; the bar in the courtyard says have a drink and it's twenty minutes." },
      { name: "Papa's Pilar rum distillery", indoor: true, appQuery: "Papa's Pilar Distillery", blurb: "The Hemingway-named distillery runs tours fresh off a Rum Producer of the Year win, and pairs neatly with Fishwife, the Bahamian seafood spot that opened early this year to real local buzz.", tip: "The tour's tasting pours are generous — make it the afternoon plan, not the pre-drive one.", bookQuery: "Key West rum distillery tour" },
    ],
    faq: [
      { q: "Is Key West worth it in August?", a: "For the right traveler, it's the best month: hotel rates drop hard, the water is calm for the reef, and Lobsterfest and Rum Fest stack back-to-back. The trades: real heat, and it's the heart of hurricane season, so buy refundable rooms." },
      { q: "Where is the Southernmost Point buoy right now?", a: "A full-scale replica stands at Duval Pocket Park, 1400 Duval Street, while the original corner at South and Whitehead is rebuilt behind a fence — reopening is targeted for late 2026." },
      { q: "Do I need a car in Key West?", a: "No — Old Town is walkable and bikes cover the rest of the island. If you drive down, park the car once; the lots near Duval charge resort prices by the hour." },
    ],
  },

  "things-to-do-st-augustine-summer-2026": {
    teaser: "The nation's oldest city turns 461 the same year the country turns 250, and the ghost tours only start after the heat breaks.",
    region: "St. Augustine",
    title: "10 Best Things to Do in St. Augustine This Summer (2026)",
    description: "Castillo de San Marcos, the amphitheater ranked first in the country, ghost tours after dark, and the America 250 season: St. Augustine's summer 2026.",
    keyword: "things to do in st augustine this summer",
    updated: "2026-08-07",
    intro: "St. Augustine is having a national moment: the amphitheater was just ranked first in the country, the travel press keeps handing the city best-of titles, and America's 250th birthday season lands in the nation's oldest city — which turns 461 this September. Summer here works on one rule: history in the morning, water in the afternoon, ghosts after dark.",
    picks: [
      { name: "Castillo de San Marcos", indoor: false, appQuery: "Castillo de San Marcos", blurb: "The 1600s Spanish coquina fortress on Matanzas Bay anchors every trip: cannon-fire demonstrations, rampart views, and stone that has outlasted every flag flown over it. Adult entry runs about $15 and kids are free.", tip: "The cannon crews fire on a posted schedule Friday through Sunday — check the day's times at the gate and plan around one." },
      { name: "St. George Street and the old town", indoor: false, appQuery: "St. George Street", blurb: "The pedestrian spine of the historic district: boutiques, courtyard bars, the Oldest Wooden Schoolhouse, and Aviles Street — billed as the country's oldest — one block over. The city was just named among the most walkable in the US.", tip: "Evening is the move in summer: the day-trip crowds leave by five and the courtyard bars open their gates." },
      { name: "A show at the number-one amphitheater in America", indoor: false, appQuery: "St. Augustine Amphitheatre", blurb: "Pollstar ranked The Amp first in the US this year, and Garden and Gun crowned St. Augustine the South's best music town — a real 2026 storyline. Between headliners, Colonial Oak Music Park runs free sets downtown.", tip: "Amp lawn tickets plus a rented chair beat mid-tier reserved seats for summer shows; the sightlines are honest everywhere." },
      { name: "The Alligator Farm's zip line", indoor: false, appQuery: "St. Augustine Alligator Farm", blurb: "The 130-year-old park houses every crocodilian species on earth, and the Crocodile Crossing zip line sends you directly over the alligator pools — which is exactly why it's all over everyone's feeds. Admission about $35, zip line extra.", tip: "The wading-bird rookery along the boardwalk is a photographer's dream in early summer — bring the long lens.", bookQuery: "St Augustine Alligator Farm tickets" },
      { name: "Ghost tours after dark", indoor: false, appQuery: null, blurb: "America's oldest city leans hard into its haunted reputation, and the walking, trolley, and pub versions all run after the heat breaks — the Old Jail, the lighthouse lore, and four centuries of material. Tours run about $20 to $55.", tip: "Book the latest walking tour on offer: cooler streets, darker corners, and the guides save their best stories for the small groups.", bookQuery: "St Augustine ghost tour" },
      { name: "The Drunken Horse", indoor: true, appQuery: "The Drunken Horse St. Augustine", blurb: "The Saint-Tropez-inspired French wine bar on Charlotte Street became the city's social-media darling: duck confit, serious pours, and an al fresco patio that fills every feed. It's also a stop on a wine tour voted first in the world on TripAdvisor.", tip: "Doors open at 4pm and the patio goes first — walk in at open or book; the beef bourguignon is the regulars' order." },
      { name: "A food and wine tour through the old city", indoor: true, appQuery: null, blurb: "The food-tour scene is having a moment: the city's wine, cocktail and food experience ranks in the top ten nationally at about $159 and sells out, with the Corks and Forks pairing tour close behind. The Floridian's new location opened in June for the DIY version.", tip: "Tours sell out a week-plus ahead in summer — book before you drive in, not after.", bookQuery: "St Augustine food tour" },
      { name: "Anastasia State Park", indoor: false, appQuery: "Anastasia State Park", blurb: "Miles of white sand just over the Bridge of Lions, with dunes, a tidal lagoon, and kayak rentals — about $8 a vehicle. This coastline is why the travel press keeps calling St. Augustine the coolest southern beach town going.", tip: "The beach north of the ramp loses the crowd within a five-minute walk; the lagoon side is the calm-water option for kids." },
      { name: "The crab-boil giants: Outback Crab Shack and Crabby's", indoor: true, appQuery: "Outback Crab Shack", blurb: "Two casual seafood spots blowing up this summer: Outback Crab Shack on the St. Johns, famous for enormous low-country platters dumped table-side off its long river dock, and Crabby's Beachside near the pier. Moderate prices, real waits at peak.", tip: "Outback's platters feed more people than the menu admits — order for two-thirds of your table." },
      { name: "Founder's Day and the America 250 season", indoor: false, appQuery: null, blurb: "This is a once-in-a-generation year to visit: the city layers its 461st birthday onto the nation's 250th, capped by the free Founder's Day landing reenactment at Mission Nombre de Dios on September 12 with cannon and musket demonstrations.", tip: "The landing reenactment is free and unticketed — arrive early for the waterfront side, where the boats come in." },
    ],
    faq: [
      { q: "Is St. Augustine walkable in summer heat?", a: "The historic district is compact and genuinely walkable — the trick is timing. Mornings and evenings on foot, the hottest hours in museums, the fort, or on the water, and the ghost tours after dark." },
      { q: "What makes 2026 special here?", a: "The amphitheater's number-one national ranking, a wave of best-of press, and the America 250 semiquincentennial layered onto the city's own 461st birthday — with Founder's Day on September 12 as the capstone." },
      { q: "Which beach should I pick?", a: "Anastasia State Park for the day trip — dunes, a lagoon, and space to spread out for about $8 a car. St. Augustine Beach proper has the pier, restaurants, and easier free parking." },
    ],
  },

  "things-to-do-daytona-beach-summer-2026": {
    teaser: "You can still drive on the sand, the dog beach is new this year, and the season ends with a night race that decides the playoffs.",
    region: "Daytona Beach",
    title: "10 Best Things to Do in Daytona Beach This Summer (2026)",
    description: "Driving on the World's Most Famous Beach, the new dog beach, the Coke Zero Sugar 400 night race, and the boardwalk at night: Daytona's summer 2026.",
    keyword: "things to do in daytona beach this summer",
    updated: "2026-08-07",
    intro: "Daytona's pitch hasn't changed in a century — 23 miles of hard-packed sand you can drive on — but 2026 sharpened it: a new dog beach opened, the historic ballpark finished its renovation, and the summer ends with a Saturday night race that decides NASCAR's playoff field. Here's the season, ranked.",
    picks: [
      { name: "Driving the World's Most Famous Beach", indoor: false, appQuery: "Daytona Beach", blurb: "One of the only places in America where you drive onto the sand, park at the water, and build the day from the tailgate — 23 miles of it, with a modest daily beach-driving toll in the marked zones. New this year: a 1.7-mile dog beach between Williams Avenue and Seabreeze Boulevard.", tip: "Sand traffic follows the tide — the driving lanes are widest and firmest in the two hours either side of low tide." },
      { name: "Daytona International Speedway", indoor: false, appQuery: "Daytona International Speedway", blurb: "The World Center of Racing runs daily tram tours with Victory Lane photo stops year-round, and thrill-seekers can book the Richard Petty Driving Experience to ride or drive a real stock car.", tip: "The full tour beats the short one for one reason: the 31-degree banking, which no TV camera has ever made look as steep as it is.", bookQuery: "Daytona Speedway tour" },
      { name: "The Coke Zero Sugar 400 under the lights", indoor: false, appQuery: null, blurb: "August 28–29 the Cup Series regular season ends here, at night, with playoff spots decided on the last lap of the last race. It is the most consequential summer date on the calendar and the best atmosphere at the track outside the 500.", tip: "Backstretch seats are the value buy for the night race — the lights and the draft show read best from there." },
      { name: "The boardwalk and pier at night", indoor: false, appQuery: "Daytona Beach Boardwalk", blurb: "The old-Florida amusement strip — arcades, rides, and the 1,000-foot pier — turns on its neon after dark, and the shot framed under the pier's pilings is on the visitors bureau's own must-capture list. Free to stroll, rides à la carte.", tip: "Joe's Crab Shack at the pier's end is tourist-priced, but a drink on its deck buys the best over-the-Atlantic view on the strip." },
      { name: "Ponce Inlet Lighthouse", indoor: false, appQuery: "Ponce Inlet Lighthouse", blurb: "Florida's tallest lighthouse: 203 steps, 360-degree views over the Atlantic and inlet, and a maritime museum at the base — with the Marine Science Center's sea-turtle rehab next door. Modest admission.", tip: "Climb before 11am: the tower stairwell is unconditioned and afternoon heat inside it is real." },
      { name: "Free concerts at the Bandshell", indoor: false, appQuery: "Daytona Beach Bandshell", blurb: "The historic coquina Bandshell runs its famous free summer series on weekends, with fireworks over the beach after the shows. Bring a chair; the tradition is the point.", tip: "Locals set chairs by late afternoon for headline nights — claim turf, then walk the boardwalk until showtime." },
      { name: "A Tortugas game at Jackie Robinson Ballpark", indoor: false, appQuery: "Jackie Robinson Ballpark", blurb: "The ballpark where Jackie Robinson broke baseball's color barrier in spring training just finished a major renovation, and a minor-league Tortugas summer night here costs single-A prices in a setting drenched in history.", tip: "Sit third-base side for the sunset over the Halifax River — the renovation kept the old grandstand's view intact." },
      { name: "Crabby Joe's on Sunglow Pier", indoor: true, appQuery: "Crabby Joe's Deck and Grill", blurb: "The deck-and-dive seafood joint perched directly over the Atlantic on a wooden pier in Daytona Beach Shores — you eat above the waves while surfers work the break below. Mains roughly $15 to $25, and the dine-over-the-ocean clips circulate constantly.", tip: "Breakfast on the deck is the sleeper: same over-the-water tables, no wait, surfer show included." },
      { name: "The Fairchild Oak and the content circuit", indoor: false, appQuery: "Bulow Creek State Park", blurb: "The creators' loop: Atlantic sunrise on the sand, the county's red-and-yellow lifeguard towers, and the 400-plus-year-old Fairchild Oak draped in Spanish moss at Bulow Creek State Park in Ormond Beach — a genuine pilgrimage tree. All free or nearly.", tip: "Shoot the oak in early light when the moss catches it; by midday the canopy goes flat and the mosquitoes clock in." },
      { name: "Daytona Lagoon and the revamped Ocean Center district", indoor: false, appQuery: "Daytona Lagoon", blurb: "The waterpark — slides, lazy river, go-karts — anchors an entertainment district mid-glow-up: the Ocean Center finishes a $40 million renovation this year and the WPA-era Main Street Arch was just restored. New JetBlue nonstops from JFK and Boston make the trip easier too.", tip: "Lagoon afternoons after 3pm often carry twilight pricing in summer — check before paying the morning rate." },
    ],
    faq: [
      { q: "Can you still drive on Daytona Beach?", a: "Yes — in designated zones during daylight hours for a modest daily toll, tide permitting. It remains one of the only beaches in America where this is legal, and it's the town's signature experience." },
      { q: "When is the NASCAR race this summer?", a: "The Coke Zero Sugar 400 runs August 28–29, 2026, as the Cup Series regular-season finale — a Saturday night race under the lights where the playoff field is decided." },
      { q: "Is Daytona good for families beyond the beach?", a: "Genuinely: the lighthouse climb, the sea-turtle rehab at the Marine Science Center, free Bandshell concerts with fireworks, minor-league baseball at Jackie Robinson Ballpark, and the Lagoon waterpark cover a week without repeating a day." },
    ],
  },

  "things-to-do-panama-city-beach-summer-2026": {
    teaser: "The undeveloped island across the pass is only reachable by boat, and the new district around Topgolf is why Pier Park feels new this year.",
    region: "Panama City Beach",
    title: "10 Best Things to Do in Panama City Beach This Summer (2026)",
    description: "Shell Island by boat, 27 miles of sugar-white sand, Pirates Voyage, Topgolf and the new Pier Park City Center: Panama City Beach's summer 2026, ranked.",
    keyword: "things to do in panama city beach this summer",
    updated: "2026-08-07",
    intro: "Panama City Beach runs on two speeds: 27 miles of sugar-white sand and emerald Gulf water on one side, and a growing entertainment district on the other — anchored this year by the new Pier Park City Center with Topgolf as its first tenant. The undeveloped island across the pass is still the best thing here, and it's only reachable by boat.",
    picks: [
      { name: "Shell Island", indoor: false, appQuery: "Shell Island Panama City Beach", blurb: "Seven undeveloped miles of barrier island between the Gulf and St. Andrew Bay, reachable only by boat — the shuttle from St. Andrews State Park, a pontoon rental, or a snorkel-and-dolphin catamaran. Wild dolphins, real shelling, and water that looks edited.", tip: "Take the first shuttle over and the mid-afternoon back: morning owns the shelling and the dolphins, and there's zero shade for the peak hours.", bookQuery: "Shell Island dolphin snorkel cruise", viatorUrl: "https://www.viator.com/tours/Panama-City-Beach/Shell-Island-Snorkel-Dolphin-Catamaran-Cruise-in-Panama-City-Beach/d22828-64698P2" },
      { name: "The 27 miles of sugar-white beach", indoor: false, appQuery: "Panama City Beach", blurb: "Consistently ranked among the country's best shorelines, with free public accesses along the whole strip and the Russell-Fields pier at its center. The sand is quartz-white, the water emerald, and none of it costs anything.", tip: "Flag rules are law here — double red means the Gulf is closed, and the fine is real. Check the flag before you commit the cooler." },
      { name: "St. Andrews State Park and the Jetties", indoor: false, appQuery: "St. Andrews State Park", blurb: "Twelve hundred protected acres at the strip's east end, with the area's best easy snorkeling at the Jetties, a kid-friendly tidal pool, fishing piers, and the Shell Island shuttle dock. The old-Florida counterweight to the condo towers.", tip: "The Jetties' fish show peaks on incoming tide; check the tide chart and snorkel the two hours before high." },
      { name: "Pirates Voyage Dinner and Show", indoor: true, appQuery: "Pirates Voyage Panama City Beach", blurb: "Dolly Parton's indoor dinner theater at Pier Park is in its second season and is the hottest family ticket in town: pirates dueling and diving around a 15-foot-deep indoor lagoon while a four-course feast lands in front of you.", tip: "It's also the town's best rainy-afternoon insurance — book the early show and keep the evening for the beach.", bookQuery: "Pirates Voyage Panama City Beach tickets" },
      { name: "Topgolf and the new Pier Park City Center", indoor: false, appQuery: "Topgolf Panama City Beach", blurb: "Topgolf opened as the first tenant of the new 80-acre Pier Park City Center district: 74 climate-controlled bays, a full bar and restaurant, and more family concepts building out around it. It's a big part of why the Pier Park area feels new this year.", tip: "Bays are pay-per-hour and split six ways — the per-person math beats most of the strip's attractions." },
      { name: "Pier Park and the SkyWheel", indoor: false, appQuery: "Pier Park", blurb: "The 120-store open-air hub is PCB's de facto downtown, and the 200-foot SkyWheel's climate-controlled gondolas deliver the panoramic Gulf photo everyone posts. The Bonny Read Fun Park — go-karts, arcade, mini golf — is in development next door.", tip: "Ride the SkyWheel in the last daylight slot: sunset over the Gulf on the way up, the lit-up strip on the way down." },
      { name: "A dolphin cruise from the marinas", indoor: false, appQuery: null, blurb: "Wild bottlenose dolphins are close to guaranteed here, whether by the Sea Screamer speedboat, the pirate-ship cruise the kids vote for, or a quieter eco-tour toward the island. Conservation-minded operators are the fastest-growing segment this year.", tip: "Sunset departures see the same dolphins with half the boat traffic — and the Gulf light does the marketing for you.", bookQuery: "Panama City Beach dolphin cruise" },
      { name: "Shipwreck Island Waterpark", indoor: false, appQuery: "Shipwreck Island Waterpark", blurb: "The tropical-themed waterpark — wave pool, lazy river, big slides — runs seasonally April through August, which is to say it exists exactly for this trip. The default cool-down when the Gulf goes double-red or the sand hits noon temperature.", tip: "It closes for the season in late August; going early in your week leaves a re-ride day if the kids demand it." },
      { name: "The TikTok food crawl: Boondocks and Coco Loco", indoor: true, appQuery: "Boondocks Panama City Beach", blurb: "PCB's food scene is doing numbers this year: waterfront seafood dive Boondocks and the over-the-top tropical drinks at Coco Loco both carry dedicated trending pages, alongside a wave of hidden-spots-to-eat videos pushing visitors off the main strip. Cheap to moderate.", tip: "Boondocks sits on the lagoon side — time dinner to sunset over the water and the video shoots itself." },
      { name: "Free concerts at Aaron Bessant Park", indoor: false, appQuery: "Aaron Bessant Park", blurb: "The amphitheater lawn next to Pier Park runs free weekly summer concerts, with the big ticketed festivals — Gulf Coast Jam, the jazz festival — bookending the season. Beach all day, live music at sunset, zero dollars.", tip: "Locals bring low-back chairs and coolers; the lawn's back half stays loose even when the front fills." },
    ],
    faq: [
      { q: "How do you get to Shell Island?", a: "By boat only: the Shell Island Shuttle from St. Andrews State Park is the budget route, pontoon rentals give you the day on your terms, and snorkel-and-dolphin catamarans bundle the crossing with the wildlife. There are no facilities on the island — carry in, carry out." },
      { q: "What do the beach flags mean?", a: "Green is calm, yellow is caution, single red is high surf or currents, double red closes the water entirely — swimming then is illegal and fined. Purple flags mean dangerous marine life. Flags fly at the piers and public accesses." },
      { q: "What's new at Pier Park this year?", a: "The Pier Park City Center district is building out with Topgolf open as its anchor, Pirates Voyage is in its second season, and the Bonny Read Fun Park is in development — the area around the pier is turning into a real second evening beyond the beach." },
    ],
  },

  "things-to-do-st-petersburg-clearwater-summer-2026": {
    teaser: "The nightly Pier 60 sunset festival is free, but the clearest water in the area is on an island with no roads and a ferry line.",
    region: "St. Petersburg",
    title: "10 Best Things to Do in St. Pete and Clearwater This Summer (2026)",
    description: "Clearwater Beach and Pier 60, the Dalí Museum, Caladesi Island's roadless sand, the new Central Park food hall, and shuffleboard Fridays: summer 2026 ranked.",
    keyword: "things to do in st petersburg clearwater this summer",
    updated: "2026-08-07",
    intro: "St. Pete and Clearwater split the job: Clearwater brings the country's most-decorated beach and a nightly sunset festival, St. Pete brings the Dalí, a downtown food scene in full sprint, and the world's oldest shuffleboard club. The clearest water in the area, though, is on an island with no roads. Here's the summer, ranked.",
    picks: [
      { name: "Clearwater Beach and the Pier 60 sunset festival", indoor: false, appQuery: "Clearwater Beach", blurb: "The perennial best-beach contender: powder sand, bathtub-warm Gulf shallows, and a free nightly sunset celebration at Pier 60 with street performers and vendors. This summer it's all over social feeds again, aesthetic edits and all.", tip: "Strolling the pier is free; the fishing deck costs $8 a day. Parking evaporates by 10am on weekends — arrive early or ride the Jolley Trolley." },
      { name: "The Dalí Museum", indoor: true, appQuery: "The Dalí Museum", blurb: "The largest surrealist collection outside Spain — 2,400-plus works — inside the building with the famous geodesic glass bubble. A $65 million expansion is underway toward 2028, and the museum stays fully open through it, immersive dome included.", tip: "The free-with-admission architecture tour explains the bubble; take it before the galleries and the building reads differently.", bookQuery: "Dali Museum tickets" },
      { name: "Caladesi Island by ferry", indoor: false, appQuery: "Caladesi Island State Park", blurb: "A roadless barrier island with some of the clearest water on this coast, reachable only by the Honeymoon Island ferry or kayak — the no-crowds island the videos keep rediscovering. Same sand as Clearwater, a fraction of the people.", tip: "The ferry line builds by mid-morning in summer; the first boats over get the shelling and the empty sandbars." },
      { name: "The St. Pete Pier district", indoor: false, appQuery: "St. Pete Pier", blurb: "The 26-acre modern pier is downtown's living room: a beach, splash pad, rooftop tiki bar, marketplace, and lawn — free to wander end to end. Perry's Porch is the district's new waterfront restaurant doing old-Florida coastal fare.", tip: "The splash pad plus the pier's beach make it the easiest free kid afternoon downtown; evenings, the tiki bar's sunset line forms early." },
      { name: "Central Park, the new five-story food hall", indoor: true, appQuery: null, blurb: "Downtown St. Pete's buzziest 2026 opening: a five-story food hall stacking international vendors under one roof, with more restaurants and a rooftop still coming online. The single easiest way to sample the city's exploding food scene.", tip: "Floors fill top-down at dinner; lunch is walk-up easy on every level." },
      { name: "Clearwater Marine Aquarium", indoor: true, appQuery: "Clearwater Marine Aquarium", blurb: "The working rescue-rehab-release facility made famous by Winter the dolphin is leaning into manatees: an expansion around a manatee rehabilitation habitat was just announced, and three new patients arrived this year. Watching active rescue is the difference from a standard aquarium.", tip: "Feedings and care sessions run on a posted daily schedule — check it at entry and route the visit around one.", bookQuery: "Clearwater Marine Aquarium tickets" },
      { name: "Sunken Gardens", indoor: false, appQuery: "Sunken Gardens", blurb: "St. Pete's hundred-year-old tropical garden hides waterfalls, rainbow eucalyptus, and a flock of Chilean flamingos that own the local feeds. City-park-cheap admission for four acres that photograph like a private botanical estate.", tip: "The flamingos are most active at morning feeding; the shaded paths make this one of the few outdoor summer picks that works at noon." },
      { name: "Fort De Soto Park", indoor: false, appQuery: "Fort De Soto Park", blurb: "Five connected islands with quiet Gulf beaches, a historic fort, kayak trails, and a campground regularly called one of Florida's best. It's where locals go when Clearwater gets slammed, for the price of a small parking fee.", tip: "North Beach's lagoon is the calm, shallow, kid-perfect water; the fort's top level is the sunset spot with a fraction of Pier 60's crowd." },
      { name: "St. Pete's new fine-dining wave", indoor: true, appQuery: "The Vinoy Resort", blurb: "The renovated Vinoy now houses Elliott Aster under a Michelin-starred-background chef, and Chris Ponte's Olivia was just named the area's best new restaurant. The budget play: the Oyster Bar's two-dollar-oyster hour, four to five daily.", tip: "Elliott Aster books out weekends; bar seating holds a nightly walk-in allotment the dining room doesn't." },
      { name: "Shuffleboard Fridays at the world's oldest club", indoor: false, appQuery: "St. Petersburg Shuffleboard Club", blurb: "The world's oldest and largest shuffleboard club — founded 1924, 74 courts — throws free public play every Friday night, volunteers teaching newcomers, suggested two-dollar donation. The quirky retro-Florida night out that shows up in every only-in-St.-Pete reel.", tip: "Courts open at 7pm and the regulars adopt beginners fast — show up by 7:15 and you'll be mid-match by 7:30." },
    ],
    faq: [
      { q: "Clearwater Beach or Caladesi Island?", a: "Clearwater for the full-service classic — restaurants, Pier 60's nightly festival, lifeguards. Caladesi for the same white sand with no roads, no buildings, and clearer water, at the cost of a ferry ride and carrying your own shade." },
      { q: "Is the Dalí Museum open during its expansion?", a: "Fully — the $65 million expansion is under construction toward a 2028 completion, and the galleries, immersive dome experience, and waterfront grounds all stay open throughout." },
      { q: "What's free here?", a: "A lot: the Pier 60 sunset festival every night, the entire St. Pete Pier district, Friday night shuffleboard at the world's oldest club, and the murals of the Central Arts District. Fort De Soto is nearly free at a few dollars' parking." },
    ],
  },

  "things-to-do-naples-summer-2026": {
    teaser: "The pier is a construction zone until next year, which moved the sunset ritual to the sand below it and the boats out of Tin City.",
    region: "Naples",
    title: "10 Best Things to Do in Naples This Summer (2026)",
    description: "Sunsets without the pier, Keewaydin Island by boat, ghost orchid season in the swamps, the Perry Hotel's rooftop, and summer dining deals: Naples 2026.",
    keyword: "things to do in naples florida this summer",
    updated: "2026-08-07",
    intro: "Naples in summer is the insider season: the winter crowds are gone, Fifth Avenue runs prix fixe deals, and the Gulf sunset shows up nightly regardless. One honest caveat this year — the pier is a construction zone until mid-2027, so the ritual moved to the sand below it and the sunset cruises out of Tin City. Here's the summer, ranked.",
    picks: [
      { name: "The Naples Beach sunset, pier or no pier", indoor: false, appQuery: "Naples Beach", blurb: "The nightly Gulf sunset is still the city's signature ritual, but know before you go: the hurricane-damaged pier is fenced off mid-rebuild — a $26 million project targeting mid-2027 — so set up on the sand at 12th Avenue South below the old pier site, or at Lowdermilk Park up the beach.", tip: "The crowd still gathers at 12th Avenue out of habit; Lowdermilk has parking, restrooms, and the same sun." },
      { name: "Keewaydin Island by boat", indoor: false, appQuery: "Keewaydin Island", blurb: "The boat-access-only barrier island between Naples and Marco keeps going viral as the rare beach where you escape the crowds: clear water, empty white sand, and a burger boat that pulls up to the sandbar on busy weekends.", tip: "Flag down the food boat when it idles past the sandbar — cash speeds the line.", bookQuery: "Keewaydin Island boat tour", viatorUrl: "https://www.viator.com/tours/Naples/Beach-Island-Shelling-Cruise-to-Keewaydin-Island/d22381-172638P3" },
      { name: "Fifth Avenue South on summer deals", indoor: false, appQuery: "Fifth Avenue South", blurb: "The palm-lined dining and gallery strip is at its most approachable in summer, when the restaurants roll out off-season prix fixe and two-for-one specials and Evenings on Fifth brings live music and open galleries — August 13 is the season's last one.", tip: "Cap it with sunset cocktails at Limón, the Mediterranean rooftop atop the AC Hotel on Fifth." },
      { name: "An Everglades airboat in ghost orchid season", indoor: false, appQuery: null, blurb: "Airboating the mangrove backcountry is the classic Naples-adjacent thrill, and this year carries a bonus: peak ghost orchid bloom runs June through October at Corkscrew Swamp, Fakahatchee Strand, and Big Cypress — one of the rarest flowers in America, in season right now. Tours roughly $40 to $90.", tip: "Go at first departure: gators up, heat down, and the backcountry light is the whole show.", bookQuery: "Everglades airboat tour Naples" },
      { name: "Corkscrew Swamp Sanctuary's boardwalk", indoor: false, appQuery: "Corkscrew Swamp Sanctuary", blurb: "The Audubon sanctuary's elevated boardwalk runs through old-growth cypress where the ghost orchids actually bloom — admission about $17, binoculars essential, and nighttime boardwalk walks on the summer calendar.", tip: "Ask at the desk where the ghost orchid is currently visible from the boardwalk; volunteers keep a scope on it in bloom." },
      { name: "Tigress at The Perry Hotel", indoor: true, appQuery: "The Perry Hotel Naples", blurb: "The buzziest table in town this summer: Cantonese-inspired cooking from James Beard nominee Dale Talde at the splashy new Perry Hotel, with a rooftop bar named among the season's best. Entrées run about $25 to $60.", tip: "The rooftop takes walk-ins that the dining room won't — sunset drinks first, then decide." },
      { name: "Clam Pass Park's mangrove boardwalk", indoor: false, appQuery: "Clam Pass Park", blurb: "A three-quarter-mile boardwalk winds through a mangrove tunnel — free tram included — before opening onto a beach one viral clip with 2.4 million views called one of the prettiest in Florida. Parking about $10.", tip: "Summer's negative low tides are prime shelling on this stretch; check the tide chart and walk out on the minus tide." },
      { name: "Naples Botanical Garden", indoor: false, appQuery: "Naples Botanical Garden", blurb: "A hundred and seventy acres of Brazilian, Caribbean, and Asian gardens that stay lush all summer, with concert nights and food events on the seasonal calendar. Admission about $25.", tip: "Locals treat the first hour after open as the heat hack — the shade gardens hold the morning cool." },
      { name: "An FC Naples match night", indoor: false, appQuery: "Paradise Coast Sports Complex", blurb: "Southwest Florida's pro soccer club is the town's best cheap night out: summer home dates through August at the Paradise Coast Sports Complex, whose stadium doubles as a lawn party with food and drinks. Tickets roughly $15 to $40.", tip: "The August 5 and August 26 home dates are the last of the summer slate — the lawn berm is the family move." },
      { name: "A sunset cruise from Tin City", indoor: false, appQuery: "Tin City Naples", blurb: "With the pier fenced, the boats own the sunset: dinner cruises, sightseeing runs, and laid-back tiki boats all depart Tin City and Crayton Cove, with dolphins riding the wake most evenings. Cruises run about $40 to $75.", tip: "Pair it with the Turtle Club — the only restaurant directly on Naples sand — for the sunset-dinner double.", bookQuery: "Naples Florida sunset cruise" },
    ],
    faq: [
      { q: "Is the Naples Pier open?", a: "No — it's fenced off for a roughly $26 million rebuild that broke ground in January 2026, with reopening targeted for mid-2027. The beach on either side is fully open, and the sunset ritual has moved to the sand and the Tin City sunset cruises." },
      { q: "What is ghost orchid season?", a: "June through October, when one of America's rarest flowers blooms in the swamps east of Naples — Corkscrew Swamp Sanctuary, Fakahatchee Strand, and Big Cypress. Corkscrew's boardwalk is the accessible way to see one; volunteers usually have a scope trained on the bloom." },
      { q: "Is Naples dead in summer?", a: "Quiet, not dead — and that's the appeal: the restaurants run genuine specials, Fifth Avenue is walkable at dinner, and the beaches empty out. Book patios for evenings and boats for mornings; the 3pm storm is near-daily and brief." },
    ],
  },
};
