// Every published guide owns a reviewed hero record. The page and guide index
// consume the same object so artwork, accessible text, and rights attribution cannot drift.
const NEUTRAL_HERO = "/brand/opt/hero-1600.webp";

const NEUTRAL_GUIDE_HERO = Object.freeze({
  src: NEUTRAL_HERO,
  alt: "Florida coastline at golden hour",
  caption: "Wayfind’s neutral Florida planning artwork.",
  credit: "Wayfind editorial",
  source: "/brand/README.md",
  license: "Wayfind repository asset",
  position: "50% 50%",
  width: 1600,
  height: 1066,
});

export const GUIDE_HERO_ART = Object.freeze({
  "swim-with-manatees-crystal-river": Object.freeze({"src":"/guides/unsplash/manatee-maegan-luckiesh.webp","alt":"Manatee swimming in clear blue water","caption":"A manatee underwater. This stock photograph was made in Belize; Crystal River is not pictured.","credit":"Maegan Luckiesh","source":"https://unsplash.com/photos/gray-sea-cow-under-water-UDdt74azlig","license":"Unsplash License","position":"50% 45%","width":1600,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "bioluminescence-kayak-tour-space-coast": Object.freeze({"src":"/guides/unsplash/florida-kayaking-eric-tompkins.webp","alt":"Kayakers paddling a tree-lined clear Florida river","caption":"Silver Springs kayaking in daylight. Bioluminescent glow is not pictured.","credit":"Eric Tompkins","source":"https://unsplash.com/photos/people-kayaking-on-river-6tNqzypQE78","license":"Unsplash License","position":"50% 52%","width":1600,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "florida-scalloping-crystal-river-homosassa": Object.freeze({"src":"/guides/unsplash/snorkel-jc-falcon.webp","alt":"Woman wearing a diving mask and snorkel in shallow water","caption":"Mask and snorkel preparation for a day on the water. Illustrative photograph, not a documented Nature Coast scalloping trip.","credit":"JC Falcon","source":"https://unsplash.com/photos/woman-wearing-black-diving-goggles-and-snorkel-GRQLq31v6Oo","license":"Unsplash License","position":"50% 50%","width":1200,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "weeki-wachee-kayak-mermaids-guide": Object.freeze({"src":"/guides/unsplash/florida-kayaking-eric-tompkins.webp","alt":"Kayakers paddling a tree-lined clear Florida river","caption":"Silver Springs kayaking. Weeki Wachee is not pictured.","credit":"Eric Tompkins","source":"https://unsplash.com/photos/people-kayaking-on-river-6tNqzypQE78","license":"Unsplash License","position":"50% 52%","width":1600,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "winter-park-scenic-boat-tour": Object.freeze({"src":"/guides/unsplash/winter-park-eric-ardito.webp","alt":"Tree-lined brick street with restaurants in Winter Park, Florida","caption":"Winter Park’s streetscape, for the walk and meal around a boat-tour outing. The boat tour itself is not pictured.","credit":"Eric Ardito","source":"https://unsplash.com/photos/a-city-street-filled-with-lots-of-traffic-iQWQUxzMvjw","license":"Unsplash License","position":"50% 50%","width":1200,"height":960,"licenseUrl":"https://unsplash.com/license"}),
  "siesta-key-drum-circle": Object.freeze({"src":"/guides/unsplash/sarasota-sunset-nathan-mullet.webp","alt":"Wooden lifeguard tower on a Sarasota beach at sunset","caption":"A Sarasota beach at sunset sets the scene. The Siesta Key drum circle itself is not pictured.","credit":"Nathan Mullet","source":"https://unsplash.com/photos/v0ipCnvovM0","license":"Unsplash License","position":"50% 53%","width":872,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "pinecraft-sarasota-amish-village": Object.freeze({"src":"/guides/unsplash/pie-kyrie-isaac.webp","alt":"Lattice-top fruit pie on a rustic wooden table","caption":"A homemade-style pie provides food context for Pinecraft. No local restaurant or bakery is pictured.","credit":"Kyrie Isaac","source":"https://unsplash.com/photos/a-pie-sitting-on-top-of-a-wooden-table-piHImUfRI4E","license":"Unsplash License","position":"50% 50%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "siesta-key-vs-lido-key": Object.freeze({"src":"/guides/unsplash/sarasota-sunset-nathan-mullet.webp","alt":"Wooden lifeguard tower on a Sarasota beach at sunset","caption":"Sarasota’s Gulf shoreline introduces this beach comparison. Neither named beach is identified in the photograph.","credit":"Nathan Mullet","source":"https://unsplash.com/photos/v0ipCnvovM0","license":"Unsplash License","position":"50% 53%","width":872,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-sarasota": Object.freeze({"src":"/guides/unsplash/sarasota-sunset-nathan-mullet.webp","alt":"Wooden lifeguard tower on a Sarasota beach at sunset","caption":"Sarasota’s Gulf shoreline at sunset.","credit":"Nathan Mullet","source":"https://unsplash.com/photos/v0ipCnvovM0","license":"Unsplash License","position":"50% 53%","width":872,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "best-cuban-sandwich-tampa": Object.freeze({"src":"/guides/unsplash/ybor-city-ikuna.webp","alt":"Historic Ybor Factory Building beside a Tampa street","caption":"Ybor City provides the Tampa Cuban sandwich’s historic neighborhood context. A sandwich and the listed restaurants are not pictured.","credit":"Ikuna","source":"https://unsplash.com/photos/a-street-with-cars-and-buildings-on-the-side-wb2DOoxIGJQ","license":"Unsplash License","position":"50% 50%","width":796,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "st-armands-circle-restaurants": Object.freeze({"src":"/guides/unsplash/dining-dogu-tuncer.webp","alt":"Two people toasting with wine in an outdoor dining setting","caption":"A contextual dining scene. St. Armands Circle and the listed restaurants are not pictured.","credit":"Doğu Tuncer","source":"https://unsplash.com/photos/O2shKYWys8M","license":"Unsplash License","position":"50% 48%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "best-restaurants-disney-springs": Object.freeze({"src":"/guides/unsplash/dining-dogu-tuncer.webp","alt":"Two people toasting with wine in an outdoor dining setting","caption":"A contextual dining scene. Disney Springs and the listed restaurants are not pictured.","credit":"Doğu Tuncer","source":"https://unsplash.com/photos/O2shKYWys8M","license":"Unsplash License","position":"50% 48%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "best-hotels-near-magic-kingdom": Object.freeze({"src":"/guides/unsplash/orlando-resort-juan-burgos.webp","alt":"Palm trees and lounge chairs beside a resort pool in Orlando","caption":"A resort pool at Four Seasons Orlando provides hotel context. This guide compares several properties; no selection is implied.","credit":"Juan Burgos","source":"https://unsplash.com/photos/green-palm-trees-near-swimming-pool-during-daytime-sRQclM9FkHI","license":"Unsplash License","position":"50% 50%","width":960,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "gatorland-vs-wild-florida": Object.freeze({"src":"/guides/unsplash/florida-alligator-damon-on-road.webp","alt":"American alligator swimming through a green Florida spring","caption":"An American alligator at Wakulla Springs provides wildlife context for the Orlando park comparison.","credit":"Damon On Road","source":"https://unsplash.com/photos/shallow-focus-photo-of-alligator-on-body-of-water-during-daytime-xgMicu8jw64","license":"Unsplash License","position":"50% 47%","width":1600,"height":900,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-orlando-not-theme-parks": Object.freeze({"src":"/guides/unsplash/orlando-skyline-mick-haupt.webp","alt":"Downtown Orlando lights reflected across Lake Eola at night","caption":"Downtown Orlando and Lake Eola at night.","credit":"Mick Haupt","source":"https://unsplash.com/photos/a-view-of-a-city-at-night-from-across-a-lake-Ci8vCyxLXsQ","license":"Unsplash License","position":"50% 50%","width":1600,"height":1067,"licenseUrl":"https://unsplash.com/license"}),
  "sarasota-half-price-dining": Object.freeze({"src":"/guides/unsplash/dining-dogu-tuncer.webp","alt":"Two people toasting with wine in an outdoor dining setting","caption":"A contextual dining scene. No participating Sarasota restaurant is pictured.","credit":"Doğu Tuncer","source":"https://unsplash.com/photos/O2shKYWys8M","license":"Unsplash License","position":"50% 48%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "orlando-in-the-rain": Object.freeze({"src":"/guides/unsplash/museum-gallery-mat.webp","alt":"Visitor viewing framed paintings in a skylit museum gallery","caption":"A museum gallery provides indoor-outing context for a rainy day. Orlando is not pictured.","credit":"Mat","source":"https://unsplash.com/photos/person-viewing-paintings-in-a-museum-gallery-yaSXnSV9fF0","license":"Unsplash License","position":"50% 50%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "birthday-freebies-bradenton-sarasota": Object.freeze({"src":"/guides/unsplash/birthday-cake-david-trinks.webp","alt":"White birthday cake with five lit candles","caption":"A birthday cake sets the occasion; no participating Sarasota or Bradenton business is pictured.","credit":"David Trinks","source":"https://unsplash.com/photos/a-birthday-cake-with-lit-candles-sitting-on-a-table-Ezs9fhp_VwQ","license":"Unsplash License","position":"50% 55%","width":1600,"height":1139,"licenseUrl":"https://unsplash.com/license"}),
  "anna-maria-island-day-trip": Object.freeze({"src":"/guides/unsplash/sarasota-sunset-nathan-mullet.webp","alt":"Wooden lifeguard tower on a Sarasota beach at sunset","caption":"A Sarasota beach at sunset provides nearby Gulf Coast context. Anna Maria Island is not pictured.","credit":"Nathan Mullet","source":"https://unsplash.com/photos/v0ipCnvovM0","license":"Unsplash License","position":"50% 53%","width":872,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "myakka-river-state-park-guide": Object.freeze({"src":"/guides/unsplash/florida-boardwalk-jamie-hagan.webp","alt":"Wooden boardwalk winding through a dense Florida forest","caption":"A nature boardwalk in Fort Myers provides Southwest Florida trail context. Myakka River State Park is not pictured.","credit":"Jamie Hagan","source":"https://unsplash.com/photos/grey-wooden-pathway-surrounded-by-trees-Hcq3i_TmszE","license":"Unsplash License","position":"50% 50%","width":900,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "ybor-city-tampa-guide": Object.freeze({"src":"/guides/unsplash/ybor-city-ikuna.webp","alt":"Historic Ybor Factory Building beside a Tampa street","caption":"The Ybor Factory Building in Tampa’s Ybor City Historic District.","credit":"Ikuna","source":"https://unsplash.com/photos/a-street-with-cars-and-buildings-on-the-side-wb2DOoxIGJQ","license":"Unsplash License","position":"50% 50%","width":796,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "tampa-riverwalk-guide": Object.freeze({"src":"/guides/unsplash/tampa-riverfront-paws-and-prints.webp","alt":"Tampa skyline and museum buildings across the Hillsborough River","caption":"The Hillsborough River and downtown Tampa waterfront.","credit":"paws and prints","source":"https://unsplash.com/photos/modern-cityscape-with-tall-buildings-by-the-water-7zLvXcOcu74","license":"Unsplash License","position":"50% 48%","width":1600,"height":1066,"licenseUrl":"https://unsplash.com/license"}),
  "de-soto-national-memorial-bradenton": Object.freeze({"src":"/guides/unsplash/florida-boardwalk-jamie-hagan.webp","alt":"Wooden boardwalk winding through a dense Florida forest","caption":"A nature boardwalk in Fort Myers provides Southwest Florida trail context. De Soto National Memorial is not pictured.","credit":"Jamie Hagan","source":"https://unsplash.com/photos/grey-wooden-pathway-surrounded-by-trees-Hcq3i_TmszE","license":"Unsplash License","position":"50% 50%","width":900,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "robinson-preserve-bradenton": Object.freeze({"src":"/guides/unsplash/florida-boardwalk-jamie-hagan.webp","alt":"Wooden boardwalk winding through a dense Florida forest","caption":"A nature boardwalk in Fort Myers provides Southwest Florida trail context. Robinson Preserve is not pictured.","credit":"Jamie Hagan","source":"https://unsplash.com/photos/grey-wooden-pathway-surrounded-by-trees-Hcq3i_TmszE","license":"Unsplash License","position":"50% 50%","width":900,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "magical-dining-orlando-2026": Object.freeze({"src":"/guides/unsplash/dining-dogu-tuncer.webp","alt":"Two people toasting with wine in an outdoor dining setting","caption":"A contextual dining scene. No 2026 Magical Dining restaurant or dish is pictured.","credit":"Doğu Tuncer","source":"https://unsplash.com/photos/O2shKYWys8M","license":"Unsplash License","position":"50% 48%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-orlando-summer-2026": Object.freeze({"src":"/guides/unsplash/orlando-skyline-mick-haupt.webp","alt":"Downtown Orlando lights reflected across Lake Eola at night","caption":"Downtown Orlando and Lake Eola at night.","credit":"Mick Haupt","source":"https://unsplash.com/photos/a-view-of-a-city-at-night-from-across-a-lake-Ci8vCyxLXsQ","license":"Unsplash License","position":"50% 50%","width":1600,"height":1067,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-miami-summer-2026": Object.freeze({"src":"/guides/unsplash/miami-beach-kian-lem.webp","alt":"Aerial view of Miami Beach hotels, sand, and turquoise ocean","caption":"Miami Beach and its Atlantic shoreline.","credit":"Kian Lem","source":"https://unsplash.com/photos/aerial-photo-of-buildings-beside-beach-V8YLE7LEjOY","license":"Unsplash License","position":"50% 52%","width":1600,"height":1067,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-tampa-summer-2026": Object.freeze({"src":"/guides/unsplash/tampa-riverfront-paws-and-prints.webp","alt":"Tampa skyline and museum buildings across the Hillsborough River","caption":"The Hillsborough River and downtown Tampa waterfront.","credit":"paws and prints","source":"https://unsplash.com/photos/modern-cityscape-with-tall-buildings-by-the-water-7zLvXcOcu74","license":"Unsplash License","position":"50% 48%","width":1600,"height":1066,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-fort-lauderdale-summer-2026": Object.freeze({"src":"/guides/unsplash/fort-lauderdale-brandon-bliss.webp","alt":"Fort Lauderdale beach with oceanfront towers in the distance","caption":"Fort Lauderdale’s Atlantic shoreline and oceanfront skyline.","credit":"Brandon Bliss","source":"https://unsplash.com/photos/a-sandy-beach-next-to-the-ocean-with-tall-buildings-in-the-background-I15wOzYnGlM","license":"Unsplash License","position":"50% 50%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-key-west-summer-2026": Object.freeze({"src":"/guides/unsplash/key-west-beach-lisa-davidson.webp","alt":"Sandy path through palms leading to turquoise water in Key West","caption":"A palm-lined beach path in Key West.","credit":"Lisa Davidson","source":"https://unsplash.com/photos/a-sandy-path-leads-to-a-beautiful-beach-WTsdPcxDOt4","license":"Unsplash License","position":"50% 52%","width":1600,"height":1067,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-st-augustine-summer-2026": Object.freeze({"src":"/guides/unsplash/st-augustine-mr-great-heart.webp","alt":"Stained-glass windows inside the Cathedral Basilica of St. Augustine","caption":"Stained glass inside the Cathedral Basilica of St. Augustine.","credit":"Mr. Great Heart","source":"https://unsplash.com/photos/old-city-st-augustine-in-florida-jBc9mrAkfBA","license":"Unsplash License","position":"50% 50%","width":1600,"height":921,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-daytona-beach-summer-2026": Object.freeze({"src":"/guides/unsplash/daytona-beach-will-forrester.webp","alt":"Blue and yellow umbrellas on the broad sand at Daytona Beach","caption":"Beach chairs and umbrellas on Daytona Beach.","credit":"Will Forrester","source":"https://unsplash.com/photos/a-beach-with-chairs-and-umbrellas-E0xOB6q4U_I","license":"Unsplash License","position":"50% 52%","width":1600,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-panama-city-beach-summer-2026": Object.freeze({"src":"/guides/unsplash/panama-city-beach-jerrod-termini.webp","alt":"People walking the shoreline at sunset in Panama City Beach","caption":"Sunset on Panama City Beach.","credit":"Jerrod Termini","source":"https://unsplash.com/photos/a-beach-at-sunset-with-people-walking-on-the-shore-epFy0crDRyY","license":"Unsplash License","position":"50% 50%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-st-petersburg-clearwater-summer-2026": Object.freeze({"src":"/guides/unsplash/clearwater-jonah-hochstadt.webp","alt":"Aerial view of Clearwater Beach, hotels, and a pier","caption":"Clearwater Beach anchors the coastal half of this St. Petersburg and Clearwater guide.","credit":"Jonah Hochstadt","source":"https://unsplash.com/photos/an-aerial-view-of-a-beach-with-a-pier-and-hotels-FPY5sckl-BQ","license":"Unsplash License","position":"50% 50%","width":1600,"height":900,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-naples-summer-2026": Object.freeze({"src":"/guides/unsplash/naples-boardwalk-joseph-biscocho.webp","alt":"Wooden beach access walkway at sunset in Naples, Florida","caption":"A beach access walkway in Naples at sunset.","credit":"Joseph Biscocho","source":"https://unsplash.com/photos/brown-wooden-walkway-fr9XrQPO_wg","license":"Unsplash License","position":"50% 50%","width":1600,"height":1067,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-in-parrish-florida": Object.freeze({"src":"/guides/unsplash/florida-boardwalk-jamie-hagan.webp","alt":"Wooden boardwalk winding through a dense Florida forest","caption":"A nature boardwalk in Fort Myers provides Florida outdoor-outing context. Parrish and the Railroad Museum are not pictured.","credit":"Jamie Hagan","source":"https://unsplash.com/photos/grey-wooden-pathway-surrounded-by-trees-Hcq3i_TmszE","license":"Unsplash License","position":"50% 50%","width":900,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-in-sarasota-florida": Object.freeze({"src":"/guides/unsplash/sarasota-sunset-nathan-mullet.webp","alt":"Wooden lifeguard tower on a Sarasota beach at sunset","caption":"Sarasota’s Gulf shoreline at sunset.","credit":"Nathan Mullet","source":"https://unsplash.com/photos/v0ipCnvovM0","license":"Unsplash License","position":"50% 53%","width":872,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "things-to-do-in-tampa-florida": Object.freeze({"src":"/guides/unsplash/tampa-waterfront-kody-cheyne.webp","alt":"Downtown Tampa skyline reflected on dark water","caption":"Downtown Tampa skyline across the water.","credit":"Kody Cheyne","source":"https://unsplash.com/photos/city-buildings-near-sea-0c1tiPP9aRs","license":"Unsplash License","position":"50% 50%","width":1600,"height":1067,"licenseUrl":"https://unsplash.com/license"}),
  "gulf-coast-brunch-and-date-night": Object.freeze({"src":"/guides/unsplash/dining-dogu-tuncer.webp","alt":"Two people toasting with wine in an outdoor dining setting","caption":"A contextual dining scene. No venue named in the guide is pictured.","credit":"Doğu Tuncer","source":"https://unsplash.com/photos/O2shKYWys8M","license":"Unsplash License","position":"50% 48%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "orlando-halloween-food-2026": Object.freeze({"src":"/guides/unsplash/orlando-halloween-nik-goodner.webp","alt":"Mickey Mouse pumpkin wreath with autumn leaves in Orlando","caption":"A Disney fall display in Orlando sets the Halloween context. No 2026 event or menu item is pictured.","credit":"Nik Goodner","source":"https://unsplash.com/photos/a-mickey-mouse-pumpkin-wreath-hanging-from-a-lamp-post-B8Nn7wdadro","license":"Unsplash License","position":"50% 48%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
  "fall-events-orlando-2026": Object.freeze({"src":"/guides/unsplash/orlando-halloween-nik-goodner.webp","alt":"Mickey Mouse pumpkin wreath with autumn leaves in Orlando","caption":"A Disney fall display in Orlando sets the seasonal context. No specific 2026 event is pictured.","credit":"Nik Goodner","source":"https://unsplash.com/photos/a-mickey-mouse-pumpkin-wreath-hanging-from-a-lamp-post-B8Nn7wdadro","license":"Unsplash License","position":"50% 48%","width":800,"height":1200,"licenseUrl":"https://unsplash.com/license"}),
});

export function guideHero(slug) {
  const key = typeof slug === "string" ? slug.trim().toLowerCase() : "";
  return GUIDE_HERO_ART[key] || NEUTRAL_GUIDE_HERO;
}

export { NEUTRAL_HERO, NEUTRAL_GUIDE_HERO };
