// GENERATED by scripts/build-guide-pick-photos.mjs — do not hand-edit.
// Slim slug -> { hero, pick } photo index for the guide card (see
// buildGuideCardPhotoIndex). Derived from lib/guideHero.js + the pick-photo
// manifest; scripts/check-guide-pick-photos.mjs fails when it is out of sync.
export const GUIDE_CARD_PHOTOS = {
  "anna-maria-island-day-trip": {
    "hero": {
      "src": "/guides/verified/nature-anna-maria-coquina-beach.webp",
      "credit": "RayRR",
      "href": "https://commons.wikimedia.org/wiki/File:Late_afternoon_on_Coquina_Beach.jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/anna-maria-island-day-trip/anna-maria-city-pier.webp",
      "credit": "RayRR",
      "href": "https://commons.wikimedia.org/wiki/File:AMI_City_Pier.jpg",
      "position": "62% 55%"
    }
  },
  "best-cuban-sandwich-tampa": {
    "hero": {
      "src": "/guides/picks/best-cuban-sandwich-tampa/hero-columbia-arcade.webp",
      "credit": "SharkshockUSA",
      "href": "https://commons.wikimedia.org/wiki/File:Columbia_restaurant_Tampa.jpg",
      "position": "30% 48%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/best-cuban-sandwich-tampa/columbia-restaurant.webp",
      "credit": "LittleT889",
      "href": "https://commons.wikimedia.org/wiki/File:Columbia,_Ybor_City.jpg",
      "position": "50% 42%"
    }
  },
  "best-hotels-near-magic-kingdom": {
    "hero": {
      "src": "/guides/picks/best-hotels-near-magic-kingdom/polynesian-resort-sunset.webp",
      "credit": "Lexi Scott",
      "href": "https://commons.wikimedia.org/wiki/File:Polynesian_Village_Resort_at_Sunset.jpg",
      "position": "45% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/best-hotels-near-magic-kingdom/contemporary-resort-monorail.webp",
      "credit": "Quarax",
      "href": "https://commons.wikimedia.org/wiki/File:Disney%27s_Contemporary_Resort_Arriving_Monorail_Teal.jpg",
      "position": "50% 30%"
    }
  },
  "best-restaurants-disney-springs": {
    "hero": {
      "src": "/guides/picks/best-restaurants-disney-springs/disney-springs-hero.webp",
      "credit": "Melissa Guadalupe Huertas",
      "href": "https://commons.wikimedia.org/wiki/File:Sunny_day_on_Disney_Springs,_USA.jpg",
      "position": "55% 60%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/best-restaurants-disney-springs/gideons-bakehouse-sign.webp",
      "credit": "Jeremy Thompson",
      "href": "https://commons.wikimedia.org/wiki/File:Gideon%27s_Bakehouse_at_Disney_Springs.jpg",
      "position": "45% 45%"
    }
  },
  "bioluminescence-kayak-tour-space-coast": {
    "hero": {
      "src": "/guides/picks/bioluminescence-kayak-tour-space-coast/bairs-cove-haulover-canal-kayakers.webp",
      "credit": "Rusty Clark",
      "href": "https://www.flickr.com/photos/23206546@N04/7062563449",
      "position": "50% 45%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/bioluminescence-kayak-tour-space-coast/a-clear-kayak-bioluminescence-tour.webp",
      "credit": "Rusty Clark ~ 100K Photos",
      "href": "https://www.flickr.com/photos/23206546@N04/31203377283",
      "position": "50% 50%"
    }
  },
  "birthday-freebies-bradenton-sarasota": {
    "hero": {
      "src": "/guides/unsplash/birthday-cake-david-trinks.webp",
      "credit": "David Trinks",
      "href": "https://unsplash.com/photos/a-birthday-cake-with-lit-candles-sitting-on-a-table-Ezs9fhp_VwQ",
      "position": "40% 55%",
      "kind": "illustrative"
    },
    "pick": null
  },
  "de-soto-national-memorial-bradenton": {
    "hero": {
      "src": "/guides/verified/nature-de-soto-boardwalk.webp",
      "credit": "Fredlyfish4",
      "href": "https://commons.wikimedia.org/wiki/File:Boardwalk_in_De_Soto_National_Memorial.JPG",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/de-soto-national-memorial-bradenton/camp-uzita.webp",
      "credit": "Ebyabe",
      "href": "https://commons.wikimedia.org/wiki/File:Bradenton_FL_DeSoto_Natl_Mem07.jpg",
      "position": "50% 45%"
    }
  },
  "fall-events-orlando-2026": {
    "hero": {
      "src": "/guides/picks/fall-events-orlando-2026/cinderella-castle-fireworks-hero.webp",
      "credit": "Jorge Royan",
      "href": "https://commons.wikimedia.org/wiki/File:Disneyworld_fireworks_-_0219.jpg",
      "position": "50% 45%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/fall-events-orlando-2026/legoland-florida-entrance.webp",
      "credit": "Ziggymarley01",
      "href": "https://commons.wikimedia.org/wiki/File:Winter_Haven,_Florida_-_Legoland_Florida.jpg",
      "position": "50% 40%"
    }
  },
  "florida-christmas-boat-parades-2026": {
    "hero": {
      "src": "/guides/verified/city-florida-christmas-boat-parades-2026.webp",
      "credit": "Tamanoeconomico",
      "href": "https://commons.wikimedia.org/wiki/File:New_River_(Fort_Lauderdale,_Florida).jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": null
  },
  "florida-holiday-nights-out-2026": {
    "hero": {
      "src": "/guides/verified/garden-florida-holiday-nights-out-2026.webp",
      "credit": "Daderot",
      "href": "https://commons.wikimedia.org/wiki/File:Entrance_-_Marie_Selby_Botanical_Gardens_-_Sarasota,_Florida_-_DSC00843.jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": null
  },
  "florida-lovebug-season": {
    "hero": {
      "src": "/guides/verified/florida-lovebug-season.webp",
      "credit": "Judy Gallagher",
      "href": "https://commons.wikimedia.org/wiki/File:Lovebugs_-_Plecia_nearctica_on_Camphorweed_-_Pluchea_odorata,_Myakka_River_State_Park,_Sarasota,_Florida.jpg",
      "position": "50% 48%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/florida-lovebug-season/lovebug-close-up-gainesville.webp",
      "credit": "Alex Abair",
      "href": "https://commons.wikimedia.org/wiki/File:Plecia_nearctica_271553494.jpg",
      "position": "50% 50%"
    }
  },
  "florida-manatee-season-2026": {
    "hero": {
      "src": "/guides/verified/nature-florida-manatee-season-2026.webp",
      "credit": "CityofCrystalRiver",
      "href": "https://commons.wikimedia.org/wiki/File:Three_Sister_Springs.jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": null
  },
  "florida-scalloping-crystal-river-homosassa": {
    "hero": {
      "src": "/guides/picks/florida-scalloping-crystal-river-homosassa/fort-island-gulf-beach-crystal-river.webp",
      "credit": "Kolin Toney",
      "href": "https://www.flickr.com/photos/43053584@N00/29618236383",
      "position": "45% 40%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/florida-scalloping-crystal-river-homosassa/a-guided-scallop-trip-from-crystal-river-or-homosassa.webp",
      "credit": "Kate Ter Haar",
      "href": "https://www.flickr.com/photos/8489692@N03/16888503408",
      "position": "50% 50%"
    }
  },
  "florida-theme-park-christmas-2026": {
    "hero": {
      "src": "/guides/verified/theme-park-florida-theme-park-christmas-2026.webp",
      "credit": "Jedi94",
      "href": "https://commons.wikimedia.org/wiki/File:Disney_Skyliner_and_Epcot_International_Gateway.jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": null
  },
  "florida-winter-beaches-2026": {
    "hero": {
      "src": "/guides/verified/nature-florida-winter-beaches-2026.webp",
      "credit": "Schwerdf",
      "href": "https://commons.wikimedia.org/wiki/File:Aerial_view_of_Bahia_Honda_Key_2025-05-17.jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": null
  },
  "gatorland-vs-wild-florida": {
    "hero": {
      "src": "/guides/verified/activity-gatorland-vs-wild-florida.webp",
      "credit": "LittleT889",
      "href": "https://commons.wikimedia.org/wiki/File:Jawlene.jpg",
      "position": "50% 60%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/gatorland-vs-wild-florida/gatorland-mouth-entrance.webp",
      "credit": "William Warby",
      "href": "https://www.flickr.com/photos/26782864@N00/1477075489",
      "position": "50% 55%"
    }
  },
  "gulf-coast-brunch-and-date-night": {
    "hero": {
      "src": "/guides/picks/gulf-coast-brunch-and-date-night/venice-fishing-pier-dusk.webp",
      "credit": "Don Miller",
      "href": "https://commons.wikimedia.org/wiki/File:Venice_Fishing_Pier_-_Flickr_-_DonMiller_ToGo.jpg",
      "position": "55% 60%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/gulf-coast-brunch-and-date-night/sharkys-pier-venice.webp",
      "credit": "Don Miller",
      "href": "https://commons.wikimedia.org/wiki/File:Sharky%27s_Pier_(28417055172).jpg",
      "position": "50% 60%"
    }
  },
  "magical-dining-orlando-2026": {
    "hero": {
      "src": "/guides/picks/magical-dining-orlando-2026/ottos-high-dive-milk-district.webp",
      "credit": "Dclemens1971",
      "href": "https://commons.wikimedia.org/wiki/File:Otto%E2%80%99s_Rum_Bar.jpg",
      "position": "50% 45%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/magical-dining-orlando-2026/ottos-high-dive-milk-district.webp",
      "credit": "Dclemens1971",
      "href": "https://commons.wikimedia.org/wiki/File:Otto%E2%80%99s_Rum_Bar.jpg",
      "position": "50% 45%"
    }
  },
  "miami-restaurants": {
    "hero": {
      "src": "/guides/picks/miami-restaurants/versailles-hero-calle-ocho.webp",
      "credit": "Sharon Hahn Darlin",
      "href": "https://commons.wikimedia.org/wiki/File:Little_Havana,_Miami,_Florida_-_Versailles_Restaurant_June_2021.jpg",
      "position": "30% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/miami-restaurants/barra-callao.webp",
      "credit": "Casingrid",
      "href": "https://commons.wikimedia.org/wiki/File:The_Cloisters_of_the_Monastery.JPG",
      "position": "50% 50%"
    }
  },
  "myakka-river-state-park-guide": {
    "hero": {
      "src": "/guides/verified/sarasota-myakka-canopy-walkway.webp",
      "credit": "Shockblaster",
      "href": "https://commons.wikimedia.org/wiki/File:Myakka_Canopy_Walkway.JPG",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/myakka-river-state-park-guide/myakka-river-kayak.webp",
      "credit": "Mwanner",
      "href": "https://commons.wikimedia.org/wiki/File:Myakka_River_-_Kayaking.jpg",
      "position": "50% 65%"
    }
  },
  "orlando-halloween-food-2026": {
    "hero": {
      "src": "/guides/picks/orlando-halloween-food-2026/raglan-road-hero.webp",
      "credit": "Flickr user berkielynn",
      "href": "https://commons.wikimedia.org/wiki/File:Downtown_Disney_-_Raglan_Road_Irish_Pub_-_retouched.jpg",
      "position": "45% 40%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/orlando-halloween-food-2026/raglan-sign.webp",
      "credit": "Ross Hawkes",
      "href": "https://www.flickr.com/photos/52768784@N07/5538137260",
      "position": "50% 50%"
    }
  },
  "orlando-in-the-rain": {
    "hero": {
      "src": "/guides/picks/orlando-in-the-rain/wonderworks-upside-down-building.webp",
      "credit": "Leonard J. DeFrancisci",
      "href": "https://commons.wikimedia.org/wiki/File:WonderWorks_(Orlando,_Florida)_001.jpg",
      "position": "50% 40%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/orlando-in-the-rain/madame-tussauds-orlando-entrance.webp",
      "credit": "Kiran891",
      "href": "https://commons.wikimedia.org/wiki/File:Madame_Tussauds_Orlando_photo_station.jpg",
      "position": "50% 55%"
    }
  },
  "orlando-restaurants": {
    "hero": {
      "src": "/guides/unsplash/orlando-skyline-mick-haupt.webp",
      "credit": "Mick Haupt",
      "href": "https://unsplash.com/photos/a-view-of-a-city-at-night-from-across-a-lake-Ci8vCyxLXsQ",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/magical-dining-orlando-2026/ottos-high-dive-milk-district.webp",
      "credit": "Dclemens1971",
      "href": "https://commons.wikimedia.org/wiki/File:Otto%E2%80%99s_Rum_Bar.jpg",
      "position": "50% 45%"
    }
  },
  "pinecraft-sarasota-amish-village": {
    "hero": {
      "src": "/guides/picks/things-to-do-sarasota/pinecraft-post-office.webp",
      "credit": "Witherpshins",
      "href": "https://commons.wikimedia.org/wiki/File:Pinecraft_Florida_Post_Office,_1240_Yoder_Avenue,_Pinecraft_Florida_34278.JPG",
      "position": "50% 45%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/pinecraft-sarasota-amish-village/how-to-visit-respectfully.webp",
      "credit": "Witherpshins",
      "href": "https://commons.wikimedia.org/wiki/File:Pinecraft_Florida_Post_Office%2C_1240_Yoder_Avenue%2C_Pinecraft_Florida_34278.JPG",
      "position": "50% 50%"
    }
  },
  "pintos-farm-miami-2026": {
    "hero": {
      "src": "/guides/pintos-farm-miami-2026/hero-family-paddle-boat-lake.webp",
      "credit": "Pinto's Farm",
      "href": "https://pintofarm.com",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": null
  },
  "red-bull-dance-your-style-tampa-2026": {
    "hero": {
      "src": "/guides/picks/red-bull-dance-your-style-tampa-2026/hero-tampa-convention-center.webp",
      "credit": "Zeng8r",
      "href": "https://commons.wikimedia.org/wiki/File:Tampa_Convention_Center.JPG",
      "position": "50% 40%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/red-bull-dance-your-style-tampa-2026/florida-s-stake-in-the-final.webp",
      "credit": "Eric Statzer",
      "href": "https://commons.wikimedia.org/wiki/File:Tampa_Riverwalk_along_the_Convention_Center_Waterfront_-_Eric_Statzer.jpg",
      "position": "50% 50%"
    }
  },
  "robinson-preserve-bradenton": {
    "hero": {
      "src": "/guides/verified/nature-robinson-preserve-tower-view.webp",
      "credit": "Gregory Urbano",
      "href": "https://commons.wikimedia.org/wiki/File:Robinson_Preserve_Observation_Tower_(24946730937).jpg",
      "position": "50% 52%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/robinson-preserve-bradenton/robinson-preserve-boardwalk-trail.webp",
      "credit": "Mark Hewitt",
      "href": "https://commons.wikimedia.org/wiki/File:Robinson_Perserve_-_panoramio.jpg",
      "position": "40% 55%"
    }
  },
  "sarasota-half-price-dining": {
    "hero": {
      "src": "/guides/verified/food-sarasota-half-price-dining.webp",
      "credit": "An Nhien",
      "href": "https://unsplash.com/photos/table-setting-with-food-drinks-and-lamp-at-dusk-f99l771qluE",
      "position": "50% 55%",
      "kind": "illustrative"
    },
    "pick": {
      "src": "/guides/picks/sarasota-half-price-dining/clipp-half-price-certificates.webp",
      "credit": "Roger W",
      "href": "https://www.flickr.com/photos/24736216@N07/5033849130",
      "position": "50% 50%"
    }
  },
  "sarasota-restaurants": {
    "hero": {
      "src": "/guides/verified/food-st-armands-meal.webp",
      "credit": "Keith Tanner",
      "href": "https://unsplash.com/photos/a-table-with-plates-of-food-and-drinks-on-it-GcUaWXO4cO4",
      "position": "50% 53%",
      "kind": "illustrative"
    },
    "pick": null
  },
  "siesta-key-drum-circle": {
    "hero": {
      "src": "/guides/picks/siesta-key-drum-circle/siesta-key-beach-sunset.webp",
      "credit": "Fred Hsu",
      "href": "https://commons.wikimedia.org/wiki/File:2017_Sarasota_Enormity_of_Siesta_Beach_on_Siesta_Key_at_Sunset_03_FRD_9744.jpg",
      "position": "50% 38%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/siesta-key-drum-circle/parking-without-the-meltdown.webp",
      "credit": "Ryan Gamma",
      "href": "https://commons.wikimedia.org/wiki/File:Siesta_Key_Beach_Pavilion_.jpg",
      "position": "50% 50%"
    }
  },
  "siesta-key-vs-lido-key": {
    "hero": {
      "src": "/guides/verified/sarasota-lido-key-beach.webp",
      "credit": "Fred Hsu",
      "href": "https://commons.wikimedia.org/wiki/File:2017_Sarasota_Lido_Key_Beach_3_FRD_9556.jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/siesta-key-vs-lido-key/lido-key-beach.webp",
      "credit": "Ryan Hodnett",
      "href": "https://commons.wikimedia.org/wiki/File:Lido_Key_-_Sarasota,_Florida_2023-01-22_(07).jpg",
      "position": "50% 50%"
    }
  },
  "st-armands-circle-restaurants": {
    "hero": {
      "src": "/guides/picks/st-armands-circle-restaurants/st-armands-circle-storefronts.webp",
      "credit": "Ebyabe",
      "href": "https://commons.wikimedia.org/wiki/File:Sarasota_FL_Harding_Circle_HD_St_Armands_Circle03.jpg",
      "position": "40% 45%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/st-armands-circle-restaurants/shore.webp",
      "credit": "Ebyabe",
      "href": "https://commons.wikimedia.org/wiki/File:Sarasota_FL_Harding_Circle_HD_St_Armands_Circle03.jpg",
      "position": "50% 50%"
    }
  },
  "st-pete-restaurants": {
    "hero": {
      "src": "/guides/verified/food-gulf-coast-brunch-and-date-night.webp",
      "credit": "Gabriel Gurrola",
      "href": "https://unsplash.com/photos/baked-pancake-and-egg-scramble-on-plate-UrXH-rUUDu4",
      "position": "57% 52%",
      "kind": "illustrative"
    },
    "pick": {
      "src": "/guides/picks/st-pete-restaurants/doc-fords-pier-patio.webp",
      "credit": "Calmuziclover",
      "href": "https://commons.wikimedia.org/wiki/File:Doc_Ford%27s_Rum_Bar_and_Grille_on_the_new_St_Petersburg_Pier_(50220515643).jpg",
      "position": "50% 55%"
    }
  },
  "swim-with-manatees-crystal-river": {
    "hero": {
      "src": "/guides/verified/activity-swim-with-manatees-crystal-river.webp",
      "credit": "David Hinkel / U.S. Fish and Wildlife Service",
      "href": "https://commons.wikimedia.org/wiki/File:Endangered_Florida_manatee_(Trichechus_manatus)_(7636809538).jpg",
      "position": "50% 45%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/swim-with-manatees-crystal-river/a-manatee-eco-cruise-for-non-swimmers.webp",
      "credit": "U.S. Fish and Wildlife Service Headquarters",
      "href": "https://commons.wikimedia.org/wiki/File:Endangered_Florida_manatee_(Trichechus_manatus),_Crystal_River_National_Wildlife_Refuge_(7636809258).jpg",
      "position": "50% 50%"
    }
  },
  "tampa-restaurants": {
    "hero": {
      "src": "/guides/unsplash/tampa-riverfront-paws-and-prints.webp",
      "credit": "paws and prints",
      "href": "https://unsplash.com/photos/modern-cityscape-with-tall-buildings-by-the-water-7zLvXcOcu74",
      "position": "50% 48%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-tampa-florida/berns-dessert-room.webp",
      "credit": "Swampyank",
      "href": "https://commons.wikimedia.org/wiki/File:Bern%27s_Steak_House.jpg",
      "position": "50% 45%"
    }
  },
  "tampa-riverwalk-guide": {
    "hero": {
      "src": "/guides/unsplash/tampa-riverfront-paws-and-prints.webp",
      "credit": "paws and prints",
      "href": "https://unsplash.com/photos/modern-cityscape-with-tall-buildings-by-the-water-7zLvXcOcu74",
      "position": "50% 48%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/tampa-riverwalk-guide/sparkman-wharf-pirate-water-taxi.webp",
      "credit": "Jackdude101",
      "href": "https://commons.wikimedia.org/wiki/File:Pirate_Water_Taxi.jpg",
      "position": "50% 45%"
    }
  },
  "things-to-do-daytona-beach-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/daytona-beach-will-forrester.webp",
      "credit": "Will Forrester",
      "href": "https://unsplash.com/photos/a-beach-with-chairs-and-umbrellas-E0xOB6q4U_I",
      "position": "50% 52%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-daytona-beach-summer-2026/jackie-robinson-ballpark-gate.webp",
      "credit": "Ebyabe",
      "href": "https://commons.wikimedia.org/wiki/File:Daytona_Beach_FL_City_Island_Robinson_Ballpark_gate01.jpg",
      "position": "50% 45%"
    }
  },
  "things-to-do-fort-lauderdale-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/fort-lauderdale-brandon-bliss.webp",
      "credit": "Brandon Bliss",
      "href": "https://unsplash.com/photos/a-sandy-beach-next-to-the-ocean-with-tall-buildings-in-the-background-I15wOzYnGlM",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-fort-lauderdale-summer-2026/an-everglades-airboat-morning.webp",
      "credit": "Gary Troutt",
      "href": "https://commons.wikimedia.org/wiki/File:Evergladesairboattour.jpg",
      "position": "50% 50%"
    }
  },
  "things-to-do-in-bradenton-florida": {
    "hero": {
      "src": "/guides/verified/nature-robinson-preserve-tower-view.webp",
      "credit": "Gregory Urbano",
      "href": "https://commons.wikimedia.org/wiki/File:Robinson_Preserve_Observation_Tower_(24946730937).jpg",
      "position": "50% 52%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-bradenton-florida/bradenton-riverwalk-tower-plaza.webp",
      "credit": "The Grid",
      "href": "https://commons.wikimedia.org/wiki/File:Bradenton_Riverwalk_Tower_Plaza.jpg",
      "position": "50% 45%"
    }
  },
  "things-to-do-in-cortez-florida": {
    "hero": {
      "src": "/guides/verified/food-sarasota-half-price-dining.webp",
      "credit": "An Nhien",
      "href": "https://unsplash.com/photos/table-setting-with-food-drinks-and-lamp-at-dusk-f99l771qluE",
      "position": "50% 55%",
      "kind": "illustrative"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-cortez-florida/fish-preserve.webp",
      "credit": "Ebyabe",
      "href": "https://commons.wikimedia.org/wiki/File:Cortez_FL_HD_Bratton_Store01.jpg",
      "position": "50% 50%"
    }
  },
  "things-to-do-in-ellenton-florida": {
    "hero": {
      "src": "/guides/verified/city-ellenton.webp",
      "credit": "Paul R. Burley",
      "href": "https://commons.wikimedia.org/wiki/File:Robert_Gamble_House_Ellenton_Florida_2019-2479_01.jpg",
      "position": "50% 45%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-ellenton-florida/gamble-mansion-front.webp",
      "credit": "Ebyabe",
      "href": "https://commons.wikimedia.org/wiki/File:Gamble_Plantation_SP_mansion01.jpg",
      "position": "50% 45%"
    }
  },
  "things-to-do-in-lakewood-ranch-florida": {
    "hero": {
      "src": "/guides/verified/city-lakewood-pond.webp",
      "credit": "Lucas Liberman",
      "href": "https://unsplash.com/photos/aquatic-plants-grow-beside-a-calm-pond-3Xb8tib8X_I",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": null
  },
  "things-to-do-in-longboat-key-florida": {
    "hero": {
      "src": "/guides/verified/city-longboat-key.webp",
      "credit": "Guspederson",
      "href": "https://commons.wikimedia.org/wiki/File:Longboat-Key_Beach.jpg",
      "position": "50% 75%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-longboat-key-florida/public-beach-access-at-4001-gulf-of-mexico-drive.webp",
      "credit": "Ebyabe",
      "href": "https://commons.wikimedia.org/wiki/File:Longboat_Key_FL_beach_bdwk01.jpg",
      "position": "50% 60%"
    }
  },
  "things-to-do-in-miami-florida": {
    "hero": {
      "src": "/guides/picks/things-to-do-in-miami-florida/vizcaya-interior.webp",
      "credit": "Zoshua Colah",
      "href": "https://unsplash.com/photos/a-large-room-with-a-large-painting-on-the-wall-8hzYzvJ38zg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-miami-summer-2026/calle-ocho-cigar-bar-sign.webp",
      "credit": "Phillip Pessar",
      "href": "https://commons.wikimedia.org/wiki/File:Guantanamera_Cigar_Bar_Sign_Calle_Ocho_Little_Havana_Miami_FL_August_2023.jpg",
      "position": "50% 30%"
    }
  },
  "things-to-do-in-palmetto-florida": {
    "hero": {
      "src": "/guides/verified/city-palmetto.webp",
      "credit": "Paul R. Burley",
      "href": "https://commons.wikimedia.org/wiki/File:Emerson_Point_Preserve_Palmetto_Florida_2019-2551.jpg",
      "position": "50% 72%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-palmetto-florida/mangrove-lagoon.webp",
      "credit": "Paul R. Burley",
      "href": "https://commons.wikimedia.org/wiki/File:Emerson_Point_Preserve_Palmetto_Florida_2019-2542.jpg",
      "position": "50% 55%"
    }
  },
  "things-to-do-in-parrish-florida": {
    "hero": {
      "src": "/guides/verified/nature-parrish-railroad-museum.webp",
      "credit": "Ebyabe",
      "href": "https://commons.wikimedia.org/wiki/File:Parrish_FL_Florida_Railroad_Museum01.jpg",
      "position": "50% 45%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-parrish-florida/coquina-beach.webp",
      "credit": "Fred Hsu",
      "href": "https://commons.wikimedia.org/wiki/File:2017_Sarasota_Coquina_Beach_Lifeguard_Station_FRD_8532.jpg",
      "position": "30% 55%"
    }
  },
  "things-to-do-in-sarasota-florida": {
    "hero": {
      "src": "/guides/unsplash/sarasota-sunset-nathan-mullet.webp",
      "credit": "Nathan Mullet",
      "href": "https://unsplash.com/photos/v0ipCnvovM0",
      "position": "50% 53%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-sarasota-florida/bayfront-park-marina.webp",
      "credit": "Wendyrichmondrn",
      "href": "https://commons.wikimedia.org/wiki/File:Sarasota,_FL_Bayfront_Park.jpg",
      "position": "45% 60%"
    }
  },
  "things-to-do-in-tampa-florida": {
    "hero": {
      "src": "/guides/unsplash/tampa-waterfront-kody-cheyne.webp",
      "credit": "Kody Cheyne",
      "href": "https://unsplash.com/photos/city-buildings-near-sea-0c1tiPP9aRs",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-tampa-florida/shell-key-clear-kayaks.webp",
      "credit": "Joe Whalen / Tampa Bay Estuary Program",
      "href": "https://unsplash.com/photos/two-people-in-a-canoe-paddling-down-a-river-KUU87l4KSoE",
      "position": "50% 50%"
    }
  },
  "things-to-do-in-venice-florida": {
    "hero": {
      "src": "/guides/picks/gulf-coast-brunch-and-date-night/venice-fishing-pier-dusk.webp",
      "credit": "Don Miller",
      "href": "https://commons.wikimedia.org/wiki/File:Venice_Fishing_Pier_-_Flickr_-_DonMiller_ToGo.jpg",
      "position": "55% 60%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-in-venice-florida/caspersen-beach-sunset-rocks.webp",
      "credit": "Grendelkhan",
      "href": "https://commons.wikimedia.org/wiki/File:Sunset_at_Caspersen_Beach.jpg",
      "position": "50% 55%"
    }
  },
  "things-to-do-key-west-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/key-west-beach-lisa-davidson.webp",
      "credit": "Lisa Davidson",
      "href": "https://unsplash.com/photos/a-sandy-path-leads-to-a-beautiful-beach-WTsdPcxDOt4",
      "position": "50% 52%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-key-west-summer-2026/august-s-festival-stack-lobsterfest-and-rum-fest.webp",
      "credit": "Christoph Meyer",
      "href": "https://www.flickr.com/photos/93095261@N06/14938159386",
      "position": "50% 50%"
    }
  },
  "things-to-do-miami-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/miami-beach-kian-lem.webp",
      "credit": "Kian Lem",
      "href": "https://unsplash.com/photos/aerial-photo-of-buildings-beside-beach-V8YLE7LEjOY",
      "position": "50% 52%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-miami-summer-2026/nu-stadium-bowl.webp",
      "credit": "Cuban Boy",
      "href": "https://commons.wikimedia.org/wiki/File:Nu_Stadium_(1).jpg",
      "position": "50% 60%"
    }
  },
  "things-to-do-naples-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/naples-boardwalk-joseph-biscocho.webp",
      "credit": "Joseph Biscocho",
      "href": "https://unsplash.com/photos/brown-wooden-walkway-fr9XrQPO_wg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-naples-summer-2026/tin-city-naples.webp",
      "credit": "Todd Van Hoosear",
      "href": "https://commons.wikimedia.org/wiki/File:Tin_City,_Naples_(49417605872).jpg",
      "position": "40% 45%"
    }
  },
  "things-to-do-orlando-not-theme-parks": {
    "hero": {
      "src": "/guides/unsplash/orlando-skyline-mick-haupt.webp",
      "credit": "Mick Haupt",
      "href": "https://unsplash.com/photos/a-view-of-a-city-at-night-from-across-a-lake-Ci8vCyxLXsQ",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-orlando-not-theme-parks/blue-spring-manatee.webp",
      "credit": "KimonBerlin",
      "href": "https://commons.wikimedia.org/wiki/File:Manatees_in_Blue_Spring_State_Park_(8501212290).jpg",
      "position": "50% 55%"
    }
  },
  "things-to-do-orlando-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/orlando-skyline-mick-haupt.webp",
      "credit": "Mick Haupt",
      "href": "https://unsplash.com/photos/a-view-of-a-city-at-night-from-across-a-lake-Ci8vCyxLXsQ",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-orlando-summer-2026/epcot-the-land.webp",
      "credit": "Michael Rivera",
      "href": "https://commons.wikimedia.org/wiki/File:The_Land_entrance.jpg",
      "position": "50% 40%"
    }
  },
  "things-to-do-panama-city-beach-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/panama-city-beach-jerrod-termini.webp",
      "credit": "Jerrod Termini",
      "href": "https://unsplash.com/photos/a-beach-at-sunset-with-people-walking-on-the-shore-epFy0crDRyY",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-panama-city-beach-summer-2026/a-dolphin-cruise-from-the-marinas.webp",
      "credit": "Nonrev.me",
      "href": "https://commons.wikimedia.org/wiki/File:Jet_Ski_Dolphin_Tours_Lagoon_Pontoons.jpg",
      "position": "50% 50%"
    }
  },
  "things-to-do-sarasota": {
    "hero": {
      "src": "/guides/verified/sarasota-ca-dzan-ringling-estate.webp",
      "credit": "HMSyume",
      "href": "https://commons.wikimedia.org/wiki/File:Ca%27_d%27Zan_at_Ringling_estate_in_Sarasota,_FL.jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-sarasota/lido-mangrove-tunnel.webp",
      "credit": "Fred Hsu",
      "href": "https://commons.wikimedia.org/wiki/File:2017_Sarasota_Red_Mangrove_Tunnels_2_FRD_9456.jpg",
      "position": "50% 55%"
    }
  },
  "things-to-do-st-augustine-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/st-augustine-mr-great-heart.webp",
      "credit": "Mr. Great Heart",
      "href": "https://unsplash.com/photos/old-city-st-augustine-in-florida-jBc9mrAkfBA",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-st-augustine-summer-2026/a-food-and-wine-tour-through-the-old-city.webp",
      "credit": "w_lemay",
      "href": "https://commons.wikimedia.org/wiki/File:Benet_House,_St._George_Street,_Colonial_Quarter,_St._Augustine,_FL.jpg",
      "position": "50% 50%"
    }
  },
  "things-to-do-st-petersburg-clearwater-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/clearwater-jonah-hochstadt.webp",
      "credit": "Jonah Hochstadt",
      "href": "https://unsplash.com/photos/an-aerial-view-of-a-beach-with-a-pier-and-hotels-FPY5sckl-BQ",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-st-petersburg-clearwater-summer-2026/caladesi-ferry-dock.webp",
      "credit": "Pinellas County",
      "href": "https://www.flickr.com/photos/63222477@N07/6106426813",
      "position": "60% 50%"
    }
  },
  "things-to-do-tampa-summer-2026": {
    "hero": {
      "src": "/guides/unsplash/tampa-riverfront-paws-and-prints.webp",
      "credit": "paws and prints",
      "href": "https://unsplash.com/photos/modern-cityscape-with-tall-buildings-by-the-water-7zLvXcOcu74",
      "position": "50% 48%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/things-to-do-tampa-summer-2026/busch-gardens-lions.webp",
      "credit": "Adog",
      "href": "https://commons.wikimedia.org/wiki/File:Lions_Busch_Gardens_Tampa.jpg",
      "position": "45% 55%"
    }
  },
  "tonights-move-tampa-september-12-2026": {
    "hero": {
      "src": "/guides/unsplash/tampa-waterfront-kody-cheyne.webp",
      "credit": "Kody Cheyne",
      "href": "https://unsplash.com/photos/city-buildings-near-sea-0c1tiPP9aRs",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/tonights-move-tampa-september-12-2026/raymond-james-stadium.webp",
      "credit": "Bernard Gagnon",
      "href": "https://commons.wikimedia.org/wiki/File:Raymond_James_Stadium02.JPG",
      "position": "50% 55%"
    }
  },
  "weeki-wachee-kayak-mermaids-guide": {
    "hero": {
      "src": "/guides/verified/nature-weeki-wachee-river.webp",
      "credit": "Gzuraski",
      "href": "https://commons.wikimedia.org/wiki/File:Weeki_Wachee_River_July_2013.jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/weeki-wachee-kayak-mermaids-guide/buccaneer-bay-the-spring-fed-water-park.webp",
      "credit": "eutrophication&hypoxia",
      "href": "https://www.flickr.com/photos/48722974@N07/4584923946",
      "position": "50% 50%"
    }
  },
  "winter-park-scenic-boat-tour": {
    "hero": {
      "src": "/guides/verified/activity-winter-park-scenic-boat-tour.webp",
      "credit": "Thomsonmg2000",
      "href": "https://commons.wikimedia.org/wiki/File:Winter_park_canal.jpg",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/winter-park-scenic-boat-tour/make-it-a-winter-park-day.webp",
      "credit": "Jared",
      "href": "https://www.flickr.com/photos/93283041@N00/8312342768",
      "position": "50% 50%"
    }
  },
  "ybor-city-tampa-guide": {
    "hero": {
      "src": "/guides/unsplash/ybor-city-ikuna.webp",
      "credit": "Ikuna",
      "href": "https://unsplash.com/photos/a-street-with-cars-and-buildings-on-the-side-wb2DOoxIGJQ",
      "position": "50% 50%",
      "kind": "documentary"
    },
    "pick": {
      "src": "/guides/picks/ybor-city-tampa-guide/seventh-avenue-ybor.webp",
      "credit": "Richard Mc Neil",
      "href": "https://commons.wikimedia.org/wiki/File:Long_corridor_de_commerces_sur_la_7i%C3%A8me_Avenue_Est_%C3%A0_Ybor_City,_Tampa,_Florida,_USA_-_panoramio.jpg",
      "position": "35% 50%"
    }
  }
};
