// Florida city coverage, researched against the linked operators on 2026-09-24.
// No guessed Place IDs, coordinates, photos, prices or operating hours.
// exactNames are operator-published identities; serving remains geo scoped.
const checked = "2026-09-24";
const pick = (name, city, indoor, blurb, tip, source) => ({ name, city, indoor, appQuery: name, exactNames: [name], blurb, tip, sources: [source], verifiedAt: checked });
const guide = (region, title, description, intro, picks, faq, extraSources = []) => ({
  region, title, description, keyword: `things to do in ${region.toLowerCase()} florida`,
  published: checked, updated: checked, teaser: {
    Bradenton: "The Bishop Museum and Riverwalk make one downtown day, but Robinson Preserve needs its own outdoor block.",
    Miami: "Choose one museum and one neighborhood first, because these Miami stops are spread across the city.",
    Ellenton: "The outlets are outdoors, but a public skating session gives Ellenton a very different indoor choice.",
    Palmetto: "You can enter the Carnegie Library during opening hours, but the other historic buildings need a guided tour.",
    "Lakewood Ranch": "Choose one town center first: Main Street for shops, or Waterside Place for lakeside dining.",
    Cortez: "A waterfront meal anchors the afternoon, but the Florida Maritime Museum is currently closed for rehabilitation.",
    "Longboat Key": "Bayfront Park faces Sarasota Bay, but the public beach access across the road takes you to the Gulf.",
    Venice: "Venice Beach is the simpler beach stop, but Caspersen currently needs a pedestrian or bicycle access plan.",
  }[region], intro, picks, faq,
  sources: [...new Set([...picks.flatMap(p => p.sources), ...extraSources])],
});

export const COVERAGE_2026_GUIDES = {
  "things-to-do-in-bradenton-florida": guide("Bradenton",
    "Bradenton, Florida: A Day of Riverfront, Art and Coastal Nature",
    "Choose a Bradenton day with the Riverwalk, Bishop Museum, Village of the Arts and Robinson Preserve, with an easy downtown plan and an outdoor alternative.",
    "Bradenton offers a useful choice between a downtown day and a longer nature outing. Start with the Bishop Museum and Riverwalk when you want science, history and river views without moving between distant stops. Add the Village of the Arts when its galleries or an art walk match your date. Robinson Preserve is the separate outdoor choice west of downtown; give it its own block of time instead of squeezing it between museum appointments. This guide helps you choose a day, not race through four stops. On a hot or wet afternoon, keep the museum as the anchor and leave the outdoor portions flexible.", [
      {...pick("The Bishop Museum of Science and Nature", "Bradenton", true,
        "The Bishop brings museum galleries, a planetarium and a manatee rehabilitation habitat into a single downtown visit. It suits a family that wants several kinds of experience without another car journey. The animals are in rehabilitation, so treat the habitat as an opportunity to understand their care rather than a promised performance. Check the day's planetarium programming before choosing how to divide your visit.",
        "Make any planetarium show the fixed appointment, then fit the galleries around it. The museum is at 201 10th Street West, making it a sensible anchor for the downtown part of the day.",
        "https://bishopscience.org/plan-your-visit/"), placeId: "ChIJr7ec9tEXw4gRwicCx3wfH2w"},
      pick("Bradenton Riverwalk", "Bradenton", false,
        "The Riverwalk follows the Manatee River through downtown and gives the museum day an outdoor counterpoint. Choose a manageable stretch for your group rather than making the entire waterfront a mileage target. It works as a short pause after the galleries or as the main low-commitment outing when you just want river views and time outside. Check the city's current park information for the facilities that matter to you.",
        "Pair it with the Bishop before driving elsewhere. Bring water and choose your turnaround point before everyone is tired; a waterfront walk need not become a long route.",
        "https://cityofbradenton.com/parks"),
      {...pick("Village of the Arts", "Bradenton", false,
        "The Village of the Arts is a neighborhood of galleries, studios, shops and places to eat. It is most rewarding when the businesses you want to visit are actually open, so use the district's shop directory and art-walk calendar before setting out. A programmed art walk offers a different visit from a quiet weekday. Treat it as a living neighborhood as well as an arts destination.",
        "Choose a gallery or a scheduled art walk first. Individual businesses set their own hours, so do not assume every door will be open whenever you arrive.",
        "https://villageofthearts.org/"), placeCard: false},
      {...pick("Robinson Preserve", "Bradenton", false,
        "Robinson Preserve supplies the longer outdoor alternative: walking, cycling and paddling routes through coastal habitats. Choose one activity and an appropriate entrance rather than arriving with a vague plan to do everything. A walk is the simpler option; a paddle needs separate arrangements and a conditions check. The dedicated Robinson guide goes deeper into the trails and observation points when this is your main reason to visit Bradenton.",
        "Keep Robinson as a separate block of time west of downtown. Check current county access notices, bring water and use the detailed preserve guide before choosing your route.",
        "https://www.mymanatee.org/connect/locations/location-details/robinson-preserve"), placeId: "ChIJR0i18icRw4gRbyGIoLLoSo0"},
    ], [
      {q: "Which stops make the simplest downtown Bradenton day?", a: "Pair the Bishop Museum with the Riverwalk, then add the Village of the Arts if gallery hours or an art walk fit your date."},
      {q: "Should I add Robinson Preserve to the same day?", a: "Choose it when you want a longer outdoor block. It is west of downtown, so keep travel and trail time separate from museum appointments."},
      {q: "What is the best anchor when the weather is poor?", a: "Start with the Bishop Museum and check its current programming. Keep the Riverwalk and preserve flexible rather than committing to a long outdoor route."},
    ]),
  "things-to-do-in-miami-florida": guide("Miami",
    "Miami Beyond the Beach: Art, Gardens and a Little Havana Afternoon",
    "Build a Miami day around Vizcaya, Pérez Art Museum Miami, Wynwood Walls or Little Havana, with practical choices that avoid racing across the city.",
    "Miami rewards a plan with fewer moves. Choose one major museum or garden visit, then add a neighborhood where you want to linger. Vizcaya suits a house-and-garden day; Pérez Art Museum Miami suits a gallery visit by Biscayne Bay. Wynwood Walls adds outdoor mural art, while Little Havana offers a street-level look at Cuban American culture. These are choices across the city, not four adjacent attractions. For a first visit, choose one of the museums and one neighborhood, check entry arrangements, and leave a generous gap for travel and a meal. This is an evergreen city plan, separate from the summer event roundup and restaurant guide.", [
      pick("Vizcaya Museum and Gardens", "Miami", false,
        "Vizcaya combines a historic house with formal gardens, making it the choice when architecture and outdoor space matter as much as galleries. Give the grounds their own time rather than treating them as a quick photo stop after the house. The estate includes uneven stone paths, steps and garden terrain, so its accessibility information deserves a look before the visit if anyone in your group needs a more predictable route.",
        "Check entry arrangements and accessibility before selecting a time. Choose comfortable footwear for the garden paths and keep the outdoor part flexible around the weather.",
        "https://vizcaya.org/visit-2/planning-your-visit/"),
      pick("Pérez Art Museum Miami", "Miami", true,
        "PAMM is the gallery-led alternative, with changing exhibitions and a visit program that can give the day a clear focus. It works when you want contemporary art to be the main activity rather than another stop on a long checklist. Look at the exhibition calendar before buying admission, and choose the material that interests your group instead of trying to see every room at the same pace.",
        "Check the current opening days and ticket availability. Make the museum your timed anchor, then decide whether another neighborhood still fits without rushing.",
        "https://www.pamm.org/en/visit/"),
      {...pick("Wynwood Walls", "Miami", false,
        "Wynwood Walls is a ticketed outdoor street-art museum, distinct from simply walking through the surrounding neighborhood. Choose it when you want a concentrated mural visit with the museum's curated collection. Leave some time afterward for the area beyond the entrance, but do not confuse a neighborhood stroll with museum admission. Because much of the experience is outdoors, weather changes how comfortably you can linger.",
        "Use the museum's own ticket and visit information. Pair the visit with time in Wynwood rather than adding another distant stop immediately afterward.",
        "https://thewynwoodwalls.com/"), placeId: "ChIJ98BffLK22YgRsymdIvOgjNA"},
      {...pick("Little Havana", "Miami", false,
        "Calle Ocho gives Little Havana a clear starting point for a neighborhood visit. The visitor center and nearby Domino Park help orient you before you explore food, shops and local history. Take the neighborhood at walking pace and leave time for a meal rather than treating it as a drive-through photo stop. Domino Park is a community gathering place; watch respectfully and avoid interrupting games.",
        "Start around Calle Ocho and 15th Avenue, then choose a manageable walking stretch. Use the visitor center for current local information instead of assuming every venue follows the same hours.",
        "https://www.miamiandbeaches.com/l/visitor-information-and-local-services/little-havana-visitor-center/6094"), placeCard: false},
    ], [
      {q: "Can I comfortably do all four Miami stops in a day?", a: "Choose one museum and one neighborhood first. The stops are spread across the city, so leave time for travel and a meal instead of rushing through all four."},
      {q: "Which option has the strongest outdoor focus?", a: "Vizcaya includes gardens, and Wynwood Walls is an outdoor street-art museum. PAMM is the gallery-led alternative when you want the museum visit to be the main activity."},
      {q: "Is Wynwood Walls the same as walking around Wynwood?", a: "No. Wynwood Walls is a ticketed museum; the surrounding neighborhood is a separate part of your visit."},
    ], ["https://www.miamiandbeaches.com/l/outdoor-experiences/domino-park/5611"]),

  "things-to-do-in-ellenton-florida": guide("Ellenton",
    "Ellenton, Florida: A Half Day of History, Shopping and Ice Skating",
    "Plan an Ellenton visit around Gamble Plantation, the outlet center and a public skating session, with clear indoor and outdoor choices.",
    "Ellenton works best as a short outing with one activity you actually want to do. The outlet center, ice rink and historic park offer three very different days, so choose your anchor before leaving home. Start outdoors at Gamble Plantation when you want history, bookend shopping with a public skate when you want something active, or keep the visit to one stop if you are passing through on I-75. The outlets are an outdoor center with covered walkways, not a completely enclosed rainy-day mall. A skating session is the stronger indoor choice, but only when the public schedule matches your visit.", [
      pick("Gamble Plantation Historic State Park", "Ellenton", false,
        "The preserved mansion and grounds give Ellenton a history stop on U.S. 301. This was the headquarters of a sugar plantation, and its later Confederate memorial history is part of what visitors encounter. Choose it for a deliberate history visit rather than treating the building as a pretty backdrop. Grounds access and a guided house tour are different experiences; checking the tour schedule first makes the difference between seeing the exterior and going inside.",
        "Put the house tour first if that is your reason for visiting. The state park lists tours on selected days, so an open park gate does not guarantee an available tour.",
        "https://www.floridastateparks.org/parks-and-trails/judah-p-benjamin-confederate-memorial-gamble-plantation-historic-state-park"),
      pick("Ellenton Premium Outlets", "Ellenton", false,
        "The outlet center is the practical shopping anchor near I-75 and U.S. 301. Its outdoor layout suits a browse with breaks, but individual stores are the reason to go. Pick a handful from the current directory before you arrive instead of trying to cover the whole center. This is an easy pairing with the nearby ice complex when different members of the group want different activities.",
        "Use the directory and center map to choose where to park. Bring rain cover for the walks between shops, even though many walkways are covered.",
        "https://www.premiumoutlets.com/outlet/ellenton/about"),
      pick("Ellenton Ice & Sports Complex", "Ellenton", true,
        "Ice skating gives this outing a proper change of pace from browsing shops. The complex has two ice rinks and runs several kinds of sports programming, so the building being open does not mean the ice is available for casual skating. Choose a published public session and make that the fixed appointment in your day; shopping can fit around it much more easily.",
        "Check the public skating calendar and rental details before driving over. Bring a warm layer for time beside the rink as well as time on the ice.",
        "https://www.ellentonice.com/"),
    ], [
      { q: "What should I choose for a short Ellenton visit?", a: "Choose Gamble Plantation for history, the outlet center for shopping, or a public skating session at the ice complex." },
      { q: "Are the outlets a fully indoor rainy-day option?", a: "No. The outlet center has an outdoor layout with covered walkways. The ice complex is the indoor alternative when a public skating session is available." },
      { q: "Can I fit all three stops into one outing?", a: "Treat the tour or public skate as the fixed appointment and shopping as the flexible stop. Check both schedules before trying to combine them." },
    ]),
  "things-to-do-in-palmetto-florida": guide("Palmetto",
    "Palmetto, Florida: Historic Buildings, a Park Break and Emerson Point",
    "A Palmetto day built around the Historical Park, Sutton Park and coastal trails at Emerson Point, including the dock closure to know before you go.",
    "Palmetto offers two useful halves of a day: a compact history stop downtown and a longer outdoor visit on Snead Island. Start with the Historical Park if you want access to the historic buildings, because that depends on a guided tour. Leave Emerson Point for the part of the day when your group wants trails and water views. Sutton Park is a simple pause between activities, not a substitute for the preserve. You will need to move between downtown and Emerson Point; this is not one continuous walking route.", [
      pick("Palmetto Historical Park", "Palmetto", true,
        "The restored buildings make this the strongest first stop for understanding the town. The Carnegie Library is accessible during opening hours, while the other historic buildings require a guided tour. That distinction matters if you are arriving casually and expecting to enter everything. School programming can also affect the experience, so use the park's current visit information to pick your arrival rather than treating it as an anytime attraction.",
        "Call ahead for the guided tour, especially during school programming season. The park lists street parking and a lot behind the buildings.",
        "https://palmettohistoricalpark.com/"),
      pick("Sutton Park", "Palmetto", false,
        "Sutton Park is the low-commitment outdoor stop in the downtown part of the plan. Use it to stretch your legs or pause between the historic buildings and the drive west. It makes most sense as breathing room within the day, rather than a separate destination requiring a long detour. Check the city calendar if you want a scheduled event; an ordinary park visit does not promise a festival or concert.",
        "Pair it with the Historical Park instead of driving back downtown later. Keep the longer walking time for Emerson Point if that is your priority.",
        "https://www.palmettofl.org/588/Sutton-Park"),
      pick("Emerson Point Preserve", "Palmetto", false,
        "At the western end of Snead Island, Emerson Point combines coastal trails, interpreted historic remains and views around the mouth of the Manatee River. It is the outdoor anchor of this itinerary. The county currently lists a dock closure following hurricane damage, so plan for the walking trails and obey closures rather than building the day around dock access. A paddle requires its own equipment and conditions check.",
        "Use 5801 17th Street West for arrival, bring water, and read the county's current closure notice before leaving. Do not assume every dock or launch has the same access status.",
        "https://www.mymanatee.org/connect/locations/location-details/emerson-point-preserve"),
    ], [
      { q: "Which Palmetto stop needs advance planning?", a: "The Historical Park needs a guided tour for access to its historic buildings beyond the Carnegie Library." },
      { q: "Is Emerson Point a walk from downtown?", a: "Plan it as a separate trip west to Snead Island. Combine downtown's Historical Park and Sutton Park before moving to the preserve." },
      { q: "Is the Emerson Point dock open?", a: "The county currently lists the dock as closed after hurricane damage. Check its current notice before your visit and use only open areas." },
    ]),
  "things-to-do-in-lakewood-ranch-florida": guide("Lakewood Ranch",
    "Lakewood Ranch: Main Street, Lakeside Dining and a Park Afternoon",
    "Choose between Main Street and Waterside Place, then add Waterside Park for a Lakewood Ranch afternoon without unnecessary driving.",
    "Lakewood Ranch has more than one town center, and choosing the right one is the main planning decision. Main Street suits a browse through shops with a meal or a cinema visit. Waterside Place suits lakeside dining and an easy walk over the bridge to Waterside Park. Start with one cluster instead of treating both as stops you have to tick off. Families can make Waterside Park the anchor and eat nearby afterward; adults planning a meal can pick the restaurant first and leave a little time for the waterfront.", [
      pick("Lakewood Ranch Main Street", "Lakewood Ranch", false,
        "Main Street brings cafes, specialty shops, restaurants and entertainment into a pedestrian-friendly center. It is the useful choice when your group wants a little browsing before a meal, or a cinema visit with dinner nearby. The center's directory is a better planning tool than an old list of tenants: select the actual restaurant or activity that appeals to you, then give yourself time to walk around it.",
        "Check the current directory and any event listing before committing. A regular afternoon and a programmed event have different rhythms, so choose the one you want.",
        "https://lakewoodranch.com/main-street/"),
      pick("Waterside Place", "Lakewood Ranch", false,
        "Waterside Place gathers dining, shops and events along Kingfisher Lake. Choose this cluster when the water is part of the outing, rather than just a backdrop seen from the car. A meal and a waterfront stroll are enough for a relaxed visit. If a market, performance or other event is your main reason to come, use its dated listing; the calendar changes and the everyday town center does not guarantee live entertainment.",
        "Keep Waterside Place and Waterside Park together in your plan. The park connects by a pedestrian bridge, so they make a more natural pair than adding another town center.",
        "https://lakewoodranch.com/waterside-place/"),
      pick("Waterside Park", "Lakewood Ranch", false,
        "Across the pedestrian bridge, the island park adds walking paths, a splash pad, volleyball courts, hammocks and open space to the lakeside visit. It is the active half of this plan, particularly for a family that needs more than a restaurant table. Pick the activities that fit the weather and your group rather than expecting to use every amenity in one visit.",
        "Bring what you need for an outdoor stop and check posted splash-pad rules on arrival. The park's pavilions are not reservable, so do not promise a particular table to a group.",
        "https://lakewoodranch.com/waterside-tenants/waterside-park/"),
    ], [
      { q: "Which two stops work together without another drive?", a: "Waterside Place and Waterside Park connect by a pedestrian bridge over Kingfisher Lake." },
      { q: "Should I visit both town centers in one afternoon?", a: "Choose Main Street for its shops, restaurants and cinema, or Waterside Place for lakeside dining and the park. Add the other only when a specific activity makes it worthwhile." },
      { q: "Is there always an event at Waterside Place?", a: "No. Check the dated event calendar when a market or performance is your reason for visiting." },
    ]),
  "things-to-do-in-cortez-florida": guide("Cortez",
    "Cortez, Florida: A Fishing Village Afternoon on the Waterfront",
    "Plan a Cortez outing with dockside seafood, the FISH Preserve and waterfront music, plus the Maritime Museum closure to know about.",
    "Cortez is a good place to slow the plan down: choose one waterfront meal, leave time for the fishing-village setting, and add a preserve walk if conditions suit. Star Fish Company and Swordfish Grill offer different meal moods, so they are alternatives rather than a requirement to eat twice. The Florida Maritime Museum is currently closed for building rehabilitation. Do not build your afternoon around entering the museum; check its own site for programming and reopening news before making a special trip.", [
      pick("Star Fish Company", "Cortez", false,
        "The dockside restaurant puts seafood and the working waterfront together. Its operator describes fish from local inland and offshore waters, with simple preparations and views toward the commercial fleet and nearby islands. Choose it when the meal itself is the main event and you want to linger beside the water. Availability varies with the menu, so ask what is being served instead of arriving for a guaranteed particular catch.",
        "Use the restaurant's current menu and visit information. Leave the rest of the afternoon flexible rather than putting a tightly timed activity immediately after lunch.",
        "https://www.starfishcompany.com/restaurant/"),
      pick("FISH Preserve", "Cortez", false,
        "The preserve maintained by the Florida Institute for Saltwater Heritage adds a conservation stop to the village visit. This is a different experience from a restaurant deck: make it a deliberate outdoor walk, respecting marked access and restoration work. The organization describes the preserve as ongoing work, so a current access check is more useful than assuming every section is an established finished trail.",
        "Check FISH's current visitor guidance before parking or entering, particularly while nearby museum rehabilitation is underway. Follow marked access and leave restoration areas undisturbed.",
        "https://fishcortez.org/the-f-i-s-h-preserve/"),
      pick("Swordfish Grill & Tiki Bar", "Cortez", false,
        "Swordfish Grill is the choice when you want a waterfront meal with a livelier entertainment component. The restaurant publishes a live-music calendar and takes dinner reservations online, which makes it easier to give the evening a fixed anchor. Look at the actual performer and time for your date before choosing it for music, rather than assuming the same show or atmosphere every visit.",
        "Choose either this meal or Star Fish as the day's anchor. If live music matters, check the dated calendar and reserve dinner through the restaurant's own booking option.",
        "https://www.swordfishgrillcortez.com/"),
    ], [
      { q: "Can I visit the Florida Maritime Museum inside?", a: "The Florida Maritime Museum is currently closed for building rehabilitation. Check its own site for reopening news and programming." },
      { q: "Which waterfront restaurant should I choose?", a: "Choose Star Fish Company for a dockside seafood meal, or Swordfish Grill when its dated live-music calendar fits your evening." },
      { q: "Should I plan Cortez as a full day of attractions?", a: "A waterfront meal and an outdoor stop make a relaxed short outing. Leave time for the village rather than expecting a string of indoor attractions." },
    ], ["https://www.floridamaritimemuseum.org/visit"]),
  "things-to-do-in-longboat-key-florida": guide("Longboat Key",
    "Longboat Key: A Beach Visit, Bayfront Break and Coastal Nature Stop",
    "Build a Longboat Key day around public beach access, Bayfront Park and Quick Point, with the parking and pet distinctions that matter.",
    "A Longboat Key visit works better when you choose your beach access before you start driving. The Gulf beach and Sarasota Bay are different sides of the island, with different reasons to stop. Bayfront Park combines practical amenities with a bayside break; the public beach access across Gulf of Mexico Drive gives you a separate Gulf visit. Quick Point, toward the southeast end, is the nature stop. These choices make a manageable outdoor day without assuming that every stretch of beachfront has visitor parking.", [
      pick("Bayfront Park", "Longboat Key", false,
        "Use Bayfront Park as the practical base for a mixed group. The town lists a playground, sports courts, picnic tables and restrooms beside Sarasota Bay. It is the better fit when some people want activity and others want a seated break. This is Longboat Key's park at 4052 Gulf of Mexico Drive, not the similarly named waterfront park in downtown Sarasota.",
        "Bring the equipment you need for a court activity and follow the posted use rules. Treat kayak access as a separate plan requiring suitable conditions and equipment.",
        "https://www.longboatkey.org/Facilities/Facility/Details/Bayfront-Park-1"),
      { name: "Public beach access at 4001 Gulf of Mexico Drive", city: "Longboat Key", indoor: false, appQuery: "4001 Gulf of Mexico Drive Longboat Key", placeCard: false,
        blurb: "The town identifies this public beach access with parking available at Bayfront Park across the road. It makes a useful Gulf-side complement to the bayside park: decide whether you want a short beach walk or a longer stay before carrying everything across. Use the designated access and crossing arrangements, and obey posted parking restrictions rather than assuming the whole beachfront is public parking.",
        tip: "Confirm current parking and beach access conditions with the town. Leave pets out of the beach plan; the town prohibits animals at beach accesses and on the beach.",
        sources: ["https://www.longboatkey.org/331/Beaches"], verifiedAt: checked },
      pick("Quick Point Nature Preserve", "Longboat Key", false,
        "Quick Point gives the south end of the island a wetland and mangrove stop. The town describes restored habitats and a tidal lagoon that supports small fish, crabs and wading birds. Choose it for a patient look at the bay's edges rather than a guaranteed wildlife sighting. Keep to open paths and heed any repair notices, especially after storms.",
        "Check current access before making it your main outing and leave pets at home. The town specifically prohibits pets in this preserve.",
        "https://www.longboatkey.org/197/Quick-Point-Nature-Preserve"),
    ], [
      { q: "Which beach access pairs with Bayfront Park?", a: "The public beach access at 4001 Gulf of Mexico Drive has parking available at Bayfront Park across the road." },
      { q: "Is Bayfront Park the Gulf beach?", a: "No. The park faces Sarasota Bay. Use the designated public beach access across Gulf of Mexico Drive for the Gulf side." },
      { q: "Can I take my dog to these stops?", a: "Do not take pets onto the beach or into Quick Point. Bayfront Park has a separate dog park with its own rules, rather than unrestricted pet access throughout the park." },
    ], ["https://www.longboatkey.org/191/Bayfront-Park"]),
  "things-to-do-in-venice-florida": guide("Venice",
    "Venice, Florida: Beach Time, Local History and a Coastal Walk",
    "Choose an easy Venice Beach visit, the Venice Museum or a planned walk to Caspersen, with current vehicle-access limits clearly explained.",
    "Start a Venice day by deciding how much walking you want. Venice Beach is the simpler beach anchor, with the city listing parking and visitor amenities. The Venice Museum gives the trip an indoor history stop in the historic Triangle Inn. Caspersen needs a different plan: the county currently says vehicle access, restrooms and the playground remain closed after storm damage, while pedestrians and bicycles can enter. Choose the beach that fits your group instead of assuming the two have interchangeable facilities.", [
      pick("Venice Beach", "Venice", false,
        "Venice Beach is the straightforward choice when you want a beach visit supported by nearby amenities. The city lists a pavilion, boardwalks, picnic space and parking, with additional parking across the street near Graser Park. Make this the default beach stop when your group does not want to work around Caspersen's access restrictions. Conditions on the water still determine how you use the beach on the day.",
        "Check posted beach conditions when you arrive. If the main parking area is full, follow the city's designated alternatives rather than improvising parking on nearby streets.",
        "https://www.venicegov.com/Home/Components/FacilityDirectory/FacilityDirectory/62/225?npage=2"),
      pick("Venice Museum", "Venice", true,
        "Inside the historic Triangle Inn, the museum offers a way to understand the city beyond its shoreline. The museum provides context for the streets and buildings you see around the city. Use this as the indoor part of the day when local history interests your group, and check the museum's current opening schedule before placing it between beach stops.",
        "Make the museum the scheduled stop and the beach the flexible one. Verify the current exhibition and opening days rather than assuming daily admission.",
        "https://www.venicegov.com/Home/Components/News/News/5958/"),
      pick("Caspersen Beach Park", "Venice", false,
        "Caspersen is the more involved coastal option while storm repairs limit access. The county currently allows pedestrian and bicycle entry but lists the vehicle parking, restrooms and playground as closed. It identifies access from South Brohard Park or the Venetian Waterway Park Trail at the City of Venice Festival Grounds. Choose it only when the walk or ride is part of what you want, not when you need convenient facilities beside the car.",
        "Read the county's current closure notice before setting out. Bring water and plan around the lack of vehicle parking and restrooms at Caspersen; use Venice Beach if that does not fit your group.",
        "https://www.scgov.net/Home/Components/FacilityDirectory/FacilityDirectory/603/41?selamenityid=5&sortd=asc-134&sortn=FCName-134&widgetId=134"),
    ], [
      { q: "Can I drive into Caspersen Beach Park?", a: "The county currently lists vehicle access and parking at Caspersen as closed. Pedestrian and bicycle access remain available." },
      { q: "Which Venice beach is the easier choice with visitor facilities?", a: "Choose Venice Beach when you want the simpler beach stop. Caspersen currently requires planning around closed parking, restrooms and playground facilities." },
      { q: "What can I add beyond the beach?", a: "The Venice Museum in the historic Triangle Inn adds an indoor local-history stop. Check its opening schedule before you go." },
    ]),
};

// A deliberate guide choice for every configured Florida city. An area's useful
// existing guide is preferred over a second page chasing the same search intent.
export const FLORIDA_CITY_GUIDES = Object.freeze({
  parrish: "things-to-do-in-parrish-florida",
  ellenton: "things-to-do-in-ellenton-florida",
  palmetto: "things-to-do-in-palmetto-florida",
  bradenton: "things-to-do-in-bradenton-florida",
  sarasota: "things-to-do-in-sarasota-florida",
  "lakewood-ranch": "things-to-do-in-lakewood-ranch-florida",
  "anna-maria-island": "anna-maria-island-day-trip",
  cortez: "things-to-do-in-cortez-florida",
  "longboat-key": "things-to-do-in-longboat-key-florida",
  "siesta-key": "siesta-key-vs-lido-key",
  venice: "things-to-do-in-venice-florida",
  tampa: "things-to-do-in-tampa-florida",
  orlando: "things-to-do-orlando-not-theme-parks",
  miami: "things-to-do-in-miami-florida",
});
