// v4.16 — SEO guide content. Server-rendered, indexable pages targeting the
// four affiliate keyword types (general "best of", branded comparison, review,
// trust-and-authority). Editorial rules match the app: honest picks, famous
// verifiable claims only, affiliate links disclosed. Each pick's bookQuery
// drives a Viator search link; hotel:true drives a Booking.com rate link.

export const SITE_NAME = "Wayfind";

export const GUIDES = {
  "winter-park-scenic-boat-tour": {
    region: "Orlando",
    title: "Winter Park Scenic Boat Tour: Is It Worth It? (Local's Review)",
    description: "Everything to know before the Winter Park Scenic Boat Tour: what you'll see, tickets, parking, the cash-only catch, and whether it earns your hour.",
    keyword: "winter park scenic boat tour",
    updated: "2026-07-07",
    intro: "Running continuously since 1938, the Winter Park Scenic Boat Tour is Orlando's oldest attraction and its least Orlando one: an hour gliding the Winter Park chain of lakes past mansions, moss canals, and rowing crews, narrated by drivers who've done it for decades. Short answer on worth it: yes, and here's how to do it right.",
    picks: [
      { name: "What the hour actually covers", appQuery: "Winter Park Scenic Boat Tour", blurb: "Three lakes and two hand-dug canals barely wider than the pontoon, with Spanish moss brushing overhead. The narration mixes mansion gossip, Rollins College history, and genuine old-Florida knowledge.", tip: "Left side of the boat gets the best canal shade and photo angles.", bookQuery: "Winter Park scenic boat tour" },
      { name: "Tickets, timing, and the cash catch", appQuery: "Winter Park Scenic Boat Tour", blurb: "Tours leave hourly from the Morse Boulevard dock; no reservations, first-come. The famous quirk: the ticket window is cash or check only, and the ATM walk will cost you your boat slot on busy days.", tip: "Weekday mornings walk right on; weekend afternoons can mean an hour wait." },
      { name: "Make it a Winter Park day", appQuery: "Winter Park, FL", blurb: "The dock sits two blocks off Park Avenue: Tiffany glass at the Morse Museum, lunch on the Avenue, and the boat tour makes the single best non-park day in Orlando.", tip: "SunRail from downtown stops three blocks from the dock, making this Orlando's easiest car-free outing." },
    ],
    faq: [
      { q: "How much does the Winter Park boat tour cost?", a: "Adult tickets run around $18 and children about $9, cash or check only at the dock window. Prices drift, so bring a cushion." },
      { q: "How long is the tour?", a: "One hour, narrated, departing hourly from 10am with the last tour at 4pm most days, weather permitting." },
      { q: "Do you see alligators?", a: "Occasionally, along with ospreys, herons, and the odd otter. It's a calm-water mansion-and-nature cruise, not a wildlife expedition; for gators, take an airboat instead." },
    ],
  },
  "siesta-key-drum-circle": {
    region: "Sarasota",
    title: "Siesta Key Drum Circle: Times, Parking, and What to Expect",
    description: "The complete guide to Sarasota's Sunday sunset ritual: when the drum circle starts, where to park, what it's like, and the etiquette locals wish you knew.",
    keyword: "siesta key drum circle",
    updated: "2026-07-07",
    intro: "Every Sunday about two hours before sunset, a patch of Siesta Key's quartz sand turns into Florida's most reliable spontaneous festival: drummers, dancers, hoopers, and a few hundred strangers facing west. It's free, it's unorganized by design, and it's been happening for over two decades. Here's how to do it like you've been before.",
    picks: [
      { name: "When and exactly where", appQuery: "Siesta Key Beach", blurb: "Sundays year-round, starting roughly two hours before sunset and peaking as the sun drops. Walk south from the main Siesta Beach pavilion about 200 yards; follow the drums.", tip: "Check the sunset time for your date and arrive 90 minutes early for a decent spot on busy season Sundays." },
      { name: "Parking without the meltdown", blurb: "The free main lot fills by mid-afternoon on Sundays. The move is the free Siesta Key Breeze trolley, which runs the length of the island and drops at the beach entrance.", tip: "Park once in the Village, dinner after, trolley both ways." },
      { name: "The unwritten rules", blurb: "Anyone can drum, dance, or watch; the circle is participatory. What draws stink-eye: flash photography in people's faces, standing dead center, and leaving trash on the sand.", tip: "Bring a drum if you have one; nobody auditions." },
    ],
    faq: [
      { q: "Is the Siesta Key drum circle every Sunday?", a: "Yes, weekly on Sundays year-round, weather permitting, starting about two hours before sunset. Some holiday weeks draw bigger crowds and extra performers." },
      { q: "Is it family friendly?", a: "Before and through sunset, very; kids dance in the circle constantly. Later in the evening the vibe skews adult." },
      { q: "Does it cost anything?", a: "Nothing. It's an informal community gathering on a public beach; parking is the only cost if you miss the free lot." },
    ],
  },
  "pinecraft-sarasota-amish-village": {
    region: "Sarasota",
    title: "Pinecraft: Inside Sarasota's Amish Village (And Yoder's Famous Pie)",
    description: "Florida's most unexpected neighborhood: how Pinecraft became the Amish winter capital, what to eat at Yoder's and Der Dutchman, and how to visit respectfully.",
    keyword: "pinecraft sarasota",
    updated: "2026-07-07",
    intro: "Tucked off Bahia Vista Street sits a neighborhood where Amish and Mennonite snowbirds have wintered for a century: adult-sized tricycles instead of buggies, shuffleboard courts that fill at dusk, and restaurants whose pies have national reputations. Pinecraft is real, it's welcoming, and it's unlike anywhere else in Florida.",
    picks: [
      { name: "Yoder's Restaurant", blurb: "The anchor since 1975. Fried chicken, real mashed potatoes, and the peanut butter cream pie that draws the line out the door. Featured on national food TV and somehow still underrated.", tip: "Closed Sundays, cash-friendly, and the pie counter next door skips the restaurant wait." },
      { name: "Der Dutchman", blurb: "The bigger Amish kitchen up the street: broasted chicken, a bakery the size of a gift shop, and breakfast that ends any diet.", tip: "The bakery's cinnamon rolls sell out on winter weekends by late morning." },
      { name: "The village itself", blurb: "Walk Pinecraft Park at dusk in season and you'll find shuffleboard leagues, bocce, and tricycles parked twenty deep. Big Olaf's ice cream, founded by an Amish family, closes the evening properly.", tip: "Season peaks January through March, when the Pioneer Trails buses arrive from Ohio and Indiana weekly." },
      { name: "How to visit respectfully", appQuery: "Pinecraft, Sarasota", blurb: "This is a residential neighborhood, not an attraction. Photograph the place, not the people, without asking; dress modestly in the restaurants; and remember Sunday is genuinely quiet.", tip: "If you're respectful, conversation comes easy; residents are famously warm with visitors." },
    ],
    faq: [
      { q: "Is Pinecraft open to visitors?", a: "Yes. The restaurants, bakeries, and shops welcome everyone. It's a working neighborhood, so visit like a guest rather than a spectator." },
      { q: "When is the best time to visit Pinecraft?", a: "December through March, when the winter community is fully present and the park is lively at dusk. Summer is quiet with some businesses on reduced hours." },
      { q: "Do the Amish in Pinecraft use cars?", a: "Most travel to Sarasota by chartered bus and get around on adult tricycles and bikes, a Pinecraft signature. Rules relax somewhat in the winter community compared with northern settlements." },
    ],
  },
  "siesta-key-vs-lido-key": {
    region: "Sarasota",
    title: "Siesta Key vs Lido Key: Which Sarasota Beach Is Right for You?",
    description: "The honest comparison locals give visitors: sand, crowds, parking, food, and which key fits your kind of beach day.",
    keyword: "siesta key vs lido key",
    updated: "2026-07-07",
    intro: "Sarasota's two famous keys sit twenty minutes apart and deliver completely different days. Pick by what you want from the beach, not by which name you've heard more.",
    picks: [
      { name: "Siesta Key: the sand", blurb: "The 99% quartz sand is genuinely different, powder-cool even at noon, and the beach is vast. It's also the busy one: spring break energy, packed village bars, and a parking hunt after 10am.", tip: "The free lot fills early; ride the open-air Breeze trolley instead of circling." },
      { name: "Lido Key: the balance", blurb: "Softer crowds, easy parking, and St. Armands Circle's restaurants a five-minute walk from the sand. The sand is fine white, not quartz, and nobody sober complains.", tip: "North Lido is the quiet stretch locals keep to themselves." },
      { name: "The verdict", blurb: "First visit or beach-obsessed: Siesta, the sand earns the hassle once. Staying several days, dining well, or traveling with people who hate crowds: Lido wins the week.", tip: "Do Siesta's Sunday sunset drum circle regardless of where you base." },
    ],
    faq: [
      { q: "Which has better sunsets?", a: "Both face west and deliver; Siesta adds the drum circle on Sundays, Lido adds dinner at the Circle afterward." },
      { q: "Are either good for shelling?", a: "Neither compares to Venice Beach twenty minutes south, the shark tooth capital; bring a sifter there instead." },
    ],
  },
  "things-to-do-sarasota": {
    region: "Sarasota",
    title: "10 Best Things to Do in Sarasota Beyond the Beach",
    description: "The Ringling, Pinecraft's Amish village, kayaking with manatees: what fills a Sarasota trip when you're sandy enough.",
    keyword: "things to do in sarasota",
    updated: "2026-07-07",
    intro: "Sarasota calls itself Florida's Cultural Coast and, unusually for Florida marketing, the claim holds. Here's what earns your non-beach hours.",
    picks: [
      { name: "The Ringling", blurb: "John Ringling's 66-acre bayfront estate: a serious art museum, the Ca' d'Zan mansion, and the circus museum with the world's largest miniature circus.", tip: "Mondays the art museum is free; the grounds alone justify the trip.", bookQuery: "Ringling Museum" },
      { name: "Kayak Lido's mangrove tunnels", blurb: "Paddle shaded tunnels where manatees and dolphins turn up regularly, minutes from downtown.", tip: "Morning glass-calm water beats afternoon wind.", bookQuery: "Sarasota mangrove kayak tour" },
      { name: "Pinecraft", blurb: "A genuine Amish and Mennonite winter village inside the city, tricycles, shuffleboard, and Yoder's pie. One of Florida's most unexpected neighborhoods.", tip: "Yoder's is cash-friendly and closed Sundays." },
      { name: "Marie Selby Botanical Gardens", blurb: "Bayfront gardens with the world's best epiphyte collection, orchids and air plants in open air.", tip: "The banyan grove is the photo." },
      { name: "Mote Marine Laboratory", blurb: "A working marine research lab with an aquarium attached; the shark tank and manatee rehab give it substance a tourist aquarium lacks.", tip: "Pair it with north Lido beach across the road.", bookQuery: "Mote Marine aquarium" },
      { name: "Sarasota Farmers Market", blurb: "Saturday mornings downtown since 1979, produce to live music; the town shows up." },
    ],
    faq: [
      { q: "Is Sarasota worth it without a car?", a: "Downtown, the bayfront, and Lido via trolley work car-free; the Ringling and Siesta realistically want wheels." },
      { q: "Best month to visit?", a: "April and May: post-snowbird, pre-summer humidity, water already warm." },
    ],
  },
  "best-cuban-sandwich-tampa": {
    region: "Tampa",
    title: "The Best Cuban Sandwich in Tampa: Where the Original Still Lives",
    description: "Tampa invented the Cuban sandwich in Ybor City's cigar factories. Here's where to eat the real one, salami and all.",
    keyword: "best cuban sandwich tampa",
    updated: "2026-07-07",
    intro: "The Cuban sandwich was born in Tampa, built for Ybor City cigar workers, and the Tampa original includes Genoa salami, the Italian workers' contribution that Miami omits and Tampa defends with civic pride. These are the places that still do it justice.",
    picks: [
      { name: "Columbia Restaurant", blurb: "Florida's oldest restaurant, in Ybor since 1905, pressing Cubans on house-baked bread longer than almost anyone alive. The 1905 Salad alongside is mandatory.", tip: "Lunch at the original Ybor location, not the satellites, for the full room.", bookQuery: "Ybor City food tour" },
      { name: "La Segunda Central Bakery", blurb: "Baking Tampa's Cuban bread since 1915 with the palmetto leaf scored down each loaf; most great Cubans in town start here anyway, so go to the source.", tip: "Take a loaf to go; it doesn't survive the drive home uneaten." },
      { name: "West Tampa Sandwich Shop", blurb: "A no-frills counter that beat celebrity chefs in citywide Cuban contests; presidents have detoured here.", tip: "Cash, weekday mornings, order the Cuban with a cafe con leche." },
      { name: "The rules of a Tampa Cuban", appQuery: null, blurb: "Ham, mojo roast pork, Genoa salami, Swiss, pickles, mustard, on real Cuban bread, pressed. No mayo, no lettuce, no tomato, and anyone serving it cold owes Ybor an apology.", tip: "Order it 'pressed hard' if you like the crackle." },
    ],
    faq: [
      { q: "Tampa vs Miami Cuban: what's actually different?", a: "Salami. Tampa's original includes it from Ybor's Italian community; Miami's version drops it. Both cities are certain they're right; the sandwich was born in Tampa." },
      { q: "Is Ybor City safe to visit?", a: "The historic district is a daytime tourist staple and a lively nightlife strip; standard city awareness applies after dark." },
    ],
  },
  "st-armands-circle-restaurants": {
    region: "Sarasota",
    title: "The 6 Best Restaurants on St. Armands Circle",
    description: "Where to actually eat on the Circle: the waterfront splurge, the locals' bistro, and the ice cream line worth joining.",
    keyword: "st armands circle restaurants",
    updated: "2026-07-07",
    intro: "St. Armands Circle has thirty-plus places to eat wrapped around one roundabout, which makes choosing feel random. It isn't. These six cover every kind of Circle evening, ranked by what each does best.",
    picks: [
      { name: "Columbia Restaurant", blurb: "The Sarasota outpost of Tampa's 1905 institution; the 1905 Salad tossed tableside and the Cuban bread travel perfectly across the bay.", tip: "The courtyard tables are the seat." },
      { name: "Café L'Europe", blurb: "The Circle's white-tablecloth anchor since 1973, continental classics done seriously; this is the anniversary table.", tip: "Bar dining takes walk-ins the dining room can't." },
      { name: "Shore", blurb: "Bright, modern, coastal; the grouper tacos and a rosé on the balcony is the platonic Lido lunch.", tip: "Sunset window tables go early; call ahead." },
      { name: "Crab & Fin", blurb: "The seafood splurge with the raw bar and live piano on the patio.", tip: "Stone crab in season is why you're here." },
      { name: "Kilwins", blurb: "Yes, the fudge chain, but the after-dinner waffle-cone stroll around the lit Circle is the actual Sarasota ritual.", tip: "One scoop; the cones are enormous." },
      { name: "Blue Dolphin Café", blurb: "The locals' breakfast counter hiding among the boutiques; beach-day fuel without resort pricing.", tip: "Before 9am on weekends beats the wait." },
    ],
    faq: [
      { q: "Is parking on the Circle bad?", a: "Free but competitive; the garage on Adams Drive and the side streets solve what the roundabout can't." },
      { q: "Dress code?", a: "Florida elegant: collars and sundresses at dinner, flip-flops forgiven everywhere before sunset." },
    ],
  },
  "best-restaurants-disney-springs": {
    region: "Orlando",
    title: "The 7 Best Restaurants at Disney Springs, Ranked by a Local",
    description: "Where to actually eat at Disney Springs: the seven restaurants worth your reservation, what to order, and which tourist traps to skip.",
    keyword: "best restaurants disney springs",
    updated: "2026-07-07",
    intro: "Disney Springs has more than 60 places to eat, and most lists just copy the map. This one ranks the seven that earn a reservation, based on what each kitchen actually does best, when to go, and what to order. Every pick links into the Wayfind app for live hours, photos, and directions.",
    picks: [
      { name: "The Boathouse", blurb: "Steak and seafood on the water with the amphicar launch as dinner theater. The filet and the baked Alaska are the plays; ask for dock seating at sunset.", tip: "Walk-up bar seating is the locals' workaround when reservations are gone." },
      { name: "Morimoto Asia", blurb: "Iron Chef Masaharu Morimoto's pan-Asian flagship. The Peking duck for two is the signature and worth planning around.", tip: "Lunch menu carries several dinner items at lower prices." },
      { name: "Homecomin'", blurb: "Chef Art Smith's Florida comfort food. The fried chicken and doughnuts made this the Springs' hardest table; hummingbird cake to finish.", tip: "The bar pours moonshine cocktails without the dining wait." },
      { name: "Wine Bar George", blurb: "The only Master Sommelier-led wine bar in Florida, 140+ wines by the glass and ounce, and the frozen wine slushies are better than they have any right to be.", tip: "Go for the burger; it quietly competes with the wine." },
      { name: "Jaleo by José Andrés", blurb: "Spanish tapas from a legendary chef; the paella cooked over wood fire and the gin and tonics carry the menu.", tip: "Weekday lunch is the value window." },
      { name: "Gideon's Bakehouse", blurb: "The half-pound cookies with the cult line. The virtual queue opens in the morning and caps fast.", tip: "Join the virtual line before noon, then shop while you wait." },
      { name: "Chef Art Smith's take on brunch or T-REX for families", appQuery: "Homecomin Disney Springs", blurb: "If you're with kids who need spectacle, T-REX delivers animatronic dinosaurs and a menu built for them. Adults dining without kids should trade it for any pick above.", tip: "Ask for the Ice Cave room." },
    ],
    faq: [
      { q: "Do you need park tickets for Disney Springs?", a: "No. Disney Springs is free to enter, parking is free, and none of these restaurants require park admission." },
      { q: "How far ahead should you book?", a: "60 days for The Boathouse and Homecomin' on weekends; walk-ups are realistic on weekday afternoons." },
    ],
  },
  "best-hotels-near-magic-kingdom": {
    region: "Orlando",
    title: "Best Hotels Near Magic Kingdom for Families (2026 Guide)",
    description: "The hotels that actually shorten your Magic Kingdom mornings: monorail access, early entry, and the value plays most families miss.",
    keyword: "best hotels near magic kingdom",
    updated: "2026-07-07",
    intro: "Proximity to Magic Kingdom is measured in minutes-to-rope-drop, not miles. This guide ranks stays by how they get you to the gate: monorail, boat, walking path, or car, and flags where the value plays are for families who'd rather spend on the parks.",
    picks: [
      { name: "Disney's Contemporary Resort", blurb: "The only hotel you can walk to Magic Kingdom from, ten minutes gate to gate, with the monorail running through the lobby.", tip: "Garden wing rooms cost meaningfully less than the tower.", hotel: true },
      { name: "Disney's Polynesian Village Resort", blurb: "Monorail access, the best resort beach on Seven Seas Lagoon, and fireworks views from the sand with the soundtrack piped in.", tip: "Capt. Cook's quick service is a budget saver inside a deluxe resort.", hotel: true },
      { name: "Disney's Grand Floridian", blurb: "The flagship. Monorail plus a walking path to Magic Kingdom, afternoon tea, and the highest polish on property.", tip: "Outer building rooms beat main building on price.", hotel: true },
      { name: "Disney's Wilderness Lodge", blurb: "Boat to Magic Kingdom through pine forest; the lobby alone is an attraction. Usually the cheapest deluxe with direct water access.", tip: "Courtyard view rooms give the geyser show for less.", hotel: true },
      { name: "Disney's Fort Wilderness Cabins", blurb: "Full cabins with kitchens, boat access, and the campfire sing-along; the sleeper pick for families of five-plus.", tip: "The Hoop-Dee-Doo Revue here is Disney's longest-running show for a reason.", hotel: true },
      { name: "Four Seasons Orlando", blurb: "Off the monorail but the best pure hotel in the area, with a lazy river kids don't want to leave and adult luxury everywhere else.", tip: "Character breakfast here skips park crowds entirely.", hotel: true },
    ],
    faq: [
      { q: "Is staying on-site worth it for Magic Kingdom?", a: "For rope-drop families, usually yes: early theme park entry (30 minutes) plus transportation time saved compounds across a week." },
      { q: "What's the budget alternative?", a: "Good-neighbor hotels on Hotel Plaza Boulevard cost far less and sit minutes from the gates by car; you trade early entry for cash." },
    ],
  },
  "gatorland-vs-wild-florida": {
    region: "Orlando",
    title: "Gatorland vs Wild Florida: Which Orlando Gator Park Wins?",
    description: "A straight comparison of Orlando's two gator attractions: shows, airboats, price, drive time, and which one fits your day.",
    keyword: "gatorland vs wild florida",
    updated: "2026-07-07",
    intro: "Both parks deliver Florida's original theme: alligators, up close. They're built differently, and picking wrong wastes half a day. Here's the honest breakdown after considering what each does best.",
    picks: [
      { name: "Gatorland: the classic park", blurb: "The 'Alligator Capital of the World' since 1949. Stronger shows (Gator Jumparoo), a breeding marsh boardwalk with wild birds, the white leucistic gators, and a zip line over the alligator pens for the brave.", tip: "The Screamin' Gator zip line sells out; book it, not just admission.", viatorUrl: "https://www.viator.com/tours/Orlando/Gatorland-General-Admission-Ticket/d663-3458ENTRY" },
      { name: "Wild Florida: the airboat experience", blurb: "Built around real airboat rides on Lake Cypress headwaters, wild gators in wild water, plus a compact gator park and drive-through safari. The airboat is the product; the park is the bonus.", tip: "Morning rides see more wildlife before boat traffic picks up.", bookQuery: "Wild Florida airboat" },
      { name: "The verdict", blurb: "Choose Gatorland for a fuller half-day park with better shows and shorter drive from the parks corridor. Choose Wild Florida if the airboat is the point, it's the better ride of the two, and you don't mind the longer drive south.", tip: "Doing both in one trip is overkill unless gators are the trip." },
    ],
    faq: [
      { q: "Which is closer to Disney?", a: "Gatorland, roughly 25 minutes from the parks corridor; Wild Florida runs 45 to 55 minutes south." },
      { q: "Are airboat rides safe for young kids?", a: "Both operators take young children with ear protection provided; infants are better suited to the parks than the boats." },
    ],
  },
  "things-to-do-orlando-not-theme-parks": {
    region: "Orlando",
    title: "12 Things to Do in Orlando That Aren't Theme Parks",
    description: "Airboats, springs, Winter Park, rocket launches: what locals actually do in Orlando when nobody's buying park tickets.",
    keyword: "things to do in orlando besides theme parks",
    updated: "2026-07-07",
    intro: "Orlando's best-kept secret is that locals rarely set foot in the parks. This is the non-park list worth building days around: real Florida nature, the elegant side of the city, and day trips that outdo any queue.",
    picks: [
      { name: "Airboat the Everglades headwaters", blurb: "Forty minutes from the parks, skimming marsh past wild gators and eagles. The single most Florida hour available to a visitor.", tip: "Sunset rides trade some wildlife for the best light.", bookQuery: "Orlando airboat tour" },
      { name: "Winter Park scenic boat tour", blurb: "A pontoon glide through chain-of-lakes mansions and moss canals, running since 1938. Pair it with Park Avenue lunch and the Morse Museum's Tiffany glass.", tip: "Cash or check only at the dock; it's part of the charm.", bookQuery: "Winter Park boat tour" },
      { name: "Kayak a natural spring", blurb: "Rock Springs at Kelly Park runs 68 degrees and crystal clear year-round; paddle it early before tubes fill the run.", tip: "County park capacity caps on weekends; arrive before 9am.", bookQuery: "Rock Springs kayak" },
      { name: "Watch a rocket launch", blurb: "Cape Canaveral is an hour east and launches are frequent now. Playalinda Beach and Titusville's waterfront give the clearest views.", tip: "Check the launch schedule the week of your trip and hold a flex morning." },
      { name: "Lake Eola and Thornton Park", blurb: "Downtown's swan boats, Sunday farmers market, and the city's best sunset walk, free.", tip: "Swan boats stop seating 45 minutes before close." },
      { name: "ICON Park's wheel at night", blurb: "The 400-foot observation wheel earns its ticket after dark when the parks corridor lights up.", tip: "Combo tickets with Madame Tussauds or SEA LIFE cut the per-attraction price.", bookQuery: "ICON Park wheel" },
    ],
    faq: [
      { q: "What's the best non-park day trip?", a: "Kennedy Space Center if a launch aligns; otherwise Winter Park for a slow day or the springs for an active one." },
      { q: "Is any of this doable without a car?", a: "Winter Park via SunRail and ICON Park via rideshare work car-free; airboats and springs realistically need wheels." },
    ],
  },
};
