// lib/guidesGulfCoast2026.js — the Gulf Coast cluster: Parrish, Sarasota, Tampa.
//
// Researched and fact-checked 2026-08-13 against Tier 1 sources (the operator's
// own site first). Per-item sourcing lives in the project docs
// wayfind-blog-{parrish,sarasota,tampa}-things-to-do-2026-08-13.
//
// EVERGREEN — no sunset date. These are the three anchor city guides for the
// Manatee/Sarasota/Hillsborough corridor and they interlink: every guide links
// up to Florida and sideways to its two siblings.
//
// NEW IN THIS FILE: picks may carry `placeId`. When present the guide renders a
// real Wayfind place card (photo, hours, the "Right now" line from
// wf_inventory.editorial_card) instead of a bare link. Picks without a placeId
// fall back to the existing "Open in Wayfind" behaviour, so nothing regresses.
// A place with no verified affiliate carriage still gets a card — parks and free
// beaches are the trust budget that makes the commercial cards convert.

export const GULF_COAST_2026_GUIDES = {
  "things-to-do-in-parrish-florida": {
    teaser: "The Willow Express is a 13-mile round trip that runs rain or shine, but you cannot see manatees at Lake Manatee State Park.",
    region: "Parrish",
    title: "10 Best Things to Do in Parrish, Florida (2026 Local Guide)",
    description: "Historic train rides, a 76-acre riverside park, an organic farm market, Manatee River sunsets and easy Gulf beach day trips. The best things to do in Parrish, Florida, verified August 2026.",
    keyword: "things to do in parrish florida",
    updated: "2026-08-13",
    intro: "Parrish used to be the place you drove through on the way somewhere else. It is quietly becoming one of the more interesting pockets of northern Manatee County — historic trains disappearing into Old Florida, organic vegetables growing minutes from brand-new subdivisions, kayaks sliding into the Manatee River, and sunsets that make you wonder why everyone else is fighting for parking at the beach. Most of this list costs under $10.",
    picks: [
      { name: "Florida Railroad Museum", indoor: false, appQuery: "Florida Railroad Museum", placeId: "ChIJ______8sw4gRMudh58gsGMU", blurb: "You do not walk around looking at old trains here — you ride one. The Willow Express is a 13-mile round trip from Parrish to Willow, about an hour and a half, with a stop to walk the rail collection. It is diesel-powered and runs rain or shine, which quietly makes it one of the best bad-weather plans in the county.", tip: "The ticket office runs Wednesday to Sunday, 10am to 4pm, and seasonal or themed departures sell out — book ahead." },
      { name: "Fort Hamer Park", indoor: false, appQuery: "Fort Hamer Park", placeId: "ChIJu9V8cNY6w4gR14jQbFoNfsE", blurb: "A compact riverside park, about 7.3 acres, sitting directly on the Manatee River with a boat ramp, a pavilion and real water access. It is also home to Manatee County's rowing programme, so on a good morning you will watch shells slice across water most visitors never knew was here.", tip: "The last hour before sunset over the Manatee River is the most underrated thing in inland Manatee County. Boat ramp parking fills early on weekends." },
      { name: "Gamble Creek Farms", indoor: false, appQuery: "Gamble Creek Farms", blurb: "A 26-acre Real Organic Certified farm growing produce right in Parrish, operating as both a working farm and a community destination with a market. They sell fresh produce alongside other Florida-grown products, run group tours and host free seasonal family events.", tip: "Market days and hours shift with the growing season — check current hours before you drive over. Buy the thing you did not come for." },
      { name: "Lake Manatee State Park", indoor: false, appQuery: "Lake Manatee State Park", placeId: "ChIJU17a-Akxw4gR3ppLxjXbveg", blurb: "The park runs three miles along the south shore of Lake Manatee with camping, fishing, hiking, swimming, boating, paddling and picnicking. And no — you cannot see manatees here. A dam built across the Manatee River in the mid-1960s created the lake and blocks them from reaching it. The name comes from the river and the county, not the animal.", tip: "$5 per vehicle, sunrise to sunset. Go early: in July and August the afternoon heat index here regularly clears 100F." },
      { name: "Bunker Hill Community Park", indoor: false, appQuery: "Bunker Hill Community Park", blurb: "Most Parrish lists miss this one entirely. Roughly 76 acres with fishing access, canoe and kayak launching, open fields, a playground, a pavilion and a 1.2-mile nature trail with fitness stations. If Parrish Community Park is the polished gathering place, Bunker Hill is where you go when you want space.", tip: "For more wild Florida nearby, Rye Preserve protects roughly 530 acres northwest of the Lake Manatee dam, free and open daily sunrise to sunset. Between Bunker Hill, Rye and Lake Manatee, Parrish has far more nature around it than first impressions suggest." },
      { name: "Parrish Community Park", indoor: false, appQuery: "Parrish Community Park", placeId: "ChIJJSK6DAolw4gR2-tcgDhSPVI", blurb: "Older guides describe this as a future project. Not anymore — it is open, on Fort Hamer Road, with a splash pad, playground, amphitheatre, boardwalk and multi-purpose trail. The amphitheatre matters more than it looks: as Parrish grows it gives the community an actual place to gather.", tip: "The splash pad runs seasonally, so check before you promise the kids. Pavilion rentals include tables, grills, restrooms and electric." },
      { name: "Ferraro's Italian Grille", indoor: true, appQuery: "Ferraro's Italian Grille", placeId: "ChIJVaGvf6gkw4gROjdp7yQzLh4", blurb: "Family-run, with roots going back three generations — the family has been in the restaurant business since 1980. Parrish's restaurant scene is still young, which is exactly why its established local places matter.", tip: "When you are exploring a new town, give at least one meal to a local business. Parrish rewards that rule better than most places its size." },
      { name: "Good Liquid Brewing Company", indoor: true, appQuery: "Good Liquid Brewing Company Parrish", placeId: "ChIJay8TEmElw4gRmgRP3SXl7eM", blurb: "The contemporary option, pairing locally brewed beer with food and cocktails at its Parrish location. Fully indoors, which matters when the 3pm storm arrives.", tip: "The Parrish Creekside Commons location is the one you want — it is the newer room and it is set up for a long afternoon." },
      { name: "Ellenton Premium Outlets", indoor: true, appQuery: "Ellenton Premium Outlets", placeId: "ChIJKYwJVy0jw4gRkXnEq-Or48M", blurb: "Technically Ellenton, not Parrish, and close enough to belong in any practical guide to the area. Nike Factory Store, Kate Spade, Under Armour, Gap Factory and others. We would not pick shopping over a perfect Florida afternoon on the water — but when a thunderstorm rolls in off the Gulf at 3pm, and in summer it will, this is a different conversation.", tip: "Save this for genuinely brutal heat, real rain, or when someone in your group insists shopping counts as an activity." },
      { name: "Coquina Beach and Anna Maria Island", indoor: false, appQuery: "Coquina Beach", placeId: "ChIJ5eLMVXE9w4gR15l0tMZGkMY", blurb: "Parrish is not a beach town, and that turns out to be useful: you get the quieter pace of inland Manatee County and a Gulf Coast day whenever the mood hits. Head west for white sand, warm Gulf water, and an afternoon whose hardest decision is whether you are ready to leave.", tip: "Make it a real day — beach first, sunset second, dinner after. Do not rush back." },
    ],
    faq: [
      { q: "Can you see manatees at Lake Manatee State Park?", a: "No. A dam built across the Manatee River in the mid-1960s created the lake and blocks manatees from reaching it. The name comes from the river and the county, not the animal. To see manatees, look to the Manatee River itself." },
      { q: "Are there free things to do in Parrish, Florida?", a: "Yes — most of the best things in Parrish are free. Fort Hamer Park, Parrish Community Park, Bunker Hill Community Park and Rye Preserve all cost nothing. Lake Manatee State Park is $5 per vehicle." },
      { q: "How long is the Florida Railroad Museum train ride?", a: "The Willow Express is a 13-mile round trip between Parrish and Willow, Florida, lasting about an hour and a half including a stop in Willow to see the museum's rail collection. It runs rain or shine." },
      { q: "What is there to do in Parrish when it rains?", a: "The Florida Railroad Museum runs rain or shine, and Ellenton Premium Outlets is minutes away. Wayfind automatically re-ranks Parrish recommendations when the weather turns, so the list during a thunderstorm is not the list on a clear morning." },
      { q: "How far is Parrish from the beach?", a: "Parrish sits inland in northern Manatee County. Anna Maria Island and Coquina Beach are the closest classic Gulf beaches — an easy drive west, making Parrish a practical, quieter base for a Gulf Coast trip." },
    ],
  },

  "things-to-do-in-sarasota-florida": {
    teaser: "Siesta Key was named the #1 beach in the United States for 2026, but the mangrove tunnels at South Lido are what locals choose.",
    region: "Sarasota",
    title: "17 Best Things to Do in Sarasota, Florida (2026 Local Guide)",
    description: "Siesta Key, The Ringling, mangrove kayaking, Myakka's canopy walkway, an Amish neighbourhood with legendary pie, and the day trips worth leaving town for. Verified August 2026.",
    keyword: "things to do in sarasota florida",
    updated: "2026-08-13",
    intro: "There are two ways to experience Sarasota. The easy one: Siesta Key, photograph the sand, walk St. Armands, eat overlooking water, go home convinced you have seen it. You have not. The other takes a little curiosity — mangrove tunnels where the city disappears behind you, an Amish bakery in the middle of Florida, a Venetian palace built by a circus king, and sunset from a boat instead of a beach towel. Three layers: the icons that earn their reputation, the places locals actually use, and the strange things most visitors never find. Day trips are kept separate, because Anna Maria Island is wonderful and it is not Sarasota.",
    picks: [
      { name: "Siesta Key", indoor: false, appQuery: "Siesta Beach", placeId: "ChIJjfu2YPBBw4gRo41o9hwHfmg", blurb: "Named the #1 beach in the United States for 2026 by U.S. News & World Report, and its white sand is composed largely of quartz crystal rather than the crushed shell most Florida beaches sit on. That is why it stays cool underfoot in August when every other beach is punishing. The quartz is believed to have travelled south from the Appalachians over an immense span of geologic time.", tip: "The main lot fills by mid-morning in season. Arrive before 10am, go late for sunset, or use Turtle Beach instead — the free Siesta Key Breeze trolley removes the problem entirely." },
      { name: "Turtle Beach", indoor: false, appQuery: "Turtle Beach Sarasota", placeId: "ChIJp6kyPa1Dw4gR5BhsSYE8pdo", blurb: "The southern end of the key: coarser sand, far fewer people, and actual parking. Siesta Key is not just Siesta Beach, and this is the correction most visitors never make.", tip: "See Siesta Beach once. Spend your second visit exploring the rest of the island." },
      { name: "Ted Sperling Nature Park at South Lido", indoor: false, appQuery: "Ted Sperling Park", blurb: "If you had to choose between looking at Sarasota's water and getting into it, it is the second every time. Launch here and work through the mangrove tunnels around South Lido. Once you are inside them Sarasota changes completely — cars disappear, buildings disappear, the mangroves close overhead, and you are scanning for herons, snook and dolphins instead of parking spaces.", tip: "Go early. The water is calmest before mid-morning. Bring a dry bag and more water than you think." },
      { name: "The Ringling", indoor: true, appQuery: "The John and Mable Ringling Museum of Art", placeId: "ChIJ6y2dx9g_w4gRWoZIRhLk-JI", blurb: "The State Art Museum of Florida, and genuinely world class: Old Master paintings, a Rubens gallery, plus Ca' d'Zan and the Circus Museum on the same bayfront estate. The fortune that bought the Old Masters came from the circus, which is why a Rubens gallery and a circus museum share a driveway.", tip: "People routinely give it ninety minutes. It needs half a day. Do the galleries when the weather is bad and the gardens and Ca' d'Zan when it is good." },
      { name: "Ca' d'Zan", indoor: true, appQuery: "Ca' d'Zan", placeId: "ChIJpXGK53VC24gRWMneFVtK6hY", blurb: "The Ringlings' Venetian Gothic mansion on Sarasota Bay — the house a circus baron built when he had decided exactly how much he had won. It is the single most photographed building on this coast for a reason.", tip: "The bay-facing terrace late in the afternoon is the shot. Interior tours are limited and separately timed." },
      { name: "Tibbals Learning Center and Circus Museum", indoor: true, appQuery: "Circus Museum Ringling", placeId: "ChIJKRTWX9g_w4gRk2YMbJtyfi4", blurb: "The part of the estate people expect to skip and end up spending an hour in, largely because of the Howard Bros. Circus Model — a 44,000-piece miniature reconstruction of the Ringling circus at its peak, built over decades by one man.", tip: "Fully indoors and air conditioned. This is the part of the Ringling estate to do when the afternoon storm arrives." },
      { name: "Marie Selby Botanical Gardens", indoor: false, appQuery: "Marie Selby Botanical Gardens", placeId: "ChIJPTvxtmpAw4gReToYD5mTNwE", blurb: "A bayfront botanical garden built around one of the world's most significant collections of epiphytes — orchids, bromeliads and the plants that live in the air. It is small enough to do properly in two hours and dense enough to reward every one of them.", tip: "Mornings. The light through the glasshouse is better and the heat has not arrived." },
      { name: "Mote Science Education Aquarium", indoor: true, appQuery: "Mote SEA", placeId: "ChIJRyOEfAo5w4gR664aD_YYBLU", blurb: "Sarasota's newest big-ticket attraction and the region's best rainy-afternoon answer — a roughly $146 million purpose-built science aquarium from Mote Marine Laboratory that opened in October 2025. Not a rebranded old one.", tip: "This is the move the moment a storm rolls in. Fully indoors, easy parking at UTC, and it absorbs a whole afternoon." },
      { name: "Myakka River State Park", indoor: false, appQuery: "Myakka River State Park", placeId: "ChIJz6wmd_5Kw4gR1PNqMrYU_RY", blurb: "More than 37,000 acres — about 58 square miles — of wetland, prairie and oak hammock, with alligators a near certainty rather than a hope. The canopy walkway was the first public treetop walkway in North America and puts you level with the tops of the oak hammock.", tip: "$6 per vehicle, 8am to sunset, 365 days. Arrive at 8 — the first two hours are the entire reason to come. Current alerts: drinking water is unavailable park-wide and the boat ramp is closed to trailered vessels." },
      { name: "The Bay Park", indoor: false, appQuery: "The Bay Park Sarasota", placeId: "ChIJLZ2vzRxBw4gRMOtW0ArhBhw", blurb: "Sarasota's reclaimed bayfront: boardwalks through restored mangroves, a lawn, and the best free sunset in the city. It is the most convincing thing the city has built in a decade.", tip: "Free. Walk the mangrove boardwalk at golden hour and finish at the bayfront." },
      { name: "Bayfront Park and Unconditional Surrender", indoor: false, appQuery: "Bayfront Park Sarasota", placeId: "ChIJ7wa-IxRAw4gRnwt6LGL2yeM", blurb: "The marina end of the bayfront, and the home of the 25-foot statue everyone photographs. Free, walkable from downtown, and the natural end of a Bay Park walk.", tip: "Sunset here, dinner downtown afterwards. It is a five-minute walk between the two." },
      { name: "The Legacy Trail", indoor: false, appQuery: "Legacy Trail", placeId: "ChIJRzUAPopDw4gR8YbL_V5iSWo", blurb: "A paved rail-trail running south from Sarasota through Osprey and Nokomis toward Venice — flat, shaded in stretches, and the way locals actually move through this county on two wheels.", tip: "Free. Ride south in the morning; the shade is better and the wind usually helps you home." },
      { name: "The Celery Fields", indoor: false, appQuery: "Celery Fields", placeId: "ChIJ7-I5X4tHw4gRAK6g4JEha7M", blurb: "A former agricultural field turned regional stormwater park, and now the best birding site in the county — plus a hill locals cheerfully call a mountain. The view from the top is genuinely the highest point around.", tip: "Free, and sunrise is the whole point. Bring binoculars; the wading bird counts here are serious." },
      { name: "Pinecraft: Yoder's and Der Dutchman", indoor: true, appQuery: "Yoder's Restaurant Sarasota", placeId: "ChIJIwZqEutAw4gR-1cOUgiln24", blurb: "An Amish and Mennonite neighbourhood in the middle of Sarasota, and the reason people drive across the county for pie. Yoder's has been doing it since 1975 and the queue at lunch is the review.", tip: "Der Dutchman is the other half of the Pinecraft argument, a few minutes away, and locals have a firm opinion about which is better. Go to both on different days. Order the pie first and let them hold it — on a busy day the good ones are gone by 2pm." },
      { name: "Lido Key and St. Armands Circle", indoor: false, appQuery: "St. Armands Circle", placeId: "ChIJ3VLBF5Jqw4gRkT1TfU3ULd8", blurb: "The shopping-and-dining circle John Ringling laid out, with Lido Beach a short walk beyond it. It is the easiest good evening in Sarasota: beach, then dinner, without moving the car twice.", tip: "Park once on the Circle and walk to the beach rather than the reverse — beach parking is the harder half." },
      { name: "Sarasota Jungle Gardens", indoor: false, appQuery: "Sarasota Jungle Gardens", placeId: "ChIJ_37IauQ_w4gRz03lc0QInIE", blurb: "A 1930s roadside botanical garden and small zoo that never modernised itself into blandness — flamingos you can feed, winding jungle paths, and a scale that works for young children without exhausting them.", tip: "It is outdoors and largely unshaded in stretches. Morning, always, and check the flamingo feeding times on arrival." },
      { name: "Owen's Fish Camp", indoor: true, appQuery: "Owens Fish Camp", placeId: "ChIJ5ab4TmtAw4gROiDA30SjNWY", blurb: "Old-Florida Southern seafood in a 1920s cottage under a banyan tree in Burns Court — whole fish, oysters, shrimp and grits, low-country boil. Dinner only, no reservations, parties capped at eight.", tip: "Doors at 4pm. Arrive right at open or plan on a wait, and split big groups." },
    ],
    faq: [
      { q: "What is the best beach in Sarasota?", a: "Siesta Key, named the #1 beach in the United States for 2026 by U.S. News & World Report. Its sand is nearly pure quartz, which is why it stays cool underfoot in August. For fewer people and easier parking, Turtle Beach at the southern end of the key is the local answer." },
      { q: "What is there to do in Sarasota when it rains?", a: "The Ringling galleries, Mote SEA, the Circus Museum and Pinecraft's Amish restaurants are all fully indoors. Wayfind re-ranks Sarasota recommendations automatically when the weather turns." },
      { q: "How much does Myakka River State Park cost?", a: "$6 per vehicle, open 8am to sunset, 365 days a year. As of August 2026 drinking water is unavailable park-wide and the boat ramp is closed to trailered vessels — the canopy walkway and bird walk are open." },
      { q: "How many days do you need in Sarasota?", a: "Two days covers it properly: one beach-and-bayfront day, one for The Ringling and Myakka. Three lets you add Pinecraft and a day trip without rushing." },
      { q: "Are Anna Maria Island and Boca Grande in Sarasota?", a: "No. Both are wonderful and both are day trips from Sarasota, not part of it — Anna Maria is in Manatee County to the north and Boca Grande is on Gasparilla Island well to the south. We keep them separate on purpose." },
    ],
  },

  "things-to-do-in-tampa-florida": {
    teaser: "The Duncan Auditorium closed on 10 March 2026 for a $24.5 million restoration, but the smaller John T. Taylor Screening Room stays open.",
    region: "Tampa",
    title: "21 Best Things to Do in Tampa, Florida (2026 Local Guide)",
    description: "Busch Gardens, Ybor City, the last working cigar factory in Cigar City, Cuban sandwiches with salami, the Riverwalk, manatee rescue and Gulf beach day trips. Verified August 2026.",
    keyword: "things to do in tampa florida",
    updated: "2026-08-13",
    intro: "An hour south, Sarasota sells refinement — white quartz sand, an orchid conservatory, a circus baron's palace on the bay. Tampa is not trying to do that. Tampa's pitch is range: in one day you can drop 206 feet at 91 degrees on the world's steepest hybrid coaster, hand-feed a giraffe, watch cigars rolled in a factory running since Ybor's boom, stand on a patch of ground deeded to the Republic of Cuba, eat a sandwich invented for cigar workers, see manatees being rehabilitated, and eat dessert inside a wine barrel. Most of it is within four miles of the rest. Tampa is not a postcard city. It is a contrast city.",
    picks: [
      { name: "Busch Gardens Tampa Bay", indoor: false, appQuery: "Busch Gardens Tampa Bay", placeId: "ChIJhRo4DU_GwogRUgjhMAj-pag", blurb: "The rare theme park that is also a serious zoo — more than 200 species and over 12,000 animals. Iron Gwazi is a 206-foot peak, a 91-degree drop (past vertical) and 76 mph, billed as North America's tallest and the world's fastest and steepest hybrid coaster. Then, ninety minutes later, you can be feeding a giraffe.", tip: "Book the Serengeti Safari — an open-air truck across the 65-acre Serengeti Plain where you hand-feed giraffes. Roughly $32 to $40, park admission separate. It is the best thing in the park that is not a coaster." },
      { name: "ZooTampa at Lowry Park", indoor: false, appQuery: "ZooTampa at Lowry Park", placeId: "ChIJBQ5SjLHGwogRL4X19g4J5tI", blurb: "Plenty of zoos say conservation. This one has receipts: the David A. Straz, Jr. Manatee Critical Care Center has run since 1991, has cared for more than 615 manatees, and released a record 26 back into the wild in 2025. That is not a plaque on a wall — it is a working hospital you can walk past.", tip: "Open 9:30am to 5pm daily. Advance admission is $48.95 against $51.95 same day for ages 12+. Buy before you drive." },
      { name: "The Florida Aquarium", indoor: true, appQuery: "The Florida Aquarium", placeId: "ChIJCXAq5_DEwogRjTPE2xlsZtE", blurb: "When the sky opens at 3pm — and in a Tampa summer it will — this is where you go. Sharks, sea turtles, rays, a penguin colony and a genuinely good coral reef exhibit on the Channelside waterfront, a short walk from the Riverwalk.", tip: "Open 9am to 5pm most of the year, 9am to 6pm in June and July. The Wild Dolphin Cruise is $17 adults and $15 children 3-11, general admission separate." },
      { name: "The Tampa Riverwalk", indoor: false, appQuery: "Tampa Riverwalk", placeId: "ChIJL_dfJozEwogRF_55TezQpYo", blurb: "2.6 free miles along the Hillsborough River from Armature Works to Sparkman Wharf. Calling it a path undersells it — it is the thread that ties downtown together, passing the art museum, the children's museum, the Straz Center, Curtis Hixon park, the History Center and Water Street without ever needing a car.", tip: "Walk it north to south in the last ninety minutes of daylight, ending at Sparkman Wharf. The West Riverwalk broke ground in April 2026 — nearly two new miles, finishing spring 2027, making a continuous 12.2-mile path." },
      { name: "Ybor City", indoor: false, appQuery: "Ybor City", placeId: "ChIJF06M0-_FwogRirItJy_x26M", blurb: "Founded in 1886 as a cigar-manufacturing town, built by Cuban, Spanish and Italian immigrants who came for the factories. Brick streets, wrought iron, social clubs, and the famous free-roaming chickens — descendants of birds families kept in their yards, and protected by city ordinance, which is why nobody chases them off.", tip: "Visit twice: daylight is history, after dark Seventh Avenue is one of the loudest nightlife strips in Florida. Take the free streetcar between them." },
      { name: "J.C. Newman's El Reloj cigar factory", indoor: true, appQuery: "J.C. Newman Cigar Company", blurb: "Not a museum with a costumed guide — a cigar factory that has been running since Ybor's boom, and by the company's own description the only cigar factory still in operation in Cigar City. You go inside and watch cigars being made by hand and on antique machines that still work.", tip: "Factory tour is 1 hour 15 minutes, $15 adults and $12 seniors, students and veterans, Monday to Friday at 9:00, 11:15 and 1:15. Pre-booking required and sessions sell out. Also one of the best rainy-day plans in the city." },
      { name: "Parque Amigos de Jose Marti", indoor: false, appQuery: "Jose Marti Park Tampa", placeId: "ChIJyyWN_lrEwogRP7gRxR2d19U", blurb: "A tiny park on East 8th Avenue that may be the only place in the United States where you can stand on land deeded to the Republic of Cuba. Jose Marti stayed at Paulina Pedroso's boarding house on this site while raising money among Ybor's cigar workers; in 1956 the land was deeded to Cuba as a memorial, accepted by the Batista government and certified through the U.S. consulate in Havana.", tip: "Be precise about this, because the internet is not: the deed history is documented, and what it means legally today is genuinely contested by historians. Ten minutes, free, and a better story than the confident version." },
      { name: "A real Tampa Cuban sandwich", indoor: true, appQuery: "Cuban sandwich Tampa", blurb: "Tampa's Cuban has salami in it. Miami's does not, and Tampanians will explain this whether or not you asked. It is not folklore: in April 2012 Tampa City Council formally designated the Historic Tampa Cuban Sandwich the city's signature sandwich, describing marinated pork, Genoa salami and sweet ham. The salami is the Italian immigrant fingerprint on a Cuban-Spanish city.", tip: "For the bread, La Segunda Central Bakery has been going since 1915, is run by the fourth generation of the same family, and bakes on the order of 20,000 loaves of Cuban bread a day." },
      { name: "Columbia Restaurant", indoor: true, appQuery: "Columbia Restaurant Ybor City", blurb: "Opened in 1905, billing itself as Florida's oldest restaurant and the largest Spanish restaurant in the world — and the scale is not a boast. The Ybor flagship has grown to 15 dining rooms across 52,000 square feet, seating up to 1,700, occupying an entire city block of tile, courtyards and stained glass.", tip: "Flamenco runs Monday to Thursday at 7pm, with an added 9:30pm show Friday and Saturday. There is a $10 per person cover for guests over 12 — worth knowing before the bill arrives." },
      { name: "Tampa Bay History Center", indoor: true, appQuery: "Tampa Bay History Center", placeId: "ChIJJboiAY3EwogRJCLbox7T-70", blurb: "Three floors on the Riverwalk covering 12,000 years: Indigenous Florida, Spanish arrival, cattle ranching, the actual pirates, the cigar boom, and how a swampy port turned into this.", tip: "Do it FIRST. Ybor, the Cuban sandwich and Gasparilla all land differently once you have the context." },
      { name: "Ybor City Museum State Park", indoor: true, appQuery: "Ybor City Museum State Park", placeId: "ChIJJb8wlVHEwogRywROz8FsuZM", blurb: "Housed in the old Ferlita Bakery building, with restored casitas — the shotgun cottages cigar workers actually lived in — out back. The casitas are the point: you can read about a company town anywhere, but walking through a two-room worker's house is different.", tip: "The bakery ovens supplied the Cuban bread that fed the cigar workers — the same bread the Tampa Cuban is still built on." },
      { name: "Tampa Theatre", indoor: true, appQuery: "Tampa Theatre", placeId: "ChIJ98cKiInEwogRfyDonUPi2bc", blurb: "A 1926 movie palace with a Mediterranean-courtyard interior and a ceiling of twinkling stars — one of the great surviving atmospheric theatres in America. Read this part carefully: the historic Duncan Auditorium closed on 10 March 2026 for the first phase of a $24.5 million restoration, targeted to reopen for the theatre's 100th anniversary in October 2026.", tip: "The smaller John T. Taylor Screening Room stays open through the work. If you are reading this before October, every guide telling you to catch a film in the big room is out of date." },
      { name: "The TECO Line Streetcar", indoor: false, appQuery: "TECO Line Streetcar", blurb: "Restored replica cars running between downtown and Ybor City, and every ride is fare free. Park once downtown, do the Riverwalk and the museums, streetcar to Ybor for dinner, streetcar back. That is the whole logistics problem of a Tampa day, solved.", tip: "Monday to Thursday 7am to 11pm, Friday to 2am, Saturday 9am to 2am, Sunday 8:30am to 11pm, roughly every 15 minutes. The fare-free service is funded year to year — it costs nothing to check on the day." },
      { name: "Bayshore Boulevard", indoor: false, appQuery: "Bayshore Boulevard Tampa", blurb: "4.5 miles of continuous waterfront sidewalk along Hillsborough Bay, with a balustrade on one side and some of the city's grandest old houses on the other. For decades this was billed as the world's longest continuous sidewalk — that title went to Galveston's Seawall Boulevard, 7.3 miles, Guinness-certified in September 2025.", tip: "Early morning or the hour before sunset. Midday in July there is no shade and no mercy." },
      { name: "Ballast Point Park", indoor: false, appQuery: "Ballast Point Park", placeId: "ChIJCZgnUKHcwogRbPR7qCWl-UA", blurb: "At the southern end of Bayshore, a small waterfront park with a pier out into the bay and a clean view back at the downtown skyline. No admission, no queue, no gift shop.", tip: "Bring something cold and watch the city light up across the water. Walk the southern end of Bayshore and finish here — that is the whole evening, and it costs nothing." },
      { name: "Lettuce Lake Park", indoor: false, appQuery: "Lettuce Lake Park", placeId: "ChIJlR-NjATIwogRoSE1MsVTpmA", blurb: "A 3,500-foot boardwalk through cypress wetlands along the Hillsborough River, where alligators, herons, ibis and turtles are genuinely common rather than theoretically possible. Twenty minutes from downtown, another century.", tip: "$2 per vehicle, CASH ONLY. Open 8am to 7pm spring and summer, 8am to 6pm fall and winter. As of August 2026 the observation tower is closed for reconstruction — the boardwalk is the reason to come anyway." },
      { name: "Armature Works", indoor: true, appQuery: "Armature Works", placeId: "ChIJYWj9iZ_PwogRQebjN7pJ_Nw", blurb: "A 1910s streetcar maintenance building on the river, restored into a food hall with a proper bar, a lawn out front and the Riverwalk running past the door. Solves the six-people-six-cravings problem better than any single restaurant in Tampa.", tip: "Fully indoors and air conditioned, which matters at 3pm in August. It is a genuinely good storm plan, not just an evening spot." },
      { name: "Sparkman Wharf and Water Street", indoor: false, appQuery: "Water Street Tampa", placeId: "ChIJy66Xe53FwogRcpjZQHX4cCI", blurb: "Sparkman Wharf sits at the southern end of the Riverwalk — shipping-container kitchens, a beer garden, a lawn, and cruise ships going by close enough to read. Next door, Water Street is the newly built district that reoriented downtown toward the bay.", tip: "Together they are where a Tampa evening starts if you are not going to Ybor. Park once and walk." },
      { name: "Bern's Steak House and the Harry Waugh Dessert Room", indoor: true, appQuery: "Bern's Steak House", placeId: "ChIJKQXHdmfDwogRJFCLuT7eJ6I", blurb: "Tampa's special-occasion restaurant for generations, with a cellar widely reported to hold on the order of half a million bottles. But the part people talk about afterwards is upstairs: the Harry Waugh Dessert Room seats you in private booths built from old wine casks. You are, quite literally, eating dessert inside a barrel.", tip: "The insider move: you can book the dessert room WITHOUT booking dinner. Reservations run 6:00 to 6:45pm daily. You get the cask booth, the wine list and the theatre of the place for the price of dessert." },
      { name: "A Tampa Bay Lightning game", indoor: true, appQuery: "Benchmark International Arena", blurb: "Two Stanley Cups this century and one of the loudest buildings in the league. The name changed: the Lightning play at Benchmark International Arena, renamed from Amalie Arena in August 2025. Same downtown building on Channelside.", tip: "The 2026-27 NHL season opens 29 September 2026. Tampa starts 1 October at the NY Rangers, and the home opener is 3 October against Washington." },
      { name: "Gasparilla Pirate Fest", indoor: false, appQuery: "Gasparilla Pirate Fest", blurb: "Once a year a fully crewed pirate ship sails into Tampa Bay, a flotilla of hundreds of boats escorts it in, the pirates capture the city, and a parade takes over Bayshore Boulevard. It has been happening since 1904. It is enormous, and it is completely sincere.", tip: "2027 dates: Children's Gasparilla on 23 January, the main Pirate Fest on 30 January, Outbound Voyage on 27 February. Book accommodation early — locals plan around it." },
    ],
    faq: [
      { q: "Can you visit Tampa Theatre right now?", a: "Partly. The historic Duncan Auditorium closed on 10 March 2026 for a $24.5 million restoration and is scheduled to reopen for the theatre's 100th anniversary in October 2026. The smaller John T. Taylor Screening Room remains open during the work." },
      { q: "Why does the Tampa Cuban sandwich have salami?", a: "Because Ybor City was built by Cuban, Spanish and Italian immigrants, and the Italian influence added Genoa salami. Tampa City Council formally recognised the Historic Tampa Cuban Sandwich — marinated pork, Genoa salami and sweet ham — as the city's signature sandwich in April 2012." },
      { q: "Is the TECO streetcar really free?", a: "Yes. The operator states all TECO Line Streetcar rides are fare free, and it has been that way since 2018. The funding is renewed year to year, so it is worth a quick check on the day you travel." },
      { q: "What are the best free things to do in Tampa?", a: "The Tampa Riverwalk (2.6 miles), the TECO streetcar, walking Ybor City, Bayshore Boulevard (4.5 miles), Ballast Point Park and Jose Marti Park all cost nothing. Lettuce Lake Park is $2 per vehicle, cash only." },
      { q: "Does Tampa have beaches?", a: "Tampa sits on a bay rather than the Gulf, so it has no true beach of its own. Clearwater Beach and St. Pete Beach are 30 to 45 minutes west and are among the best in Florida." },
      { q: "What is there to do in Tampa when it rains?", a: "The Florida Aquarium, the Tampa Bay History Center, the El Reloj cigar factory tour, Armature Works and Columbia Restaurant are all fully indoors. Wayfind re-ranks Tampa recommendations automatically when the weather turns." },
    ],
  },

  // Job guide, not a city directory. Two confident tables from existing Atlas
  // food cards, then a short rail of alternatives that already have cards.
  // No new editorial-cards.json rows. No Tampa / Winter Park food chapter —
  // those metros have no food cards. St. Armands Circle keeps its own guide;
  // Columbia is the only Circle restaurant with a card.
  "gulf-coast-brunch-and-date-night": {
    teaser: "The brunch kitchen closes at two. The date-night room does not open until five. Which job you book first decides the day.",
    region: "Sarasota",
    cluster: "gulf-coast-food",
    title: "Gulf Coast Brunch and Date Night: Two Tables, Not a List",
    description: "One brunch table and one date-night room on Florida's Gulf Coast, drawn only from existing Atlas cards: Original Word of Mouth in Venice, Ophelia's on the Bay on Siesta Key, and a short rail of alternatives.",
    keyword: "gulf coast brunch date night",
    updated: "2026-08-19",
    intro: "Two jobs, two tables. This is not a restaurant list. The Atlas already holds the food cards for this coast, and most of them are not the answer to brunch or to dinner for two. The brunch kitchen is Original Word of Mouth in Venice: from-scratch breakfast since 1996, jumbo cinnamon rolls, open daily 7:30am to 2pm, no dinner. The date-night room is Ophelia's on the Bay at the south end of Siesta Key: dinner only, 5 to 10pm, a nightly-printed menu, a Wine Spectator cellar, and a small bayfront room you book ahead. The brunch kitchen closes at two. The date-night room does not open until five. Which job you book first decides the day. The four names after those two are a short rail of alternatives that already have cards — independents, not the chain breakfast room. Ranking is never for sale. On St. Armands Circle, Columbia is the only restaurant with a card; the Circle keeps its own guide.",
    picks: [
      {
        name: "Original Word of Mouth",
        indoor: true,
        appQuery: "Original Word of Mouth Venice",
        placeId: "ChIJSZyKtGVaw4gRkKUbiPqvOVI",
        blurb: "The brunch table. A Venice morning kitchen at 1740 E Venice Avenue, open daily 7:30am to 2pm for breakfast and lunch only. From-scratch cooking since 1996, carried through three owners — American, English, and now Mario and Elena Mazzini — without dropping the recipes. People plan the morning around the jumbo fresh-baked cinnamon roll, or the Cinnamon Roll French Toast built on it; the hearty plate is the Uncle Buck's Buckwheat Special. Official pages list Sarasota, Venice, and Englewood rooms. This card is Venice. Fresh Florida orange juice, a latte, or a mimosa if you are making a morning of it.",
        tip: "Weekend mornings still draw a wait. A weekday walks in. Come hungry — portions run large — and do not arrive at 2pm expecting dinner.",
      },
      {
        name: "Ophelia's on the Bay",
        indoor: true,
        appQuery: "Ophelia's on the Bay",
        placeId: "ChIJs8HMPKxDw4gR8rXHdqdvpmE",
        blurb: "The date-night room. A small dinner-only house at 9105 Midnight Pass Road on the south end of Siesta Key, open daily 5 to 10pm. The menu is printed fresh every night around the day's catch and Florida produce. The signature is Paella Ophelia — snapper, tiger shrimp, scallop, clams, mussels, duck confit, and lobster butter — and the starter the card names is the colossal lump blue crab cake. The cellar holds a Wine Spectator Award of Excellence and a 200-plus-selection, sommelier-driven list. Official pages are dinner, reservations, and 941-349-2212. Top-tier priced, no lunch, not a walk-in plan.",
        tip: "Reserve a bayfront or patio table at sunset — regulars report dolphins in the bay — by phone or OpenTable. The room is small, so book ahead.",
      },
      {
        name: "Gulf Drive Cafe",
        indoor: true,
        appQuery: "Gulf Drive Cafe",
        placeId: "ChIJJWCbj5kRw4gRYkZ7QJ-L91s",
        blurb: "If the job is breakfast on the sand, not a Venice kitchen. Gulf Drive Cafe has sat on the Gulf at 900 Gulf Drive North, Bradenton Beach, since 1981, with breakfast until about 1pm and the Kokonut Hut tiki bar attached. Official pages still call it an Anna Maria Island fixture on the south-end sand, dog-friendly, breakfast through dinner. The card is honest about the trade: you are here for the Gulf-front patio and the sunset drink, and service and value complaints are part of the record. Not the polished pick.",
        tip: "Ask for a Gulf-front patio table, and expect crowds and waits in season. Breakfast runs late enough that a slow beach morning still makes it.",
      },
      {
        name: "Yoder's Restaurant",
        indoor: true,
        appQuery: "Yoder's Restaurant Sarasota",
        placeId: "ChIJIwZqEutAw4gR-1cOUgiln24",
        blurb: "If the job is pie with breakfast in Pinecraft. Yoder's has been family-run at 3434 Bahia Vista Street since 1975 — Levi and Amanda Yoder, now with their daughter Mary Lou — famous for from-scratch cream pies and Yoder's Famous Fried Chicken. Official pages, fetched August 2026, serve breakfast 7:00 to 10:30 Monday through Saturday and close Sunday. Pies are baked each morning and sell out. Next door, Yoder's Pie Craft Coffee Co. opened in 2025 for coffee and mini pies. Not a late-riser table, and not a Sunday table.",
        tip: "Order pie early, or take a whole one to go. Confirm hours on the official site before you drive — the restaurant posts temporary closes.",
      },
      {
        name: "Columbia Restaurant",
        indoor: true,
        appQuery: "Columbia Restaurant St Armands",
        placeId: "ChIJaTQEjpFqw4gRnHJU2Klfw0o",
        blurb: "If the evening is already on St. Armands Circle. Columbia opened this room in 1959; the family began in Ybor City in 1905 and still calls itself Florida's oldest restaurant. Official hours match the card: 11am to 9pm Sunday through Thursday, to 10pm Friday and Saturday, at 411 St. Armands Circle. The ritual is the trademarked 1905 Salad tossed tableside; the bigger plate is paella Española, and the house pour is Sangria de Cava. The room is large and lively, not intimate. This is the only Circle restaurant that already has an Atlas card. The Circle keeps its own guide for the walk; this page does not add names the cards do not have.",
        tip: "Ask for a patio table on the Circle when the weather is good. Reservations are wise in winter season; parking on the Circle is tight.",
      },
      {
        name: "Fins At Sharky's",
        indoor: true,
        appQuery: "Fins at Sharky's Venice",
        placeId: "ChIJf5M5VmBZw4gRVHX-dcX1dBk",
        blurb: "If you brunch in Venice and stay for dinner. Fins is the upscale sister to casual Sharky's next door, on the Venice Fishing Pier at 1600 Harbor Drive South: wood-fired prime steaks from a Josper oven and a full sushi program with a Gulf view. Official pages confirm the pier setting, the Josper, and the sushi. Hours on the card: lunch 11:45am to 3:30pm, dinner 3:30 to 10pm, sushi and cocktails straight through from 11:45am. Dressier and pricier than Sharky's. Not a cheap or quick bite.",
        tip: "Fins Frenzy runs 4 to 6pm daily for lighter bites and drink specials. Sushi is available all day, not only at dinner.",
      },
    ],
    faq: [
      {
        q: "Why only two recommendations?",
        a: "Wayfind is a decision engine, not a directory. The existing Atlas food cards support one confident brunch kitchen — Original Word of Mouth in Venice — and one confident date-night room — Ophelia's on the Bay. The other four names are a short rail for when you are already on Anna Maria, in Pinecraft, on St. Armands Circle, or staying in Venice for dinner. First Watch has a card in North Port; it is a chain, it closes at 2:30pm, and it is not the recommendation.",
      },
      {
        q: "What if I want Sunday brunch on Siesta Key, near Ophelia's?",
        a: "Ophelia's is dinner only and does not open until 5. Turtles Restaurant, a few doors down Midnight Pass Road, has a card and posts Sunday brunch 10am to 1pm at a casual bay table. That is the Sunday morning alternative on the same stretch, not a third recommendation.",
      },
      {
        q: "Is there a Tampa or Winter Park chapter?",
        a: "No. Atlas has no food cards for Tampa or Winter Park, and this guide does not invent them. Stay on the Sarasota–Manatee–Venice coast, where the cards actually are.",
      },
      {
        q: "What about the other restaurants on St. Armands Circle?",
        a: "The St. Armands Circle restaurants guide still covers the Circle walk. On Atlas cards, Columbia is the only Circle restaurant. This page does not add names the cards do not have.",
      },
      {
        q: "Do you rank restaurants that pay you?",
        a: "No. Ranking is never for sale. If a partner link appears on the page, it is disclosed. The two tables above are here because the cards already make the case, not because anyone bought a slot.",
      },
    ],
  },
};
