// Evergreen Florida restaurant guides, 2026.
// Research-backed editorial pages with exact Wayfind place identities.
// Map pins, article picks, place-card links, and photo requests all derive
// from the same pinned placeId so the map cannot drift from the guide.

function pinPhoto(placeId) {
  return "/api/photo?place=" + encodeURIComponent(placeId) + "&g=2&w=800";
}

function toMapSpot(p) {
  return {
    id: p.placeId,
    name: p.name,
    groups: p.groups || ["all"],
    city: p.city,
    when: p.when,
    detail: p.mapDetail || p.blurb,
    tip: p.tip,
    href: "/places/" + encodeURIComponent(p.placeId),
    image: pinPhoto(p.placeId),
    lat: p.lat,
    lng: p.lng,
    category: p.category,
    primary_type: p.primary_type,
    mapFamily: "food",
  };
}

function foodGuide({
  teaser, region, title, description, keyword, relatedKeywords, intro,
  filters, picks, faq, sources,
}) {
  return {
    teaser,
    region,
    title,
    description,
    keyword,
    relatedKeywords,
    published: "2026-09-23",
    updated: "2026-09-23",
    intro,
    mapExplorer: {
      kicker: "Wayfind restaurant map",
      heading: "Pick your table on the map",
      description: "Tap a pin to lift its matching Wayfind card. Swipe the cards and the map follows.",
      proof: ["Exact place identity", "Verified map pin", "Wayfind place card"],
      note: "Hours and menus can change. Open the place card before you go.",
      accent: "#F97316",
      filters,
      spots: picks.map(toMapSpot),
    },
    picks,
    faq,
    sources,
  };
}

export const FOOD_CITY_2026_GUIDES = Object.freeze({
  "sarasota-restaurants": foodGuide({
    teaser: "One map shows which Sarasota restaurant fits downtown, waterfront, lunch or dinner.",
    region: "Sarasota",
    title: "Best Restaurants in Sarasota: 10 Places Worth Planning Around",
    description: "Ten Sarasota restaurants for lunch, date night, waterfront seafood and a special dinner, with an interactive map and exact Wayfind place cards.",
    keyword: "best restaurants Sarasota",
    relatedKeywords: [
      "best restaurants in Sarasota",
      "Sarasota restaurants",
      "where to eat in Sarasota",
      "best food Sarasota Florida",
      "Sarasota dinner",
    ],
    intro: "Sarasota is easier to eat well in when you plan by occasion instead of chasing one giant ranking. Start with Lucky 8 or Focaccia for two of the city’s current MICHELIN Guide selections, use downtown for a polished dinner, head toward Cortez for old Florida seafood, or stay near UTC when the rest of the day is already there. This guide keeps every recommendation tied to an exact Wayfind place identity, so the restaurant card and the interactive map point to the same business.",
    filters: [
      { id: "michelin", label: "MICHELIN Guide", family: "food" },
      { id: "downtown", label: "Downtown", family: "food" },
      { id: "waterfront", label: "Waterfront", family: "food" },
      { id: "lunch", label: "Lunch", family: "food" },
      { id: "date-night", label: "Dinner out", family: "food" },
      { id: "all", label: "Everything", family: "food" },
    ],
    picks: [
      {
        name: "Lucky 8", placeId: "ChIJaeoTfN9Bw4gR4KQRHwdosqs", indoor: true,
        city: "Sarasota", when: "Dinner", groups: ["michelin", "downtown", "date-night"],
        lat: 27.3170225, lng: -82.5339824, category: "food", primary_type: "restaurant",
        eyebrow: "MICHELIN Guide pick",
        blurb: "Choose Lucky 8 when you want one of Sarasota’s current MICHELIN Guide restaurants without turning dinner into an all night production. It is a strong first reservation for visitors who want to see where the city’s newer food energy is going.",
        tip: "Build the rest of the night around this reservation, then keep the second stop in central Sarasota.",
        mapDetail: "A current MICHELIN Guide restaurant and a strong anchor for a Sarasota dinner plan.",
      },
      {
        name: "Focaccia Sandwich + Bakery", placeId: "ChIJk-o9uSlBw4gR6tDfhvqtdRk", indoor: true,
        city: "Sarasota", when: "Lunch", groups: ["michelin", "lunch"],
        lat: 27.2983492, lng: -82.5242932, category: "food", primary_type: "restaurant",
        eyebrow: "MICHELIN Guide lunch",
        blurb: "Focaccia is the useful counterpoint to Sarasota’s dinner heavy lists. The MICHELIN Guide includes it in the current Sarasota selection, making it an easy choice when you want a food focused lunch instead of another long sit down meal.",
        tip: "Use this as the midday stop on a beach or museum day rather than saving every strong meal for dinner.",
        mapDetail: "A current MICHELIN Guide selection that works especially well as a focused lunch stop.",
      },
      {
        name: "Indigenous Restaurant", placeId: "ChIJZUZzwm5Aw4gR1qnftvzg0lg", indoor: true,
        city: "Sarasota", when: "Dinner", groups: ["downtown", "date-night"],
        lat: 27.3343461, lng: -82.5329472, category: "food", primary_type: "american_restaurant",
        eyebrow: "Downtown dinner",
        blurb: "Indigenous is a useful downtown anchor when the goal is a proper sit down American dinner rather than a waterfront view or a shopping district stop. It fits a night when dinner itself is the plan.",
        tip: "Pair it with downtown Sarasota before or after dinner so you are not driving between stops.",
      },
      {
        name: "Sage Restaurant", placeId: "ChIJtcnZQU9Bw4gROmYnVLnl0hE", indoor: true,
        city: "Sarasota", when: "Dinner", groups: ["downtown", "date-night"],
        lat: 27.3370954, lng: -82.54617, category: "food", primary_type: "restaurant",
        eyebrow: "Special dinner",
        blurb: "Sage belongs on the list for nights when atmosphere matters as much as getting fed. Keep it in the downtown dinner lane and choose it when you want the meal to feel like the main event.",
        tip: "This is a better fit for an intentional dinner than a quick meal between attractions.",
      },
      {
        name: "Florence and the Spice Boys", placeId: "ChIJWerCJQA5w4gRkgxRabmvuBI", indoor: true,
        city: "Sarasota", when: "Lunch or dinner", groups: ["lunch", "date-night"],
        lat: 27.3839799, lng: -82.4565209, category: "food", primary_type: "middle_eastern_restaurant",
        eyebrow: "Middle Eastern",
        blurb: "Florence and the Spice Boys gives the guide a Middle Eastern option that is useful when the table wants bold flavors without defaulting to another seafood or American dinner. It is especially convenient when your day is already around the UTC area.",
        tip: "Keep this in mind for groups that want shareable food and a less formal plan.",
      },
      {
        name: "Zōtō", placeId: "ChIJJYDKlHM5w4gRpCS0kh1pDG8", indoor: true,
        city: "Sarasota", when: "Dinner", groups: ["date-night"],
        lat: 27.3857879, lng: -82.4555949, category: "food", primary_type: "japanese_restaurant",
        eyebrow: "Japanese",
        blurb: "Zōtō is the Japanese restaurant pick for a night when staying near UTC makes more sense than crossing town. It adds a polished option to an area that is often treated only as a shopping stop.",
        tip: "Choose it when convenience around UTC matters but you still want dinner to feel planned.",
      },
      {
        name: "Star Fish Company", placeId: "ChIJmcZ22HARw4gR5Th1Pxcl9II", indoor: false,
        city: "Cortez", when: "Lunch or early dinner", groups: ["waterfront", "lunch"],
        lat: 27.4658942, lng: -82.6853432, category: "shopping", primary_type: "market",
        eyebrow: "Old Florida seafood",
        blurb: "Star Fish Company is the change of pace pick: leave central Sarasota and head to Cortez when you want the working waterfront to be part of the meal. This is the one to choose when place and setting matter more than polish.",
        tip: "Treat the drive to Cortez as part of the outing rather than squeezing it between downtown plans.",
      },
      {
        name: "Blu Kouzina UTC", placeId: "ChIJUTI3PKk5w4gRtaS2weXk70A", indoor: true,
        city: "Sarasota", when: "Lunch or dinner", groups: ["lunch", "date-night"],
        lat: 27.3819462, lng: -82.4560474, category: "food", primary_type: "restaurant",
        eyebrow: "Greek near UTC",
        blurb: "Blu Kouzina is the practical Greek option when you are already around UTC and want a real meal without rerouting the whole day. It works for both a shopping break and an easy dinner.",
        tip: "Use it when geography matters. The point is a good meal that fits the day you already planned.",
      },
      {
        name: "Columbia Restaurant", placeId: "ChIJaTQEjpFqw4gRnHJU2Klfw0o", indoor: true,
        city: "Sarasota", when: "Lunch or dinner", groups: ["lunch", "date-night"],
        lat: 27.3192075, lng: -82.57728, category: "food", primary_type: "spanish_restaurant",
        eyebrow: "St. Armands",
        blurb: "Columbia is the St. Armands option when you want Spanish and Cuban restaurant history folded into a Circle day. Choose it because it fits the neighborhood plan, not because you need to leave the rest of Sarasota to get there.",
        tip: "Pair it with St. Armands and Lido Key so parking once does more work.",
      },
      {
        name: "Dry Dock Waterfront Grill", placeId: "ChIJ38CBz8Vqw4gRg0oFYUGBU_s", indoor: true,
        city: "Longboat Key", when: "Lunch or dinner", groups: ["waterfront", "lunch", "date-night"],
        lat: 27.339286, lng: -82.5898843, category: "food", primary_type: "seafood_restaurant",
        eyebrow: "Waterfront seafood",
        blurb: "Dry Dock is the pick when a Gulf Coast restaurant guide needs an actual waterfront meal in the plan. It is best used on a Longboat Key or Lido day when the view and the meal should happen in the same stop.",
        tip: "Do not cross the bridges just for a fast bite. Make it part of a coastal afternoon or evening.",
      },
    ],
    faq: [
      { q: "Which Sarasota restaurants are in the current MICHELIN Guide?", a: "The current Sarasota selection includes Lucky 8, Focaccia Sandwich + Bakery, and Tralia. This Wayfind guide maps Lucky 8 and Focaccia because those two currently resolve to exact Wayfind place identities." },
      { q: "Where should I eat near St. Armands Circle?", a: "Columbia Restaurant is the mapped pick in this guide. Wayfind also has a dedicated St. Armands restaurant guide for a deeper neighborhood comparison." },
      { q: "What is the easiest Sarasota restaurant plan without a lot of driving?", a: "Keep one meal downtown, or keep the whole outing around UTC. The interactive map is designed to make those clusters obvious before you commit." },
    ],
    sources: [
      "https://guide.michelin.com/us/en/florida/sarasota_2987163/restaurants",
      "https://www.visitsarasota.com/restaurants",
    ],
  }),

  "tampa-restaurants": foodGuide({
    teaser: "One map shows which Tampa restaurant fits Ybor, Hyde Park, Tampa Heights or dinner.",
    region: "Tampa",
    title: "Best Restaurants in Tampa: 10 Places Worth the Drive",
    description: "Ten Tampa restaurants for steak, Italian, Filipino, Greek, Cuban and brunch, with an interactive map and exact Wayfind place cards.",
    keyword: "best restaurants Tampa",
    relatedKeywords: [
      "best restaurants in Tampa",
      "Tampa restaurants",
      "where to eat in Tampa",
      "best food Tampa Florida",
      "Tampa dinner",
    ],
    intro: "Tampa is not one restaurant neighborhood. Ybor gives you history and Cuban food, Hyde Park and SoHo handle polished dinners, Tampa Heights has destination restaurants, and the city’s strongest newer kitchens keep spreading between them. This guide is built to help you choose by part of town and type of meal. Every mapped pick is pinned to an exact Wayfind business record, so a pin, a restaurant card, and a place page all describe the same location.",
    filters: [
      { id: "ybor", label: "Ybor", family: "food" },
      { id: "hyde-park", label: "Hyde Park and SoHo", family: "food" },
      { id: "tampa-heights", label: "Tampa Heights", family: "food" },
      { id: "casual", label: "Casual", family: "food" },
      { id: "date-night", label: "Dinner out", family: "food" },
      { id: "all", label: "Everything", family: "food" },
    ],
    picks: [
      {
        name: "Bern's Steak House", placeId: "ChIJKQXHdmfDwogRJFCLuT7eJ6I", indoor: true,
        city: "Tampa", when: "Dinner", groups: ["hyde-park", "date-night"],
        lat: 27.931603, lng: -82.482852, category: "food", primary_type: "steak_house",
        eyebrow: "Tampa institution",
        blurb: "Bern’s is the reservation to build a classic Tampa steakhouse night around. Choose it when the occasion calls for a destination dinner and you would rather commit to one memorable stop than bounce around the city.",
        tip: "Treat this as the whole evening and make the reservation before you plan the rest of the night.",
      },
      {
        name: "Rocca", placeId: "ChIJ1WZIXhjFwogR1M-_3DXnG6Y", indoor: true,
        city: "Tampa", when: "Dinner", groups: ["tampa-heights", "date-night"],
        lat: 27.9624349, lng: -82.465183, category: "food", primary_type: "italian_restaurant",
        eyebrow: "Italian dinner",
        blurb: "Rocca is the Italian dinner pick for a night when you want Tampa Heights to be the destination. It fits visitors who care more about the meal than checking off a famous neighborhood.",
        tip: "Keep nearby drinks or dessert in Tampa Heights so the night stays compact.",
      },
      {
        name: "Columbia Restaurant", placeId: "ChIJz8e7TVLEwogRBeybvscHnD4", indoor: true,
        city: "Tampa", when: "Lunch or dinner", groups: ["ybor", "casual", "date-night"],
        lat: 27.9599924, lng: -82.4351423, category: "food", primary_type: "spanish_restaurant",
        eyebrow: "Ybor City",
        blurb: "Columbia is the restaurant to choose when the meal needs to connect directly to Ybor City. The Spanish and Cuban menu makes more sense here when you also give yourself time to walk the neighborhood.",
        tip: "Use it as the anchor for an Ybor outing instead of driving in only for the table.",
      },
      {
        name: "Ulele", placeId: "ChIJ3Vyq7WTEwogRA-WDC7Mze2E", indoor: true,
        city: "Tampa", when: "Lunch or dinner", groups: ["tampa-heights", "date-night"],
        lat: 27.9599384, lng: -82.4628003, category: "food", primary_type: "american_restaurant",
        eyebrow: "Riverfront Tampa",
        blurb: "Ulele is a useful Tampa Heights choice when your plan also includes the Riverwalk or Armature Works area. It gives the day a sit down American restaurant stop without sending you to another side of town.",
        tip: "Best used as part of a riverfront plan where you can walk between stops.",
      },
      {
        name: "Psomi", placeId: "ChIJ_RvwD3nDwogRCeHQydPsx_k", indoor: true,
        city: "Tampa", when: "Brunch or lunch", groups: ["hyde-park", "casual"],
        lat: 27.9501545, lng: -82.4827529, category: "food", primary_type: "greek_restaurant",
        eyebrow: "Greek",
        blurb: "Psomi is one of Tampa’s current MICHELIN Guide value picks and the guide’s strongest daytime Greek stop. Choose it when brunch or lunch deserves as much attention as dinner.",
        tip: "Put it earlier in the day and save your evening reservation for a different neighborhood.",
      },
      {
        name: "On Swann", placeId: "ChIJ5crCip3EwogRQnhkbw_Ir6U", indoor: true,
        city: "Tampa", when: "Lunch or dinner", groups: ["hyde-park", "date-night"],
        lat: 27.9374672, lng: -82.4749343, category: "food", primary_type: "american_restaurant",
        eyebrow: "Hyde Park",
        blurb: "On Swann is the Hyde Park anchor for a polished American meal that can roll naturally into Village shopping, drinks, or a walk. It is a strong group choice when the neighborhood matters as much as the restaurant.",
        tip: "Park the car once and let Hyde Park Village handle the rest of the outing.",
      },
      {
        name: "Oxford Exchange", placeId: "ChIJ11hsiYXEwogRjDBv39F04J8", indoor: true,
        city: "Tampa", when: "Breakfast or lunch", groups: ["hyde-park", "casual"],
        lat: 27.9449261, lng: -82.4646338, category: "food", primary_type: "american_restaurant",
        eyebrow: "Daytime Tampa",
        blurb: "Oxford Exchange earns its spot because it solves breakfast, lunch, coffee and a visually distinctive daytime stop in one address. Choose it when your restaurant plan needs to start before dinner.",
        tip: "This is the daytime pick. Do not force it into the same role as Tampa’s destination dinner rooms.",
      },
      {
        name: "OLIVIA", placeId: "ChIJh4m6DH7DwogRcwo9evYZIhg", indoor: true,
        city: "Tampa", when: "Dinner", groups: ["hyde-park", "date-night"],
        lat: 27.9378381, lng: -82.5019732, category: "food", primary_type: "italian_restaurant",
        eyebrow: "SoHo Italian",
        blurb: "OLIVIA is the SoHo Italian option when you want a polished dinner but Bern’s is not the mood. It is especially useful for a date night that should continue nearby after the meal.",
        tip: "Keep the rest of the night in South Tampa instead of adding an Ybor or downtown transfer.",
      },
      {
        name: "Lucky Tigre", placeId: "ChIJKZW0N5XDwogRoKTCdhDprnU", indoor: true,
        city: "Tampa", when: "Lunch or dinner", groups: ["casual"],
        lat: 27.9587934, lng: -82.4827273, category: "food", primary_type: "filipino_restaurant",
        eyebrow: "Filipino",
        blurb: "Lucky Tigre gives this list a Filipino restaurant that feels more like a discovery than a ceremonial reservation. Choose it when you want the food to be the interesting part of a low pressure meal.",
        tip: "This is a good counterweight to the steakhouses and special occasion rooms on the list.",
      },
      {
        name: "La Segunda Bakery and Cafe", placeId: "ChIJXTeLe0XEwogR-wheRdFeKEY", indoor: true,
        city: "Tampa", when: "Breakfast or lunch", groups: ["ybor", "casual"],
        lat: 27.9658405, lng: -82.4433739, category: "food", primary_type: "bakery",
        eyebrow: "Tampa bakery",
        blurb: "La Segunda is the casual Tampa food history stop when a bakery and Cuban sandwich lane fits better than another full dinner. It is easy to work into an Ybor or central Tampa day.",
        tip: "Use it for breakfast or lunch so your evening stays open for another neighborhood.",
      },
    ],
    faq: [
      { q: "What Tampa neighborhood should I choose for dinner?", a: "Choose Ybor when history and Cuban or Spanish food are part of the outing, Hyde Park and SoHo for a polished dinner, or Tampa Heights when you want to pair dinner with the riverfront." },
      { q: "Which Tampa restaurant in this guide is in the current MICHELIN Guide value selection?", a: "Psomi appears in MICHELIN’s 2026 affordable Florida restaurant selection. Tampa also has additional MICHELIN restaurants beyond the ten mapped here." },
      { q: "Does Wayfind accept paid placement in this restaurant guide?", a: "No. These are editorial picks. Business partnerships do not buy a place in the ranking or change Wayfind scores." },
    ],
    sources: [
      "https://guide.michelin.com/en/us/florida/tampa/restaurants",
      "https://guide.michelin.com/en/article/michelin-guide-ceremony/florida-s-most-affordable-restaurants-in-2026-copy1",
    ],
  }),

  "st-pete-restaurants": foodGuide({
    teaser: "One map shows which St. Pete restaurant to choose for downtown, Central Avenue, waterfront or casual food.",
    region: "St. Petersburg",
    title: "Best Restaurants in St. Pete: 10 Places for Your Next Meal",
    description: "Ten St. Petersburg restaurants for Italian, sushi, Japanese, Cuban, seafood and a waterfront meal, with an interactive map and exact Wayfind place cards.",
    keyword: "best restaurants St Petersburg Florida",
    relatedKeywords: [
      "best restaurants St Pete",
      "St Petersburg restaurants",
      "where to eat St Pete",
      "St Pete dinner",
      "downtown St Pete restaurants",
    ],
    intro: "St. Pete is compact enough that one restaurant map can actually change the night. Downtown gives you several of the city’s current MICHELIN Guide restaurants within a tight radius, Central Avenue handles casual food and neighborhood energy, and the Pier gives you a waterfront finish. Use the filters to choose the version of St. Pete you want, then tap a pin for the exact Wayfind business card instead of hunting through a generic list.",
    filters: [
      { id: "michelin", label: "MICHELIN Guide", family: "food" },
      { id: "downtown", label: "Downtown", family: "food" },
      { id: "central", label: "Central Avenue", family: "food" },
      { id: "waterfront", label: "Waterfront", family: "food" },
      { id: "casual", label: "Casual", family: "food" },
      { id: "all", label: "Everything", family: "food" },
    ],
    picks: [
      {
        name: "Elliott Aster", placeId: "ChIJnZwugRXhwogRpN-HY445tJM", indoor: true,
        city: "St. Petersburg", when: "Dinner", groups: ["michelin", "downtown"],
        lat: 27.7779082, lng: -82.6296313, category: "food", primary_type: "restaurant",
        eyebrow: "MICHELIN Guide",
        blurb: "Elliott Aster is one of five St. Petersburg restaurants in the current MICHELIN Guide. Choose it when you want a downtown dinner where the kitchen is the reason for going, not just the address.",
        tip: "Keep the rest of the evening downtown so this stays an easy walkable plan.",
      },
      {
        name: "in between days", placeId: "ChIJPRvtBsfjwogRvhNpBGje2hA", indoor: true,
        city: "St. Petersburg", when: "Dinner", groups: ["michelin", "central"],
        lat: 27.7699385, lng: -82.6653121, category: "food", primary_type: "japanese_izakaya_restaurant",
        eyebrow: "MICHELIN Guide",
        blurb: "in between days is the current MICHELIN Guide pick for a Japanese contemporary and izakaya leaning night away from the waterfront. It is a strong choice when you want a smaller neighborhood feel.",
        tip: "Use this for a focused dinner, then move toward Central Avenue only if you want a second stop.",
      },
      {
        name: "Il Ritorno", placeId: "ChIJ3SpvbYPhwogRS17En4FSzVI", indoor: true,
        city: "St. Petersburg", when: "Dinner", groups: ["michelin", "downtown"],
        lat: 27.771354, lng: -82.639632, category: "food", primary_type: "italian_restaurant",
        eyebrow: "MICHELIN Guide Italian",
        blurb: "Il Ritorno is the Italian MICHELIN Guide option in central St. Pete. Pick it when you want the evening to feel like a destination dinner without leaving downtown.",
        tip: "Reserve first, then choose drinks or dessert within the downtown core.",
      },
      {
        name: "Sushi Sho Rexley", placeId: "ChIJM8CbE53hwogR_Py8YaLt6As", indoor: true,
        city: "St. Petersburg", when: "Dinner", groups: ["michelin", "downtown"],
        lat: 27.7739625, lng: -82.6357933, category: "food", primary_type: "sushi_restaurant",
        eyebrow: "MICHELIN Guide sushi",
        blurb: "Sushi Sho Rexley is the guide’s sushi choice when you want the meal to be the entire plan. The current MICHELIN Guide includes it among St. Petersburg’s five listed restaurants.",
        tip: "Choose it for a sushi centered night rather than trying to squeeze it between other downtown stops.",
      },
      {
        name: "Fortu", placeId: "ChIJdaUo-PPhwogRii2HqysdgjI", indoor: true,
        city: "St. Petersburg", when: "Dinner", groups: ["michelin", "downtown"],
        lat: 27.771391, lng: -82.633608, category: "food", primary_type: "restaurant",
        eyebrow: "MICHELIN Guide",
        blurb: "Fortu gives downtown St. Pete a current MICHELIN Guide Asian restaurant that works for a polished night out without needing a long drive. It is one of the easiest high intent dinners to pair with the rest of downtown.",
        tip: "Keep the after dinner plan on foot and let the downtown location do the work.",
      },
      {
        name: "Wild Child", placeId: "ChIJG00H7u7jwogRoWLHFmmGmbY", indoor: true,
        city: "St. Petersburg", when: "Brunch or dinner", groups: ["central", "casual"],
        lat: 27.770798, lng: -82.6703767, category: "food", primary_type: "american_restaurant",
        eyebrow: "Central Avenue",
        blurb: "Wild Child is the flexible Central Avenue pick when the group wants a lively American restaurant without making the meal overly formal. It works well when you want food plus a neighborhood night.",
        tip: "Use it as the anchor for the west side of Central Avenue rather than a prelude to the Pier.",
      },
      {
        name: "Bodega on Central", placeId: "ChIJRfPBKCriwogR4yaS_ccI5so", indoor: true,
        city: "St. Petersburg", when: "Lunch or dinner", groups: ["central", "casual"],
        lat: 27.770948, lng: -82.6508335, category: "food", primary_type: "cuban_restaurant",
        eyebrow: "Cuban on Central",
        blurb: "Bodega is the casual Cuban stop when you want Central Avenue energy without a formal reservation. It is one of the easiest places on this list to fold into an afternoon that becomes an evening.",
        tip: "Choose it when the plan needs to stay spontaneous.",
      },
      {
        name: "Juno & The Peacock", placeId: "ChIJK6b43nXhwogRCV39bMyGJGo", indoor: true,
        city: "St. Petersburg", when: "Dinner", groups: ["downtown"],
        lat: 27.7774078, lng: -82.6314419, category: "food", primary_type: "american_restaurant",
        eyebrow: "Downtown American",
        blurb: "Juno & The Peacock is a downtown American option for groups that want a central table and an easy transition into the rest of the city center. Choose it when logistics matter as much as the menu category.",
        tip: "This is a strong first stop for a downtown night because the next move can stay walkable.",
      },
      {
        name: "Mullet's Fish Camp", placeId: "ChIJh6exAYbhwogRd4RP1WCELps", indoor: true,
        city: "St. Petersburg", when: "Lunch or dinner", groups: ["casual"],
        lat: 27.7333978, lng: -82.641149, category: "food", primary_type: "seafood_restaurant",
        eyebrow: "Casual seafood",
        blurb: "Mullet’s Fish Camp is the seafood move when you would rather have a relaxed local meal than a polished downtown room. It adds a south St. Pete option to a guide that could otherwise cluster too tightly in the center.",
        tip: "Pick it when casual seafood is the point and you do not need the Pier view.",
      },
      {
        name: "Doc Ford's Rum Bar and Grille St Pete Pier", placeId: "ChIJIyCdCXfhwogRH8MxhxaUGgs", indoor: true,
        city: "St. Petersburg", when: "Lunch or dinner", groups: ["waterfront", "casual"],
        lat: 27.7728195, lng: -82.6263351, category: "food", primary_type: "restaurant",
        eyebrow: "St. Pete Pier",
        blurb: "Doc Ford’s is the practical waterfront choice when the Pier is already part of your day. Choose it when you want the water, the skyline and the meal to happen without moving the car again.",
        tip: "This is strongest as part of a full Pier visit, not as a stand alone drive across town.",
      },
    ],
    faq: [
      { q: "Which St. Pete restaurants are in the current MICHELIN Guide?", a: "The current St. Petersburg selection lists Elliott Aster, in between days, Il Ritorno, Sushi Sho Rexley, and Fortu. All five are mapped in this Wayfind guide." },
      { q: "Where should I eat if I want to stay around Central Avenue?", a: "Wild Child and Bodega on Central are the easiest casual anchors in this list. The map also shows which downtown restaurants are close enough to keep the night compact." },
      { q: "Which pick is easiest to combine with the St. Pete Pier?", a: "Doc Ford’s at the Pier is the direct waterfront pairing. Several downtown restaurants are nearby, but they serve a different kind of dinner plan." },
    ],
    sources: [
      "https://guide.michelin.com/en/us/florida/saint-petersburg_2883233/restaurants",
    ],
  }),

  "orlando-restaurants": foodGuide({
    teaser: "One map shows which Orlando restaurant fits Mills 50, East End, west Orlando or dinner.",
    region: "Orlando",
    title: "Best Restaurants in Orlando Beyond Disney",
    description: "Where to eat in Orlando outside Disney World, from Mills 50 to Winter Park and west Orlando, with an interactive map and exact Wayfind place cards.",
    keyword: "best restaurants Orlando",
    relatedKeywords: [
      "best restaurants in Orlando",
      "Orlando restaurants",
      "restaurants outside Disney World",
      "restaurants near Disney World",
      "where to eat Orlando",
      "Mills 50 restaurants",
    ],
    intro: "Orlando’s strongest restaurant day does not have to happen inside a theme park. Mills 50 is the clearest starting point, with Filipino, Japanese, Lao and neighborhood food packed into a small area, while Winter Park and west Orlando add destination meals that are worth the drive. This page owns the broader Orlando restaurant question. If you only want Disney Springs, Wayfind has a separate Disney Springs restaurant guide so the two searches do not compete with each other.",
    filters: [
      { id: "mills-50", label: "Mills 50", family: "food" },
      { id: "east-end", label: "East End", family: "food" },
      { id: "west-orlando", label: "West Orlando", family: "food" },
      { id: "japanese", label: "Japanese", family: "food" },
      { id: "date-night", label: "Dinner out", family: "food" },
      { id: "all", label: "Everything", family: "food" },
    ],
    picks: [
      {
        name: "Kaya", placeId: "ChIJ3YuEdVp754gRoWwBx528kNc", indoor: true,
        city: "Orlando", when: "Dinner", groups: ["mills-50", "date-night"],
        lat: 28.5520128, lng: -81.3657407, category: "food", primary_type: "filipino_restaurant",
        eyebrow: "Filipino in Mills 50",
        blurb: "Kaya is the Filipino restaurant to build a Mills 50 dinner around. The current MICHELIN Guide describes it as a modern Filipino restaurant using Central Florida produce and local seafood, which makes it a strong first stop for visitors who want Orlando beyond the parks.",
        tip: "Make the reservation the fixed point, then explore Mills 50 before or after dinner.",
      },
      {
        name: "Otto’s High Dive", placeId: "ChIJOwkr93R754gRwukRdzlSJgM", indoor: true,
        city: "Orlando", when: "Dinner and drinks", groups: ["date-night"],
        lat: 28.5458202, lng: -81.3526658, category: "food", primary_type: "restaurant",
        eyebrow: "MICHELIN value pick",
        blurb: "Otto’s High Dive appears in MICHELIN’s 2026 affordable Florida selection and gives the guide a restaurant that can carry dinner and drinks in the same stop. Choose it when you want a lively Orlando night without returning to the resort corridor.",
        tip: "This is a good first night off property because the restaurant already gives you a full evening mood.",
      },
      {
        name: "DOMU", placeId: "ChIJYb7ys7N654gRxvFvaVDAB0c", indoor: true,
        city: "Orlando", when: "Lunch or dinner", groups: ["east-end", "japanese"],
        lat: 28.5682793, lng: -81.3436535, category: "food", primary_type: "japanese_restaurant",
        eyebrow: "Japanese at East End",
        blurb: "DOMU is the East End Market area Japanese pick with enough identity to be a destination on its own. It also appears in MICHELIN’s 2026 affordable Florida restaurant selection.",
        tip: "Pair it with East End Market instead of treating the restaurant as an isolated drive.",
      },
      {
        name: "Zaru", placeId: "ChIJm9xjdgx754gRvYolbCqZPBQ", indoor: true,
        city: "Orlando", when: "Lunch or dinner", groups: ["mills-50", "japanese"],
        lat: 28.5529006, lng: -81.3648705, category: "food", primary_type: "japanese_restaurant",
        eyebrow: "Japanese in Mills 50",
        blurb: "Zaru keeps the Mills 50 food crawl focused on Japanese cooking and appears in MICHELIN’s 2026 affordable Florida list. Choose it when the goal is to taste the neighborhood rather than cross Orlando for one famous dining room.",
        tip: "It works best as part of a Mills 50 cluster because several other mapped picks sit close by.",
      },
      {
        name: "Coro Restaurant", placeId: "ChIJ91E5TZp754gR6UAe4qltcFE", indoor: true,
        city: "Orlando", when: "Dinner", groups: ["east-end", "date-night"],
        lat: 28.5675259, lng: -81.3452484, category: "food", primary_type: "restaurant",
        eyebrow: "MICHELIN value pick",
        blurb: "Coro is another current MICHELIN affordable selection and gives East End a dinner option that feels more intentional than a quick market stop. Choose it when you want to stay in this part of Orlando for the evening.",
        tip: "Keep East End and Audubon Park in the same outing so the geography stays simple.",
      },
      {
        name: "TORI TORI", placeId: "ChIJS6okKNZ754gRnwUlHBXAhU8", indoor: true,
        city: "Orlando", when: "Dinner and drinks", groups: ["mills-50", "japanese", "date-night"],
        lat: 28.5540171, lng: -81.364687, category: "food", primary_type: "japanese_restaurant",
        eyebrow: "Mills 50 night",
        blurb: "TORI TORI is the Mills 50 Japanese restaurant for a night that should feel social rather than formal. It is useful when you want food and drinks in the same neighborhood as several of Orlando’s strongest independent restaurants.",
        tip: "This is a better fit for a neighborhood night than a rushed meal before driving back to Disney.",
      },
      {
        name: "Sticky Rice", placeId: "ChIJjXi_isN654gRGkLnctUt860", indoor: true,
        city: "Orlando", when: "Lunch or dinner", groups: ["mills-50"],
        lat: 28.5533983, lng: -81.3565241, category: "food", primary_type: "restaurant",
        eyebrow: "Mills 50 casual",
        blurb: "Sticky Rice is the casual Mills 50 stop when the table wants a lower pressure meal without leaving the neighborhood food crawl. It helps make this guide useful for a full day, not only reservation dinners.",
        tip: "Use it when you want flexibility and still want to stay inside the Mills 50 orbit.",
      },
      {
        name: "Mills Market", placeId: "ChIJG1opWwB754gRGs--XkuAER0", indoor: true,
        city: "Orlando", when: "Lunch or dinner", groups: ["mills-50"],
        lat: 28.552895, lng: -81.3651621, category: "food", primary_type: "food_court",
        eyebrow: "Mills 50 food hall",
        blurb: "Mills Market is the choose your own adventure stop for groups that cannot agree on one kitchen. The Infatuation’s 2026 travel food coverage specifically called out Mills 50 and the market’s Cantonese barbecue as a reason to prioritize this Orlando neighborhood.",
        tip: "Choose this when variety matters more than a single formal restaurant experience.",
      },
      {
        name: "Kabooki Sushi - East Colonial", placeId: "ChIJpegta8x654gRmUI2JGqYuus", indoor: true,
        city: "Orlando", when: "Dinner", groups: ["east-end", "japanese", "date-night"],
        lat: 28.5529879, lng: -81.3439378, category: "food", primary_type: "sushi_restaurant",
        eyebrow: "Sushi",
        blurb: "Kabooki Sushi on East Colonial gives the guide a dedicated sushi dinner with an exact branch pinned on the map. That branch level identity matters in Orlando, where a restaurant name can otherwise send a visitor to the wrong side of town.",
        tip: "Use the Wayfind place card for this exact East Colonial branch before you route.",
      },
      {
        name: "Kappo Tsan", placeId: "ChIJuclcIkWB3YgRi8GT12wxByM", indoor: true,
        city: "Orlando", when: "Dinner", groups: ["west-orlando", "japanese", "date-night"],
        lat: 28.3994657, lng: -81.4889521, category: "food", primary_type: "japanese_restaurant",
        eyebrow: "West Orlando",
        blurb: "Kappo Tsan is the west Orlando Japanese option for travelers who are staying closer to the Disney side of the metro but still want to leave the resort restaurant loop. It gives this guide a useful western anchor instead of forcing every recommendation into Mills 50.",
        tip: "Choose it when you want an off property dinner without driving all the way to central Orlando.",
      },
    ],
    faq: [
      { q: "Where should I eat near Disney World if I want to leave the parks?", a: "West Orlando gives you shorter off property options, while Mills 50 is the stronger choice when you are willing to make the restaurant neighborhood part of the night. This guide maps both." },
      { q: "What if I only want restaurants at Disney Springs?", a: "Use Wayfind’s dedicated Best Restaurants at Disney Springs guide. Keeping Disney Springs on its own page prevents the broader Orlando guide from competing with a more specific Disney search." },
      { q: "Which Orlando neighborhood should a food focused visitor prioritize?", a: "Mills 50 is the clearest starting point in this guide because several strong independent restaurants sit close enough to combine into one outing." },
    ],
    sources: [
      "https://guide.michelin.com/us/en/florida/orlando/restaurant/kaya",
      "https://guide.michelin.com/en/article/michelin-guide-ceremony/florida-s-most-affordable-restaurants-in-2026-copy1",
      "https://www.theinfatuation.com/orlando/guides/best-restaurants-orlando",
    ],
  }),

  "miami-restaurants": foodGuide({
    teaser: "One map shows which Miami restaurant to choose for Little River, Design District, downtown or Cuban food.",
    region: "Miami",
    title: "Best Restaurants in Miami: 10 Places Worth Crossing Town For",
    description: "Ten Miami restaurants for steak, Italian, Peruvian, Cuban, pizza and casual food, with an interactive map and exact Wayfind place cards.",
    keyword: "best restaurants Miami",
    relatedKeywords: [
      "best restaurants in Miami",
      "Miami restaurants",
      "where to eat Miami",
      "best food Miami",
      "Miami dinner",
    ],
    intro: "Miami punishes a bad restaurant plan with traffic, so geography matters as much as the reservation. This guide mixes destination dinners with casual places that justify their part of town, then puts every pick on one interactive map. The goal is not to collect famous names. It is to help you choose the meal that is worth the drive you are actually making, with an exact Wayfind place card behind every pin.",
    filters: [
      { id: "little-river", label: "Little River", family: "food" },
      { id: "design-district", label: "Design District", family: "food" },
      { id: "downtown", label: "Downtown", family: "food" },
      { id: "cuban", label: "Cuban", family: "food" },
      { id: "casual", label: "Casual", family: "food" },
      { id: "all", label: "Everything", family: "food" },
    ],
    picks: [
      {
        name: "Sunny’s Steakhouse", placeId: "ChIJ0dm17kix2YgRoDAy8rxLOjU", indoor: true,
        city: "Miami", when: "Dinner", groups: ["little-river"],
        lat: 25.8428922, lng: -80.1969685, category: "food", primary_type: "steak_house",
        eyebrow: "Little River",
        blurb: "Sunny’s is the destination steakhouse pick when Little River is worth making the center of the night. It appears near the top of current 2026 Miami restaurant coverage, but the practical reason to choose it is simpler: make one reservation and let the dinner justify the drive.",
        tip: "Do not stack this with a far away second dinner plan. Let Little River own the night.",
      },
      {
        name: "Boia De", placeId: "ChIJte0b2xux2YgRr8f-xaLb0jw", indoor: true,
        city: "Miami", when: "Dinner", groups: ["little-river"],
        lat: 25.8242908, lng: -80.1913478, category: "food", primary_type: "italian_restaurant",
        eyebrow: "Italian",
        blurb: "Boia De is the Italian restaurant pick for diners who want a smaller destination room instead of a giant Miami scene. It is a useful choice when the food is the main reason you are crossing town.",
        tip: "Build the reservation first, then choose anything else in the same part of Miami.",
      },
      {
        name: "COTE Miami", placeId: "ChIJT8zbHlex2YgRbmlvb54NTIY", indoor: true,
        city: "Miami", when: "Dinner", groups: ["design-district"],
        lat: 25.8128901, lng: -80.1914914, category: "food", primary_type: "steak_house",
        eyebrow: "Design District",
        blurb: "COTE is the steakhouse choice when you want dinner folded into a Design District night. It works best when the neighborhood, not only the restaurant name, is already part of your plan.",
        tip: "Pair it with the Design District so you are not fighting Miami traffic for a second neighborhood.",
      },
      {
        name: "Barra Callao", placeId: "ChIJv7BTO4-t2YgRqNxbUEldJjE", indoor: true,
        city: "Miami", when: "Lunch or dinner", groups: ["casual"],
        lat: 25.9327778, lng: -80.1535769, category: "food", primary_type: "restaurant",
        eyebrow: "Peruvian",
        blurb: "Barra Callao is the Peruvian pick for a guide that should reflect more than steakhouses and Italian rooms. MICHELIN’s 2026 Florida value coverage highlighted the restaurant, making it a useful northern Miami anchor.",
        tip: "Choose it when your day already runs north. Do not treat every Miami food plan as a downtown plan.",
      },
      {
        name: "Walrus Rodeo", placeId: "ChIJsSLy8Nex2YgRgbI_3id8b_E", indoor: true,
        city: "Miami", when: "Dinner", groups: ["little-river"],
        lat: 25.8234753, lng: -80.1915522, category: "food", primary_type: "restaurant",
        eyebrow: "Little River",
        blurb: "Walrus Rodeo is the playful Little River dinner to choose when you want a restaurant with its own point of view but do not need the ceremony of a classic fine dining room.",
        tip: "Keep it in the same geographic lane as Boia De or Sunny’s when you compare options.",
      },
      {
        name: "B & M Market", placeId: "ChIJ9ZlVHnmx2YgRIhh-NLFLt5w", indoor: true,
        city: "Miami", when: "Lunch or dinner", groups: ["little-river", "casual"],
        lat: 25.8477491, lng: -80.1924117, category: "food", primary_type: "restaurant",
        eyebrow: "Caribbean market stop",
        blurb: "B & M Market is the casual Caribbean counterweight to Miami’s reservation driven restaurant scene. Choose it when the goal is flavor and specificity, not a long dining room experience.",
        tip: "This is a food stop, not a dress up dinner. Let that be the advantage.",
      },
      {
        name: "Chug's Diner", placeId: "ChIJoZfKYcy32YgR4ROg8Mdxtnw", indoor: true,
        city: "Miami", when: "Breakfast or lunch", groups: ["casual"],
        lat: 25.727472, lng: -80.2432042, category: "food", primary_type: "restaurant",
        eyebrow: "Coconut Grove",
        blurb: "Chug’s Diner gives the guide a strong daytime reason to eat in Coconut Grove. Use it when breakfast or lunch should feel like part of the Miami restaurant trip rather than the meal you settle for before dinner.",
        tip: "Pair it with a Grove morning or afternoon instead of crossing town only to eat.",
      },
      {
        name: "La Natural", placeId: "ChIJaeBbjZmx2YgRI0Yb0-WQtPU", indoor: true,
        city: "Miami", when: "Dinner", groups: ["little-river", "casual"],
        lat: 25.841881, lng: -80.2005808, category: "food", primary_type: "restaurant",
        eyebrow: "Little River",
        blurb: "La Natural is the relaxed Little River choice when you want a restaurant night that feels neighborhood driven rather than scene driven. It is especially useful when you are comparing several north Miami options on the map.",
        tip: "Use the map to keep Little River dinners in one cluster and cut down on unnecessary driving.",
      },
      {
        name: "Over Under", placeId: "ChIJzwEW8bK32YgRoeQcKaBkwrs", indoor: true,
        city: "Miami", when: "Dinner and drinks", groups: ["downtown", "casual"],
        lat: 25.774428, lng: -80.190885, category: "nightlife", primary_type: "cocktail_bar",
        eyebrow: "Downtown casual",
        blurb: "Over Under is the downtown casual option when the night needs food and drinks without a major reservation production. It gives the guide a useful answer for people already in the urban core.",
        tip: "Choose it because you are downtown, not because you want to cross Miami for formality.",
      },
      {
        name: "Versailles Restaurant Cuban Cuisine", placeId: "ChIJt9yvFgu32YgRrk-vKGEQB6g", indoor: true,
        city: "Miami", when: "Breakfast, lunch or dinner", groups: ["cuban", "casual"],
        lat: 25.765024, lng: -80.252796, category: "food", primary_type: "cuban_restaurant",
        eyebrow: "Cuban Miami",
        blurb: "Versailles is the guide’s Cuban institution pick because a Miami food map should help first time visitors understand the city beyond the latest reservation list. Choose it when Cuban restaurant history is part of what you came to experience.",
        tip: "Treat the restaurant as a Miami cultural stop and plan the rest of the outing around Little Havana.",
      },
    ],
    faq: [
      { q: "What part of Miami should I choose for a food focused night?", a: "Little River gives you the densest cluster in this Wayfind guide. The Design District is easier when you want dinner plus galleries or shopping, while downtown works when you are already in the urban core." },
      { q: "Which restaurant is the classic Cuban choice in this guide?", a: "Versailles is the mapped Cuban institution here. It serves a different purpose from the newer destination restaurants and belongs in the guide for that reason." },
      { q: "Why does the map matter so much in Miami?", a: "Traffic can turn two good restaurant choices into a bad night if they are far apart. The map is designed to make neighborhood clusters obvious before you commit." },
    ],
    sources: [
      "https://www.theinfatuation.com/miami/guides/best-restaurants-in-miami",
      "https://guide.michelin.com/en/article/michelin-guide-ceremony/florida-s-most-affordable-restaurants-in-2026-copy1",
    ],
  }),
});
