// Canonical Gulf Coast fall records promoted from external research packages.
//
// This file is the reviewed boundary between discovery and production data:
// only evidence-backed event rows and narrowly scoped corrections belong here.
// Held candidates remain explicit so a future pass does not silently publish
// conflicting dates, unverified prices, or placeless offers as events.

const VERIFIED_AT = "2026-09-07T00:00:00+00:00";

const BASE = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  state: "FL",
  last_verified_at: VERIFIED_AT,
};

const SARASOTA_AUDIT_BASE = {
  ...BASE,
  last_verified_at: "2026-09-08T00:00:00+00:00",
};

export const GULF_COAST_FALL_2026_ROWS = Object.freeze([
  {
    ...BASE,
    event_id: "gallaghers-pumpkins-2026",
    event_series_id: "gallaghers-pumpkins",
    event_name: "Gallagher's Pumpkins & Christmas Trees",
    short_title: "Gallagher's Pumpkins",
    slug: "gallaghers-pumpkins-st-pete-2026",
    start_date: "2026-09-21",
    end_date: null,
    start_time: "09:00:00",
    end_time: "21:00:00",
    select_nights: false,
    schedule_note: "Open daily from September 21, 9am–9pm. The 2026 closing date has not been published.",
    venue: "Gallagher's Pumpkins & Christmas Trees",
    address: "7401 4th St N, St. Petersburg, FL 33702",
    city: "St. Petersburg",
    county: "Pinellas",
    lat: 27.843052,
    lng: -82.6449,
    place_id: null,
    category: "seasonal",
    subcategory: "pumpkin-patch",
    tags: ["fall", "pumpkins", "family", "photo-ops", "local"],
    audience: ["families", "kids", "couples"],
    is_free: null,
    price_min: null,
    price_max: null,
    price_band: null,
    official_event_url: "https://www.gallagherspumpkinsandchristmastrees.com/",
    source_url: "https://www.gallagherspumpkinsandchristmastrees.com/",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Official site confirms the September 21 opening, daily 9am–9pm hours, address, and free casual family photos. Admission and pumpkin prices are not posted.",
    card_hook: "St. Pete's daily pumpkin stop, with the vintage red truck photo waiting out front.",
    editorial_summary: "An easy neighborhood pumpkin and photo run with a goat pen, food trailer and an expanded 2026 layout.",
    why_go: "Pick this for a local fall stop without committing to a full farm-festival day.",
    insider_tip: "Casual family photos are free; professional sessions require a reservation.",
    wayfind_verdict: "Pinellas' easy, everyday pumpkin patch.",
    duration_recommendation: "1–2 hours",
    crowd_level: "moderate",
    editorial_score: 8,
    uniqueness_score: 7,
    popularity_score: 7,
  },
  {
    ...BASE,
    event_id: "seminole-heights-great-pumpkin-patch-2026",
    event_series_id: "seminole-heights-great-pumpkin-patch",
    event_name: "Seminole Heights Great Pumpkin Patch",
    short_title: "Seminole Heights Pumpkin Patch",
    slug: "seminole-heights-great-pumpkin-patch-2026",
    start_date: "2026-10-07",
    end_date: "2026-10-31",
    start_time: null,
    end_time: null,
    select_nights: true,
    schedule_note: "October 7–31. Closed Monday–Tuesday until October 19; Wednesday–Thursday 5–8pm, Friday 4–8:30pm, Saturday 10am–8pm, Sunday noon–6pm.",
    venue: "Seminole Heights Great Pumpkin Patch",
    address: "6111 N Central Ave, Tampa, FL 33604",
    city: "Tampa",
    county: "Hillsborough",
    lat: 28.002979,
    lng: -82.454603,
    place_id: null,
    category: "seasonal",
    subcategory: "pumpkin-patch",
    tags: ["fall", "pumpkins", "family", "community", "local"],
    audience: ["families", "kids"],
    is_free: null,
    price_min: null,
    price_max: null,
    price_band: null,
    official_event_url: "https://www.myhtca.org/shgpp",
    source_url: "https://www.myhtca.org/shgpp",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Organizer page body confirms the 2026 dates, hours and address. Admission pricing is not stated.",
    card_hook: "A neighborhood pumpkin patch whose proceeds stay in Seminole Heights.",
    editorial_summary: "A volunteer-run community patch with useful evening hours and a central Tampa location.",
    why_go: "Choose it when you want pumpkins nearby instead of a drive to a farm.",
    insider_tip: "Check the day-specific hours before leaving; the patch is closed Monday and Tuesday until October 19.",
    wayfind_verdict: "Tampa's most neighborhood-first pumpkin stop.",
    duration_recommendation: "Under 2 hours",
    crowd_level: "moderate",
    editorial_score: 8,
    uniqueness_score: 7,
    popularity_score: 7,
  },
  {
    ...BASE,
    event_id: "sarasota-oktoberfest-benderson-2026",
    event_series_id: "sarasota-oktoberfest-benderson",
    event_name: "Sarasota Oktoberfest at Nathan Benderson Park",
    short_title: "Sarasota Oktoberfest",
    slug: "sarasota-oktoberfest-benderson-2026",
    start_date: "2026-10-10",
    end_date: "2026-10-11",
    start_time: "10:00:00",
    end_time: "17:00:00",
    select_nights: false,
    schedule_note: "October 10–11, 10am–5pm. Admission is free; parking is $20 per car.",
    venue: "Nathan Benderson Park",
    address: "5851 Nathan Benderson Circle, Sarasota, FL 34235",
    city: "Sarasota",
    county: "Sarasota",
    lat: 27.3742443,
    lng: -82.4500873,
    place_id: "ChIJczkDFL04w4gRwfowcSv8Tro",
    category: "festival",
    subcategory: "oktoberfest",
    tags: ["fall", "oktoberfest", "food", "beer", "family", "free", "local"],
    audience: ["families", "adults", "couples"],
    is_free: true,
    price_min: 0,
    price_max: 0,
    price_band: "free",
    official_event_url: "https://nathanbendersonpark.org/event/oktoberfest/",
    source_url: "https://nathanbendersonpark.org/event/oktoberfest/",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Official park page confirms October 10–11, 10am–5pm, free admission, and $20 per-car parking.",
    card_hook: "Free lakeside Oktoberfest with regatta energy; budget $20 per car for parking.",
    editorial_summary: "German food, live bands, a beer garden and kids zone share the lakefront with rowing and dragon-boat racing.",
    why_go: "It gives Sarasota a full Oktoberfest day without an admission ticket.",
    parking_tip: "Parking is $20 per car, paid on arrival.",
    wayfind_verdict: "Sarasota's best free-entry Oktoberfest day.",
    duration_recommendation: "Half day",
    crowd_level: "high",
    editorial_score: 9,
    uniqueness_score: 8,
    popularity_score: 8,
  },
  {
    ...BASE,
    event_id: "cape-coral-oktoberfest-2026",
    event_series_id: "cape-coral-oktoberfest",
    event_name: "Cape Coral Oktoberfest",
    short_title: "Cape Coral Oktoberfest",
    slug: "cape-coral-oktoberfest-2026",
    start_date: "2026-10-16",
    end_date: "2026-10-25",
    start_time: null,
    end_time: null,
    select_nights: true,
    schedule_note: "Two weekends: October 16–18 and October 23–25. The organizer has not yet posted 2026 daily hours.",
    venue: "German American Social Club of Cape Coral",
    address: "2101 SW Pine Island Rd, Cape Coral, FL 33991",
    city: "Cape Coral",
    county: "Lee",
    lat: 26.6392039,
    lng: -82.0158109,
    place_id: null,
    category: "festival",
    subcategory: "oktoberfest",
    tags: ["fall", "oktoberfest", "food", "beer", "family"],
    audience: ["families", "adults", "couples"],
    is_free: false,
    price_min: 8,
    price_max: 10,
    price_band: "$",
    official_event_url: "https://www.gasc-capecoral.com/oktoberfest",
    official_ticket_url: "https://capecoraloktoberfest.com/tickets/",
    source_url: "https://festivalnet.com/42073/Cape-Coral-Florida/Ethnic-Festivals/Oktoberfest-Largest-in-Florida",
    source_type: "reputable-calendar",
    source_tier: 2,
    verification_confidence: "medium",
    verify_note: "The club confirms a two-weekend 2026 event and the venue. FestivalNet supplies the specific dates and $8 advance/$10 gate pricing; official daily hours remain unpublished.",
    card_hook: "Cape Coral's German-club Oktoberfest returns for two weekends of biergarten, food and live music.",
    editorial_summary: "A large Southwest Florida Oktoberfest with multiple stages, German food, vendors and family activities.",
    why_go: "Choose it for the full German-club festival experience instead of a one-night bar event.",
    insider_tip: "Confirm the daily schedule before driving; the organizer still lists 2026 hours as coming soon.",
    wayfind_verdict: "Southwest Florida's big traditional Oktoberfest.",
    duration_recommendation: "Half day",
    crowd_level: "high",
    editorial_score: 8,
    uniqueness_score: 8,
    popularity_score: 8,
  },
  {
    ...BASE,
    event_id: "plant-city-oktoberfest-2026",
    event_series_id: "plant-city-oktoberfest",
    event_name: "Plant City Oktoberfest",
    short_title: "Plant City Oktoberfest",
    slug: "plant-city-oktoberfest-2026",
    start_date: "2026-09-26",
    end_date: "2026-09-26",
    start_time: "15:00:00",
    end_time: "22:00:00",
    select_nights: false,
    schedule_note: "Saturday, September 26, 3–10pm. Admission pricing has not been published.",
    venue: "McCall Park",
    address: "100 N Collins St, Plant City, FL 33563",
    city: "Plant City",
    county: "Hillsborough",
    lat: 28.0157,
    lng: -82.1219,
    place_id: null,
    category: "festival",
    subcategory: "oktoberfest",
    tags: ["fall", "oktoberfest", "food", "beer", "family", "local"],
    audience: ["families", "adults", "couples"],
    is_free: null,
    price_min: null,
    price_max: null,
    price_band: null,
    official_event_url: null,
    source_url: "https://www.plantcityobserver.com/parks-rec-to-host-oktoberfest/",
    source_type: "local-news",
    source_tier: 2,
    verification_confidence: "medium",
    verify_note: "Plant City Observer directly quotes city officials confirming the September 26 date, 3–10pm time, organizers and downtown program. Admission is unposted; the map point is McCall Park.",
    card_hook: "Downtown Plant City's one-night Oktoberfest runs 3–10pm with biergartens, music and a free kids zone.",
    editorial_summary: "A civic Oktoberfest with German-inspired food, live music, games, local vendors and family activities.",
    why_go: "It is the compact east-Hillsborough choice for an Oktoberfest evening.",
    insider_tip: "Check the city's event update for street closures and any late admission announcement.",
    wayfind_verdict: "Plant City's easy hometown Oktoberfest night.",
    duration_recommendation: "2–4 hours",
    crowd_level: "high",
    editorial_score: 8,
    uniqueness_score: 7,
    popularity_score: 7,
  },
  // 2026-09-08 Sarasota 40-mile audit. Every row below has a current
  // organizer, venue, government, or ticket source; the companion audit
  // fixture records the held and non-event discoveries that deliberately do
  // not enter wf_events.
  {
    ...SARASOTA_AUDIT_BASE,
    event_id: "ghostbusters-in-concert-van-wezel-2026",
    event_series_id: "ghostbusters-in-concert-van-wezel",
    event_name: "Ghostbusters in Concert",
    short_title: "Ghostbusters in Concert",
    slug: "ghostbusters-in-concert-van-wezel-2026",
    start_date: "2026-10-29",
    end_date: "2026-10-29",
    start_time: "19:00:00",
    end_time: null,
    select_nights: false,
    schedule_note: "October 29 at 7pm; doors open one hour before the performance.",
    venue: "Van Wezel Performing Arts Hall",
    address: "777 N Tamiami Trl, Sarasota, FL 34236",
    city: "Sarasota",
    county: "Sarasota",
    lat: 27.3427563,
    lng: -82.5504342,
    place_id: "ChIJew4bcA9Aw4gR3bU-SA7qAgU",
    category: "halloween",
    subcategory: "film-concert",
    tags: ["fall", "halloween", "concert", "film", "date-night"],
    audience: ["adults", "couples", "teens"],
    is_free: false,
    price_min: 46,
    price_max: 91,
    price_band: "$$",
    official_event_url: "https://www.vanwezel.org/events/detail/ghostbusters-in-concert",
    source_url: "https://www.vanwezel.org/events/detail/ghostbusters-in-concert",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Van Wezel's official event page confirms the October 29, 7pm performance, venue, all-in $46–$91 price range, and ticket path. Prices are subject to change.",
    card_hook: "A Ghostbusters concert night at Van Wezel, two nights before Halloween.",
    editorial_summary: "A dated Sarasota performance for a Halloween-season night out, with official venue pricing published.",
    why_go: "Choose it for a scheduled arts night rather than a generic Halloween listing.",
    wayfind_verdict: "A Sarasota Halloween-week concert plan with a real curtain time.",
    duration_recommendation: "Evening",
    crowd_level: "high",
    editorial_score: 8,
    uniqueness_score: 8,
    popularity_score: 8,
  },
  {
    ...SARASOTA_AUDIT_BASE,
    event_id: "trick-or-treat-on-the-lake-benderson-2026",
    event_series_id: "trick-or-treat-on-the-lake-benderson",
    event_name: "Trick or Treat on the Lake",
    short_title: "Trick or Treat on the Lake",
    slug: "trick-or-treat-on-the-lake-benderson-2026",
    start_date: "2026-10-27",
    end_date: "2026-10-27",
    start_time: "16:30:00",
    end_time: "19:30:00",
    select_nights: false,
    schedule_note: "October 27, 4:30–7:30pm at Regatta Island. Admission and parking are free.",
    venue: "Regatta Island, Nathan Benderson Park",
    address: "5851 Nathan Benderson Circle, Sarasota, FL 34235",
    city: "Sarasota",
    county: "Sarasota",
    lat: 27.3742443,
    lng: -82.4500873,
    place_id: "ChIJczkDFL04w4gRwfowcSv8Tro",
    category: "halloween",
    subcategory: "trick-or-treat",
    tags: ["fall", "halloween", "trick-or-treat", "family", "free"],
    audience: ["families", "kids"],
    is_free: true,
    price_min: 0,
    price_max: 0,
    price_band: "free",
    official_event_url: "https://nathanbendersonpark.org/trick-or-treat-on-the-lake/",
    source_url: "https://nathanbendersonpark.org/trick-or-treat-on-the-lake/",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Nathan Benderson Park and Visit Sarasota confirm the October 27 date and 4:30–7:30pm time; Visit Sarasota states free admission and the park publishes the address.",
    card_hook: "A free lakefront trick-or-treat evening with free parking.",
    editorial_summary: "A short, scheduled Halloween outing for families at Nathan Benderson Park.",
    why_go: "Pick it when the plan needs kid-safe Halloween timing and an easy park arrival.",
    wayfind_verdict: "A practical Sarasota family Halloween stop.",
    duration_recommendation: "1–2 hours",
    crowd_level: "high",
    editorial_score: 8,
    uniqueness_score: 7,
    popularity_score: 8,
  },
  {
    ...SARASOTA_AUDIT_BASE,
    event_id: "venice-night-market-halloween-2026",
    event_series_id: "venice-night-market-halloween",
    event_name: "Venice Night Market & Music Halloween Event",
    short_title: "Venice Halloween Night Market",
    slug: "venice-night-market-halloween-2026",
    start_date: "2026-10-17",
    end_date: "2026-10-17",
    start_time: "17:00:00",
    end_time: "22:00:00",
    select_nights: false,
    schedule_note: "October 17, 5–10pm at Maxine Barritt Park. Free admission.",
    venue: "Maxine Barritt Park",
    address: "1800 Harbor Dr S, Venice, FL 34285",
    city: "Venice",
    county: "Sarasota",
    lat: 27.0711111,
    lng: -82.4480556,
    place_id: "ChIJg1HuP9xbw4gRs9PHCFmC4VU",
    category: "festival",
    subcategory: "night-market",
    tags: ["fall", "halloween", "night-market", "market", "music", "free"],
    audience: ["families", "adults", "couples"],
    is_free: true,
    price_min: 0,
    price_max: 0,
    price_band: "free",
    official_event_url: "https://www.venicegov.com/Home/Components/Calendar/Event/7113/20?curm=10&cury=2026",
    official_ticket_url: "https://www.eventbrite.com/e/venice-night-market-music-halloween-edition-tickets-1987626272687",
    source_url: "https://www.venicegov.com/Home/Components/Calendar/Event/7113/20?curm=10&cury=2026",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "City of Venice calendar confirms the 2026 event and its date/time; the organizer's Eventbrite listing supplies the free-admission detail and the park address is published.",
    card_hook: "A free Venice night market with a Halloween and music edition.",
    editorial_summary: "An evening market in Maxine Barritt Park with a published October 17 schedule.",
    why_go: "Choose it for a Venice outdoor market plan, not a ticketed haunted attraction.",
    wayfind_verdict: "Venice's free Halloween-market night.",
    duration_recommendation: "2–3 hours",
    crowd_level: "moderate",
    editorial_score: 7,
    uniqueness_score: 7,
    popularity_score: 7,
  },
  {
    ...SARASOTA_AUDIT_BASE,
    event_id: "sun-fiesta-venice-2026",
    event_series_id: "sun-fiesta-venice",
    event_name: "Sun Fiesta 2026",
    short_title: "Sun Fiesta",
    slug: "sun-fiesta-venice-2026",
    start_date: "2026-10-16",
    end_date: "2026-10-18",
    start_time: null,
    end_time: null,
    select_nights: true,
    schedule_note: "October 16–18 at Centennial Park. Friday runs 4–9:30pm; the organizer publishes the weekend program by date. Admission and parking are free.",
    venue: "Centennial Park",
    address: "200 W Venice Ave, Venice, FL 34285",
    city: "Venice",
    county: "Sarasota",
    lat: 27.1006258,
    lng: -82.4468937,
    place_id: "ChIJu73by6Rbw4gR857K3YRfLQo",
    category: "festival",
    subcategory: "community-festival",
    tags: ["fall", "festival", "outdoor", "community", "free"],
    audience: ["families", "adults", "couples"],
    is_free: true,
    price_min: 0,
    price_max: 0,
    price_band: "free",
    official_event_url: "https://www.womenssertoma.com/sun-fiesta",
    source_url: "https://www.womenssertoma.com/sun-fiesta",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Women's Sertoma and the City of Venice confirm current October 16–18 dates, Centennial Park, free admission, and festival programming. The city listing gives Friday's 4–9:30pm hours; unposted weekend hours are not inferred.",
    card_hook: "A free Venice fall festival weekend at Centennial Park.",
    editorial_summary: "A three-day community festival with current organizer and city confirmation.",
    why_go: "Choose it for a free Venice festival plan with confirmed dates.",
    wayfind_verdict: "Venice's confirmed free festival weekend.",
    duration_recommendation: "Half day",
    crowd_level: "high",
    editorial_score: 8,
    uniqueness_score: 7,
    popularity_score: 8,
  },
  {
    ...SARASOTA_AUDIT_BASE,
    event_id: "night-of-wonder-ringling-2026",
    event_series_id: "night-of-wonder-ringling",
    event_name: "Night of Wonder: Season Kickoff Party",
    short_title: "Night of Wonder",
    slug: "night-of-wonder-ringling-2026",
    start_date: "2026-10-16",
    end_date: "2026-10-16",
    start_time: "19:00:00",
    end_time: "23:59:00",
    select_nights: false,
    schedule_note: "October 16, 7pm–midnight. VIP entry begins at 7pm; general admission begins at 7:30pm.",
    venue: "The Ringling Museum, Museum of Art Courtyard",
    address: "5401 Bay Shore Rd, Sarasota, FL 34243",
    city: "Sarasota",
    county: "Sarasota",
    lat: 27.3815477,
    lng: -82.5605716,
    place_id: "ChIJ6y2dx9g_w4gRWoZIRhLk-JI",
    category: "festival",
    subcategory: "museum-party",
    tags: ["fall", "date-night", "arts", "museum", "nightlife"],
    audience: ["adults", "couples"],
    is_free: false,
    price_min: 45,
    price_max: 200,
    price_band: "$$$$",
    official_event_url: "https://www.ringling.org/",
    official_ticket_url: "https://www.ringling.org/event/ringling-revealed/",
    source_url: "https://sarasotaarts.org/event/night-of-wonder-season-kickoff-party/",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Current Ringling and Visit Sarasota listings confirm the October 16 date, 7pm–midnight hours, Museum of Art Courtyard, and $45 general/$200 VIP ticket prices.",
    card_hook: "A ticketed Ringling courtyard party with a published late-night schedule.",
    editorial_summary: "A one-night Museum of Art Courtyard season kickoff with separate VIP and general entry times.",
    why_go: "Choose it for a planned museum-night date, with the price tier visible before you go.",
    wayfind_verdict: "A confirmed Ringling date-night event, not a stale Halloween listing.",
    duration_recommendation: "Evening",
    crowd_level: "high",
    editorial_score: 8,
    uniqueness_score: 8,
    popularity_score: 8,
  },
  {
    ...SARASOTA_AUDIT_BASE,
    event_id: "uf-ifas-edfest-plant-sale-2026",
    event_series_id: "uf-ifas-edfest-plant-sale",
    event_name: "UF/IFAS Master Gardener Plant Sale & EdFest",
    short_title: "UF/IFAS Plant Sale & EdFest",
    slug: "uf-ifas-edfest-plant-sale-sarasota-2026",
    start_date: "2026-10-10",
    end_date: "2026-10-10",
    start_time: "08:00:00",
    end_time: "13:00:00",
    select_nights: false,
    schedule_note: "October 10, 8am–1pm at UF/IFAS Extension Sarasota County, Twin Lakes Park. Admission is free; plant prices vary.",
    venue: "UF/IFAS Extension Sarasota County, Twin Lakes Park",
    address: "6600 Clark Road, Sarasota, FL 34241",
    city: "Sarasota",
    county: "Sarasota",
    lat: 27.2672577,
    lng: -82.4393082,
    place_id: "ChIJ8SekLo9Gw4gR81Gftma1QvU",
    category: "festival",
    subcategory: "plant-sale",
    tags: ["fall", "festival", "gardening", "plant-sale", "family", "free"],
    audience: ["families", "adults", "couples"],
    is_free: true,
    price_min: 0,
    price_max: 0,
    price_band: "free",
    official_event_url: "https://sfyl.ifas.ufl.edu/sarasota/gardening-and-landscaping/horticulture-residential/master-gardener/plant-sale/",
    source_url: "https://sfyl.ifas.ufl.edu/sarasota/gardening-and-landscaping/horticulture-residential/master-gardener/plant-sale/",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "UF/IFAS and Visit Sarasota confirm the October 10, 8am–1pm event, the extension location, and free admission. Plant prices vary and are not represented as admission.",
    card_hook: "A free Sarasota plant sale and gardening day with a clear 8am start.",
    editorial_summary: "A daytime UF/IFAS plant-sale event at Twin Lakes Park, with admission separated from plant purchases.",
    why_go: "Pick it for a morning outdoor plan with a verified local host.",
    wayfind_verdict: "A free Sarasota fall garden event with honest purchase details.",
    duration_recommendation: "1–2 hours",
    crowd_level: "moderate",
    editorial_score: 7,
    uniqueness_score: 7,
    popularity_score: 7,
  },
  {
    ...SARASOTA_AUDIT_BASE,
    event_id: "wellen-park-wine-festival-2026",
    event_series_id: "wellen-park-wine-festival",
    event_name: "Wellen Park Wine Festival 2026",
    short_title: "Wellen Park Wine Festival",
    slug: "wellen-park-wine-festival-2026",
    start_date: "2026-11-13",
    end_date: "2026-11-14",
    start_time: null,
    end_time: null,
    select_nights: true,
    schedule_note: "Wine dinner November 13, 6–9pm; November 14 tasting class 11am–noon and Grand Tasting 1–4pm. Dinner is $175; class is $25; Grand Tasting is $95 general or $175 VIP.",
    venue: "Downtown Wellen Park, Solis Hall and Wellen Park Boulevard",
    address: "19745 Wellen Park Blvd, Venice, FL 34293",
    city: "Venice",
    county: "Sarasota",
    lat: 27.0462517,
    lng: -82.3272153,
    place_id: "ChIJJQVMQuJXw4gRhD0CpEOETGo",
    category: "festival",
    subcategory: "wine-festival",
    tags: ["fall", "festival", "food", "wine", "date-night"],
    audience: ["adults", "couples"],
    is_free: false,
    price_min: 25,
    price_max: 175,
    price_band: "$$$$",
    official_event_url: "https://wellenpark.com/wine/",
    official_ticket_url: "https://www.eventbrite.com/e/wellen-park-wine-festival-tickets-1990418718969",
    source_url: "https://wellenpark.com/news/2026-wellen-park-wine-festival-tickets-now-on-sale/",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Wellen Park's official ticket announcement and event page confirm November 13–14 programming, prices, food-and-wine tasting format, and the Wellen Park address.",
    card_hook: "A two-day Wellen Park wine festival with every published ticket tier spelled out.",
    editorial_summary: "One festival series with a wine dinner, a tasting class, and a Grand Tasting—rather than duplicate session cards.",
    why_go: "Choose it for a ticketed November food-and-wine plan with a known schedule.",
    wayfind_verdict: "Wellen Park's fully scheduled fall wine weekend.",
    duration_recommendation: "Half day",
    crowd_level: "high",
    editorial_score: 8,
    uniqueness_score: 8,
    popularity_score: 8,
  },
  {
    ...SARASOTA_AUDIT_BASE,
    event_id: "utc-night-market-tailgate-2026-09-17",
    event_series_id: "utc-night-market-tailgate",
    event_name: "UTC Night Market Tailgate Edition",
    short_title: "UTC Night Market Tailgate",
    slug: "utc-night-market-tailgate-sarasota-2026",
    start_date: "2026-09-17",
    end_date: "2026-09-17",
    start_time: "18:30:00",
    end_time: "21:30:00",
    select_nights: false,
    schedule_note: "September 17, 6:30–9:30pm at The Green at UTC. Admission is free.",
    venue: "The Green at UTC",
    address: "125 N Cattlemen Road, Sarasota, FL 34243",
    city: "Sarasota",
    county: "Sarasota",
    lat: 27.3844559,
    lng: -82.4526274,
    place_id: "ChIJHcu6u2BHw4gRDKuRC9sow20",
    category: "festival",
    subcategory: "night-market",
    tags: ["fall", "market", "night-market", "food", "free"],
    audience: ["families", "adults", "couples"],
    is_free: true,
    price_min: 0,
    price_max: 0,
    price_band: "free",
    official_event_url: "https://utcsarasota.com/event/utc-night-market-7/",
    source_url: "https://utcsarasota.com/event/utc-night-market-7/",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "UTC and Visit Sarasota confirm the September 17 date/time, The Green location, and free public-market format. Vendor lineups are not claimed.",
    card_hook: "A free UTC night market with a published early-fall evening window.",
    editorial_summary: "A single free market evening at The Green, without inventing a vendor or food-truck roster.",
    why_go: "Choose it for a casual September market plan at UTC.",
    wayfind_verdict: "UTC's confirmed free tailgate-market night.",
    duration_recommendation: "1–2 hours",
    crowd_level: "moderate",
    editorial_score: 7,
    uniqueness_score: 7,
    popularity_score: 7,
  },
]);

export const GULF_COAST_FALL_2026_PATCHES = Object.freeze([
  {
    event_id: "raprager-fall-festival-2026",
    set: {
      address: "16907 Boy Scout Rd, Odessa, FL 33556",
      end_date: null,
      schedule_note: "Grand opening September 18; select dates September through November. Fridays 11am–11pm, Saturdays 9am–11pm and Sundays 9am–9pm. The farm has not published a hard closing date.",
      source_url: "https://rapragerfarm.com/fall-festival",
      source_type: "official-organizer",
      source_tier: 1,
      verification_confidence: "high",
      last_verified_at: VERIFIED_AT,
      verify_note: "Official festival page confirms 16907 Boy Scout Rd and select dates September through November; no hard 2026 closing date is published.",
    },
  },
  {
    event_id: "lights-at-spooky-point-2026",
    set: {
      schedule_note: "October 1–31 with two entry times, 6:30pm and 7:45pm; ends at 9pm. CLOSED Tuesday, October 13. October 19 is unavailable on the ticket calendar.",
      source_url: "https://selby.org/lights-at-spooky-point-returns-october-1-through-october-31/",
      source_type: "official-organizer",
      source_tier: 1,
      verification_confidence: "high",
      last_verified_at: VERIFIED_AT,
      verify_note: "Official Selby press release explicitly states the October 13 closure; the ticket calendar separately shows October 19 unavailable.",
      wayfind_verdict: "A polished waterfront Halloween walk on select October nights.",
    },
  },
  {
    event_id: "fearville-dk-farms-2026",
    set: {
      price_min: null,
      price_max: null,
      price_band: null,
      schedule_note: "Fridays and Saturdays in October, 7–10pm; the gate closes about 9:30pm. Confirm current haunt admission in the official ticket flow.",
      source_url: "https://www.dkfarmsandgardens.com/fearville",
      source_type: "official-organizer",
      source_tier: 1,
      verification_confidence: "medium",
      last_verified_at: VERIFIED_AT,
      verify_note: "The official page confirms October Friday/Saturday hours. Its visible $8/$12 amounts are labeled additional entertainment, not main haunt admission; current page does not mention SpookyVille.",
      card_hook: "Three local farm haunts on Friday and Saturday nights in October.",
      editorial_summary: "A Largo farm haunt built around a haunted house, hayride and higher-intensity trail, with optional activities sold separately.",
      why_go: "Pick it for a local Pinellas scare night without theme-park scale.",
      insider_tip: "The gate closes around 9:30pm; check the official ticket flow for current admission before leaving.",
      wayfind_verdict: "Pinellas' full farm-haunt night.",
    },
  },
  {
    event_id: "zootampa-creatures-2026",
    set: {
      schedule_note: "Member preview September 25. Public nights: September 26; October 2–3, 9–11, 16–18, 23–25 and 30–31, 4–10pm. Zoo Fun Ticket blockouts after 4pm: October 10, 17 and 24.",
      source_url: "https://zootampa.org/events/creatures-of-the-night/",
      source_type: "official-organizer",
      source_tier: 1,
      verification_confidence: "high",
      last_verified_at: VERIFIED_AT,
      verify_note: "Official ZooTampa event page confirms dates, prices, blockouts, no-reservation policy and costume restrictions.",
      insider_tip: "No reservation is required. Costumes are limited to children 12 and under; toy weapons are prohibited.",
    },
  },
]);

export const GULF_COAST_FALL_2026_HELD = Object.freeze([
  { id: "farmer-mikes-u-pick-fall-festival-2026", reason: "Package says Friday, October 3, but October 3, 2026 is Saturday." },
  { id: "sarasota-cupcake-pumpkin-spice-order", reason: "Order-and-pickup offer has no storefront place row; publishing it as an event would mislead visitors." },
  { id: "seasonal-food-offers", reason: "Local availability and end dates are unverified, and placeless offers do not surface in the current product model." },
  { id: "3-daughters-fall-bouquet-workshop-2026-09-09", reason: "Verified floral workshop does not match any current Fall poster promise; it must not be misfiled as seasonal food or spooky date night." },
  { id: "skye-ranch-witches-ride-2026", reason: "Organizer confirms date, time, and address but not 2026 public admission or spectator status." },
  { id: "undead-in-the-water-tampa-2026", reason: "Ticket price and nightly hours were not retrievable from current sources." },
  { id: "halloween-at-the-ringling-2026", reason: "Only 2024 official Halloween evidence was found; no 2026 date may be rolled forward." },
  { id: "bradenton-fall-craft-fair-2026", reason: "No independent organizer or venue confirmation with admission detail was found." },
  { id: "sarasota-fall-seafood-music-festival-2026", reason: "Official Sarasota Seafood & Music Festival source confirms winter dates, not a fall 2026 event." },
  { id: "sertoma-bradenton-pumpkin-patch-2026", reason: "Organizer page is explicitly the 2025 season; no 2026 announcement was found." },
  { id: "north-port-food-and-fall-fest-2026", reason: "A third-party listing has details but the city has not confirmed the 2026 event." },
  { id: "sarasota-cupcake-pumpkin-spice-2026", reason: "Order-ahead pickup product, not a storefront place card or event." },
  { id: "pour-and-decor-gilmore-girls-fall-menu-2026", reason: "Seasonal menu discovery is a place-menu product, not an event row." },
  { id: "publix-pumpkin-bakery-lakewood-ranch-2026", reason: "Store-variable seasonal bakery inventory is a place-menu product, not an event row." },
  { id: "paris-baguette-new-tampa-pumpkin-2026", reason: "Seasonal menu candidate is outside the Sarasota 40-mile scope." },
  { id: "waffle-monkey-pumpkin-sku-check-2026", reason: "No dated 2026 seasonal SKU proof was found." },
  { id: "good-liquid-waterside-oktoberfest-2026", reason: "No dated organizer confirmation or admission detail was found." },
  { id: "calusa-kolben-2026-tap-check", reason: "No dated 2026 tap-list proof was found." },
  { id: "local-seasonal-cocktails-2026", reason: "No canonical venue, address, or dated 2026 proof exists for the umbrella claim." },
  { id: "florida-stone-crab-season-open-2026", reason: "Statewide regulatory season is editorial context, not a venue event or place card." },
  { id: "starbucks-fall-menu-2026-sarasota-area", reason: "Participating-store chain menu is a place-menu product, not an event row." },
  { id: "dunkin-fall-pumpkin-2026-sarasota-area", reason: "Participating-franchise chain menu is a place-menu product, not an event row." },
]);
