// Canonical Gulf Coast fall records promoted from external research packages.
//
// This file is the reviewed boundary between discovery and production data:
// only evidence-backed event rows and narrowly scoped corrections belong here.
// Held candidates remain explicit so a future pass does not silently publish
// conflicting dates, unverified prices, or placeless offers as events.

const VERIFIED_AT = "2026-09-07T00:00:00+00:00";

const BASE = {
  year: 2026,
  timezone: "America/New_York",
  event_status: "scheduled",
  state: "FL",
  last_verified_at: VERIFIED_AT,
};

export const GULF_COAST_FALL_2026_ROWS = Object.freeze([
  {
    ...BASE,
    event_id: "gallaghers-pumpkins-2026",
    event_series_id: "gallaghers-pumpkins",
    event_name: "Gallagher's Pumpkins & Christmas Trees",
    short_title: "Gallagher's Pumpkins",
    slug: "gallaghers-pumpkins-st-pete-2026",
    start_date: "2026-09-21",
    end_date: null,
    start_time: "09:00:00",
    end_time: "21:00:00",
    select_nights: false,
    schedule_note: "Open daily from September 21, 9am–9pm. The 2026 closing date has not been published.",
    venue: "Gallagher's Pumpkins & Christmas Trees",
    address: "7401 4th St N, St. Petersburg, FL 33702",
    city: "St. Petersburg",
    county: "Pinellas",
    lat: 27.843052,
    lng: -82.6449,
    place_id: null,
    category: "seasonal",
    subcategory: "pumpkin-patch",
    tags: ["fall", "pumpkins", "family", "photo-ops", "local"],
    audience: ["families", "kids", "couples"],
    is_free: null,
    price_min: null,
    price_max: null,
    price_band: null,
    official_event_url: "https://www.gallagherspumpkinsandchristmastrees.com/",
    source_url: "https://www.gallagherspumpkinsandchristmastrees.com/",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Official site confirms the September 21 opening, daily 9am–9pm hours, address, and free casual family photos. Admission and pumpkin prices are not posted.",
    card_hook: "St. Pete's daily pumpkin stop, with the vintage red truck photo waiting out front.",
    editorial_summary: "An easy neighborhood pumpkin and photo run with a goat pen, food trailer and an expanded 2026 layout.",
    why_go: "Pick this for a local fall stop without committing to a full farm-festival day.",
    insider_tip: "Casual family photos are free; professional sessions require a reservation.",
    wayfind_verdict: "Pinellas' easy, everyday pumpkin patch.",
    duration_recommendation: "1–2 hours",
    crowd_level: "moderate",
    editorial_score: 8,
    uniqueness_score: 7,
    popularity_score: 7,
  },
  {
    ...BASE,
    event_id: "seminole-heights-great-pumpkin-patch-2026",
    event_series_id: "seminole-heights-great-pumpkin-patch",
    event_name: "Seminole Heights Great Pumpkin Patch",
    short_title: "Seminole Heights Pumpkin Patch",
    slug: "seminole-heights-great-pumpkin-patch-2026",
    start_date: "2026-10-07",
    end_date: "2026-10-31",
    start_time: null,
    end_time: null,
    select_nights: true,
    schedule_note: "October 7–31. Closed Monday–Tuesday until October 19; Wednesday–Thursday 5–8pm, Friday 4–8:30pm, Saturday 10am–8pm, Sunday noon–6pm.",
    venue: "Seminole Heights Great Pumpkin Patch",
    address: "6111 N Central Ave, Tampa, FL 33604",
    city: "Tampa",
    county: "Hillsborough",
    lat: 28.002979,
    lng: -82.454603,
    place_id: null,
    category: "seasonal",
    subcategory: "pumpkin-patch",
    tags: ["fall", "pumpkins", "family", "community", "local"],
    audience: ["families", "kids"],
    is_free: null,
    price_min: null,
    price_max: null,
    price_band: null,
    official_event_url: "https://www.myhtca.org/shgpp",
    source_url: "https://www.myhtca.org/shgpp",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Organizer page body confirms the 2026 dates, hours and address. Admission pricing is not stated.",
    card_hook: "A neighborhood pumpkin patch whose proceeds stay in Seminole Heights.",
    editorial_summary: "A volunteer-run community patch with useful evening hours and a central Tampa location.",
    why_go: "Choose it when you want pumpkins nearby instead of a drive to a farm.",
    insider_tip: "Check the day-specific hours before leaving; the patch is closed Monday and Tuesday until October 19.",
    wayfind_verdict: "Tampa's most neighborhood-first pumpkin stop.",
    duration_recommendation: "Under 2 hours",
    crowd_level: "moderate",
    editorial_score: 8,
    uniqueness_score: 7,
    popularity_score: 7,
  },
  {
    ...BASE,
    event_id: "sarasota-oktoberfest-benderson-2026",
    event_series_id: "sarasota-oktoberfest-benderson",
    event_name: "Sarasota Oktoberfest at Nathan Benderson Park",
    short_title: "Sarasota Oktoberfest",
    slug: "sarasota-oktoberfest-benderson-2026",
    start_date: "2026-10-10",
    end_date: "2026-10-11",
    start_time: "10:00:00",
    end_time: "17:00:00",
    select_nights: false,
    schedule_note: "October 10–11, 10am–5pm. Admission is free; parking is $20 per car.",
    venue: "Nathan Benderson Park",
    address: "5851 Nathan Benderson Circle, Sarasota, FL 34235",
    city: "Sarasota",
    county: "Sarasota",
    lat: 27.3742443,
    lng: -82.4500873,
    place_id: "ChIJczkDFL04w4gRwfowcSv8Tro",
    category: "festival",
    subcategory: "oktoberfest",
    tags: ["fall", "oktoberfest", "food", "beer", "family", "free", "local"],
    audience: ["families", "adults", "couples"],
    is_free: true,
    price_min: 0,
    price_max: 0,
    price_band: "free",
    official_event_url: "https://nathanbendersonpark.org/event/oktoberfest/",
    source_url: "https://nathanbendersonpark.org/event/oktoberfest/",
    source_type: "official-organizer",
    source_tier: 1,
    verification_confidence: "high",
    verify_note: "Official park page confirms October 10–11, 10am–5pm, free admission, and $20 per-car parking.",
    card_hook: "Free lakeside Oktoberfest with regatta energy; budget $20 per car for parking.",
    editorial_summary: "German food, live bands, a beer garden and kids zone share the lakefront with rowing and dragon-boat racing.",
    why_go: "It gives Sarasota a full Oktoberfest day without an admission ticket.",
    parking_tip: "Parking is $20 per car, paid on arrival.",
    wayfind_verdict: "Sarasota's best free-entry Oktoberfest day.",
    duration_recommendation: "Half day",
    crowd_level: "high",
    editorial_score: 9,
    uniqueness_score: 8,
    popularity_score: 8,
  },
  {
    ...BASE,
    event_id: "cape-coral-oktoberfest-2026",
    event_series_id: "cape-coral-oktoberfest",
    event_name: "Cape Coral Oktoberfest",
    short_title: "Cape Coral Oktoberfest",
    slug: "cape-coral-oktoberfest-2026",
    start_date: "2026-10-16",
    end_date: "2026-10-25",
    start_time: null,
    end_time: null,
    select_nights: true,
    schedule_note: "Two weekends: October 16–18 and October 23–25. The organizer has not yet posted 2026 daily hours.",
    venue: "German American Social Club of Cape Coral",
    address: "2101 SW Pine Island Rd, Cape Coral, FL 33991",
    city: "Cape Coral",
    county: "Lee",
    lat: 26.6392039,
    lng: -82.0158109,
    place_id: null,
    category: "festival",
    subcategory: "oktoberfest",
    tags: ["fall", "oktoberfest", "food", "beer", "family"],
    audience: ["families", "adults", "couples"],
    is_free: false,
    price_min: 8,
    price_max: 10,
    price_band: "$",
    official_event_url: "https://www.gasc-capecoral.com/oktoberfest",
    official_ticket_url: "https://capecoraloktoberfest.com/tickets/",
    source_url: "https://festivalnet.com/42073/Cape-Coral-Florida/Ethnic-Festivals/Oktoberfest-Largest-in-Florida",
    source_type: "reputable-calendar",
    source_tier: 2,
    verification_confidence: "medium",
    verify_note: "The club confirms a two-weekend 2026 event and the venue. FestivalNet supplies the specific dates and $8 advance/$10 gate pricing; official daily hours remain unpublished.",
    card_hook: "Cape Coral's German-club Oktoberfest returns for two weekends of biergarten, food and live music.",
    editorial_summary: "A large Southwest Florida Oktoberfest with multiple stages, German food, vendors and family activities.",
    why_go: "Choose it for the full German-club festival experience instead of a one-night bar event.",
    insider_tip: "Confirm the daily schedule before driving; the organizer still lists 2026 hours as coming soon.",
    wayfind_verdict: "Southwest Florida's big traditional Oktoberfest.",
    duration_recommendation: "Half day",
    crowd_level: "high",
    editorial_score: 8,
    uniqueness_score: 8,
    popularity_score: 8,
  },
  {
    ...BASE,
    event_id: "plant-city-oktoberfest-2026",
    event_series_id: "plant-city-oktoberfest",
    event_name: "Plant City Oktoberfest",
    short_title: "Plant City Oktoberfest",
    slug: "plant-city-oktoberfest-2026",
    start_date: "2026-09-26",
    end_date: "2026-09-26",
    start_time: "15:00:00",
    end_time: "22:00:00",
    select_nights: false,
    schedule_note: "Saturday, September 26, 3–10pm. Admission pricing has not been published.",
    venue: "McCall Park",
    address: "100 N Collins St, Plant City, FL 33563",
    city: "Plant City",
    county: "Hillsborough",
    lat: 28.0157,
    lng: -82.1219,
    place_id: null,
    category: "festival",
    subcategory: "oktoberfest",
    tags: ["fall", "oktoberfest", "food", "beer", "family", "local"],
    audience: ["families", "adults", "couples"],
    is_free: null,
    price_min: null,
    price_max: null,
    price_band: null,
    official_event_url: null,
    source_url: "https://www.plantcityobserver.com/parks-rec-to-host-oktoberfest/",
    source_type: "local-news",
    source_tier: 2,
    verification_confidence: "medium",
    verify_note: "Plant City Observer directly quotes city officials confirming the September 26 date, 3–10pm time, organizers and downtown program. Admission is unposted; the map point is McCall Park.",
    card_hook: "Downtown Plant City's one-night Oktoberfest runs 3–10pm with biergartens, music and a free kids zone.",
    editorial_summary: "A civic Oktoberfest with German-inspired food, live music, games, local vendors and family activities.",
    why_go: "It is the compact east-Hillsborough choice for an Oktoberfest evening.",
    insider_tip: "Check the city's event update for street closures and any late admission announcement.",
    wayfind_verdict: "Plant City's easy hometown Oktoberfest night.",
    duration_recommendation: "2–4 hours",
    crowd_level: "high",
    editorial_score: 8,
    uniqueness_score: 7,
    popularity_score: 7,
  },
]);

export const GULF_COAST_FALL_2026_PATCHES = Object.freeze([
  {
    event_id: "raprager-fall-festival-2026",
    set: {
      address: "16907 Boy Scout Rd, Odessa, FL 33556",
      end_date: null,
      schedule_note: "Grand opening September 18; select dates September through November. Fridays 11am–11pm, Saturdays 9am–11pm and Sundays 9am–9pm. The farm has not published a hard closing date.",
      source_url: "https://rapragerfarm.com/fall-festival",
      source_type: "official-organizer",
      source_tier: 1,
      verification_confidence: "high",
      last_verified_at: VERIFIED_AT,
      verify_note: "Official festival page confirms 16907 Boy Scout Rd and select dates September through November; no hard 2026 closing date is published.",
    },
  },
  {
    event_id: "lights-at-spooky-point-2026",
    set: {
      schedule_note: "October 1–31 with two entry times, 6:30pm and 7:45pm; ends at 9pm. CLOSED Tuesday, October 13. October 19 is unavailable on the ticket calendar.",
      source_url: "https://selby.org/lights-at-spooky-point-returns-october-1-through-october-31/",
      source_type: "official-organizer",
      source_tier: 1,
      verification_confidence: "high",
      last_verified_at: VERIFIED_AT,
      verify_note: "Official Selby press release explicitly states the October 13 closure; the ticket calendar separately shows October 19 unavailable.",
      wayfind_verdict: "A polished waterfront Halloween walk on select October nights.",
    },
  },
  {
    event_id: "fearville-dk-farms-2026",
    set: {
      price_min: null,
      price_max: null,
      price_band: null,
      schedule_note: "Fridays and Saturdays in October, 7–10pm; the gate closes about 9:30pm. Confirm current haunt admission in the official ticket flow.",
      source_url: "https://www.dkfarmsandgardens.com/fearville",
      source_type: "official-organizer",
      source_tier: 1,
      verification_confidence: "medium",
      last_verified_at: VERIFIED_AT,
      verify_note: "The official page confirms October Friday/Saturday hours. Its visible $8/$12 amounts are labeled additional entertainment, not main haunt admission; current page does not mention SpookyVille.",
      card_hook: "Three local farm haunts on Friday and Saturday nights in October.",
      editorial_summary: "A Largo farm haunt built around a haunted house, hayride and higher-intensity trail, with optional activities sold separately.",
      why_go: "Pick it for a local Pinellas scare night without theme-park scale.",
      insider_tip: "The gate closes around 9:30pm; check the official ticket flow for current admission before leaving.",
      wayfind_verdict: "Pinellas' full farm-haunt night.",
    },
  },
  {
    event_id: "zootampa-creatures-2026",
    set: {
      schedule_note: "Member preview September 25. Public nights: September 26; October 2–3, 9–11, 16–18, 23–25 and 30–31, 4–10pm. Zoo Fun Ticket blockouts after 4pm: October 10, 17 and 24.",
      source_url: "https://zootampa.org/events/creatures-of-the-night/",
      source_type: "official-organizer",
      source_tier: 1,
      verification_confidence: "high",
      last_verified_at: VERIFIED_AT,
      verify_note: "Official ZooTampa event page confirms dates, prices, blockouts, no-reservation policy and costume restrictions.",
      insider_tip: "No reservation is required. Costumes are limited to children 12 and under; toy weapons are prohibited.",
    },
  },
]);

export const GULF_COAST_FALL_2026_HELD = Object.freeze([
  { id: "dakin-harvest-festival-2026", reason: "Official tourism listing says October 10–11; secondary sources claim multiple weekends and $20." },
  { id: "sweetfields-fall-season-2026", reason: "Already live; package contains unresolved schedule and ticket conflicts." },
  { id: "farmer-mikes-u-pick-fall-festival-2026", reason: "Package says Friday, October 3, but October 3, 2026 is Saturday." },
  { id: "sarasota-cupcake-pumpkin-spice-order", reason: "Order-and-pickup offer has no storefront place row; publishing it as an event would mislead visitors." },
  { id: "seasonal-food-offers", reason: "Local availability and end dates are unverified, and placeless offers do not surface in the current product model." },
]);
