// GENERATED from lib/hotelBookingVerification.json — do not hand-edit.
// The RUNTIME allow-list: only the hotels whose Stay22 handoff was verified
// to land on the property named on the card. Kept to the allowed rows alone
// so the full 394-row audit record never ships to the browser; the evidence
// file stays in the repo for scripts/check-hotel-booking-verified.mjs, which
// pins this list against it.
export const VERIFIED_HOTEL_BOOKINGS = [
  { key: "wfh-aloft-sarasota-27334", placeId: "ChIJx26IQRNAw4gRgUI4V2RHDfY" },
  { key: "wfh-art-ovation-hotel-autograph-collection-27337", placeId: "ChIJn_4zMBJAw4gRnyPviItiNRs" },
  { key: "wfh-baymont-by-wyndham-sarasota-27321", placeId: "ChIJ2T-loFxAw4gRiMRtmFiC1h0" },
  { key: "wfh-best-western-plus-27109", placeId: "ChIJsbdss39Qw4gROz3jKBdAg6s" },
  { key: "wfh-best-western-plus-ambassador-suites-venice-27109", placeId: "ChIJsbdss39Qw4gROz3jKBdAg6s" },
  { key: "wfh-best-western-plus-bradenton-hotel-suites-27492", placeId: "ChIJGVfX-IE8w4gRX8KO6QLmUs8" },
  { key: "wfh-captiva-beach-resort-27248", placeId: "ChIJ69RB9SRCw4gRqecKrWvfQF4" },
  { key: "wfh-comfort-suites-27272", placeId: "ChIJ_QplV7dGw4gRTpiFE2yYNCk" },
  { key: "wfh-courtyard-by-marriott-bradenton-sarasota-riverfr-27499", placeId: "ChIJmRgc9NYXw4gRQlAxbX-KlVU" },
  { key: "wfh-courtyard-sarasota-bradenton-airport-27381", placeId: "ChIJY-XJdNs_w4gRkICZyqxST-4" },
  { key: "wfh-days-inn-27268", placeId: "ChIJocOSvL1Gw4gRkrBXa1uxi3k" },
  { key: "wfh-days-inn-bradenton-i-75-27493", placeId: "ChIJd5qo-H07w4gRhKeDRhi_fOs" },
  { key: "wfh-days-inn-bradenton-near-the-gulf-27469", placeId: "ChIJ0VZYHiAWw4gR6m1e6WaWTUc" },
  { key: "wfh-embassy-suites-by-hilton-27338", placeId: "ChIJfYV_5RFAw4gRoWMEc-mBd6I" },
  { key: "wfh-even-hotel-27386", placeId: "ChIJsYtTeeM4w4gRRLv8RnmCiTk" },
  { key: "wfh-fairfield-inn-suites-venice-27109", placeId: "ChIJU2Qx24BQw4gR9wu-GZwnPFA" },
  { key: "wfh-gulf-shores-beach-resort-27128", placeId: "ChIJQTbtpGNbw4gRytP88QU-p7w" },
  { key: "wfh-hampton-inn-by-hilton-27533", placeId: "ChIJ33HyU8w8w4gRvymJsl3cseA" },
  { key: "wfh-hibiscus-suites-27258", placeId: "ChIJ41HLaBZBw4gR_yW1-hLguu4" },
  { key: "wfh-holiday-inn-express-suites-sarasota-east-i-75-27271", placeId: "ChIJCTdG_NtHw4gR3BC76VMTDcA" },
  { key: "wfh-holiday-inn-express-venice-27108", placeId: "ChIJbfHWKX5Qw4gRPhAbPorsNuo" },
  { key: "wfh-home2-suites-by-hilton-sarasota-i-75-bee-ridge-27302", placeId: "ChIJP-PvIANHw4gRdApbE3-oiWE" },
  { key: "wfh-hyatt-place-sarasota-lakewood-ranch-27392", placeId: "ChIJqftER-I4w4gRWIOCznnHnqM" },
  { key: "wfh-island-sun-inn-27089", placeId: "ChIJBcDh9bdbw4gRyOaF8EDbJtU" },
  { key: "wfh-lido-beach-resort-27310", placeId: "ChIJg-jF3Ihqw4gRNJ0QhK4Ywsg" },
  { key: "wfh-ramada-by-wyndham-sarasota-waterfront-27413", placeId: "ChIJ_1W8M5AVw4gRRBIwOhNShU4" },
  { key: "wfh-red-roof-inn-ellenton-27528", placeId: "ChIJX6QIx9Y8w4gReQx67QrCz24" },
  { key: "wfh-residence-inn-sarasota-bradenton-27381", placeId: "ChIJz-ZAlMQ_w4gRLLYRhgPCJVg" },
  { key: "wfh-rodeway-inn-27072", placeId: "ChIJzaHdGi9aw4gR5M3AZWT7QwQ" },
  { key: "wfh-sleep-inn-27380", placeId: "ChIJq-iKP9s_w4gRekl-76tuBCc" },
  { key: "wfh-springhill-suites-by-marriott-bradenton-downtown-27499", placeId: "ChIJq4KWDc4Xw4gRJ_ZVutHZh3I" },
  { key: "wfh-the-resort-at-longboat-key-club-27331", placeId: "ChIJqZAQtMVqw4gRQSMDzhntYY4" },
  { key: "wfh-the-ritz-carlton-sarasota-27338", placeId: "ChIJRxeQRxBAw4gRi93tRdpVyX0" },
  { key: "wfh-the-sarasota-modern-a-tribute-portfolio-hotel-27341", placeId: "ChIJEfkg0A1Aw4gRaUdlFUu85bA" },
  { key: "wfh-the-westin-sarasota-27336", placeId: "ChIJQzeGphFAw4gRUVSuNnIkJT4" },
  { key: "wfh-towneplace-suites-by-marriott-27108", placeId: "ChIJCXyITIdQw4gRo9fHGjbfmkE" },
  { key: "wfh-towneplace-suites-by-marriott-sarasota-bradenton-27460", placeId: "ChIJg6L5LJAWw4gRWfpjVd_rTPw" },
  { key: "wfh-tru-by-hilton-27442", placeId: "ChIJd_iPrv07w4gRfBSjYDKmqjM" },
  { key: "wfh-warm-mineral-springs-motel-27048", placeId: "ChIJNx_mOHxUw4gRW_dbjdLGEJg" },
  { key: "wfh-zota-beach-resort-27399", placeId: "ChIJpYzyJX4Tw4gR7Eisirbe6xI" },
];
