// lib/partnerCollectionsData.js — the HEAVY partner place data (baked Google
// photo resource names are ~800 chars each). Split out of lib/partnerCollections.js
// and loaded ONLY via dynamic import when a partner sheet opens, so these strings
// never enter the eager home-route bundle (check-bundle's 500KB gz budget — the
// Vercel build that caught this, 2026-08-23). Everything the AMAZON-RAIL TILE
// needs (gate, art, titles) stays in the light module; only the sheet's place
// list lives here.
//
// rating/reviews are a Google snapshot; the SHOWN score is recomputed by
// wayfindScore() at hydrate time (see partnerCollections.hydratePartnerCollection).
//
// Each place also carries an `ed` (editorial) block — the CGNA's curated take:
// role (where-to-go / where-to-stay), why it was picked, what not to miss, an
// insider tip, a good-for tag and a price band. The partner sheet renders this
// as the Wayfind place-card editorial (HookDetail partnerSplash path), so a
// reader knows exactly why each place earned its spot. Researched from primary
// sources (Infatuation, Miami New Times, Time Out, INK, official sites), not
// invented — 2026-08-23.
const PARTNER_PLACES = {
  "coconut-grove": [
    {"id":"ChIJb8Zih8-32YgRgxaWQFJtIFg","name":"Barracuda","lat":25.727761,"lng":-80.243179,"rating":4.4,"reviews":950,"primaryType":"bar_and_grill","types":["bar_and_grill","sports_bar","seafood_restaurant","american_restaurant"],"photoRef":"places/ChIJb8Zih8-32YgRgxaWQFJtIFg/photos/wfplacediscovery","address":"Parking lot, 3035 Fuller St, Coconut Grove","ed":{"role":"Where the Grove hangs out","why":"The Grove's unpretentious anchor — 52 beers on tap, the game on, and a crowd of regulars who've been coming for years.","order":"The blackened snapper sandwich on house garlic bread — the thing locals send you for.","tip":"Wednesday is Bottles & Beats — live music from 7pm with 20% off craft beer bottles & cans and 99¢ wings (min 6, dine-in). Any other night, come for trivia or the game.","goodFor":"Casual · Sports · Live music Wed","price":"$$"}},
    {"id":"ChIJe1t0Q8W32YgRHGUckw_C5Uw","name":"Amal","lat":25.726471,"lng":-80.244213,"rating":4.7,"reviews":2700,"primaryType":"restaurant","types":["restaurant","lebanese_restaurant","mediterranean_restaurant","middle_eastern_restaurant"],"photoRef":"places/ChIJe1t0Q8W32YgRHGUckw_C5Uw/photos/wfplacediscovery","address":"3480 Main Hwy Ste 100, Miami","ed":{"role":"Where to linger over dinner","why":"Modern Lebanese built for sharing — generous mezze in a Studio Munge room that turns dinner into a whole evening.","order":"The Monk Salad and Truffle Rakakat to start, then the Black Cod Harra as the centerpiece.","tip":"There's a 5,000 sq ft rooftop bar upstairs — arrive early for a drink with a Grove view.","goodFor":"Date night · Groups","price":"$$$"}},
    {"id":"ChIJVVVFQsW32YgRshiwWyuedns","name":"Level 6","lat":25.726456,"lng":-80.244222,"rating":4.8,"reviews":3350,"primaryType":"restaurant","types":["restaurant","food","point_of_interest","establishment"],"photoRef":"places/ChIJVVVFQsW32YgRshiwWyuedns/photos/wfplacediscovery","address":"3480 Main Hwy 6th floor, Coconut Grove","ed":{"role":"Where to catch sunset","why":"The Grove's highest-rated table — a sixth-floor rooftop where shareable plates meet a straight shot to Biscayne Bay at golden hour.","order":"Small plates to share, timed for sunset, when the terrace becomes the after-work scene.","tip":"Go at golden hour on a weekday; it fills fast once the sun drops.","goodFor":"Sunset · Views","price":"$$$"}},
    {"id":"ChIJZRBieMW32YgRe9uja7jsGmQ","name":"Sapore di Mare","lat":25.72731,"lng":-80.242833,"rating":4.5,"reviews":1530,"primaryType":"italian_restaurant","types":["italian_restaurant","seafood_restaurant","restaurant","point_of_interest"],"photoRef":"places/ChIJZRBieMW32YgRe9uja7jsGmQ/photos/wfplacediscovery","address":"3433 Main Hwy, Miami","ed":{"role":"Where locals eat Italian","why":"A tiny, nautical Campanian seafood room where the staff are Italian natives who remember your order — the Grove's regulars' hangout.","order":"Tagliolini cacio e pepe finished tableside in a wheel of aged Pecorino — and anything from the crudo list.","tip":"Book ahead; it's small and the year-round locals fill it.","goodFor":"Intimate dinner","price":"$$$"}},
    {"id":"ChIJY7MwUQy32YgR39Vs9IYxci4","name":"BodyRok","lat":25.728972,"lng":-80.241977,"rating":4.8,"reviews":55,"primaryType":"gym","types":["gym","sports_complex","sports_school","sports_activity_location"],"photoRef":"places/ChIJY7MwUQy32YgR39Vs9IYxci4/photos/wfplacediscovery","address":"3015 Grand Ave #216, Miami","ed":{"role":"Where to start the day","why":"The Grove's newest reformer studio — 45-minute classes that run high-intensity but low-impact, so you leave worked, not wrecked.","order":"Book the Flow format first; every move comes in three levels, so beginners and athletes share the room.","tip":"It's inside CocoWalk — pair a morning class with brunch a floor away.","goodFor":"Morning workout","price":""}},
    {"id":"ChIJKYka48u32YgRf_i5mqV5VaU","name":"Ritz-Carlton Coconut Grove","lat":25.730447,"lng":-80.238056,"rating":4.5,"reviews":1295,"primaryType":"hotel","types":["hotel","wedding_venue","lodging","event_venue"],"photoRef":"places/ChIJKYka48u32YgRf_i5mqV5VaU/photos/wfplacediscovery","address":"3300 SW 27th Ave, Miami","ed":{"role":"Where to stay","why":"The Grove's luxury boutique base — 115 rooms with private balconies, a rooftop pool, and a bohemian-meets-refined feel that fits the neighborhood.","order":"A bay-view room with a balcony; drinks at The Commodore and dinner on Isabelle's garden terrace.","tip":"Not a guest? The rooftop pool and craft-cocktail bar are still worth the trip.","goodFor":"Where to stay","price":"$$$$"}},
    {"id":"ChIJ1cyBvGa32YgRKpni9-JNbbo","name":"Grand Public","lat":25.728336,"lng":-80.242369,"rating":4.8,"reviews":266,"primaryType":"american_restaurant","types":["american_restaurant","steak_house","sports_bar","cocktail_bar"],"photoRef":"places/ChIJ1cyBvGa32YgRKpni9-JNbbo/photos/wfplacediscovery","address":"3015 Grand Ave Ste 201, Coconut Grove","ed":{"role":"Where the Grove gathers","why":"An all-day American room above CocoWalk that swings from prime steaks to fresh sushi — the neighborhood's new everyday table.","order":"A prime steak or the sushi, then a craft cocktail — the espresso martini is a regular order.","tip":"Daily happy hour runs 3–6pm, and weekend brunch is the move.","goodFor":"All-day · Brunch","price":"$$$"}},
  ],
};

export function partnerPlacesFor(id) {
  return PARTNER_PLACES[id] || [];
}
