// lib/partnerCollectionsData.js — the HEAVY partner place data (baked Google
// photo resource names are ~800 chars each). Split out of lib/partnerCollections.js
// and loaded ONLY via dynamic import when a partner sheet opens, so these strings
// never enter the eager home-route bundle (check-bundle's 500KB gz budget — the
// Vercel build that caught this, 2026-08-23). Everything the AMAZON-RAIL TILE
// needs (gate, art, titles) stays in the light module; only the sheet's place
// list lives here.
//
// rating/reviews are a Google snapshot; the SHOWN score is recomputed by
// wayfindScore() at hydrate time (see partnerCollections.hydratePartnerCollection).
//
// Each place also carries an `ed` (editorial) block — the CGNA's curated take:
// role (where-to-go / where-to-stay), why it was picked, what not to miss, an
// insider tip, a good-for tag and a price band. The partner sheet renders this
// as the Wayfind place-card editorial (HookDetail partnerSplash path), so a
// reader knows exactly why each place earned its spot. Researched from primary
// sources (Infatuation, Miami New Times, Time Out, INK, official sites), not
// invented — 2026-08-23.
const PARTNER_PLACES = {
  "coconut-grove": [
    {"id":"ChIJb8Zih8-32YgRgxaWQFJtIFg","name":"Barracuda","lat":25.727761,"lng":-80.243179,"rating":4.4,"reviews":950,"primaryType":"bar_and_grill","types":["bar_and_grill","sports_bar","seafood_restaurant","american_restaurant"],"photoRef":"places/ChIJb8Zih8-32YgRgxaWQFJtIFg/photos/AVoNoXTMmlk69Cog_985svZCJgR8X7Tux_vZWGTrGpfZnCnhHhIRaFspY6-hMZy2RYQosl52JXlORrest2gQjIA1q76OXnduf2lwIm6vNG75LjCp-5h_nBn9exK-SYuWFAM1CBTRqLcX4feJATveVSJNdZmSN_Ci6jKqyEjEtE73eRhAuwdR14BEONV7z8wilSxTtL_0AlCHRzkEmEdwQdrwX6QC1ORvoS7MOAXqgOXBAPnc6XbNAGnd0iR3L39CQnXKKyexapbw7uWSYJECgQx2iFjPzGllSa-zWFiZPQCfGgy_WmwJDx9IelChJzSZDweDtY_vn4O-Kr1udrWU6uzeLFkySPFiUeH1HXTWqBR8CyWldk6Nbje9EYtNNhZ0r57ZjxGDstXbE8-wgw3yPQQC0Kzts17vvUj86Mn_DDIucgz3HiOHLlG-VODP8010ul3D","address":"Parking lot, 3035 Fuller St, Coconut Grove","ed":{"role":"Where the Grove hangs out","why":"The Grove's unpretentious anchor — 52 beers on tap, the game on, and a crowd of regulars who've been coming for years.","order":"The blackened snapper sandwich on house garlic bread — the thing locals send you for.","tip":"Wednesday is Bottles & Beats — live music from 7pm with 20% off craft beer bottles & cans and 99¢ wings (min 6, dine-in). Any other night, come for trivia or the game.","goodFor":"Casual · Sports · Live music Wed","price":"$$"}},
    {"id":"ChIJe1t0Q8W32YgRHGUckw_C5Uw","name":"Amal","lat":25.726471,"lng":-80.244213,"rating":4.7,"reviews":2700,"primaryType":"restaurant","types":["restaurant","lebanese_restaurant","mediterranean_restaurant","middle_eastern_restaurant"],"photoRef":"places/ChIJe1t0Q8W32YgRHGUckw_C5Uw/photos/AVoNoXSE-JPB8DsoH4UU3kXWSP02TXonGftfzoov3GmRa-Ic40a8k4Voe_VjuRSIBMUsP92kG0jOaG2LpY1VctcAliGhL3gAeL784Y7Lj26wZ55s9NfAJhszQmj5z41re6LOCqJF6ySAo67V0r3RDFUloaZ6T7ZNcjHfdI299Z3Ta0riOndkE-nW45Nve9VQ6VxQ_UBaAWj2x8Rvpdg_qZl7SkLP2IQAuqR1fnO_Klkx_6yZKkdQhdqEeXyGFZsZjgRh5Dju3xyaCuxgmpfeOO4DWO4zUvOB9zKwuG0i3D2GCzyRWubWz-OC278KKGRLvR2Li0BfIdf4uxwk0fRWn7H7jW3Ek6LtCIjFtb8qamqMBl3tkmdSuF2CSuQXsEHZa3ydXv7Q2bYBqJfuZ5kE5kMDaLh_ZsE4qTV4IYfIF8GzcoL3TPNI","address":"3480 Main Hwy Ste 100, Miami","ed":{"role":"Where to linger over dinner","why":"Modern Lebanese built for sharing — generous mezze in a Studio Munge room that turns dinner into a whole evening.","order":"The Monk Salad and Truffle Rakakat to start, then the Black Cod Harra as the centerpiece.","tip":"There's a 5,000 sq ft rooftop bar upstairs — arrive early for a drink with a Grove view.","goodFor":"Date night · Groups","price":"$$$"}},
    {"id":"ChIJVVVFQsW32YgRshiwWyuedns","name":"Level 6","lat":25.726456,"lng":-80.244222,"rating":4.8,"reviews":3350,"primaryType":"restaurant","types":["restaurant","food","point_of_interest","establishment"],"photoRef":"places/ChIJVVVFQsW32YgRshiwWyuedns/photos/AVoNoXTN6c7rXgbkPp_BJ4eguNWlRs0aL7NtpQzOs8RPXM5b-hvU05a7Io5LTjmxZboVohJmMQj67l4-PvV0C-rbqaEC_YNbUGUZhBygkf4s9wdV6rH2BnPLk5Jt4KVI2Z95qUhrcJqOYBB7CFtRWUG69pnzHfeY35rS_zD6BEA1emAgerxjAjpU7ALiU5VIdoeaoLj0qjG3vEHcg9WtITSj8uT1iLXcC1kl-DH54CrjBRyLRS3Bq-sNofDjKGNcw3x7QIgc5ER321yRsmKZblzaYEJXft4U9-C3ivju4VkXxK3u7WP9RxSABBOsfpuwxArOSmDYbM75jbMjqauUdYmY8i56VdIjF4CKB3GOmH1X8aJQx2PnrD6RMTlYXtUDy3iALtq9f3d9pKPqa6Lb4m6SrR6bmuz_7GlssWmteMlEOe5Qfs8m","address":"3480 Main Hwy 6th floor, Coconut Grove","ed":{"role":"Where to catch sunset","why":"The Grove's highest-rated table — a sixth-floor rooftop where shareable plates meet a straight shot to Biscayne Bay at golden hour.","order":"Small plates to share, timed for sunset, when the terrace becomes the after-work scene.","tip":"Go at golden hour on a weekday; it fills fast once the sun drops.","goodFor":"Sunset · Views","price":"$$$"}},
    {"id":"ChIJZRBieMW32YgRe9uja7jsGmQ","name":"Sapore di Mare","lat":25.72731,"lng":-80.242833,"rating":4.5,"reviews":1530,"primaryType":"italian_restaurant","types":["italian_restaurant","seafood_restaurant","restaurant","point_of_interest"],"photoRef":"places/ChIJZRBieMW32YgRe9uja7jsGmQ/photos/AVoNoXQfQFo9D1OlyxvX5oxrU78PqkzaVxNct3uBFMr2JmrhibpTBkaRqiGxqDMmSaUAsKsm_wtlIS79mrGHQdlLDVJZxCN2tbOYGBCBiSO4yGk89uV4zqokz7vQUQCE_wZR5vi2bSOdorpDIgBQ2ojOn3X221hw8Nr4646T5yrOk9RgjGQNYzyTJL2Lxl3o0q3XDCivHUhYk0ds8k90KkeT4M7LH1fqHgjaQWaz9gfUklHVQz1dcKt1wewv2t_JvnhsGjgZemJG6k2nE1gAYs9E6hKy2VG6rCUViYxx6L0UoXreUn7mu3ypp9Q0ou2WB92DVRO1pSIy30u4eQTfahWUybKYgskGeBWodQw2vdVkyfJg-yCzZT7hDfGXTPGGHNc42AfcNRAG-lbVnSaQVAawVAXeAcRWE4Ztq3MjVIwcKABemg","address":"3433 Main Hwy, Miami","ed":{"role":"Where locals eat Italian","why":"A tiny, nautical Campanian seafood room where the staff are Italian natives who remember your order — the Grove's regulars' hangout.","order":"Tagliolini cacio e pepe finished tableside in a wheel of aged Pecorino — and anything from the crudo list.","tip":"Book ahead; it's small and the year-round locals fill it.","goodFor":"Intimate dinner","price":"$$$"}},
    {"id":"ChIJY7MwUQy32YgR39Vs9IYxci4","name":"BodyRok","lat":25.728972,"lng":-80.241977,"rating":4.8,"reviews":55,"primaryType":"gym","types":["gym","sports_complex","sports_school","sports_activity_location"],"photoRef":"places/ChIJY7MwUQy32YgR39Vs9IYxci4/photos/AVoNoXR8XquKzLQsyhTl27_Y3ouIwf8osI2x-1BYFqHyao6EiBocQX0IpeM2Ju9dB2OwYFccSJMhZ0TxoyVBIlRiZOTa1lgUWMtY75jT6Vbg7LhnvMRLR00tS736HG4wOJTJu0cudsJB1C-LkD3rHqrXK-cZD-CQrDEJgrxWVWobsxA6zyrRqvWXGfm4kjiVAj0gm-AWXS0NXq4xtBC3n6PduVtQWaPyot7h9YAM2kCSZSljM2Yw8ai-OZWChtpensuMx_NTtT23kKNWUbuJ3KBA5Q9xFZNLWCrVVPMa5fPpP6HS30nitnlt_7Jlu0fSbRC8Fa0WA0EAFeqwLedTYEnwfbCusMEXwIvPvVvaSWrKJnLOOrR931cOug8B6ztEsHr2DpEOwJqqPS38UEV-qexoc0NvGgql1kLoEkXxEUoHrU3wnfBNBPn_PjPjLOl5lhkN","address":"3015 Grand Ave #216, Miami","ed":{"role":"Where to start the day","why":"The Grove's newest reformer studio — 45-minute classes that run high-intensity but low-impact, so you leave worked, not wrecked.","order":"Book the Flow format first; every move comes in three levels, so beginners and athletes share the room.","tip":"It's inside CocoWalk — pair a morning class with brunch a floor away.","goodFor":"Morning workout","price":""}},
    {"id":"ChIJKYka48u32YgRf_i5mqV5VaU","name":"Ritz-Carlton Coconut Grove","lat":25.730447,"lng":-80.238056,"rating":4.5,"reviews":1295,"primaryType":"hotel","types":["hotel","wedding_venue","lodging","event_venue"],"photoRef":"places/ChIJKYka48u32YgRf_i5mqV5VaU/photos/AVoNoXTdDfZaHZ3RD-3NpvpadIMwyRWl0RgJdrc-ZpiBPoMLK85sBINsDAn-ZPnDxxxXu7-nJxur4EGj8i6-kHY746sTZQvuyAUE6y0F0LQO0ftcqb07hxCYGs8rGQM2Tr3d64q17XU43JrEEKNBTjpsZ8zbqJzMDYC6zbGSjM6wLhrQTxG0giay_jOcjkwKX-Ag2WhoJrV-oKm27HRD2edUaNQbBhzy6oMhoVMri99Xtf-n20NTb-gokokSMKqM93xMDbb2jGFIO3H6lNOM8CsBEulHEXx4xSeOqWzYMY6m0JTydGH79eYoGwVXzA5TTTacN9cygtSQtypbuAnb4XS-ApbqdqtfQGrxcm4Ep1fX8pcbeYr3QO-3xW9Sg24DZjaY03Ce-E6W7bbsmDeNgLT8LvHEYoDkoEeh5JOOfkRhwnri6oC8wCqtMOLwE8e2_c7P","address":"3300 SW 27th Ave, Miami","ed":{"role":"Where to stay","why":"The Grove's luxury boutique base — 115 rooms with private balconies, a rooftop pool, and a bohemian-meets-refined feel that fits the neighborhood.","order":"A bay-view room with a balcony; drinks at The Commodore and dinner on Isabelle's garden terrace.","tip":"Not a guest? The rooftop pool and craft-cocktail bar are still worth the trip.","goodFor":"Where to stay","price":"$$$$"}},
    {"id":"ChIJ1cyBvGa32YgRKpni9-JNbbo","name":"Grand Public","lat":25.728336,"lng":-80.242369,"rating":4.8,"reviews":266,"primaryType":"american_restaurant","types":["american_restaurant","steak_house","sports_bar","cocktail_bar"],"photoRef":"places/ChIJ1cyBvGa32YgRKpni9-JNbbo/photos/AVoNoXTZBilNgUmAjFwAiJN6j6Urn_eZ0XQ_apnMYce874FBeOVTGXb7msSWY8rY0joytm6JRYf052V7WVqesS6PcVMHqAIBtlPXreFGQZurhRjguom6LPRyAckJDk9U9zZ5TBLnBXLLoxt-BfFWadsL99-Gtq-bzG6_m6vNrQL8pmmUdEHmm_seQ8zTZeesXtjSTNnonX3Ris4EigGXVmzEJcf92fWMuRsu3OvB3_fjuYpxbZHBsaYO-p02dM6C3-lNeECKYVqfx7JeS_FqFi4-yVy-p7r5p54_GHPq8b7DsD7S28eZq6wCWCKb3CP5JEgst3QKKsgpCzM21sgoi8Od2QLt3TPNb9Aw5s_7xbT7l95qyw7rGz-RovZojWl4P5BR6ARsd6nQmGmLgLLjdsHM0ARh4JcVgDotpOwMI2OVTSHk2Mkb_BmMWiCM-qUh7g","address":"3015 Grand Ave Ste 201, Coconut Grove","ed":{"role":"Where the Grove gathers","why":"An all-day American room above CocoWalk that swings from prime steaks to fresh sushi — the neighborhood's new everyday table.","order":"A prime steak or the sushi, then a craft cocktail — the espresso martini is a regular order.","tip":"Daily happy hour runs 3–6pm, and weekend brunch is the move.","goodFor":"All-day · Brunch","price":"$$$"}},
  ],
};

export function partnerPlacesFor(id) {
  return PARTNER_PLACES[id] || [];
}
