// app/api/aasa/route.js — the Apple App Site Association document.
//
// Served at /.well-known/apple-app-site-association via an internal REWRITE in
// next.config.js. Three constraints Apple enforces, and the reason this is a
// route handler rather than a file in public/:
//
//   1. NO FILE EXTENSION. The path must be exactly
//      /.well-known/apple-app-site-association.
//   2. Content-Type MUST be application/json. An extensionless file in public/
//      is served as application/octet-stream, which Apple rejects. A route
//      handler sets the header explicitly, so it cannot drift.
//   3. NO REDIRECT. Apple does not follow one. A rewrite is internal — the
//      response comes back on the requested URL with a 200 — so it satisfies
//      this where a redirect would not.
//
// A file in public/ would also depend on Next copying a DOT-directory through
// the build, which is a second thing that can silently not happen. This way the
// document is generated by code the guard can import and CALL.
//
// ── WHY UNIVERSAL LINKS MATTER FOR THIS APP SPECIFICALLY ──────────────────
// Guideline 4.2 rejects an app that is only a website in a native frame.
// Wayfind's shell already does real native work — push, camera, share sheet,
// Sign in with Apple — and deep-link handling is the piece that makes a SHARED
// Wayfind link open in the app instead of Safari. That is the retention loop
// (share -> return) the product is built around, and it cannot exist in a
// browser tab.
//
// THE RECEIVING END ALREADY EXISTS, which is why this is only two files:
//   SceneDelegate.scene(_:continue:)  -> SceneDelegateProxy (Capacitor)
//   lib/native.js appUrlOpen listener -> onDeepLink(pathname + search)
// Both were written for this and are live. The entitlement and this document
// were the only missing links in that chain.

// Static: the document never varies by request, so it is generated at build
// time and served from the edge cache. Apple fetches it rarely and expects it
// to be fast and stable.
export const dynamic = "force-static";

/**
 * appID is TEAMID.BUNDLEID, and both halves are real values from
 * ios/App/App.xcodeproj/project.pbxproj (DEVELOPMENT_TEAM,
 * PRODUCT_BUNDLE_IDENTIFIER). A mismatch here does not error anywhere — the
 * link simply opens in Safari forever — so scripts/check-universal-links.mjs
 * reads both out of the pbxproj and compares them against this constant.
 */
export const APP_ID = "VZGMT57ND7.com.gowayfind.app";

/**
 * Only www. The canonical host is https://www.gowayfind.com (lib/site.js
 * SITE_URL, and 32 of the 34 hard-coded URLs in the codebase). The apex is
 * deliberately NOT declared: if gowayfind.com redirects to www — which is the
 * normal canonical setup — Apple's fetch of the apex document follows nothing
 * and the association silently fails while LOOKING configured. Declaring the
 * apex is a one-line change once its response has actually been checked, and
 * shipping it unverified would be the "styled surface with no door" pattern.
 */
export const APPLINK_DOMAINS = Object.freeze(["www.gowayfind.com"]);

export const AASA = Object.freeze({
  applinks: {
    details: [
      {
        appIDs: [APP_ID],
        // Modern `components` form (iOS 13+). Order matters: the FIRST match
        // wins, so the exclusions must precede the catch-all.
        components: [
          {
            // API routes are machine endpoints. /api/commerce/go and
            // /api/eats/go in particular are 302s to partner domains, and a
            // partner checkout belongs in Safari with its own cookie jar, not
            // inside our WebView.
            "/": "/api/*",
            exclude: true,
            comment: "API endpoints and outbound affiliate redirects stay in the browser",
          },
          {
            // Including this path would ask the app to open the very document
            // that decides which paths the app opens.
            "/": "/.well-known/*",
            exclude: true,
            comment: "Association documents are not user-facing pages",
          },
          {
            "/": "/*",
            comment: "Every user-facing Wayfind page opens in the app",
          },
        ],
      },
    ],
  },
});

export async function GET() {
  return new Response(JSON.stringify(AASA), {
    status: 200,
    headers: {
      // Required by Apple. Explicit so it cannot be inferred wrongly from a
      // missing file extension.
      "Content-Type": "application/json",
      // Apple caches this; so should the edge. Not immutable — adding a domain
      // or an app id must be able to take effect.
      "Cache-Control": "public, max-age=3600",
    },
  });
}
