// app/api/aasa/route.js — the Apple App Site Association document.
//
// Served at /.well-known/apple-app-site-association via an internal REWRITE in
// next.config.js. Three constraints Apple enforces, and the reason this is a
// route handler rather than a file in public/:
//
//   1. NO FILE EXTENSION. The path must be exactly
//      /.well-known/apple-app-site-association.
//   2. Content-Type MUST be application/json. An extensionless file in public/
//      is served as application/octet-stream, which Apple rejects. A route
//      handler sets the header explicitly, so it cannot drift.
//   3. NO REDIRECT. Apple does not follow one. A rewrite is internal — the
//      response comes back on the requested URL with a 200 — so it satisfies
//      this where a redirect would not.
//
// A file in public/ would also depend on Next copying a DOT-directory through
// the build, which is a second thing that can silently not happen. This way the
// document is generated by code the guard can import and CALL.
//
// ── WHY UNIVERSAL LINKS MATTER FOR THIS APP SPECIFICALLY ──────────────────
// Guideline 4.2 rejects an app that is only a website in a native frame.
// Wayfind's shell already does real native work — push, camera, share sheet,
// Sign in with Apple — and deep-link handling is the piece that makes a SHARED
// Wayfind link open in the app instead of Safari. That is the retention loop
// (share -> return) the product is built around, and it cannot exist in a
// browser tab.
//
// THE RECEIVING END ALREADY EXISTS, which is why this is only two files:
//   SceneDelegate.scene(_:continue:)  -> SceneDelegateProxy (Capacitor)
//   lib/native.js appUrlOpen listener -> onDeepLink(pathname + search)
// Both were written for this and are live. The entitlement and this document
// were the only missing links in that chain.

// Static: the document never varies by request, so it is generated at build
// time and served from the edge cache. Apple fetches it rarely and expects it
// to be fast and stable.
export const dynamic = "force-static";

/**
 * appID is TEAMID.BUNDLEID, and both halves are real values from
 * ios/App/App.xcodeproj/project.pbxproj (DEVELOPMENT_TEAM,
 * PRODUCT_BUNDLE_IDENTIFIER). A mismatch here does not error anywhere — the
 * link simply opens in Safari forever — so scripts/check-universal-links.mjs
 * reads both out of the pbxproj and compares them against this constant.
 */
export const APP_ID = "VZGMT57ND7.com.gowayfind.app";

/**
 * BOTH HOSTS. www.gowayfind.com is canonical (lib/site.js SITE_URL, and 32 of
 * the 34 hard-coded URLs in the codebase), so it is what Wayfind's own share
 * links use and the one that must work.
 *
 * The apex was previously left unclaimed because its response could not be
 * checked — every request from the verifying machine returned 429, INCLUDING
 * requests to www, so that was the IP being rate-limited rather than anything
 * about the apex. Owner decision 2026-08-05: claim it, because the outcomes are
 * asymmetric. Apple evaluates each domain independently:
 *
 *   apex serves the document -> non-www shared links open the app
 *   apex redirects to www    -> Apple's fetch of the apex fails, that domain
 *                               does not associate, and www is UNAFFECTED
 *
 * Worst case is a silent no-op identical to not claiming it; best case is a
 * whole class of shared links that stops bouncing to Safari.
 *
 * STILL UNVERIFIED, recorded rather than glossed: fetch
 * https://gowayfind.com/.well-known/apple-app-site-association from any machine
 * Vercel is not rate-limiting. HTTP 200, Content-Type application/json and zero
 * redirects means the apex genuinely works; anything else means this entry is
 * inert and should be fixed at the host layer or dropped.
 */
export const APPLINK_DOMAINS = Object.freeze(["www.gowayfind.com", "gowayfind.com"]);

export const AASA = Object.freeze({
  applinks: {
    details: [
      {
        appIDs: [APP_ID],
        // Modern `components` form (iOS 13+). Order matters: the FIRST match
        // wins, so the exclusions must precede the catch-all.
        components: [
          {
            // API routes are machine endpoints. /api/commerce/go and
            // /api/commerce/go and /api/viator/go are 302s to partner domains, and a
            // partner checkout belongs in Safari with its own cookie jar, not
            // inside our WebView.
            "/": "/api/*",
            exclude: true,
            comment: "API endpoints and outbound affiliate redirects stay in the browser",
          },
          {
            // Including this path would ask the app to open the very document
            // that decides which paths the app opens.
            "/": "/.well-known/*",
            exclude: true,
            comment: "Association documents are not user-facing pages",
          },
          {
            "/": "/*",
            comment: "Every user-facing Wayfind page opens in the app",
          },
        ],
      },
    ],
  },
});

export async function GET() {
  return new Response(JSON.stringify(AASA), {
    status: 200,
    headers: {
      // Required by Apple. Explicit so it cannot be inferred wrongly from a
      // missing file extension.
      "Content-Type": "application/json",
      // Apple caches this; so should the edge. Not immutable — adding a domain
      // or an app id must be able to take effect.
      "Cache-Control": "public, max-age=3600",
    },
  });
}
